### ISSUE TITLE
[theming] changing themes quickly results in a dialog 

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6786] opened 2019-12-23 13:27 UTC
**Description**

Using #6475, if a user changes themes quickly, a dialog is displayed that there is inconsistency in the global `settings.json` in the editor and on the filesystem  (auto-save is off)

![image](https://user-images.githubusercontent.com/40359487/71360379-b067cb80-255d-11ea-9cbc-923d32a2e8c4.png)

**Steps to Reproduce**
1. using #6475, attempt to change the color theme quickly.
2. a dialog appears that there are unsaved changes in the `settings.json`.

**Comment by akosyakov** [comment] 2019-12-26 08:48
I don't think it can happen often, does it? I had hard time to reproduce it.

**Comment by akosyakov** [comment] 2019-12-30 17:44
but it breaks tests from time to time, i.e. https://github.com/eclipse-theia/theia/pull/5774 failing because of it

**Comment by akosyakov** [comment] 2020-01-01 18:48
Oh, basically we need to reimplement logic from the monaco editor model to handle concurrent updates for resource. I think we are better to rewrite `AbstractResourcePreferenceProvider` with the monaco editor model instead of using the resource directly as @vince-fugnitto were suggesting in another PR. In such implementation if there is no opened editors for such resource we will trigger auto save, otherwise rely on a user to save the dirty preference editor.

**Comment by akosyakov** [comment] 2020-01-01 20:12
That's tricky:
- the editor model cannot be acquired if editor preferences are not ready, so there is a cycle
- it breaks preference tests, since it requires Monaco

I think we can do it after https://github.com/eclipse-theia/theia/issues/6409 that we can port tests to run within the app.

**Comment by akosyakov** [comment] 2020-01-14 04:27
`KeymapsService` suffers from the same problems

**Comment by akosyakov** [comment] 2020-02-09 16:54
It should be fixed with https://github.com/eclipse-theia/theia/pull/7110. @vince-fugnitto could you try?

**Closed** 2020-02-12 14:21 UTC
Labels: bug, theming
