### ISSUE TITLE
widgets input can't undo

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6256] opened 2019-09-25 03:20 UTC
### Description
![temp](https://user-images.githubusercontent.com/10203793/59894942-23f51880-9415-11e9-9453-872fb506153e.gif)

### Reproduction Steps

- input some thing in main editor
- `Ctrl + F` open search at editor
- input some thing in search widgets
- `Ctrl + Z` undo input
- search widgets nothing happend but main editor undo it

**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment] 2019-09-25 04:15
Something wrong with registered keybinding, i.e. there should be undo handler for the search widget registered from Monaco which takes priority over default handler by `when` closure.

**Comment by spoenemann** [comment] 2020-02-18 08:16
The same problem applies to all other input fields: Search view (search text), Git view (commit message) etc.

**Comment by Hanksha** [comment] 2020-03-13 01:57
I just encountered that as well, I can't use undo/redo in any input text or textarea I used.
The fix for me was to add this:
```typescript
commands.registerHandler(CommonCommands.UNDO.id, {
            execute: () => {
                document.execCommand("undo", true);
            },
            isEnabled: () => document.activeElement instanceof HTMLInputElement && document.activeElement.type === "text"
        });
        commands.registerHandler(CommonCommands.REDO.id, {
            execute: () => {
                document.execCommand("redo", true);
            },
            isEnabled: () => document.activeElement instanceof HTMLInputElement && document.activeElement.type === "text"
        });
```

Although the documentation says `document.execCommand` might not work for every browser. Works well so far.

**Comment by akosyakov** [comment] 2020-04-06 08:00
@spoenemann @502647092 @Hanksha Could you reproduce it against https://github.com/eclipse-theia/theia/pull/7481? 

Please help with testing 🙏  You can test with Gitpod: https://gitpod.io#https://github.com/eclipse-theia/theia/pull/7481

**Comment by spoenemann** [comment] 2020-04-06 08:25
Yes it seems the issue is fixed in that revision!

**Comment by Hanksha** [comment] 2020-04-06 08:26
Looks like it's fixed, I'll try within my project as well once it's merged.

**Closed** 2020-05-03 02:18 UTC
Labels: bug, editor
