### ISSUE TITLE
Theia shows absolute path in "Peek References" popup

### ISSUE THREAD

**Issue by MoHcmp** [eclipse-theia/theia#10692] opened 2022-01-31 08:01 UTC
### Bug Description:
Theia shows absolute path in "Peek References" popup. Theia is web ide and can be hosted on server. It is not right to show absolute path. Path should be relative to current workspace

### Steps to Reproduce:

1. Create several files with code
2. Create method in second file
3. Call this method in first file
4. Call "Peek References" on metod in second file

Path in "Peek References" popup will be absolute, but should be relative.

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.21

**Comment by vince-fugnitto** [comment] 2022-01-31 12:54
@MoHcmp thank you for reporting the issue.

Verifying the behavior with VS Code, I noticed that they also use the absolute path when displaying the path, I do not believe there is a reason to deviate from this behavior and we should instead keep aligning by default:

![image](https://user-images.githubusercontent.com/40359487/151796595-2f7289c3-f598-4747-8224-a31eaa20bbd0.png)

I did verify on Linux however, can you confirm (and possibly share a screenshot) of what you experience on Windows for VS Code?

**Comment by msujew** [comment] 2022-01-31 15:05
@MoHcmp VSCode is also capable of running as a web IDE, see also [this repo](https://github.com/gitpod-io/openvscode-server). In web mode, VSCode also shows the full path to the file:

![image](https://user-images.githubusercontent.com/4377073/151816998-698b18f9-255a-4740-bf0e-d04fc73a0ce3.png)

**Comment by MoHcmp** [comment] 2022-01-31 15:08
@vince-fugnitto 
Checked vscode Web IDE on linux. It uses relative paths
![image](https://user-images.githubusercontent.com/24322410/151818368-b80cf844-2ea4-4b7e-89d7-be1c0a3dde57.png)

**Comment by xcariba** [comment] 2022-01-31 15:35
@vince-fugnitto you can get thin if you open repository on github using "." key. It opens your repository in their vscode web version and it replaces absolute paths with relative ones (it starts with your repository path).

**Comment by msujew** [comment] 2022-01-31 16:19
@vince-fugnitto Yes, I think so too. I don't see this behavior included in the framework, but rather done as an extension.

**Comment by MoHcmp** [comment] 2022-02-01 11:26
@vince-fugnitto @msujew How can i override this behaviour as an extension? I found out that reference view is from @theia/monaco-editor-core which uses vscode dependency. Class responsible for path to file is this one: https://github.com/microsoft/vscode/blob/release/1.63/src/vs/editor/standalone/browser/simpleServices.ts#L740

Tried to find out how to override this behaviour but did not find out how.

**Comment by vince-fugnitto** [comment] 2022-02-02 15:33
@MoHcmp I don't think it's an easy customization to make (I haven't tried myself), the `@theia/monaco-editor-core` package is built by us based on the standalone monaco editor, and some extra functionality pulled in (some vscode functionality). You may be able to somehow monkeypatch it, I believe https://github.com/eclipse-theia/theia/pull/10524 does some monkeypatching related to semantic tokens.

**Comment by vince-fugnitto** [comment] 2022-07-19 12:48
Closing as the absolute path in the _peek references_ is the intended behavior.

**Closed by vince-fugnitto** 2022-07-19 12:48 UTC
Labels: :thinking: needs more info
