### ISSUE TITLE
paste when file exist

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8208] opened 2020-07-20 21:10 UTC
# Feature Description:

Currently when copy pasting file to its own folder nothing happens.
It would be nice if it is created with different file name. Either adding copy to its name (like in vscode) or askingt he user to choose different name (like in other IDEs).

**Comment by vince-fugnitto** [comment] 2020-07-20 21:52
Closing since it is a duplicate of https://github.com/eclipse-theia/theia/issues/4794.

**Closed by vince-fugnitto** 2020-07-20 21:52 UTC
Labels: navigator
