### ISSUE TITLE
bug: support codicons in vscode extensions

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8011] opened 2020-06-15 13:45 UTC
#### Bug Description:

It is possible for VS Code extensions to define [codicons](https://code.visualstudio.com/api/references/icons-in-labels#icons-in-labels) in their `package.json` which is unsupported in Theia. We should support such icons so that builtin and external extensions work correctly. The `vscode-builtin-npm` extension is one such extension that makes use of such icons: https://github.com/eclipse-theia/theia/pull/8000#issuecomment-643325676

_VS Code_:

<div align='left'>

![Screenshot from 2020-06-15 09-34-03](https://user-images.githubusercontent.com/40359487/84664481-9c899a80-aeec-11ea-916c-95514b4ec712.png)

</div>

_Theia_:

<div align='left'>

![Screenshot from 2020-06-15 09-38-50](https://user-images.githubusercontent.com/40359487/84664471-972c5000-aeec-11ea-8d78-cc94bc88c404.png)

</div>

_Example:_

```json
"contributes": {
  "commands": [
    {
      "command": "codicons.refreshEntry",
      "title": "Codicons: Refresh",
      "icon": "$(refresh)"
    }			
  ]
}
```

#### Steps to Reproduce:

1. copy the following test extension [codicons-test](https://github.com/vince-fugnitto/codicons-test/releases/download/0.0.1/codicons-test-0.0.1.vsix)
2. open the `codicon` view and observe the icons (toolbar) are missing

**Comment by akosyakov** [comment] 2020-06-15 14:11
duplicate of https://github.com/eclipse-theia/theia/issues/7634

**Closed by akosyakov** 2020-06-15 14:11 UTC
Labels: bug, builtins, vscode
