### ISSUE TITLE
"add folder to workspace" is invisible even if theia has multi root workspace support

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#5020] opened 2019-04-26 14:53 UTC
### Description
"add folder to workspace" does not show up in the context menu, even if "workspace.supportMultiRootWorkspace" is set true.

### Reproduction Steps
1. make a multi-root workspace
2. remove all roots from that workspace. at this point, the current workspace becomes a multi root workspace with zero roots.
3. refresh browser
4. right click the explorer
expected: "add folder to workspace" is visible in the context menu, so that users can add roots to the workspace
actual: "add folder to workspace" is invisible
workaround: close the explorer, refresh browser, and make the explorer visible again

**OS and Theia version:**
Ubuntu. Master branch of Theia on Apr 26 2019

![Peek 2019-04-26 10-46](https://user-images.githubusercontent.com/37082801/56816445-9086d900-6811-11e9-8477-5150e6654559.gif)

**Diagnostics:**

**Comment by akosyakov** [comment] 2019-04-26 15:34
Make sure to use `test-123` as a workspace name. I've tried to reproduce with `theia` as a workspace name and could not.

**Comment by akosyakov** [comment] 2019-04-26 15:35
PRs are welcomed. Something fishy is here: https://github.com/theia-ide/theia/blob/3ddca955fe7f9b371c94086871838c0c99d1a870/packages/preferences/src/browser/preferences-tree-widget.ts#L241-L244

**Comment by vince-fugnitto** [comment] 2019-07-02 17:19
@elaihau is the issue resolved? I wasn't able to reproduce the problem.

**Steps**:
1. open folder `A`
2. add folder `B` to workspace
3. save the workspace as `tmp-123`
4. remove folder `A` and `B` (no folders present in the workspace)
5. `Add Folder to Workspace` is still present and visible in the explorer's context menu

**Comment by elaihau** [comment] 2019-07-04 17:23
@vince-fugnitto this problem persists. I tested again with the lastest changes on master.

**Comment by vince-fugnitto** [comment] 2019-07-05 00:47
> @vince-fugnitto this problem persists. I tested again with the latest changes on master.

I see the `preferences-widget` did the trick, I am able to reproduce it.

**Comment by msujew** [comment] 2024-05-07 15:42
I can't reproduce this anymore and I believe that the responsible code has since been deleted. Closing

**Closed by msujew** 2024-05-07 15:42 UTC
Labels: bug, help wanted, Team: Che-Editors, multi-root, che/next-sprint
