### ISSUE TITLE
Task output not shown with error

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8195] opened 2020-07-19 08:45 UTC
### Bug Description:
When running shell task terminal is opened but the output of the task is not shown. Also there is an error message in the console.

### Steps to Reproduce:

Create the following tasks.json:
```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Mock Task",
      "type": "shell",
      "command": "echo AAAA"
    }
  ]
}
```

Run: F1 -> Task: Run Task... -> "Mock Task" -> "Continue without scanning..."

Most of the times the task console does not show the echo output and the browser console shows:
```
Uncaught (in promise) Error: Failed to start terminal for id: 14.
    at t.<anonymous> (terminal-widget-impl.ts:346)
    at user-preference-provider.ts:34
    at Object.next (user-preference-provider.ts:34)
    at a (user-preference-provider.ts:34)
```

### Additional Information

- Operating System: Gitpod
- Theia Version: master

**Comment by vince-fugnitto** [comment] 2020-07-19 12:14
Duplicate of https://github.com/eclipse-theia/theia/issues/2961.

**Closed by vince-fugnitto** 2020-07-19 12:14 UTC
Labels: tasks
