### ISSUE TITLE
vscode-clangd extension does not work

### ISSUE THREAD

**Issue by spoenemann** [eclipse-theia/theia#7493] opened 2020-04-03 08:23 UTC
### Description
The vscode-clangd extension fails to activate with an exception.

Marketplace:
https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd

Source:
https://github.com/llvm/llvm-project/tree/master/clang-tools-extra/clangd/clients/clangd-vscode

Trace:
```
root INFO [hosted-plugin: 5551] PLUGIN_HOST(5551): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/llvm-vs-code-extensions.vscode-clangd-0.0.21.vsix/extension/out/src/extension)
root INFO [hosted-plugin: 5551] Clang Language Server is now active!
root ERROR [hosted-plugin: 5551] Promise rejection not handled in one second: TypeError: vscode_1.languages.registerSelectionRangeProvider is not a function , reason: TypeError: vscode_1.languages.registerSelectionRangeProvider is not a function
With stack trace: TypeError: vscode_1.languages.registerSelectionRangeProvider is not a function
    at SelectionRangeFeature.registerLanguageProvider (/tmp/vscode-unpacked/llvm-vs-code-extensions.vscode-clangd-0.0.21.vsix/extension/node_modules/vscode-languageclient/lib/selectionRange.js:51:36)
    at SelectionRangeFeature.register (/tmp/vscode-unpacked/llvm-vs-code-extensions.vscode-clangd-0.0.21.vsix/extension/node_modules/vscode-languageclient/lib/client.js:709:33)
    at SelectionRangeFeature.initialize (/tmp/vscode-unpacked/llvm-vs-code-extensions.vscode-clangd-0.0.21.vsix/extension/node_modules/vscode-languageclient/lib/selectionRange.js:29:14)
    at ClangdLanguageClient.initializeFeatures (/tmp/vscode-unpacked/llvm-vs-code-extensions.vscode-clangd-0.0.21.vsix/extension/node_modules/vscode-languageclient/lib/client.js:2462:21)
    at connection.initialize.then (/tmp/vscode-unpacked/llvm-vs-code-extensions.vscode-clangd-0.0.21.vsix/extension/node_modules/vscode-languageclient/lib/client.js:2147:18)
```

### Reproduction Steps

 * Add the extension as described [in the Wiki](https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-Extensions).
 * Use the "Manually activate clangd extension" to activate it (it is not activated by default on .cpp files)

**OS and Theia version:** macOS 10.15.3, commit `5e45d2b` on master branch

**Diagnostics:** 
The extension is using vscode-languageclient version 6.1.0, which expects vscode ^1.41.0.

**Comment by akosyakov** [comment] 2020-04-03 08:36
Duplicate of https://github.com/eclipse-theia/theia/issues/6623

**Closed by akosyakov** 2020-04-03 08:36 UTC
Labels: vscode
