### ISSUE TITLE
[vscode][typescript] root ERROR [hosted-plugin: 42] Invalid Completion Item -> must be single line and on the same line

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#7246] opened 2020-02-29 10:14 UTC
### Description

after remove `@theia/typescript` and use `@theia/vscode-builtin-typescript-language-features`
Ts in ide can't auto completion

### Reproduction Steps

- remove @theia/typescript
- add @theia/vscode-builtin-typescript-language-features@next

**OS and Theia version:**
0.17.0-next.c965552a

**Diagnostics:** 
```
theia_1  | root ERROR [hosted-plugin: 42] Invalid Completion Item -> must be single line and on the same line
theia_1  | Invalid Completion Item -> must be single line and on the same line
```

**Comment by vince-fugnitto** [comment] 2020-02-29 17:08
@502647092 if you'd like to use the `vscode-builtin-typescript-language-features`, you should include it as a plugin and not directly as a dependency in your `dependencies` section of your application.

For example:
https://github.com/eclipse-theia/theia/blob/c965552a41d7963a0f6f960b831f894a75de2713/package.json#L80-L146

For additional information you can consult the [migration steps](https://github.com/eclipse-theia/theia/wiki/Consuming-Builtin-and-External-VS-Code-Extensions) following the removal of `@theia/typescript` for instance.

**Comment by akosyakov** [comment] 2020-03-01 04:42
@vince-fugnitto It is about latest version of built-in typescript extension, not which one which we use on master.

**Comment by vince-fugnitto** [comment] 2022-08-19 15:52
Closing since the issue is quite old, and language support has increased. If you confirm there is still an issue please re-comment.

**Closed by vince-fugnitto** 2022-08-19 15:52 UTC
Labels: bug, vscode, :thinking: needs more info
