### ISSUE TITLE
[theme] The hard-coded dark theme always shows up for a sec at app start-up

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7382] opened 2020-03-20 13:57 UTC
### Description
 

If I select a custom color theme and I refresh the browser, I can see the hard-coded dark theme first, them my desired theme. This also happens when load the app.

Steps to reproduce:
 - Start Theia from the source (ae5591edb),
 - Select a theme other than the default dark if you have not done that yet,
 - Refresh the browser.

You can see the dark theme, then the HC in my case.

![screencast 2020-03-20 14-53-33](https://user-images.githubusercontent.com/1405703/77170208-fed42a00-6aba-11ea-9a37-258a863fd527.gif)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment] 2020-03-20 14:07
Here:
https://github.com/eclipse-theia/theia/blob/ae5591edb22b06f890b090e5c4eb36ddeed05122/packages/core/src/browser/theming.ts#L129

First I can see that the theme ID is `"Default High Contrast"`, then various contributions reset it to `"dark"` for a short time. I did not collect all contributions:

![Screen Shot 2020-03-20 at 15 04 08](https://user-images.githubusercontent.com/1405703/77171259-7787b600-6abc-11ea-91b7-89e390d1af5e.jpg)
![Screen Shot 2020-03-20 at 15 04 37](https://user-images.githubusercontent.com/1405703/77171262-78b8e300-6abc-11ea-9d13-c424471cfcbc.jpg)
![Screen Shot 2020-03-20 at 15 01 34](https://user-images.githubusercontent.com/1405703/77171245-73f42f00-6abc-11ea-91cb-05267fb6f70c.jpg)

**Comment by akosyakov** [comment] 2020-03-20 14:12
A duplicate of https://github.com/eclipse-theia/theia/issues/6999?

**Comment by vince-fugnitto** [comment] 2021-07-14 16:30
The issue has been fixed, likely thanks to https://github.com/eclipse-theia/theia/pull/9303.

**Closed by vince-fugnitto** 2021-07-14 16:30 UTC
Labels: bug, theming
