### ISSUE TITLE
VSCode Webviews do not open in Theia in Safari

### ISSUE THREAD

**Issue by xcariba** [eclipse-theia/theia#12272] opened 2023-03-08 22:42 UTC
### Bug Description:
In Safari (tested in 15.1) webviews does not work. There are several `'allow-downloads'` attributes in webview initialization code that raise exception and it prevents webviews from fully initializing (after error plugin resources cannot be loaded).
[webview.ts](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/main/browser/webview/webview.ts#L258)
[main.js](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/main/browser/webview/pre/main.js#L485)
This attribute is not implemented in Safari yet [Can I use...](https://caniuse.com/mdn-html_elements_iframe_sandbox-allow-downloads).

I tried to remove them manually (using developer tools local override option) and removed these attributes, but there is one more error. If you use vscode api to communicate with parent window message is not recieved in parent window handler.
```
const vscode = acquireVsCodeApi();
vscode.postMessage({some: 0});
```
This code will call
```
const originalPostMessage = window.parent.postMessage.bind(window.parent);
...
originalPostMessage({ command: 'onmessage', data: msg }, targetOrigin);
```
in [main.js](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/main/browser/webview/pre/main.js#L163)

And this command will not be recieved in [webview.ts](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/main/browser/webview/webview.ts#L286).

I use have not tested it on localhost yet. I launch Theia on linux and add https connection using nginx and self-signed certificate. Then I open `https://<myIp>` page in Safari. This certificate dows not work in chrome, but it works in Safari.

### Steps to Reproduce:

1. Build Theia
2. Start it
3. Tunnel Theia to add SSL support (I use nginx with simple configuration and self-signed certificate)
4. Install vscode image preview plugin
5. Open any image (png or jpeg)
6. Error will be raised and webview will be empty

### Additional Information

- Operating System:
- Theia Version:

**Comment by pisv** [comment] 2023-06-18 12:58
FWIW, webviews seem to work fine with Theia latest backend and frontend running locally on macOS 13.4 / Safari 16.5. In particular, `allow-downloads` attributes don't seem to cause any issue, as demonstrated by the following screenshot:

<img width="1920" alt="Screenshot" src="https://github.com/eclipse-theia/theia/assets/8298491/5ce83b74-3610-4881-8fcf-9e8cf47ebc76">

@xcariba If this is still an issue for you, it looks like much more information will be needed to help in reproducing the issue (as @vince-fugnitto has already indicated):

* Exact setup for reproducing the issue (including relevant configuration files)

* Precise steps to reproduce the issue (including exact terminal commands and other code such as specific extensions and/or tests needed for reproducing the issue; please also note that some of the line numbers you referred to above seem to have become stale in the meantime)

* Details of observed outcomes (including exceptions with stack traces)

Thanks!

**Comment by msujew** [comment] 2024-06-04 22:21
Given the lack of reproducibility, I'll close this. Please create another issue in case this is still relevant.

**Closed by msujew** 2024-06-04 22:21 UTC
Labels: webviews, :thinking: needs more info, browser/safari
