### ISSUE TITLE
package.json lookup is using cwd causing infinite waiting 

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#734] opened 2017-10-24 18:39 UTC
If theia is started from outside the root like `cd / && node .. main.js `

package.json is not found since it looks for `/package.json` this causes the extension system tab to load forever.

package.json should be relative to main.js

@akosyakov can you have a look ?

**Comment by marcdumais-work** [comment] 2017-10-30 15:09
A side-effect of this is, when Theia is started through the VS Code "Launch Backend" launch, "cwd" is not set correctly (i.e. starts from Theia repo root), then the extension manager doesn't work as intended.

**Comment by akosyakov** [comment] 2017-11-03 14:52
> package.json should be relative to main.js

It is not easy to do. Right now it is another way around: main.js is resolved relative to the given app project path.

What is your use case? Why do you run `node main.js` instead of `theia start .` from the app package?

**Comment by hexa00** [comment] 2017-11-03 15:44
Couln't we use the __dirname of main.js ?

**Comment by akosyakov** [comment] 2017-11-03 15:49
Maybe, I don't know how to do it from here: https://github.com/theia-ide/theia/blob/28ebfce9906c8cd8fa75f38706e11c33471a053f/packages/extension-manager/src/node/application-project-cli.ts#L29-L33

**Comment by hexa00** [comment] 2017-11-04 00:47
How about having server.js pass it into to the BackendApplication
Then make the application-project-cli fetch it from there ?

**Comment by hexa00** [comment] 2017-11-04 00:51
I think we could pass it from server.js to CliManager and then to the cli contribution

**Comment by msujew** [comment] 2024-10-02 08:31
I believe this has been fixed by https://github.com/eclipse-theia/theia/pull/13584.

**Closed by msujew** 2024-10-02 08:31 UTC
Labels: bug, extension system
