### ISSUE TITLE
Unable to use the newly installed theme from open-vsx

### ISSUE THREAD

**Issue by nisarhassan12** [eclipse-theia/theia#8028] opened 2020-06-17 09:16 UTC
### Bug Description:

I just tried installing https://open-vsx.org/extension/GitHub/github-vscode-theme in theia  I can see it in installed section but when I select `View` -> `Find Command` and type Color Theme and in the menu, I can't find github-vscode-theme see the below gif. Thanks

![Peek 2020-06-17 14-01](https://user-images.githubusercontent.com/46004116/84879010-144df580-b0a4-11ea-9188-df976e95b720.gif)

Note: the above gif is recorded in gitpod-staging I have tested that the same can be reproduced in theia as well.

this is the error that I get in the console:

![image](https://user-images.githubusercontent.com/46004116/84879701-fcc33c80-b0a4-11ea-8357-78d2a6ba9499.png)

### Steps to Reproduce:

Follow what's shown in the above gif.

### Additional Information

- Operating System:
- Theia Version:

**Comment by akosyakov** [comment] 2020-06-17 11:38
@nisarhassan12 can you reproduce it with Theia from sources?

**Comment by nisarhassan12** [comment] 2020-06-17 15:10
> I have tested that the same can be reproduced in theia as well.

Thanks @akosyakov from the :arrow_up: in https://github.com/eclipse-theia/theia/issues/8028#issue-640280570 I meant "Theia from sources" sorry that I have not clearly specified it.

Actually I didn't know what does "Theia from sources" Thanks to @jankeromnes who explained this to me :slightly_smiling_face:

**Comment by JonasHelming** [comment] 2021-02-19 08:33
I retested this from the sources, in Theia Blueprint and in Gitpod, it works for me. I am closing this, please reopen, if you experience this issue again.

**Closed by JonasHelming** 2021-02-19 08:33 UTC
Labels: bug, help wanted, theming
