### ISSUE TITLE
Cannot use express middleware in BackendApplicationContribution.configure

### ISSUE THREAD

**Issue by leon-js** [eclipse-theia/theia#11318] opened 2022-06-21 02:37 UTC
The BackendApplicationContribution leads one to believe they can inject custom functionality into the express server. However:

server
```javascript
import { injectable, inject } from '@theia/core/shared/inversify';
import { ILogger } from '@theia/core';
import { BackendApplicationContribution } from '@theia/core/lib/node';
import * as express from 'express';


@injectable()
export class TheiaCorsBackendApplicationContribution implements BackendApplicationContribution {
    @inject(ILogger) private readonly logger: ILogger;

    configure(app: express.Application): void {
        console.log('hello1')
        this.logger.info('Setting up Middleware');
        app.use((req: any, res: any, next: any) => {
            console.log('world')
            next();
        });
    }
}
```

backend-module
```javascript
import { TheiaCorsBackendApplicationContribution } from './user-server';
import { ContainerModule } from '@theia/core/shared/inversify';
import { BackendApplicationContribution } from '@theia/core/lib/node';

export default new ContainerModule(bind => {
    bind(TheiaCorsBackendApplicationContribution).toSelf().inSingletonScope();
    bind(BackendApplicationContribution).toService(TheiaCorsBackendApplicationContribution);
});
```

**Comment by vince-fugnitto** [comment] 2022-06-21 12:06
@leon-js thank you for the issue, however it seems to be a duplicate of https://github.com/eclipse-theia/theia/issues/8931 (word for word). I believe we should comment on the original issue instead.

**Closed by vince-fugnitto** 2022-06-21 12:06 UTC
Labels: duplicate
