### ISSUE TITLE
Slow scrolling in editors using mouse wheel [Firefox/Ubuntu]

### ISSUE THREAD

**Issue by geropl** [eclipse-theia/theia#6390] opened 2019-10-15 09:07 UTC
### Description
Scrolling using my mouse wheel is dead slow on Firefox/Ubuntu for a few weeks now. It used to work fine before. Interestingly the markdown preview works as expected.

### Reproduction Steps
 - open any editor, scroll with mouse wheel -> observe slow scrolling
 - open a markdown preview, scroll with mouse wheel -> regular scrolling
![slow-scrolling](https://user-images.githubusercontent.com/32448529/66817330-d197b480-ef3b-11e9-8fc8-224900657443.gif)

**OS and Theia version:**
 - OS: Linux Mint 19.1 Cinnamon (based on Ubuntu 18.04)
 - Theia: 0.12.0-next.2186ccb7 (on gitpod.io)

**Diagnostics:** 
none

**Comment by akosyakov** [comment] 2019-10-15 09:36
It was fixed in latest Monaco. We have to review https://github.com/TypeFox/monaco-languageclient/pull/178 and then follow https://github.com/eclipse-theia/theia/wiki/LSP-and-Monaco-integration#migration-guidelines.

**Comment by fgreinacher** [comment] 2019-12-02 07:31
@akosyakov Can we somehow support in getting this resolved? Or alternatively is there any workaround (patch, extra config) that we can apply to our Theia bundle?

**Comment by akosyakov** [comment] 2019-12-02 08:18
Yes, someone should do what’s mentioned in my previous comment.

**Comment by RDIL** [comment] 2019-12-22 15:30
This is also happening on every windows machine I try it on.  Please fix it!

**Comment by ViRb3** [comment] 2020-02-28 23:13
Confirmed on Windows 10 with Firefox, makes working quite hard.

**Comment by RomanNikitenko** [comment] 2020-03-05 13:37
Tested on Ubuntu 18.04.1 LTS and Firefox 68.0.1 (64-bit) against https://github.com/eclipse-theia/theia/pull/7149
Looks like the issue will be fixed by upgrade of Monaco version:

![scroll](https://user-images.githubusercontent.com/5676062/75986651-25a93280-5ef7-11ea-8564-c14fc792f0f9.gif)

**Comment by vince-fugnitto** [comment] 2020-03-27 15:18
Fixed thanks to https://github.com/eclipse-theia/theia/pull/7149

**Closed by vince-fugnitto** 2020-03-27 15:18 UTC
Labels: browser/firefox, bug, monaco

**Comment by RDIL** [comment] 2020-03-27 15:19
Thanks Vincent!
