### ISSUE TITLE
"focus" class on terminal creates an empty rectangle

### ISSUE THREAD

**Issue by ghokun** [eclipse-theia/theia#8158] opened 2020-07-12 10:31 UTC
### Bug Description:
Terminal has an empty rectangle when focused.
![terminal](https://user-images.githubusercontent.com/3802058/87243976-245aba00-c443-11ea-8fe2-778b17efe9e8.png)

### Steps to Reproduce:

1. Run with: docker run -it --init -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:latest 
2. Open a browser and browse to <ip>:3000
3. Press Terminal -> New Terminal
4. Press anywhere on Terminal to focus

### Additional Information

- Operating System: 
Running with docker image theiaide/theia:latest and theiaide/theia:next
Browsing with Windows 10 Firefox Developer Edition, Edge
Browsing with Mac OS Catalina Safari
- Theia Version: next, latest

**Comment by akosyakov** [comment] 2020-07-14 06:57
I wonder whether it is the shell issue somehow or xtermjs. Usually it is a good idea to try to reproduce such issues outside of Theia with the system shell.

**Comment by ghokun** [comment] 2020-07-14 09:30
Let me know how i can help.

**Comment by perrinjerome** [comment] 2020-07-15 05:21
I could narrow down that this happens with xterm 4.8.1 and that it did not happen with 4.6.0 ( I have not tried versions in between )

It's really annoying because the rectangle moves as you type :
![theia-terminal](https://user-images.githubusercontent.com/521510/87506004-42bff000-c6a5-11ea-99c3-78fed1bcd02b.gif)

**Comment by ghokun** [comment] 2020-07-15 08:45
Looks like 4.7.0 does not have this problem.

![image](https://user-images.githubusercontent.com/3802058/87524252-996eff00-c690-11ea-962e-a9fcb7bfbeba.png)

**Comment by perrinjerome** [comment] 2020-07-15 09:10
isn't https://github.com/xtermjs/xterm.js/pull/2996#issuecomment-657213849 the same thing ?

**Comment by akosyakov** [comment] 2020-07-15 09:15
@perrinjerome it seems that https://github.com/xtermjs/xterm.js/pull/2996#issuecomment-657213849 is a part of 4.8.1?

**Comment by ghokun** [comment] 2020-07-15 10:03
I fixed my build with a resolution block in packages.json
https://github.com/ghokun/theia-cv/blob/master/package.json

**Comment by perrinjerome** [comment] 2020-07-16 13:05
@akosyakov this problem started with 4.8.0

if I understood correctly, xtermjs uses a textarea for input methods and this textarea is the empty rectangle we can see here. With xterm's css, this textarea is supposed to be invisible with this [`opacity: 0`](https://github.com/xtermjs/xterm.js/blob/4.7.0/css/xterm.css#L67) rule and also out of the screen with this [`left: -9999em;`](https://github.com/xtermjs/xterm.js/blob/4.7.0/css/xterm.css#L68) rule.

There's this rule in theia's css, which sets `opacity: 1` for all `:focus` elements:
https://github.com/eclipse-theia/theia/blob/9afc819182ae94cd44f19efe42828ce704d9fecc/packages/core/src/browser/style/index.css#L145-L151

That rule applies on xterm textarea, but with <= 4.7.0, it's was OK because the textarea was anyway outside of the screen with the `left: -9999em` rule.

The changes from https://github.com/xtermjs/xterm.js/pull/2996 were about making the textarea appear next to the cursor, by setting the position with style attributes of the  element, so it's now visible, because of theia's opacity rule.


xterm 4.7.0:

![image](https://user-images.githubusercontent.com/521510/87673140-0082d580-c7af-11ea-9f9c-df5d10f1473b.png)


xterm 4.8.0:

![image](https://user-images.githubusercontent.com/521510/87673611-c7973080-c7af-11ea-911b-e57f9c297e28.png)


Maybe theia does not need such a global rule as this  `:focus { opacity: 1!important }`  ?
https://github.com/eclipse-theia/theia/blob/9afc819182ae94cd44f19efe42828ce704d9fecc/packages/core/src/browser/style/index.css#L149

at least if I disable this rule, everything seems OK with xterm 4.8.0.

**Comment by ghokun** [comment] 2020-07-16 13:45
A similar rectangle occurs under mouse pointer, when right click is pressed in terminal area with xterm 4.7.0. (Could not capture the mouse pointer)
![image](https://user-images.githubusercontent.com/3802058/87678465-a4568c00-c783-11ea-807a-0d8882688442.png)

**Comment by vince-fugnitto** [comment] 2020-07-20 13:53
> A similar rectangle occurs under mouse pointer, when right click is pressed in terminal area with xterm 4.7.0. (Could not capture the mouse pointer)

The bug occurs for `xterm` context-menus in electron, it should be fixed once the following issue is implemented (a proper context-menu for terminals with the following menu items). In the meantime, perhaps we can prevent the display of the empty "context-menu" as shown in the screenshot.

- #7632

**Closed** 2020-07-20 16:28 UTC
Labels: bug, help wanted, terminal
