### ISSUE TITLE
[siw] SIW should not return matches from `./git` folder.

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7459] opened 2020-03-31 11:01 UTC
### Description
 

When I open Theia with the `theia` workspace and I search for `aa`, I can see search results from the `.git/logs/refs` folder. It works as expected in VS Code.

Theia:

![Screen Shot 2020-03-31 at 12 51 59](https://user-images.githubusercontent.com/1405703/78019252-a40ac000-734f-11ea-8c36-5d5a3a991183.jpg)

The `options` looks as expected, and `includeIgnored` is `false`.

![Screen Shot 2020-03-31 at 12 59 26](https://user-images.githubusercontent.com/1405703/78019224-95bca400-734f-11ea-99fe-00a58374cf45.jpg)

Related code:

https://github.com/eclipse-theia/theia/blob/9481af8e21f3be4b2e6658854327d8fa2b390da3/packages/search-in-workspace/src/node/ripgrep-search-in-workspace-server.ts#L97

https://github.com/eclipse-theia/theia/blob/9481af8e21f3be4b2e6658854327d8fa2b390da3/packages/search-in-workspace/src/node/ripgrep-search-in-workspace-server.ts#L114-L120

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment] 2020-03-31 11:06
Here is the VS Code ref to follow: https://github.com/microsoft/vscode/blob/f2a80a180e8b549b32cff4a712f2f434b3e85c1d/src/vs/workbench/services/search/node/ripgrepFileSearch.ts#L32-L82

**Comment by vince-fugnitto** [comment] 2020-03-31 11:50
Duplicate of https://github.com/eclipse-theia/theia/issues/7273?

**Closed** 2020-03-31 12:10 UTC
Labels: bug, search in workspace
