### ISSUE TITLE
Cursor misplaced when typing mid-blink

### ISSUE THREAD

**Issue by galefino** [eclipse-theia/theia#12030] opened 2022-12-27 12:26 UTC
### Bug Description:
While typing into Theia, and waiting for the cursor to almost reappear post-blink, the cursor will be placed in the wrong position, to the left of the recently typed character.

### Steps to Reproduce:

1. Open a file in Theia.
2. Start typing.
3. Wait for the cursor's blink - It seems to have to be precisely near the end of it
4. Pay attention to the cursor's position.

Attaching a video - Sorry in advance for the quality and blur:
https://user-images.githubusercontent.com/50100613/209665711-b417f000-982b-437f-8950-bfd77c5ff2f7.mp4

### Additional Information

- Operating System: Linux 
- Theia Version: 1.30
- Browser: Firefox v102.5.0esr, Chrome v108.0.5359.125

**Comment by msujew** [comment] 2022-12-27 13:45
Hey @galefino,

can you check whether this issue still appears when using the latest `master`? We updated the monaco integration in 1.32.0 (see https://github.com/eclipse-theia/theia/pull/11787). It might be that it's an upstream monaco issue and in this case it could that the update already fixed this.

**Comment by galefino** [comment] 2022-12-27 13:52
Will do! I'll update later today. Thank you for the quick response!

**Comment by galefino** [comment] 2022-12-29 12:07
Hi @msujew!
I'm now using 1.33.0 from master, and the issue persists.
Thanks in advance!

**Comment by FernandoAscencio** [comment] 2023-03-22 20:20
I am having trouble reproducing this error in the latest master. Does it still persist?
Windows Version: 10.0.19045 Build 19045
Theia version: 1.35.0
Default VS Code API: 1.70.2
Firefox: 102.9.0esr (64-bit)
![Issue12030](https://user-images.githubusercontent.com/48699277/227028356-4fb01a4b-654f-486a-aa14-6cfc0513eb19.gif)

**Comment by msujew** [comment] 2024-06-04 22:25
I've been unable to reproduce it and we've had several updates to our monaco package since then. I assume this has been fixed in the meantime. If that's not the case, please comment here.

**Closed by msujew** 2024-06-04 22:25 UTC
Labels: bug, monaco
