### ISSUE TITLE
Copy/Paste/Undo/Redo Keyboard Shortcuts are not working within WebViews

### ISSUE THREAD

**Issue by chrisunl** [eclipse-theia/theia#7357] opened 2020-03-17 15:39 UTC
### Description

Within Webviews in Theia, we have noticed that the following keyboard shortcuts are not working as expected:

CMD/Ctrl-C : the selection is not copied to the clipboard
CMD/Ctrl-V : the content of the clipboard is pasted, with what was copied from an external app
CMD/Ctrl-Z : Undo is NOT working in e.g. an input or textarea field.
CMD/Ctrl-Shift-Z : Redo is NOT working in e.g. an input or textarea field.

### Reproduction Steps

1. Open a WebView within Theia in Chrome _without_ Chrome DevTools open.
(That is to say: ensure that Chrome is not handling the commands).

2. Enter text into a text field / text area / content editable within the webview.

3. Try to copy the text within the text area using the Theia edit submenu's copy command (or just CMD/CTRL+C).

4. Notice the text is not copied onto the clipboard.

Undo and redo also don't work although paste does using CMD/Ctrl + V but without copy working it will just paste whatever happens to be in the clipboard.

**OS and Theia version:**

MacOS Mojave 10.14.6
Theia 0.12.0
Google Chrome (version 80).

**Diagnostics:** 

Also noticed:

Using the Paste option from the edit menu gives the following warning message: Please use the browser's paste command or shortcut.

Other keyboard shortcuts like CMD/Ctrl+B, and CMD/Ctrl+I are working fine within contenteditable blocks.

Now, if we open up the Chrome devTools, then reload the webview with devTools open, all of the above commands start working as expected.

We observed that once devTools are open, these keyboard shortcuts are handled by the browser natively.

When devTools are closed, it seems that these keyboard shortcuts are being swallowed by Theia

**Comment by chrisunl** [comment] 2020-03-17 17:40
HI @akosyakov is there any more information that you need from me?

**Comment by akosyakov** [comment] 2020-03-18 07:53
Hi, it is more that someone has to investigate the root cause.

**Comment by akosyakov** [comment] 2020-04-06 07:57
@chrisunl Could you test please against https://github.com/eclipse-theia/theia/pull/7481?

**Comment by chrisunl** [comment] 2020-04-06 14:49
> @chrisunl Could you test please against #7481?

Hi, I'll take a look but it may have to wait till Thursday because of work commitments.

**Comment by akosyakov** [comment] 2020-04-07 07:56
@chrisunl ok, we merged the fix, please feel free to double test it when you have time and reopen the issue if it is still the case

**Closed by akosyakov** 2020-04-07 07:56 UTC
Labels: :thinking: needs more info, bug, help wanted, keybindings, webviews
