### ISSUE TITLE
yarn test failing on @theia/git

### ISSUE THREAD

**Issue by adamretter** [eclipse-theia/theia#8215] opened 2020-07-21 15:20 UTC
### Bug Description:

Running `yarn test` fails in `@theia/git` module.

### Steps to Reproduce:

1. `git clone https://github.com/eclipse-theia/theia.git`
2. `cd theia`
3. `yarn`
4. `yarn test`

Logs:
```
@theia/git:   1 failing
@theia/git:   1) git
@theia/git:        branch
@theia/git:          should list the branch in chronological order:
@theia/git:       AssertionError: expected [ 'a', 'b', 'c', 'master' ] to deeply equal [ 'master', 'c', 'b', 'a' ]
@theia/git:       + expected - actual
@theia/git:        [
@theia/git:       +  "master"
@theia/git:       +  "c"
@theia/git:       +  "b"
@theia/git:          "a"
@theia/git:       -  "b"
@theia/git:       -  "c"
@theia/git:       -  "master"
@theia/git:        ]
@theia/git:
@theia/git:       at Context.<anonymous> (lib/node/dugite-git.spec.js:1336:130)
@theia/git:       at step (lib/node/dugite-git.spec.js:48:23)
@theia/git:       at Object.next (lib/node/dugite-git.spec.js:29:53)
@theia/git:       at fulfilled (lib/node/dugite-git.spec.js:20:58)
@theia/git:       at process._tickCallback (internal/process/next_tick.js:68:7)
@theia/git: Exit with failure status (1): nyc mocha --opts ../../configs/mocha.opts "./lib/**/*.*spec.js" --no-cluster
@theia/git: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@theia/git: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run test
lerna ERR! (node:37948) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
lerna ERR! (node:37948) ExperimentalWarning: The fs.promises API is experimental
lerna ERR! Exit with failure status (1): nyc mocha --opts ../../configs/mocha.opts "./lib/**/*.*spec.js" --no-cluster
lerna ERR! error Command failed with exit code 1.
lerna ERR!
lerna ERR! $ theiaext test --no-cluster
lerna ERR! $ nyc mocha --opts ../../configs/mocha.opts "./lib/**/*.*spec.js" --no-cluster
lerna ERR!
lerna ERR!
lerna ERR!   GitRepositoryProvider
lerna ERR!     ✓ should adds all existing git repo(s) on theia loads
lerna ERR!     - should refresh git repo(s) on receiving a root change event from WorkspaceService
lerna ERR!     - should refresh git repo(s) on receiving a file system change event
lerna ERR!     - should ignore the invalid or nonexistent root(s)
lerna ERR!     ✓ should mark the first repo in the first root as "selectedRepository", if the "selectedRepository" is unavailable in the first place
lerna ERR!
lerna ERR!   git-watcher-slow
lerna ERR! root INFO Using Git [2.27.0] from the PATH. (/usr/local/bin/git)
lerna ERR! Repository watcher is already active.
lerna ERR! Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
lerna ERR! '--no-optional-locks' is a valid Git option for the current Git version: '2.27.0'.
lerna ERR!     ✓ watching the same repository multiple times should not duplicate the events (12013ms)
lerna ERR!
lerna ERR!   git-slow
lerna ERR!     diff-slow
lerna ERR!       ✓ diff with rename/move (8815ms)
lerna ERR!
lerna ERR!   git
lerna ERR!     repositories
lerna ERR!       ✓ should discover only first repository (183ms)
lerna ERR!       ✓ should discover all nested repositories (175ms)
lerna ERR!       ✓ should discover all nested repositories and the root repository which is at the workspace root (218ms)
lerna ERR!       ✓ should discover all nested repositories and the container repository (216ms)
lerna ERR!     status
lerna ERR!       ✓ modifying a staged file should result in two changes (158ms)
lerna ERR!     WorkingDirectoryStatus#equals
lerna ERR!       ✓ staged change should matter
lerna ERR!     show
lerna ERR!       ✓ modified in working directory
lerna ERR!       ✓ modified in working directory (nested)
lerna ERR!       ✓ modified in index
lerna ERR!       ✓ modified in index and in working directory
lerna ERR!     remote
lerna ERR!       ✓ remotes are not set by default (102ms)
lerna ERR!       ✓ origin is the default after a fresh clone (1618ms)
lerna ERR!       ✓ remotes can be added and queried (111ms)
lerna ERR!     exec
lerna ERR!       ✓ version (92ms)
lerna ERR!       ✓ config (95ms)
lerna ERR!     map-status
lerna ERR!       ✓ deleted
lerna ERR!       ✓ added with leading whitespace
lerna ERR!       ✓ modified with trailing whitespace
lerna ERR!       ✓ copied with percentage
lerna ERR!       ✓ renamed with percentage
lerna ERR!     similarity-status
lerna ERR!       ✓ copied (2)
lerna ERR!       ✓ copied (20)
lerna ERR!       ✓ copied (020)
lerna ERR!       ✓ renamed (2)
lerna ERR!       ✓ renamed (20)
lerna ERR!       ✓ renamed (020)
lerna ERR!       ✓ invalid
lerna ERR!     blame
lerna ERR!       ✓ blame file with dirty content (140ms)
lerna ERR!       ✓ uncommitted file (115ms)
lerna ERR!       ✓ blame file (221ms)
lerna ERR!       ✓ commit summary and body (135ms)
lerna ERR!     diff
lerna ERR!       ✓ diff without ranges / unstaged (133ms)
lerna ERR!       ✓ diff without ranges / staged (172ms)
lerna ERR!       ✓ diff with ranges (512ms)
lerna ERR!     branch
lerna ERR!       1) should list the branch in chronological order
lerna ERR!     ls-files
lerna ERR!       ✓ errorUnmatched - A.txt should exist
lerna ERR!       ✓ errorUnmatched - missing.txt should not exist
lerna ERR!       ✓ errorUnmatched - ../outside.txt should not exist
lerna ERR!
lerna ERR!   log
lerna ERR!     ✓ should not fail when executed from the repository root (119ms)
lerna ERR!     ✓ should not fail when executed against an empty repository (98ms)
lerna ERR!
lerna ERR!
lerna ERR!   43 passing (29s)
lerna ERR!   3 pending
lerna ERR!   1 failing
lerna ERR!
lerna ERR!   1) git
lerna ERR!        branch
lerna ERR!          should list the branch in chronological order:
lerna ERR!
lerna ERR!       AssertionError: expected [ 'a', 'b', 'c', 'master' ] to deeply equal [ 'master', 'c', 'b', 'a' ]
lerna ERR!       + expected - actual
lerna ERR!
lerna ERR!        [
lerna ERR!       +  "master"
lerna ERR!       +  "c"
lerna ERR!       +  "b"
lerna ERR!          "a"
lerna ERR!       -  "b"
lerna ERR!       -  "c"
lerna ERR!       -  "master"
lerna ERR!        ]
lerna ERR!
lerna ERR!       at Context.<anonymous> (lib/node/dugite-git.spec.js:1336:130)
lerna ERR!       at step (lib/node/dugite-git.spec.js:48:23)
lerna ERR!       at Object.next (lib/node/dugite-git.spec.js:29:53)
lerna ERR!       at fulfilled (lib/node/dugite-git.spec.js:20:58)
lerna ERR!       at process._tickCallback (internal/process/next_tick.js:68:7)
lerna ERR!
lerna ERR!
lerna ERR!
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/Users/aretter/tmp-code/theia/node_modules/execa/index.js:236:11)
{ Error: Command failed: yarn run test
(node:37948) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
(node:37948) ExperimentalWarning: The fs.promises API is experimental
Exit with failure status (1): nyc mocha --opts ../../configs/mocha.opts "./lib/**/*.*spec.js" --no-cluster
error Command failed with exit code 1.
```

### Additional Information

- Operating System: macOS 10.15.5 / nodeJS 10.16.3 / Python 2.7.16
- Theia Version: `HEAD` of `master` branch (commit 4c63f08)

**Comment by vince-fugnitto** [comment] 2020-07-21 15:24
@adamretter duplicate of https://github.com/eclipse-theia/theia/issues/8023? It may be related to the git version.

**Comment by adamretter** [comment] 2020-07-21 15:41
@vince-fugnitto Ah ha. It looks like it might be:

```
❯ git --version
git version 2.27.0
```

Whilst the issue is being kept open, I am wondering if it will be fixed? I was trying to contribute to Theia, but having a broken-test suite makes it hard to know if the problem is my own work or something unrelated.

In the mean-time is there an argument I can give to yarn test to exclude that known bad test?

**Comment by vince-fugnitto** [comment] 2020-07-21 15:44
> @vince-fugnitto Ah ha. It looks like it might be:
> 
> ```
> ❯ git --version
> git version 2.27.0
> ```
> 
> Whilst the issue is being kept open, I am wondering if it will be fixed? I was trying to contribute to Theia, but having a broken-test suite makes it hard to know if the problem is my own work or something unrelated.
> 
> In the mean-time is there an argument I can give to yarn test to exclude that known bad test?

I agree, perhaps the test case can be skipped for the moment as it looks dependent based on version which is not always controllable.

**Closed** 2020-07-21 18:41 UTC
Labels: git, test

**Comment by adamretter** [comment] 2020-07-21 19:21
@vince-fugnitto Thanks very much for the quick response - I can confirm that a fresh checkout now passes `yarn test` 100% :-)
