### ISSUE TITLE
Duplicate action extension doesn't work

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8895] opened 2020-12-23 13:50 UTC
### Bug Description:
Clicking on "Duplicate file or folder" command throws an error that extension activation failed.
Doesn't happen in vscode.

### Steps to Reproduce:

1. Install "Duplicate action" extension (mrmlnc.vscode-duplicate) from Open VSX Registry
2. Right click on a file in your workspace
3. Click on "Duplicate file or folder"

I get the following error:
Activating extension 'Duplicate action' failed.

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by vince-fugnitto** [comment] 2021-01-08 17:18
@rayakoren I believe this is an error with the extension itself and how it is packaged (packaging it myself and using it on `vscode` also did not work). In addition, the extension is quite old (~2 years since the last commit) and is not well maintained. I do not know how much value there is in fixing it, when their package script does not work correctly.

_vscode_:

![image](https://user-images.githubusercontent.com/40359487/104044598-85253e00-51ab-11eb-8a16-59a1280fed3a.png)

**Comment by vince-fugnitto** [comment] 2021-01-08 17:20
I'm inclined on closing the issue, and if you believe it should be addressed maybe open the issue directly on their repo or `open-vsx` on removing the extension or determining how it can be properly packaged so it can be consumed.

**Comment by vince-fugnitto** [comment] 2021-01-08 17:35
I'm inclined on closing the issue due to:
- the extension being outdated and not well maintained so the effort in getting it working may not be high (duplicating files is also covered with copy + paste).
- the packaging of the extension cannot be reproduced properly given the scripts provided (I attempted to package and it also did not work in vscode).

**Closed** 2022-12-16 12:44 UTC
Labels: :thinking: needs more info, open-vsx
