### ISSUE TITLE
Stop a debug session

### ISSUE THREAD

**Issue by meng-jpg** [eclipse-theia/theia#10385] opened 2021-11-05 01:42 UTC
### Bug Description:
Open a widget for one of the debug sessions, the stop button of the new widget we opened can only stop the `current session` but not the one displayed in the same widget.

### Steps to Reproduce:

1.start two debug sessions
<img width="280" alt="截屏2021-11-04 下午1 41 44" src="https://user-images.githubusercontent.com/74631407/140443073-6f293ab1-7ec1-4b17-a0aa-7c131eac84fc.png">

2.open widget for the second one
<img width="261" alt="截屏2021-11-04 下午1 42 01" src="https://user-images.githubusercontent.com/74631407/140443121-2683679a-b517-4519-aaf6-92edd85e8329.png">

3.select the first session to make it be the `current session`
<img width="312" alt="截屏2021-11-05 上午9 41 00" src="https://user-images.githubusercontent.com/74631407/140444006-886c0ae9-6769-4631-8594-bcf26478c5e5.png">

4.click the stop button in the widget we has opened for the second session
<img width="261" alt="截屏2021-11-04 下午1 42 01" src="https://user-images.githubusercontent.com/74631407/140443294-55642ce3-b35b-40f3-bba7-a1e92c079f4f.png">

5.then the first session will be stoped

### Additional Information

- Operating System: macOS Big Sur 11.2
- Theia Version: 1.16

**Comment by vince-fugnitto** [comment] 2021-11-05 11:53
@meng-jpg thank you for reporting the issue, I confirmed it is a bug :+1: Are you interested in contributing a fix?

**Comment by msujew** [comment] 2021-11-05 12:23
@vince-fugnitto This issue will already be addressed by https://github.com/eclipse-theia/theia/pull/10333. Using the PR, I couldn't reproduce the issue.

**Comment by tsmaeder** [comment] 2021-11-20 11:47
Haha....that seems to have been a drive-by fix :-)

**Comment by vince-fugnitto** [comment] 2022-07-21 18:48
Closing thanks to https://github.com/eclipse-theia/theia/pull/10333.

**Closed by vince-fugnitto** 2022-07-21 18:48 UTC
Labels: bug, debug
