### ISSUE TITLE
Draw.io VS Code extension fails with "registerCustomEditorProvider is not a function"

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia#8052] opened 2020-06-19 06:29 UTC
### Bug Description:

https://github.com/open-vsx/publish-extensions/issues/51

> This particular one failed with en error related to registerCustomEditorProvider is not a function. I'm guessing it is using new API for registering custom editors that is not official or not supported

### Steps to Reproduce:

1. Install the Draw.io VS Code extension: https://github.com/hediet/vscode-drawio
2. Check the browser console for above error

### Additional Information

- Operating System:
- Theia Version: Gitpod's Theia

**Comment by akosyakov** [comment] 2020-06-19 11:12
A duplicate of https://github.com/eclipse-theia/theia/issues/6636

**Closed by akosyakov** 2020-06-19 11:12 UTC
