### ISSUE TITLE
Auto-open a file

### ISSUE THREAD

**Issue by galefino** [eclipse-theia/theia#12049] opened 2023-01-09 08:28 UTC
Hi! 
I suggest an option allowing you to dictate a file that will automatically open when the Theia editor opens up.

1. Set the path to the file
2. Open Theia
3. Notice the aforementioned file open in the editor.

**Comment by vince-fugnitto** [comment] 2023-01-09 12:45
@galefino thank you for reporting the issue, do you mind providing additional details to better understand the feature request? When you mention setting the path to the file, do you mean in the URL of the browser, or did you have something else in mind?

It's possible that this issue is a duplicate of https://github.com/eclipse-theia/theia/issues/11255.

**Comment by galefino** [comment] 2023-01-09 13:37
@vince-fugnitto Hi!
It is possible.
For my current needs, I have made a mutation in which **navigator-contribution.ts** contains the following **open** function:
`   private async open(
        openerService: OpenerService,
        uri: URI
    ): Promise<object | undefined> {
        const opener = await openerService.getOpener(uri);
        return opener.open(uri);
    }`
and called from within the **init** function modified as such:
`
    @postConstruct()
    protected async init(): Promise<void> {
        await this.fileNavigatorPreferences.ready;
        this.shell.onDidChangeCurrentWidget(() => this.onCurrentWidgetChangedHandler());
        const fileURI = new URI("/home/student/workspace/main.py");
        this.open(this.openerService, fileURI);
        const updateFocusContextKeys = () => {
            const hasFocus = this.shell.activeWidget instanceof FileNavigatorWidget;
            this.contextKeyService.explorerViewletFocus.set(hasFocus);
            this.contextKeyService.filesExplorerFocus.set(hasFocus);
        };
        updateFocusContextKeys();
        this.shell.onDidChangeActiveWidget(updateFocusContextKeys);
        this.workspaceCommandContribution.onDidCreateNewFile(async event => this.onDidCreateNewResource(event));
        this.workspaceCommandContribution.onDidCreateNewFolder(async event => this.onDidCreateNewResource(event));
    }
`
This results in **/home/student/workspace/main.py** being open on the Theia editor as soon as it is accessed.

I believe there are better solutions for the matter and figured I should submit a feature request :)
If you need more details, please let me know!

**Comment by vince-fugnitto** [comment] 2023-01-09 13:47
I don't believe there is anything preventing others to actually open document on startup by the framework, everything should already exist (including lifecycle hooks and openers) to allow files to open like you've done. 

Is there anything specific you think this feature should achieve that you haven't achieved yet?

**Comment by galefino** [comment] 2023-01-09 13:51
My way does not necessarily work properly, as some extensions fail to identify the file as open, I opened this feature hoping for it to be configurable, without the need for code modification and re-compilation with each upcoming version.
Perhaps I'm using Theia wrong and missed something?

**Comment by vince-fugnitto** [comment] 2023-01-09 16:16
> Perhaps I'm using Theia wrong and missed something?

The framework's main purpose is to allow developers the ability to create their own IDE-like products, and offer the ability to customize any behavior or add new features based on their needs.

I'm trying to better understand the feature request overall, in general we should add features if the functionality is generic enough, and if it fills a need that cannot otherwise be achieved easily. Given that there should already be lifecycle hooks and the ability to open files automatically on startup I don't think there is a need to have any configurable code (example: preference under `settings.json`) where a file is automatically opened from.

Is there some basic functionality missing that is needed to get the feature to work in your product?

**Closed** 2023-02-14 20:52 UTC
Labels: :thinking: needs more info
