### ISSUE TITLE
Visual select only folders for Workspace

### ISSUE THREAD

**Issue by jyggiz** [eclipse-theia/theia#9607] opened 2021-06-17 15:43 UTC
### Feature Description:
Hey! When I wanted to open a new workspace, I noticed that you can select not only folders, but also files:

<img width="1790" alt="Screen Shot 2021-06-17 at 21 30 17" src="https://user-images.githubusercontent.com/40149112/122429808-e0f2bf00-cfb4-11eb-9d9d-cfbc6b65fc0c.png">

But when I selected in the lower right corner I got a window with an error that I selected the wrong workspace:

<img width="504" alt="Screen Shot 2021-06-17 at 21 30 33" src="https://user-images.githubusercontent.com/40149112/122429898-f2d46200-cfb4-11eb-8e52-793d6a21c674.png">

Maybe, when choosing a workspace, it is worth adding functionality that will not allow you to select files and will visually show that you can only select folders?

**Comment by vince-fugnitto** [comment] 2021-06-17 16:21
@jyggiz `open workspace` allows users to open `workspace` files (which represent multi-root workspaces).
They are generally in the form as `*.theia-workspace` or `*.code-workspace` (you can see if you update the format dropdown).

The only real issue is the filter displaying `all files` which is already being tracked by: https://github.com/eclipse-theia/theia/issues/8179.

**Comment by vince-fugnitto** [comment] 2021-06-17 16:48
Closing as it is a duplicate of https://github.com/eclipse-theia/theia/issues/8179, thank you anyways for reporting the issue.

**Closed by vince-fugnitto** 2021-06-17 16:48 UTC
Labels: duplicate, workspace
