### ISSUE TITLE
could not able to build new theia extension

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6203] opened 2019-09-17 13:47 UTC
Compiling my old theia extensions stopped working suddenly. even if I make new extension 
using " yo theia-extension" command it still doesn't compile and gives following error:

browser-app: npm ERR!     /home/ubuntu/.npm/_logs/2019-09-17T13_40_52_989Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! Error: webpack exited with an unexpected signal: SIGKILL.
lerna ERR!     at ChildProcess.<anonymous> (/home/ubuntu/theia2/theia/programmr_php/node_module             s/@theia/application-manager/lib/application-process.js:59:28)
lerna ERR!     at ChildProcess.emit (events.js:189:13)
lerna ERR!     at maybeClose (internal/child_process.js:970:16)
lerna ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

Yo version: 2.0.6
yarn version: 1.15.2

**Comment by vince-fugnitto** [comment] 2019-09-17 13:55
@dhananjayharel I recently tested and it works correctly for me.
Can you provide the exact steps or perhaps the custom extension?
Also, which `node` version are you using?

**Comment by dhananjayharel** [comment] 2019-09-17 18:19
mkdir pluginDir
 cd pluginDir/
 yo theia-extension pluginDir

After that:
yarn prepare

My node version is 10.15.3

**Comment by dhananjayharel** [comment] 2019-09-17 18:30
This is the full error message given below:
yarn run v1.15.2
$ lerna run prepare
lerna info version 2.4.0
my_plugin: > my_plugin@0.0.0 prepare /home/ubuntu/theia2/theia/my_plugin/my_plugin
my_plugin: > yarn run clean && yarn run build
my_plugin: warning package.json: No license field
my_plugin: $ rimraf lib
my_plugin: warning package.json: No license field
my_plugin: $ tsc
browser-app: > browser-app@0.0.0 prepare /home/ubuntu/theia2/theia/my_plugin/browser-app
browser-app: > theia build --mode development
electron-app: > electron-app@0.0.0 prepare /home/ubuntu/theia2/theia/my_plugin/electron-app
electron-app: > theia build --mode development
electron-app: please install @theia/electron@0.10.0 as a runtime dependency
electron-app: Error: webpack exited with an unexpected signal: SIGKILL.\n    at ChildProcess.<anonymous> (/home/ubuntu/theia2/theia/my_plugin/node_modules/@theia/application-manager/lib/application-process.js:59:28)\n    at ChildProcess.emit (events.js:189:13)\n    at maybeClose (internal/child_process.js:970:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
electron-app: npm ERR! code ELIFECYCLE
electron-app: npm ERR! errno 1
electron-app: npm ERR! electron-app@0.0.0 prepare: `theia build --mode development`
electron-app: npm ERR! Exit status 1
electron-app: npm ERR!
electron-app: npm ERR! Failed at the electron-app@0.0.0 prepare script.
electron-app: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
electron-app: npm ERR! A complete log of this run can be found in:
electron-app: npm ERR!     /home/ubuntu/.npm/_logs/2019-09-17T18_22_58_164Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! please install @theia/electron@0.10.0 as a runtime dependency
lerna ERR! Error: webpack exited with an unexpected signal: SIGKILL.
lerna ERR!     at ChildProcess.<anonymous> (/home/ubuntu/theia2/theia/my_plugin/node_modules/@theia/application-manager/lib/application-process.js:59:28)
lerna ERR!     at ChildProcess.emit (events.js:189:13)
lerna ERR!     at maybeClose (internal/child_process.js:970:16)
lerna ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! electron-app@0.0.0 prepare: `theia build --mode development`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the electron-app@0.0.0 prepare script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /home/ubuntu/.npm/_logs/2019-09-17T18_22_58_164Z-debug.log
lerna ERR!
lerna ERR!
lerna ERR! > electron-app@0.0.0 prepare /home/ubuntu/theia2/theia/my_plugin/electron-app
lerna ERR! > theia build --mode development
lerna ERR!
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/home/ubuntu/theia2/theia/my_plugin/node_modules/execa/index.js:236:11)
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
browser-app: Hash: 6c48e4f27c4b69179d3d
browser-app: Version: webpack 4.40.2
browser-app: Time: 201219ms
browser-app: Built at: 09/17/2019 6:23:01 PM
browser-app:                                   Asset      Size  Chunks                   Chunk Names
browser-app:                             0.bundle.js  34.4 KiB       0  [emitted]
browser-app:                         0.bundle.js.map  43.2 KiB       0  [emitted] [dev]
browser-app:  0a32a80243e05284a5d741c5dc093f31.woff2  23.8 KiB          [emitted]
browser-app:                             1.bundle.js  31.4 KiB       1  [emitted]
browser-app:                         1.bundle.js.map    25 KiB       1  [emitted] [dev]
browser-app:                            10.bundle.js   212 KiB      10  [emitted]
browser-app:                        10.bundle.js.map   224 KiB      10  [emitted] [dev]
browser-app:                            11.bundle.js  14.9 KiB      11  [emitted]
browser-app:                        11.bundle.js.map  15.3 KiB      11  [emitted] [dev]
browser-app:  11d1a2390613abf202bfd2ebbd5c4500.woff2  88.6 KiB          [emitted]
browser-app:                            12.bundle.js  15.4 KiB      12  [emitted]
browser-app:                        12.bundle.js.map    36 KiB      12  [emitted] [dev]
browser-app:                            13.bundle.js   303 KiB      13  [emitted]
browser-app:                        13.bundle.js.map   319 KiB      13  [emitted] [dev]
browser-app:                            14.bundle.js  60.9 KiB      14  [emitted]
browser-app:                        14.bundle.js.map  48.3 KiB      14  [emitted] [dev]
browser-app:                            15.bundle.js  23.2 KiB      15  [emitted]
browser-app:                        15.bundle.js.map  18.5 KiB      15  [emitted] [dev]
browser-app:                            16.bundle.js  23.9 KiB      16  [emitted]
browser-app:                        16.bundle.js.map  17.6 KiB      16  [emitted] [dev]
browser-app:                            17.bundle.js  61.1 KiB      17  [emitted]
browser-app:                        17.bundle.js.map  67.6 KiB      17  [emitted] [dev]
browser-app:                            18.bundle.js    18 KiB      18  [emitted]
browser-app:                        18.bundle.js.map  15.7 KiB      18  [emitted] [dev]
browser-app:                            19.bundle.js   373 KiB      19  [emitted]
browser-app:                        19.bundle.js.map   338 KiB      19  [emitted] [dev]
browser-app:                             2.bundle.js   117 KiB       2  [emitted]
browser-app:                         2.bundle.js.map  98.1 KiB       2  [emitted] [dev]
browser-app:                            20.bundle.js   579 KiB      20  [emitted]
browser-app:                        20.bundle.js.map  1010 KiB      20  [emitted] [dev]
browser-app:                            21.bundle.js   322 KiB      21  [emitted]
browser-app:                        21.bundle.js.map   318 KiB      21  [emitted] [dev]
browser-app:                            22.bundle.js   175 KiB      22  [emitted]
browser-app:                        22.bundle.js.map   153 KiB      22  [emitted] [dev]
browser-app:                            23.bundle.js   178 KiB      23  [emitted]
browser-app:                        23.bundle.js.map   144 KiB      23  [emitted] [dev]
browser-app:                            24.bundle.js   107 KiB      24  [emitted]
browser-app:                        24.bundle.js.map    92 KiB      24  [emitted] [dev]
browser-app:                            25.bundle.js   105 KiB      25  [emitted]
browser-app:                        25.bundle.js.map    79 KiB      25  [emitted] [dev]
browser-app:                            26.bundle.js  44.5 KiB      26  [emitted]
browser-app:                        26.bundle.js.map  24.7 KiB      26  [emitted] [dev]
browser-app:                            27.bundle.js  22.1 KiB      27  [emitted]
browser-app:                        27.bundle.js.map  17.4 KiB      27  [emitted] [dev]
browser-app:                            28.bundle.js  16.8 KiB      28  [emitted]
browser-app:                        28.bundle.js.map  12.8 KiB      28  [emitted] [dev]
browser-app:                            29.bundle.js  22.4 KiB      29  [emitted]
browser-app:                        29.bundle.js.map  21.1 KiB      29  [emitted] [dev]
browser-app:                             3.bundle.js  44.3 KiB       3  [emitted]
browser-app:                         3.bundle.js.map  33.9 KiB       3  [emitted] [dev]
browser-app:                            30.bundle.js  24.9 KiB      30  [emitted]
browser-app:                        30.bundle.js.map  15.8 KiB      30  [emitted] [dev]
browser-app:                            31.bundle.js  14.4 KiB      31  [emitted]
browser-app:                        31.bundle.js.map  16.8 KiB      31  [emitted] [dev]
browser-app:                            32.bundle.js  14.4 KiB      32  [emitted]
browser-app:                        32.bundle.js.map  16.8 KiB      32  [emitted] [dev]
browser-app:                            33.bundle.js   7.5 KiB      33  [emitted]
browser-app:                        33.bundle.js.map  5.76 KiB      33  [emitted] [dev]
browser-app:                            34.bundle.js  9.35 KiB      34  [emitted]
browser-app:                        34.bundle.js.map  16.1 KiB      34  [emitted] [dev]
browser-app:                            35.bundle.js  10.9 KiB      35  [emitted]
browser-app:                        35.bundle.js.map  7.86 KiB      35  [emitted] [dev]
browser-app:                            36.bundle.js  4.49 KiB      36  [emitted]
browser-app:                        36.bundle.js.map  2.82 KiB      36  [emitted] [dev]
browser-app:                            37.bundle.js  13.7 KiB      37  [emitted]
browser-app:                        37.bundle.js.map  16.3 KiB      37  [emitted] [dev]
browser-app:                            38.bundle.js  13.7 KiB      38  [emitted]
browser-app:                        38.bundle.js.map  16.3 KiB      38  [emitted] [dev]
browser-app:                            39.bundle.js  13.7 KiB      39  [emitted]
browser-app:                        39.bundle.js.map  16.3 KiB      39  [emitted] [dev]
browser-app:                             4.bundle.js  29.3 KiB       4  [emitted]
browser-app:                         4.bundle.js.map  19.4 KiB       4  [emitted] [dev]
browser-app:                            40.bundle.js  13.7 KiB      40  [emitted]
browser-app:                        40.bundle.js.map  16.3 KiB      40  [emitted] [dev]
browser-app:                            41.bundle.js  13.7 KiB      41  [emitted]
browser-app:                        41.bundle.js.map  16.3 KiB      41  [emitted] [dev]
browser-app:                            42.bundle.js  13.7 KiB      42  [emitted]
browser-app:                        42.bundle.js.map  16.3 KiB      42  [emitted] [dev]
browser-app:                            43.bundle.js  13.7 KiB      43  [emitted]
browser-app:                        43.bundle.js.map  16.3 KiB      43  [emitted] [dev]
browser-app:                            44.bundle.js  13.7 KiB      44  [emitted]
browser-app:                        44.bundle.js.map  16.3 KiB      44  [emitted] [dev]
browser-app:                            45.bundle.js  13.7 KiB      45  [emitted]
browser-app:                        45.bundle.js.map  16.3 KiB      45  [emitted] [dev]
browser-app:                            46.bundle.js  3.05 KiB      46  [emitted]
browser-app:                        46.bundle.js.map  2.49 KiB      46  [emitted] [dev]
browser-app:                            47.bundle.js  1.97 KiB      47  [emitted]
browser-app:                        47.bundle.js.map  1.56 KiB      47  [emitted] [dev]
browser-app:                             5.bundle.js  22.3 KiB       5  [emitted]
browser-app:                         5.bundle.js.map  16.5 KiB       5  [emitted] [dev]
browser-app:                             6.bundle.js   890 KiB       6  [emitted]
browser-app:                         6.bundle.js.map   939 KiB       6  [emitted] [dev]
browser-app:    674f50d287a8c48dc19ba404d20fe713.eot   162 KiB          [emitted]
browser-app:                             7.bundle.js  31.5 KiB       7  [emitted]
browser-app:                         7.bundle.js.map  29.3 KiB       7  [emitted] [dev]
browser-app:                             8.bundle.js    61 KiB       8  [emitted]
browser-app:                         8.bundle.js.map  64.8 KiB       8  [emitted] [dev]
browser-app:                             9.bundle.js   587 KiB       9  [emitted]
browser-app:                         9.bundle.js.map   679 KiB       9  [emitted] [dev]
browser-app:    912ec66d7572ff821749319396470bde.svg   434 KiB          [emitted]
browser-app:  af7ae505a9eed503f8b8e6982036873e.woff2  75.4 KiB          [emitted]
browser-app:    b06871f281fee6b241d60582ae9369b9.ttf   162 KiB          [emitted]
browser-app:                               bundle.js  5.38 MiB    main  [emitted]        main
browser-app:                           bundle.js.map  5.67 MiB    main  [emitted] [dev]  main
browser-app:    cf2aabacdc2b3a5768b03545cb1d8330.svg    21 KiB          [emitted]
browser-app:  de59a97248b44599e6747a27a943f738.woff2  19.8 KiB          [emitted]
browser-app:  e19892df121e7f85c61754c54bbb7951.woff2  48.6 KiB          [emitted]
browser-app:    e817279537a0417d042f62fbb1b99eea.gif  43.1 KiB          [emitted]
browser-app:   f8f821a66b20e5801e35df5ec4565b30.wasm   583 KiB          [emitted]
browser-app:   fee66e712a8a08eef5805a46892932ad.woff  95.7 KiB          [emitted]
browser-app:            vs/base/worker/workerMain.js   489 KiB          [emitted]
browser-app:        vs/base/worker/workerMain.js.map   661 KiB          [emitted]
browser-app:               vs/editor/editor.main.css   255 KiB          [emitted]
browser-app:                vs/editor/editor.main.js  5.19 MiB          [emitted]
browser-app:            vs/editor/editor.main.js.map  8.03 MiB          [emitted]
browser-app:         vs/editor/editor.main.nls.de.js  41.3 KiB          [emitted]
browser-app:         vs/editor/editor.main.nls.es.js  41.8 KiB          [emitted]
browser-app:         vs/editor/editor.main.nls.fr.js  45.2 KiB          [emitted]
browser-app:         vs/editor/editor.main.nls.it.js  43.5 KiB          [emitted]
browser-app:         vs/editor/editor.main.nls.ja.js  45.9 KiB          [emitted]
browser-app:            vs/editor/editor.main.nls.js  35.6 KiB          [emitted]
browser-app:         vs/editor/editor.main.nls.ko.js  41.9 KiB          [emitted]
browser-app:         vs/editor/editor.main.nls.ru.js    63 KiB          [emitted]
browser-app:      vs/editor/editor.main.nls.zh-cn.js  34.2 KiB          [emitted]
browser-app:      vs/editor/editor.main.nls.zh-tw.js  34.3 KiB          [emitted]
browser-app:              vs/language/css/cssMode.js  28.2 KiB          [emitted]
browser-app:            vs/language/css/cssWorker.js   597 KiB          [emitted]
browser-app:  vs/language/css/monaco.contribution.js  2.11 KiB          [emitted]
browser-app:            vs/language/html/htmlMode.js  27.3 KiB          [emitted]
browser-app:          vs/language/html/htmlWorker.js   337 KiB          [emitted]
browser-app: vs/language/html/monaco.contribution.js  2.14 KiB          [emitted]
browser-app:                            vs/loader.js  77.8 KiB          [emitted]
browser-app:                        vs/loader.js.map    88 KiB          [emitted]
browser-app: Entrypoint main = bundle.js bundle.js.map
browser-app: [../node_modules/@theia/core/src/common/keyboard/layouts sync recursive ^\.\/.*\.json$] ../node_modules/@theia/core/src/common/keyboard/layouts sync ^\.\/.*\.json$ 1.39 KiB {main} [built]
browser-app: [../node_modules/moment/locale sync recursive ^\.\/.*$] ../node_modules/moment/locale sync ^\.\/.*$ 3 KiB {31} {32} {37} {38} {39} {40} {41} {42} {43} {44} {45} [optional] [built]
browser-app: [../node_modules/vscode-textmate/release sync recursive] ../node_modules/vscode-textmate/release sync 160 bytes {31} {32} [built]
browser-app: [../my_plugin/lib/browser/my_plugin-contribution.js] 2.62 KiB {36} [built]
browser-app: [../my_plugin/lib/browser/my_plugin-frontend-module.js] 617 bytes {36} [built]
browser-app: [./src-gen/frontend/index.js] 3.89 KiB {main} [built]
browser-app:     + 1334 hidden modules
browser-app: WARNING in ../node_modules/vscode-textmate/release/main.js 23:15-27
browser-app: Critical dependency: the request of a dependency is an expression
browser-app:  @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js
browser-app:  @ ../node_modules/@theia/monaco/lib/browser/textmate/index.js
browser-app:  @ ../node_modules/@theia/json/lib/browser/json-frontend-module.js
browser-app:  @ ./src-gen/frontend/index.js
browser-app: WARNING in ../node_modules/vscode-textmate/release/main.js
browser-app: Module Warning (from ../node_modules/source-map-loader/index.js):
browser-app: (Emitted value instead of an instance of Error) Cannot find SourceMap 'main.js.map': Error: Can't resolve './main.js.map' in '/home/ubuntu/theia2/theia/my_plugin/node_modules/vscode-textmate/release'
browser-app:  @ ../node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js 73:24-50
browser-app:  @ ../node_modules/@theia/monaco/lib/browser/textmate/index.js
browser-app:  @ ../node_modules/@theia/json/lib/browser/json-frontend-module.js
browser-app:  @ ./src-gen/frontend/index.js
browser-app: WARNING in ../node_modules/typescript-language-server/lib/commands.js
browser-app: Module Warning (from ../node_modules/source-map-loader/index.js):
browser-app: (Emitted value instead of an instance of Error) Cannot find source file '../src/commands.ts': Error: Can't resolve '../src/commands.ts' in '/home/ubuntu/theia2/theia/my_plugin/node_modules/typescript-language-server/lib'
browser-app:  @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-contribution.js 93:17-67
browser-app:  @ ../node_modules/@theia/typescript/lib/browser/typescript-frontend-module.js
browser-app:  @ ./src-gen/frontend/index.js
(node:3287) UnhandledPromiseRejectionWarning: Error: Command failed: npm run prepare
please install @theia/electron@0.10.0 as a runtime dependency
Error: webpack exited with an unexpected signal: SIGKILL.
    at ChildProcess.<anonymous> (/home/ubuntu/theia2/theia/my_plugin/node_modules/@theia/application-manager/lib/application-process.js:59:28)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-app@0.0.0 prepare: `theia build --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-app@0.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-09-17T18_22_58_164Z-debug.log


> electron-app@0.0.0 prepare /home/ubuntu/theia2/theia/my_plugin/electron-app
> theia build --mode development


    at Promise.all.then.arr (/home/ubuntu/theia2/theia/my_plugin/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:3287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.

**Comment by vince-fugnitto** [comment] 2019-09-17 18:53
The issue is likely fixed by https://github.com/theia-ide/generator-theia-extension/pull/39, but no new version of the generator has yet to be published.

The issue comes from the fact that we cannot specify a default value when calling the generator. You can however call, `yo theia-extension` and follow the generator wizard.

**Comment by vince-fugnitto** [comment] 2019-09-17 19:04
> mkdir pluginDir
> cd pluginDir/
> yo theia-extension pluginDir
> 
> After that:
> yarn prepare


Here I'd do:
```
yo theia-extension
```

and not

```
yo theia-extension pluginDir
```

**Comment by dhananjayharel** [comment] 2019-09-18 13:17
I was able to build it... it was machine issue.. it doesn't have enough memory in my linux box.
created swap partition in it and now working fine.
thanks

**Comment by vince-fugnitto** [comment] 2019-09-18 13:22
Thanks for getting back and providing the reason! :)

**Closed by vince-fugnitto** 2019-09-18 13:22 UTC
Labels: :thinking: needs more info
