### ISSUE TITLE
electron window become unresponsive on windows laptop

### ISSUE THREAD

**Issue by linhanyu** [eclipse-theia/theia#10126] opened 2021-09-17 07:48 UTC
### Bug Description:
Some test user (about 2 / 100) report that their window become unresponsive after wake up for a period of time( about 6 hours or more). It's only appear on windows 10 laptop.

What strange is that, they can manipulate menus for beginning, but become unresponsive after keyboard input on terminal. So I'm suspect something block in backend server.

### Steps to Reproduce:

It's occasionally happened. 

### Additional Information

- Operating System: windows10
- Theia Version: 1.11.0 to 1.17.2

**Comment by vince-fugnitto** [comment] 2021-09-17 11:58
@linhanyu thank you for reporting the issue :+1: 

Unfortunately, I'm not sure how actionable the issue is on it's own, there is not enough information provided in order to reproduce, determine the cause, and what a fix might be. It would be good if you can obtain more information given it has happened to your users.

**Comment by msujew** [comment] 2024-06-04 22:42
Given the lack of reproducibility, I'm closing this.

**Closed by msujew** 2024-06-04 22:42 UTC
Labels: OS/Windows, :thinking: needs more info
