### ISSUE TITLE
Down-arrow key should move cursor down in editor

### ISSUE THREAD

**Issue by gbodeen** [eclipse-theia/theia#7137] opened 2020-02-11 20:29 UTC
### Description
Two unexpected behaviors of the down-arrow key.

Within the main editor pane, the keyboard down-arrow key no longer moves the cursor down.  The up-arrow, left-arrow, and right-arrow keys still work as expected.

Within the file explorer widget, the up-arrow key moves up to the next item in the tree.  For a directory, the down-arrow key toggles a directory from expanded to collapsed state.  For a file, the down-arrow key opens the file and moves the cursor to the editor pane.

### Reproduction Steps
On the Theia master branch, run `yarn` and `yarn start:electron`. Open any workspace and use the arrow keys to move around.

**OS and Theia version:
Known to occur on RHEL7 with Theia 0.15.0.
Known not to occur on RHEL7 with Theia 0.14.0.
I'll investigate further regarding which commit introduces the issue.

**Diagnostics:** 
I'm unsure which diagnostics are desired but can provide.  No error messages or warnings were printed to the console.

**Comment by akosyakov** [comment] 2020-02-11 20:31
Can you reproduce it from sources in this repo?

**Comment by gbodeen** [comment] 2020-02-11 22:22
Yes, if I open this repo as the workspace and look at, e.g., the base directory README.md, the problem occurs there.

I ran a git-bisect and the commit where this behavior was introduced is:
commit d5f4a867599156712f93c578bcf59d2efdf268a7
Date:   Tue Jan 14 04:37:20 2020 +0000
[keybinding] fix #6878: allow a user to change default keybindings

**Comment by vince-fugnitto** [comment] 2020-02-11 23:12
@gbodeen I was unable to reproduce the problem regarding <kbd>down-arrow</kbd> when navigating the `README.md` as you mentioned, do you perhaps have additional information regarding if you've updated the default keybindings? (it will help in troubleshooting the issue)

It's easy to check if you open the `keymaps.json`:
1. in the `File` menu, select `Settings` > `Open Keyboard Shortcuts`
2. click the `JSON` toolbar item which displays the content of `keymaps.json`

**Comment by gbodeen** [comment] 2020-02-11 23:41
Hi Vince, keymaps.json is an empty file. I tried editing it (via the UI) to the following:

```
[
    {
        "command": "cursorDown",
        "keybinding": "shift+up",
        "when": "textInputFocus"
    },
    {
        "command": "-cursorDown",
        "keybinding": "down",
        "when": "textInputFocus"
    }
]
```

Then shift+up moves the cursor down within the editor as expected.  We're using Red Hat Enterprise Linux Server release 7.7 (Maipo) accessed via Citrix Receiver, and I'd be inclined to think it's a Citrix issue, altering the "down" keybinding somehow, except that the problem did not occur prior to the commit mentioned above. So it's at least an interaction between the environment and the code.

(We also tested gitpod and Ubuntu 19.04.  The problem does not occur on these.)

**Comment by vince-fugnitto** [comment] 2020-02-11 23:45
> Hi Vince, keymaps.json is an empty file. I tried editing it (via the UI) to the following:
> 
> ```
> [
>     {
>         "command": "cursorDown",
>         "keybinding": "shift+up",
>         "when": "textInputFocus"
>     },
>     {
>         "command": "-cursorDown",
>         "keybinding": "down",
>         "when": "textInputFocus"
>     }
> ]
> ```
> 
> Then shift+up moves the cursor down within the editor as expected. We're using Red Hat Enterprise Linux Server release 7.7 (Maipo) accessed via Citrix Receiver, and I'd be inclined to think it's a Citrix issue, altering the "down" keybinding somehow, except that the problem did not occur prior to the commit mentioned above. So it's at least an interaction between the environment and the code.
> 
> (We also tested gitpod and Ubuntu 19.04. The problem does not occur on these.)

Thank you for coming back with additional information, on my end I was unable to reproduce the same problem on both Gitpod and macOS.

**Comment by gbodeen** [comment] 2020-02-12 00:12
`xev` gives the same "keysym 0xff54, Down" on both working and non-working systems, so that eliminates the possibility of Citrix Receiver intercepting/mutating the keystroke.

**Comment by kittaakos** [comment] 2020-02-12 08:55
FYI: I had a very similar experience: https://github.com/eclipse-theia/theia/issues/7133
I could not move the cursor in the editor. It happened a few times since the last Theia release. I was also unable to zoom in/out.

**Comment by akosyakov** [comment] 2020-02-12 10:30
> FYI: I had a very similar experience: #7133
I could not move the cursor in the editor. It happened a few times since the last Theia release. I was also unable to zoom in/out.

I'm not sure that it is the same, in your case keybindings are applied to another editor. In this case some keybindings are applied and other not to the same focused editor. @gbodeen could you check whether you have several editors and then you move down it just happens for another editor?

**Comment by gbodeen** [comment] 2020-02-12 21:55
Found it.  

First, the problem went away if I commented out the `keydownListener.dispose()` line in the `suppressMonacoKeybindingListener` method that was introduced in the commit mentioned above.  This means Monaco's listener was working fine, but the fallback listener was having a keybinding problem on our machines.

In `packages/core/src/browser/keyboard/key.ts`, in the `toKey` function, the first conditional checks if `event.code` is falsy.  For us it isn't, but it's also not the information we want.  On our RHEL7 machines, the information we want is in `event.keyCode`, which is tested in the second conditional.  So if I move the second conditional in front of the first, everything works correctly for us.  A comment mentions that `event.keyCode` has been deprecated; I guess that's the pitfall of us using an old OS.

**Comment by akosyakov** [comment] 2020-02-13 08:22
> In packages/core/src/browser/keyboard/key.ts, in the toKey function, the first conditional checks if event.code is truthy. For us it is truthy, but it's also not the information we want. On our RHEL7 machines, the information we want is in event.keyCode, which is tested in the second conditional. So if I move the second conditional in front of the first, everything works correctly for us. A comment mentions that event.keyCode has been deprecated; I guess that's the pitfall of us using an old OS.

@spoenemann do you see any consequences for checking `keyCode` first? As far as I remember It is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and that's why we check it only as a fall back. I'm not sure whether we can check whether we un on old OS to inverse the check.

**Comment by spoenemann** [comment] 2020-02-13 08:50
> For us it is truthy, but it's also not the information we want. On our RHEL7 machines, the information we want is in event.keyCode, which is tested in the second conditional.

@gbodeen what does "we want" mean? How did you get to this conclusion?

> do you see any consequences for checking keyCode first?

Yes. We need to get the code of the pressed key that corresponds to a standard US keyboard in order for the keyboard layout service to work properly. `keyCode` does _not_ meet this requirement. For example, if I press `Y` on my German keyboard, `code === 'KeyZ'`, but `keyCode === 89`, which corresponds to `KeyY`.

**Comment by gbodeen** [comment] 2020-02-13 22:47
I think this is a local IT problem for my team. Our key codes should follow the standards, but do not.

**Comment by spoenemann** [comment] 2020-02-14 07:54
What are the `code`s of your arrow keys?
You can check here: https://w3c.github.io/uievents/tools/key-event-viewer.html

**Comment by gbodeen** [comment] 2020-02-14 16:18
The `event.code`s we saw for (left, up, right, down) arrows are (Convert, undefined, NonConvert, NumpadEnter).  A variety of other keys have missing or misdefined `code`s, in no particular pattern that we've noticed.  The `event.key` and `event.keyCode` values are all correct, however.

Google finds no other reports of that, which is why I think it's a local issue best fixed by IT for my team.  Only if that IT request goes nowhere, we'll have to make a PR or customize the core package.  On second thought from what I wrote earlier, we'd probably modify it to use `event.key`.

**Comment by spoenemann** [comment] 2020-02-17 07:37
`key` gives you the actual character produced by the keystroke, including any pressed modifiers. In order to use that as a basis for keybindings, we would have to reverse-map the character to the key that was pressed. With `code` we directly get the pressed key.

**Comment by spoenemann** [comment] 2020-02-17 07:41
> I think it's a local issue best fixed by IT for my team.

I'll close this for now. Please Let us know if you can't fix it locally. In that case we could consider making the keyboard event processing better adaptable, e.g. by allowing to disable the usage of the `code` field.

**Closed by spoenemann** 2020-02-17 07:41 UTC
Labels: bug, editor, help wanted, keybindings
