### ISSUE TITLE
[preview/md] Scroll preview with editor

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-theia/theia#2537] opened 2018-08-09 11:56 UTC
The sole reason this was not implemented in the beginning was, that throttling of scroll events and computing the top most visible line in editor was not as accurate as needed. And scrolling of the preview works only immediately, as the built-in smooth scroll leads to other issues with the reveal on click. AFAIR the underlying issue was, that there is no signal when the smooth scroll stops, and interrupting of same behaves unpredictable.
We can easily create a cancelable (almost-)smooth scroll, to support scroll sync in both directions.

**Comment by vince-fugnitto** [comment] 2020-01-30 18:15
The issue is closed by #5442 :champagne:

**Closed by vince-fugnitto** 2020-01-30 18:15 UTC
Labels: enhancement, preview
