### ISSUE TITLE
Notebook web view iframe is collapsed

### ISSUE THREAD

**Issue by mkhubaibumer** [eclipse-theia/theia#13139] opened 2023-12-01 17:44 UTC
### Bug Description:
Opening Notebook with interactive widgets and running that with Theia results in collapsed web view iframe and doesn't renders the view properly

### Steps to Reproduce:

1. Clone this open source repository https://github.com/WillKoehrsen/Data-Analysis.git
2. Open notebook under Data-Analysis/widgets/Widgets-Overview.ipynb
3. Run the cells

### Additional Information

![Screenshot 2023-12-01 at 10 42 01 PM](https://github.com/eclipse-theia/theia/assets/119607707/47e03443-2b57-4e5b-b453-d9670c12d5ea)

https://github.com/eclipse-theia/theia/assets/119607707/e5519b0b-19bb-4f54-86d7-bc4e622cf95b

- Operating System: Mac OSX
- Theia Version: 1.43.0

**Comment by msujew** [comment] 2023-12-01 19:09
cc @jonah-iden you might want to take a look at this if you have time.

**Comment by JonasHelming** [comment] 2024-01-11 13:32
@jonah-iden @msujew This looks a but like a blocker for the use case, any idea if and when you could look at this?

**Comment by jonah-iden** [comment] 2024-01-12 08:45
I'll see if i can take a look next week. Can't promise anything though, since i don't have alot of time left this mont for open source projects

**Comment by JonasHelming** [comment] 2024-01-12 09:45
@jonah-iden Sounds great! Based on the high quality of this bug report, I would assume @mkhubaibumer could potentially support with testing any fix.

**Comment by JonasHelming** [comment] 2024-01-12 09:46
@mkhubaibumer One question, though: Could you quickly verify that the bug still occurs in 1.45?

**Comment by bvenreply** [comment] 2024-01-12 09:52
@JonasHelming on my end I can still reproduce the issue on 1.45. I'm also available to test any fix if needed.

**Comment by JonasHelming** [comment] 2024-01-18 18:25
@jonah-iden Any chance we can get this fixed in 1.46?

**Comment by jonah-iden** [comment] 2024-01-19 07:47
I'll take a look at it today. If its not to complex i should be able to hopefully create a PR today. I just don't have alot of time left  this month

**Comment by jonah-iden** [comment] 2024-01-19 08:27
@bvenreply im having some issues with running the notebook.
When running the first cell i get  `Jupyter command `jupyter-nbextension` not found.`
When i ignore that in the secon cell im getting
```
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
```
ignoring that again, installing all neccessary packages and pulling the pandas import down to the data cell the other cells are just running forever without displaying a result when executing

**Comment by bvenreply** [comment] 2024-01-19 08:34
@jonah-iden Sorry I don't know about that specific notebook, I think you should rather ask @mkhubaibumer.

As far as I know the issue arises when rendering any interactive figure created with the `plotly` library. I can look into creating a small example myself, If I'm able to do so quickly I'll post it here.

**Comment by bvenreply** [comment] 2024-01-19 08:43
@jonah-iden Ok I was able to reproduce this very straight-forwardly.

Install python packages in any python environment (just make sure to take note which and use it for the notebook) with `pip install -U plotly nbformat`

Then create a notebook, create a cell with this code
```python
# x and y given as array_like objects
import plotly.express as px
fig = px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16])
fig.show()
```
Run the notebook. Results for me, vscode vs Theia:

![image](https://github.com/eclipse-theia/theia/assets/105274814/d1ae8925-270c-485b-9c03-ffeff319a24f)

Let me know if you can work with this.

**Comment by jonah-iden** [comment] 2024-01-19 08:45
@bvenreply thank you! that example works perfectly for me. I was able to reproduce the issue

**Closed** 2024-01-22 09:14 UTC
Labels: ui/ux, notebook
