### ISSUE TITLE
"window.showTextDocument" Does Not open Resources With "untitled" Scheme

### ISSUE THREAD

**Issue by TomHermanSAP** [eclipse-theia/theia#6565] opened 2019-11-17 10:54 UTC
### Description
Using SQLTools extension **(0.21.3)**, https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools.
When trying to connect to a db at the first time, SQLite dependency is installed.
The dependency can be installed automatically if using in User preferences:
```
"sqltools.dependencyManager": {
        "autoAccept": true
    }
```

Based on https://github.com/mtxr/vscode-sqltools/releases/tag/v0.21.2.

In vscode no error apears, yet in gitprod the following error notification appears:
![SQLTools - Error installing dependency SQLite](https://user-images.githubusercontent.com/54273024/69006427-ab4ca680-0937-11ea-9e01-24d9f478675b.jpg)

### Reproduction Steps
1. Download SQLTools extension (current version 0.21.3)
2. Create in workspace/theia a new file called "tom.db".
3. Add to User preferences the following values:
```
{
    "sqltools.useNodeRuntime": true,
    "sqltools.dependencyManager": {
        "autoAccept": true
    },
    "sqltools.connections": [
        {
            "name": "sqlite",
            "dialect": "SQLite",
            "database": "workspace/theia/tom.db"
        }
    ]
}
```
![image](https://user-images.githubusercontent.com/54273024/69006518-8ad11c00-0938-11ea-9f8d-3ebdf45024c6.png)

4. Click on SQLTools extension. In "sqlite" linem, click on connect:
![image](https://user-images.githubusercontent.com/54273024/69006533-da174c80-0938-11ea-90a7-5fb8c363c9ec.png)

5. Expect the error notification displayed in the **Description** section to appear.

**OS and Theia version:**
- https://gitpod.io/#https://github.com/eclipse-theia/theia:
- Share code: e1c15265-b237-435c-87e5-255f22e8c298

**Diagnostics:** 
![SQLTools - Error installing dependency SQLite](https://user-images.githubusercontent.com/54273024/69006471-f9fa4080-0937-11ea-81f8-cb962058a93b.jpg)
![SQLTools - Error installing dependency SQLite - Log Info](https://user-images.githubusercontent.com/54273024/69006472-fbc40400-0937-11ea-9365-d8a09b761712.jpg)

**Comment by akosyakov** [comment] 2019-12-02 05:43
It would be helpful if someone investigates what is missing.

**Comment by amiramw** [comment] 2019-12-02 07:38
@TomHermanSAP and me are investigating.

**Comment by amiramw** [comment] 2019-12-05 08:11
I think we found the gap.

This is a minimal code that reproduce it:

```
const uri = vscode.Uri.file(os.homedir + '/newnew.txt');
const fileUri = vscode.Uri.parse(`untitled:${uri}`).with({ scheme: 'untitled' });
vscode.window.showTextDocument(fileUri);
```

We tried it with hosted theia. The editor doesn't open and we get this error on theia:
```
root ERROR [hosted-plugin: 9850] Promise rejection not handled in one second: Error: TypeError: Cannot read property 'dispose' of undefined
root ERROR [hosted-plugin: 9850] With stack trace: Error: TypeError: Cannot read property 'dispose' of undefined
    at e.<anonymous> (https://webide-workspaces-ws-qwkth-app5.cry10.int.webide.cloud.sap/bundle.js:19:785104)
    at https://webide-workspaces-ws-qwkth-app5.cry10.int.webide.cloud.sap/bundle.js:19:781329
    at Object.throw (https://webide-workspaces-ws-qwkth-app5.cry10.int.webide.cloud.sap/bundle.js:19:781434)
    at s (https://webide-workspaces-ws-qwkth-app5.cry10.int.webide.cloud.sap/bundle.js:19:780231)
```

On VS Code this code opens a new tab with unsaved document newnew.txt.

**Comment by TomHermanSAP** [comment] 2019-12-08 12:37
Seems like "untitled" scheme does not have a resource resolver "ResourceResolver" (for example as File Resource has:
https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/browser/file-resource.ts#L143

**Comment by offer8** [comment] 2019-12-16 13:21
Do you know why the untitled file created by this method: "createUntitledResource"(https://github.com/eclipse-theia/theia/blob/e147cf39c7f484374b7ec0cd0d04958c3ef00bca/packages/plugin-ext/src/main/browser/editor/untitled-resource.ts#L49)
is read-only one?

**Comment by offer8** [comment] 2019-12-17 11:24
Found it:
https://github.com/eclipse-theia/theia/blob/master/packages/monaco/src/browser/monaco-editor-model.ts#L199

**Comment by offer8** [comment] 2019-12-17 16:10
@akosyakov after investigation, there seems to be 2 options to proceed:
1. "UntitledResourceResolver" - add support to create files in file systems
2. Direct 'untitled' schema typed files to be resolved by the "FileResourceResolver" somehow. 
We tried and currently it cannot find files because it is concatenating 'untitiled' to file url, as seen here:

```
root ERROR [hosted-plugin: 18608] With stack trace: Error: Error: 'untitled:file%3A///c%3A/Users/i055501/newnew.txt' has not been found.
    at DocumentsMainImpl.<anonymous> (http://localhost:3000/47.bundle.js:338:31)
    at step (http://localhost:3000/47.bundle.js:153:23)
    at Object.throw (http://localhost:3000/47.bundle.js:134:53)
    at rejected (http://localhost:3000/47.bundle.js:126:65)
```

Do you a proposal how to continue?

**Comment by akosyakov** [comment] 2019-12-18 08:37
> "UntitledResourceResolver" - add support to create files in file systems

@offer8 Can it be implemented by delegating to `FileResourceResolver`? i.e. whenever `saveContents` a user is prompted to save a file and then an instance of `FileResource` is created, to which `UntitledResource` delegates all calls

**Comment by akosyakov** [comment] 2020-01-01 18:25
@amiramw @TomHermanSAP @offer8 Could you test https://github.com/eclipse-theia/theia/pull/6803 please?

**Closed** 2020-02-24 10:33 UTC
Labels: bug, help wanted, vscode

**Comment by offer8** [comment] 2020-02-24 15:21
@akosyakov can this one be part of v0.16.0 release?

**Comment by amiramw** [comment] 2020-02-24 19:49
it's in the master and 0.16.0 was not released yet so why not?
