### ISSUE TITLE
[terminal] Vertical scrollbar does not show in the terminal

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#1954] opened 2018-05-24 18:31 UTC
Vertical scroll in terminal does not show (On Chrome, but is showing in Firefox). Execute a command that should trigger the vertical scroll to show i.e. 'ls -alF' in a folder with many entries. We can use the mouse wheel, but not th vertcal scrollbar.

It looks like the view area of the terminal overlaps the space needed to display the vertical scrollbar.
 
Resize the width of Theia does not show the vertical scroll either. Sometimes, we can see the vertical scroll when we en-large the terminal area, but never shows when reducing the terminal.
Tested on ubuntu 16.04 operating system

**Comment by svenefftinge** [comment] 2019-05-15 01:55
Cannot reproduce. I think this has been solved in the meantime.

**Comment by AndrienkoAleksandr** [comment] 2019-05-15 09:13
This limitation still in the code: https://github.com/theia-ide/theia/blob/master/packages/terminal/src/browser/terminal-widget-impl.ts#L369

**Comment by karimaijala** [comment] 2019-12-30 05:17
I have the same issue on Ubuntu 18.04 LTS, Chrome 78.0.3904.108, Theia@f255f5a8.
The vertical scrollbar of the terminal window alternates between invisible, partially visible or completely visible depending on the width of the browser window.

Screen shots:
![terminal-scrollbar-invisible](https://user-images.githubusercontent.com/5416703/71568968-4e1a4800-2ad4-11ea-8a8f-d03e23d28a68.png)

![terminal-scrollbar-visible](https://user-images.githubusercontent.com/5416703/71568983-5ecabe00-2ad4-11ea-8ea9-7fcabedc8b73.png)

**Comment by akosyakov** [comment] 2020-01-01 19:40
I had the same another day:
<img width="445" alt="Screen Shot 2020-01-02 at 00 39 37" src="https://user-images.githubusercontent.com/3082655/71645321-6d91ba80-2cf8-11ea-972e-942b7abf8862.png">

**Comment by vince-fugnitto** [comment] 2020-07-08 21:14
Closing since there is a newer duplicate open tracking the small scrollbar: #8096

**Comment by vince-fugnitto** [comment] 2021-02-22 14:56
Re-opening, I was able to reproduce the issue on Firefox: https://github.com/eclipse-theia/theia/issues/8096#issuecomment-783431887

**Comment by vince-fugnitto** [comment] 2021-03-29 13:33
Closing in favor of https://github.com/eclipse-theia/theia/issues/8096.

**Closed by vince-fugnitto** 2021-03-29 13:33 UTC
Labels: browser/chrome, bug, help wanted, terminal
