### ISSUE TITLE
Show number of git changes in the sidebar

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#7210] opened 2020-02-25 00:26 UTC
### Description

Show number of git changes in the sidebar

Theia:
![image](https://user-images.githubusercontent.com/50386709/75203046-b8e1ab80-5732-11ea-9e9e-7a3f1654a547.png)

VSCode
![image](https://user-images.githubusercontent.com/50386709/75203137-f47c7580-5732-11ea-9367-db0a66603f78.png)

**Comment by vince-fugnitto** [comment] 2020-02-25 02:12
Thank you for the issue @JesterOrNot :)
Closing as it is a duplicate of https://github.com/eclipse-theia/theia/issues/4782.

**Closed by vince-fugnitto** 2020-02-25 02:12 UTC
Labels: enhancement, scm, ui/ux
