### ISSUE TITLE
[Monaco] Go to definition or references does not scroll to desired location

### ISSUE THREAD

**Issue by xcariba** [eclipse-theia/theia#11017] opened 2022-04-12 20:40 UTC
### Steps to Reproduce:

1. Install TS/JS extensions
2. Create file `myReference.js` which exports function called `myRefFunc` with a lot of new line before function: `\n\n\n\n\n\n\n\n\n export function myRefFunc() { }`
3. Create file `main.js` and import `myRefFunc` from `myReference`: `import { myRefFunc } from './myReference'`
4. Add function in `main.js` that calls `myRefFunc`: `function test() { myRefFunc() }`
5. Ctrl+Click on `myRefFunc()` call

It will open `myReference.js` but selection will stay on first line. It is expected to go to function.

### Additional Information

- Operating System: Fedora
- Theia Version: 1.24

**Comment by xcariba** [comment] 2022-04-12 21:14
Selection was passed here:
https://github.com/eclipse-theia/theia/blob/master/packages/monaco/src/browser/monaco-editor-service.ts#L110
but it was removed in #10736

**Comment by vince-fugnitto** [comment] 2022-04-13 16:04
> but it was removed in https://github.com/eclipse-theia/theia/pull/10736

@xcariba from what I can tell the code still exists, and the bug also exists in older versions of the framework (ex: verified with `1.20.0`) so it predates earlier than the recent monaco upgrade.

Ultimately I believe the issue is a duplicate of https://github.com/eclipse-theia/theia/issues/9495.

**Closed** 2022-04-21 13:10 UTC
Labels: editor, monaco
