### ISSUE TITLE
Multiple Unsupported Activation Events and Plugin Loading Errors in Theia 1.52.0 on Windows 11

### ISSUE THREAD

**Issue by wenhaofan** [eclipse-theia/theia#14003] opened 2024-08-05 08:57 UTC
### Bug Description:
During the setup of Theia using the provided steps and version, multiple errors related to unsupported activation events and plugin loading issues were encountered, leading to the inability to properly start Theia with the custom configuration.

### Steps to Reproduce:
1. Follow the installation and build instructions from the Theia documentation: https://theia-ide.org/docs/composing_applications
2. Run the commands:
   - `yarn`
   - `yarn theia build`
   - `yarn start`
3. Observe the errors in the console log during the startup process.

### Expected Behavior:
Theia should start without errors and all plugins should load successfully without causing activation event or provider registration conflicts.

- 
### Actual Behavior:
Multiple errors are thrown related to unsupported activation events and problems with registering file system providers, leading to a failed startup or improper functioning of Theia.

2024-08-05T08:48:42.777Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): initializing(yaml@1.88.1 with L:\Work\3d\theia-custom\lib\backend\plugin-vscode-init)
2024-08-05T08:48:42.777Z root ERROR [hosted-plugin: 12068] Unsupported activation events: onProfile, onProfile:github, please open an issue: https://github.com/eclipse-theia/theia/issues/new
2024-08-05T08:48:42.777Z root ERROR [hosted-plugin: 12068] Unsupported activation events: onWalkthrough:nodejsWelcome, please open an issue: https://github.com/eclipse-theia/theia/issues/new
2024-08-05T08:48:42.777Z root ERROR [hosted-plugin: 12068] Unsupported activation events: onEditSession:file, please open an issue: https://github.com/eclipse-theia/theia/issues/new
2024-08-05T08:48:42.783Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): PluginManagerExtImpl/loadPlugin(L:\Work\3d\theia-custom\plugins\vscode.emmet\extension\dist\node\emmetNodeMain)
2024-08-05T08:48:42.791Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): PluginManagerExtImpl/loadPlugin(L:\Work\3d\theia-custom\plugins\ms-vscode.js-debug\extension\src\extension.js)
2024-08-05T08:48:42.855Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): PluginManagerExtImpl/loadPlugin(L:\Work\3d\theia-custom\plugins\vscode.debug-auto-launch\extension\dist\extension)
2024-08-05T08:48:42.856Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): PluginManagerExtImpl/loadPlugin(L:\Work\3d\theia-custom\plugins\vscode.merge-conflict\extension\dist\mergeConflictMain)
2024-08-05T08:48:42.867Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): PluginManagerExtImpl/loadPlugin(L:\Work\3d\theia-custom\plugins\vscode.git-base\extension\dist\extension.js)
2024-08-05T08:48:42.878Z root INFO [hosted-plugin: 12068] Debug configuration provider has been registered: pwa-chrome, trigger: 1
2024-08-05T08:48:42.878Z root INFO [hosted-plugin: 12068] Debug configuration provider has been registered: chrome, trigger: 1
Debug configuration provider has been registered: pwa-msedge, trigger: 1
Debug configuration provider has been registered: msedge, trigger: 1
Debug configuration provider has been registered: pwa-extensionHost, trigger: 1
Debug configuration provider has been registered: extensionHost, trigger: 1
Debug configuration provider has been registered: pwa-node, trigger: 1
Debug configuration provider has been registered: node, trigger: 1
Debug configuration provider has been registered: node-terminal, trigger: 1
2024-08-05T08:48:42.878Z root INFO [hosted-plugin: 12068] Debug configuration provider has been registered: pwa-chrome, trigger: 1
Debug configuration provider has been registered: pwa-msedge, trigger: 1
Debug configuration provider has been registered: pwa-node, trigger: 1
Debug configuration provider has been registered: pwa-node, trigger: 2
2024-08-05T08:48:42.883Z root INFO [hosted-plugin: 12068] calling activation function on Emmet (built-in)
2024-08-05T08:48:42.883Z root INFO [hosted-plugin: 12068] calling activation function on JavaScript Debugger
calling activation function on Node Debug Auto-attach (built-in)
2024-08-05T08:48:42.886Z root INFO [hosted-plugin: 12068] calling activation function on Merge Conflict (built-in)
2024-08-05T08:48:42.887Z root INFO [hosted-plugin: 12068] calling activation function on Git Base (built-in)
2024-08-05T08:48:42.893Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): PluginManagerExtImpl/loadPlugin(L:\Work\3d\theia-custom\plugins\vscode.github\extension\dist\extension.js)
2024-08-05T08:48:42.906Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): PluginManagerExtImpl/loadPlugin(L:\Work\3d\theia-custom\plugins\vscode.git\extension\dist\main)
2024-08-05T08:48:42.949Z root INFO [hosted-plugin: 12068] calling activation function on GitHub (built-in)
2024-08-05T08:48:43.033Z root INFO [hosted-plugin: 12068] calling activation function on Git (built-in)
2024-08-05T08:48:43.046Z root INFO [28c32ccd-d8b1-4610-8df4-c1ea32de17ad] Starting plugins.
2024-08-05T08:48:43.046Z root INFO [28c32ccd-d8b1-4610-8df4-c1ea32de17ad] Start of 82 plugins: 507.3 ms [Finished 2999.454 s after frontend start]
2024-08-05T08:48:43.080Z root INFO [hosted-plugin: 12068] PLUGIN_HOST(12068): PluginManagerExtImpl/loadPlugin(L:\Work\3d\theia-custom\plugins\vscode.npm\extension\dist\npmMain)
2024-08-05T08:48:43.096Z root ERROR [hosted-plugin: 12068] Canonical URI provider for scheme: 'ssh' already exists globally
Canonical URI provider for scheme: 'https' already exists globally
2024-08-05T08:48:43.096Z root ERROR [hosted-plugin: 12068] Canonical URI provider for scheme: 'file' already exists globally  
2024-08-05T08:48:43.099Z root INFO [hosted-plugin: 12068] calling activation function on NPM support for VS Code (built-in)   
2024-08-05T08:48:43.105Z root ERROR [hosted-plugin: 12068] There is no document for breakpointinput:vs.editor.ICodeEditor%3A1 
2024-08-05T08:48:44.100Z root ERROR [hosted-plugin: 12068] Promise rejection not handled in one second: Error: A filesystem provider for the scheme 'git' is already registered. , reason: Error: A filesystem provider for the scheme 'git' is already registered.
2024-08-05T08:48:44.100Z root ERROR [hosted-plugin: 12068] With stack trace: Error: A filesystem provider for the scheme 'git' is already registered.
    at FileService.registerProvider (http://127.0.0.1:3000/bundle.js:94506:19)
    at new RemoteFileSystemProvider (http://127.0.0.1:3000/vendors-node_modules_theia_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5663:42)
    at FileSystemMainImpl.$registerFileSystemProvider (http://127.0.0.1:3000/vendors-node_modules_theia_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5570:40)
    at http://127.0.0.1:3000/vendors-node_modules_theia_notebook_lib_common_index_js-node_modules_theia_plugin-ext_lib_com-c8361e.js:1341:71
    at async RpcProtocol.handleRequest (http://127.0.0.1:3000/bundle.js:80420:28)

### Additional Information:
- **Operating System:** Windows 11
- **IDE:** Visual Studio Code
- **Theia Version:** 1.52.0

**Comment by zhouxinghong** [comment] 2024-08-05 09:01
The C# toolkit on Windows 10 systems doesn't work in Theia either.

**Comment by wenhaofan** [comment] 2024-08-05 12:29
> The C# toolkit on Windows 10 systems doesn't work in Theia either.Windows 10 系统上的 C# 工具包在 Theia 中也无法使用。

Hey, I haven't experienced that issue. Have you tried running Python and the debugger plugin locally?

**Comment by tsmaeder** [comment] 2024-08-05 13:26
@wenhaofan I can confirm that there are a bunch of unsupported activation events with the Theia built-ins. Unfortunately, the documentation on the VS Code side is woefully out of date (https://code.visualstudio.com/api/references/activation-events). 
I cannot confirm any of the file system provider-related issues, though. What is your application configuration (i.e. which Theia extensions do you include") and what plugins (aka VS Code extensions) at what version level do you have installed?

**Comment by wenhaofan** [comment] 2024-08-07 04:45
> @wenhaofan I can confirm that there are a bunch of unsupported activation events with the Theia built-ins. Unfortunately, the documentation on the VS Code side is woefully out of date (https://code.visualstudio.com/api/references/activation-events). I cannot confirm any of the file system provider-related issues, though. What is your application configuration (i.e. which Theia extensions do you include") and what plugins (aka VS Code extensions) at what version level do you have installed?

This configuration matches the official documentation and there are no differences from the recommended setup.
package.json
` {
  "private": true,
  "dependencies": {
    "@theia/callhierarchy": "latest",
    "@theia/file-search": "latest",
    "@theia/git": "latest",
    "@theia/markers": "latest",
    "@theia/messages": "latest",
    "@theia/navigator": "latest",
    "@theia/outline-view": "latest",
    "@theia/plugin-ext-vscode": "latest",
    "@theia/preferences": "latest",
    "@theia/preview": "latest",
    "@theia/search-in-workspace": "latest",
    "@theia/terminal": "latest",
    "@theia/vsx-registry": "latest"
  },
  "devDependencies": {
    "@theia/cli": "latest"
  },
  "scripts": {
    "prepare": "yarn run clean && yarn build && yarn run download:plugins",
    "clean": "theia clean",
    "build": "theia build --mode development",
    "start": "theia start --plugins=local-dir:plugins",
    "download:plugins": "theia download:plugins"
  },
  "theiaPluginsDir": "plugins",
  "theiaPlugins": {
    "vscode-builtin-extensions-pack": "https://open-vsx.org/api/eclipse-theia/builtin-extension-pack/1.50.1/file/eclipse-theia.builtin-extension-pack-1.50.1.vsix"
  },
  "theiaPluginsExcludeIds": [
    "ms-vscode.js-debug-companion",
    "vscode.extension-editing",
    "vscode.git",
    "vscode.git-ui",
    "vscode.github",
    "vscode.github-authentication",
    "vscode.microsoft-authentication"
  ]
}
`

**Comment by zhouxinghong** [comment] 2024-08-07 06:45
I think Python, Web, and a bunch of other extensions are not working properly...

**Comment by tsmaeder** [comment] 2024-08-07 07:21
@wenhaofan two things I can see immediately:

1. You are using the 1.50.1 version of the built-in extension pack. The extensions pack version correspond to VS Code version, not the Theia version, 1.88.1 would be the right version to use with recent Theia versions.
2. The git extension is deprecated. Use the vs code git built-in instead.

The documentation you linked is supposed to serve as an example, not a recipe. In general, it's better to base Theia applications on the example application the the theia repo or on https://github.com/eclipse-theia/theia-blueprint.

**Comment by tsmaeder** [comment] 2024-08-20 07:26
See https://github.com/eclipse-theia/theia-website/pull/587. Closing since we have an issue for the activation events and the other issue is suspected to be a configuration issue.

**Closed by tsmaeder** 2024-08-20 07:26 UTC
