### ISSUE TITLE
Extension view: give priority to the plugin's version instead of the icon when resizing

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7628] opened 2020-04-20 15:19 UTC
### Description
 
In the extension view, a priority should be given to always display the plugin's version. Currently, the priority is given to the icon.

### Reproduction Steps

- Open Theia
- Open The extension view
- Resize the view to allow minimal information being display on a line
--> When the width is minimal, we should at least see the plugin's version and portion of the plugin's name as a minimum.
Ref: See VSCode extension view

**OS and Theia version:**
Theia: latest
OS:: Ubuntu 18.04

**Diagnostics:** 

VSCOde resize:
![vscodeExtension_Version](https://user-images.githubusercontent.com/419051/79768251-869a9780-82f8-11ea-9909-917c3f6c85f4.gif)

Theia resize:
![theiaExtensionVersion](https://user-images.githubusercontent.com/419051/79768283-90bc9600-82f8-11ea-8e09-4340a2d3a051.gif)

**Comment by vince-fugnitto** [comment] 2020-04-20 15:32
Duplicate of https://github.com/eclipse-theia/theia/issues/7385

**Closed by vince-fugnitto** 2020-04-20 15:32 UTC
Labels: vsx-registry
