### ISSUE TITLE
[vscode] No error message if vscode.open command is invoked with resource that doesn't exist

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#5667] opened 2019-07-08 18:22 UTC
In VS Code, if you do `vscode.commands.executeCommand("vscode.open"` with a file that doesn't exist, you get an error message like the following:

![image](https://user-images.githubusercontent.com/8888438/60833225-c8a08580-a18b-11e9-8be6-59463c9a223e.png)

It would be nice if theia had the same behaviour.

**Comment by tolusha** [comment] 2019-08-08 09:30
I've just installed the extension [1] for testing purpose in VS Code.
It doesn't show any error messages above. I guess that error message comes from another place.

[1] https://github.com/tolusha/vscode-test-extensions/blob/master/open-some-file-0.0.1.vsix

**Comment by tolusha** [comment] 2019-08-08 09:30
@tetchel Could you tell what the exact usecase is?

**Comment by tsmaeder** [comment] 2019-08-14 07:51
@tolusha how are you sure the code you think you're executing is even executing? Without some log output or such you might just not executing the command.
However, since we don't have steps to reproduce, I am closing this one. @tetchel feel free to reopen if this is still a problem for you.

**Comment by tetchel** [comment] 2019-08-14 17:36
It's still an issue. In one of my extension's WebViews I have a button which opens a particular file. If that file is missing in VS Code, the user gets an error. If it's missing in Theia, the button appears to not work even though it is executing the command.

**Comment by tolusha** [comment] 2019-08-15 07:18
@tetchel 
Thank you. I've updated my test extension [1] and I am able to reproduce the bug.
Obviously VS Code try to create a new file [2] when it isn't found.

[1] https://github.com/tolusha/vscode-test-extensions/blob/master/open-some-file-0.0.1.vsix
[2] https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#L184

**Comment by svenefftinge** [comment] 2019-09-29 14:31
https://github.com/eclipse-theia/theia/pull/6290 might be the reason an error is ignored.

**Comment by vrubezhny** [comment] 2019-11-09 00:06
@tolusha's test extension doesn't work anymore as the following check is added for the command parameters at https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L79:
```
                if (!URI.isUri(resource)) {
                    throw new Error(`Invalid argument for ${VscodeCommands.OPEN.id} command with URI argument. Found ${resource}`);
                }
```
As result of the change the other kind of error is being reported instead of `Error: 'file:///bla-bla' has not been found.`:
```
root ERROR [hosted-plugin: 23072] Promise rejection not handled in one second: Error: Invalid argument for vscode.open command with URI argument. Found file:///bla-bla
root ERROR [hosted-plugin: 23072] With stack trace: Error: Invalid argument for vscode.open command with URI argument. Found file:///bla-bla
    at PluginVscodeCommandsContribution.<anonymous> (http://localhost:3000/91.bundle.js:217:39)
    at step (http://localhost:3000/91.bundle.js:155:23)
    at Object.next (http://localhost:3000/91.bundle.js:136:53)
    at http://localhost:3000/91.bundle.js:130:71
    at new Promise (<anonymous>)
    at push.../../packages/plugin-ext-vscode/lib/browser/plugin-vscode-commands-contribution.js.__awaiter (http://localhost:3000/91.bundle.js:126:12)
    at Object.execute (http://localhost:3000/91.bundle.js:208:68)
    at CommandRegistry.<anonymous> (http://localhost:3000/bundle.js:113517:62)
    at step (http://localhost:3000/bundle.js:113303:23)
    at Object.next (http://localhost:3000/bundle.js:113284:53)
```

@tolusha Could you please confirm that ` file:///bla-bla` is a valid URI that still can be used in the test?

**Comment by tolusha** [comment] 2019-11-11 08:10
@vrubezhny It used to work
Probably it doesn't path the instance of URI into the command.

**Comment by FernandoAscencio** [comment] 2023-03-01 15:33
Possible link to #3828 as it was handling that before.

**Closed** 2023-04-10 18:50 UTC
Labels: bug, vscode
