### ISSUE TITLE
Deploy plugin by id to have indication about the result

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8622] opened 2020-10-12 20:59 UTC
### Feature Description:

Deploy plugin by id currently runs as a command with no indication about its result. Deploying could reuslt in error or success and the end user doesn't know anything about it. 

It would be nice to have some indication in the UI about which plugins were installed and whether an entry has no resolver.

**Comment by vince-fugnitto** [comment] 2020-10-13 12:08
Closing since it is a duplicate of:
- https://github.com/eclipse-theia/theia/issues/5552
- https://github.com/eclipse-theia/theia/issues/3632

**Closed by vince-fugnitto** 2020-10-13 12:08 UTC
Labels: plug-in system, progress
