### ISSUE TITLE
Launching with "preLaunchTask" pointing to a tsc build task generate errors

### ISSUE THREAD

**Issue by alvsan09** [eclipse-theia/theia#8930] opened 2021-01-08 21:51 UTC
### Bug Description:
Debug launch with automatically generated tasks and launch files for a helloworld typescript program fail with errors

### Steps to Reproduce:

1. In an empty folder Create a **helloworld.ts** file and corresponding **tsconfig.json** (see example in [3])
2. From main menu Terminal-> Run Build Task, to configure/create a default task ***"tsc: bulild - tsconfig.json"***, the generated file under **.theia/tasks.json** shall look like [1].
3. Make sure your build works by selecting Terminal -> Run build task
4. Select your .ts file and click the main Debug icon, on the drop down menu 'No Configurations' select 'Add Configuration' and select **Node.js**, a new **launch.json** shall be created as in [2]
5. Press the green 'Play' button to the right of the new 'Launch Program' lauch
6. The following error appear:
![image](https://user-images.githubusercontent.com/76971376/104065939-93d11c80-51ce-11eb-895b-4831ac70b2e2.png)

### Additional Information

- Operating System: linux debian
- Theia Version: master branch, commit: 335273bf9

Reference project files:
[1] Generated tasks.json
```ts
{
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "problemMatcher": [
                "$tsc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

[2] Generated launch.json
```ts
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${file}",
      "preLaunchTask": "tsc: build - tsconfig.json",
      "outFiles": [
        "${workspaceFolder}/out/**/*.js"
      ]
    }
  ]
}
```

[3] Example tsconfig.json
```ts
{
    "compilerOptions": {
      "target": "es5",
      "module": "commonjs",
      "outDir": "out",
      "sourceMap": true
    }
  }
```

**Comment by vince-fugnitto** [comment] 2021-01-21 19:45
Closing thanks to #8949.

**Closed by vince-fugnitto** 2021-01-21 19:45 UTC
Labels: bug, debug, tasks

**Comment by 0xkiichiro** [comment] 2022-08-10 21:40
"tsc: bulild - tsconfig.json" there is a typo. pls fix

**Comment by vince-fugnitto** [comment] 2022-08-10 23:05
> "tsc: bulild - tsconfig.json" there is a typo. pls fix

@0xkiichiro can you clarify where the typo is in the code I do not see it? If you're referring to the description of the issue it is not important and quite old anyways (the issue is fixed as well).

**Comment by 0xkiichiro** [comment] 2022-08-12 12:26
under steps to reproduce 2nd step had "tsc: bulild - tsconfig.json" instead of "build".
