### ISSUE TITLE
[Feature Request] Terminal overlapping workspace

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#7158] opened 2020-02-14 18:56 UTC
### Description
Original post: https://github.com/gitpod-io/gitpod/issues/1222
The request is for a popup terminal that would overlap the workspace sort of like this
![](https://user-images.githubusercontent.com/11302521/74558734-1c195400-4f63-11ea-9f41-1c2076642264.png)

**Comment by vince-fugnitto** [comment] 2020-02-14 19:52
I'm not sure how useful such a feature would be, it is quite intrusive.
If one does not like the terminal at the bottom, they can always move it in the main area and be able to open many tabs (such as editors) and always go back to it. I'm not found of dialogs displaying in front of the application hiding information behind.

**Comment by Kreyren** [comment] 2020-02-14 20:13
To elaborate this is how my workspace usually looks like
![image](https://user-images.githubusercontent.com/11302521/74563531-4e2fb380-4f6d-11ea-9df2-abbb77ba8769.png)

If i get the terminal at the bottom i can't see the problems that may require multiple files open even even if i could i need at least 15 lines of terminal to see all the issues so the current best placement is like this

![image](https://user-images.githubusercontent.com/11302521/74563677-96e76c80-4f6d-11ea-8fba-77012ff24697.png)


Where i have to use tabs which is annoying 

and if i put the terminal at the side it just messes up everything once invoked

![image](https://user-images.githubusercontent.com/11302521/74563747-c1d1c080-4f6d-11ea-80b6-d36151524350.png)

I find this being quite inconvenient

**Comment by vince-fugnitto** [comment] 2020-02-14 22:15
> If i get the terminal at the bottom i can't see the problems that may require multiple files open even even if i could i need at least 15 lines of terminal to see all the issues so the current best placement is like this

You can always split in the bottom panel as well. One side the `problems` and the other side the `terminal` itself.

<div align='center'>

<img width="1398" alt="Screen Shot 2020-02-14 at 5 13 30 PM" src="https://user-images.githubusercontent.com/40359487/74572634-6c85b700-4f4d-11ea-9d90-5e61103752ff.png">

</div>

> I find this being quite inconvenient

The first time you dock the terminal to the side, it might mess up but only once.
You can always run `clear` or `reset` in the terminal and it should display properly if you experience issues.

<div align='center'>

<img width="1398" alt="Screen Shot 2020-02-14 at 5 14 54 PM" src="https://user-images.githubusercontent.com/40359487/74572712-917a2a00-4f4d-11ea-82cf-e89d6594700f.png">

</div>

I think the application is flexible to support any layout, but having a terminal within a dialog (or overlapping) is a bit intrusive and might cause problems (when is it cleared, when is it destroyed, etc).

**Comment by Kreyren** [comment] 2020-02-15 00:21
@vince-fugnitto afaik suggested is what i am doing atm, but i was hoping to get terminal on demand since i don't neccesary need the terminal to be present at all time it gets quite distracting when it's not needed where my usually workflow outside of gitpod is to press `Ctrl+\``  type, see the result and close it again with `Ctrl+\`` or reading through it on demand or kept it open while debugging.

Currently having the terminal at the left toolbar seems to be the most efficient for this purpose, but the issue is that it resizes the workspace (makes it pita to work on assuming multiple windows open) and that it takes around 2 seconds for the workspace to adjust once the terminal is toggled off.

**Comment by vince-fugnitto** [comment] 2020-02-15 00:56
> @vince-fugnitto afaik suggested is what i am doing atm, but i was hoping to get terminal on demand since i don't neccesary need the terminal to be present at all time it gets quite distracting when it's not needed where my usually workflow outside of gitpod is to press `` Ctrl+\`` type, see the result and close it again with ``Ctrl+`` or reading through it on demand or kept it open while debugging.
> 
> Currently having the terminal at the left toolbar seems to be the most efficient for this purpose, but the issue is that it resizes the workspace (makes it pita to work on assuming multiple windows open) and that it takes around 2 seconds for the workspace to adjust once the terminal is toggled off.

I understand your scenario, just not sure it'd be worth the effort, at least for the framework itself. 
If others are interested, they can always contribute their own extension that provides this exact functionality. The way I see it, the best approach would be to keep the terminal as is (bottom panel), and collapse the bottom panel whenever one wants to focus on other tabs (such as editors). This means you can dismiss the terminals whenever wish to hide them. If there is a view you'd like to keep (such as the `problems` view), you can dock it to the sidepanels.

**Comment by vince-fugnitto** [comment] 2021-03-12 14:17
Closing since there is not enough interest in the community to implement the proposal (~1 year old).

The best course of action would be to implement the feature as part of a [custom extension](https://theia-ide.org/docs/authoring_extensions/), and possibly upstream afterwards.
I do not believe it's something the main community will focus on at this time.

**Closed by vince-fugnitto** 2021-03-12 14:17 UTC
Labels: proposal, terminal
