### ISSUE TITLE
[VSCode] Enable Drag and Drop for views

### ISSUE THREAD

**Issue by EstherPerelman** [eclipse-theia/theia#9442] opened 2021-05-06 05:24 UTC
### Feature Description:
In VSCode there is an option to drag & drop views inside the sidebar panel (Grouping views feature),
It enables to group multiple views at the same container without the need to navigate between the containers.
[VSCode doc](https://code.visualstudio.com/updates/v1_46#_flexible-layout)
![dnd](https://user-images.githubusercontent.com/71729183/117245592-c40a8e00-ae43-11eb-86a0-33bcd9c179b0.gif)

**Comment by vince-fugnitto** [comment] 2021-05-06 11:59
I believe it is a duplicate of https://github.com/eclipse-theia/theia/issues/9203.

**Closed by vince-fugnitto** 2021-05-06 11:59 UTC
Labels: duplicate, enhancement
