### ISSUE TITLE
Generate .editorconfig doesn't work

### ISSUE THREAD

**Issue by RDIL** [eclipse-theia/theia#7613] opened 2020-04-20 02:08 UTC
### Description

`Generate editorconfig` from the context menu is saying:
```
vscode_1.workspace.fs.stat is not a function
```

can be repro'd by just trying to generate an editorconfig

**OS and Theia version:** on gitpod

**Diagnostics:** 
Nothing in console.

**Comment by akosyakov** [comment] 2020-04-20 06:22
Duplicate of https://github.com/eclipse-theia/theia/issues/7269

We are going to work on missing FS API soon. cc @marcdumais-work @svenefftinge

**Closed by akosyakov** 2020-04-20 06:22 UTC
Labels: bug, filesystem, vscode
