### ISSUE TITLE
WorkspaceSaveResourceService cannot save editor

### ISSUE THREAD

**Issue by MoHcmp** [eclipse-theia/theia#11004] opened 2022-04-08 08:28 UTC
### Bug Description:

My editor is Widget and can be saved, but cannot be saved as. When i call save command i get error 'Cannot save the current widget'. This happens because my widget cannot pass `this.workspaceFrontendContribution.canBeSavedAs(widget)` check. Other checks passes and `saveable.save(options)` can be called but it does not. Why WorkspaceSaveResourceService has such strange logic? Looks like a bug.

See `WorkspaceSaveResourceService.save(widget, options?)` method

### Steps to Reproduce:

-

### Additional Information

- Operating System: -
- Theia Version: 1.24

**Comment by msujew** [comment] 2022-04-08 11:30
Hi @MoHcmp, are you sure that you are using Theia version `1.24.0`? Because in version `1.24.0` `WorkspaceFrontendContribution#canBeSavedAs` is not used any longer, so it shouldn't influence your saving logic.

Instead, do you maybe mean the `FilesystemSaveResourceService`?

**Comment by vince-fugnitto** [comment] 2022-04-08 12:12
@MoHcmp in order to `save as`, the following conditions should be met, have you satisfied them in your custom widget?

https://github.com/eclipse-theia/theia/blob/1c7bdf70025c684e7ca22c482e206cceb405ddbd/packages/filesystem/src/browser/filesystem-save-resource-service.ts#L32-L45

**Comment by MoHcmp** [comment] 2022-04-08 13:40
@msujew 
This code is called when im trying to save my editor
https://github.com/eclipse-theia/theia/blob/release/1.24.0/packages/workspace/src/browser/workspace-save-resource-service.ts#L37

@vince-fugnitto 
I do not want to 'save as'. I want to 'save' (File - save or Ctrl+S).  My editor does not met `canSaveAs` conditions. But it has `saveable` where `saveable.save(options)` can be called. But because my editor does not pass `this.workspaceFrontendContribution.canBeSavedAs(widget)` from this line: https://github.com/eclipse-theia/theia/blob/release/1.24.0/packages/workspace/src/browser/workspace-save-resource-service.ts#L37 error is thrown and editor is not saved

**Comment by vince-fugnitto** [comment] 2022-04-08 13:47
> I do not want to 'save as'. I want to 'save'

I was confused as the description said "my editor is Widget and can be saved, but cannot be saved as", no problem :)

@MoHcmp can you try against master (using `next` if necessary), I believe it has been fixed by https://github.com/eclipse-theia/theia/pull/10868 (`workspace-save-resource-service` no longer exists).

**Comment by LXY12121234** [comment] 2022-04-13 02:10
I encountered the same problem when I upgraded theia. Also, when i set  preferences, i got error 'Cannot save the current widget' if saved using keyboard shortcut.

**Comment by vince-fugnitto** [comment] 2022-04-13 02:25
> I encountered the same problem when I upgraded theia. Also, when i set preferences, i got error 'Cannot save the current widget' if saved using keyboard shortcut.

@LXY12121234 what version exactly are you using? 

Also if possible can you provide reproduction steps? (I was not able to reproduce the problem when saving the `settings.json` when dirty or the widget on master)

**Comment by LXY12121234** [comment] 2022-04-13 06:46
@vince-fugnitto  Theia version 1.24.0.
Steps to Reproduce:
1.File-Preferences-Open Settings
2.Save (ctrl+s)
<img width="960" alt="pic" src="https://user-images.githubusercontent.com/52768004/163116229-fe8edb20-9b5a-4ffb-9755-a4cb5e20bcf5.png">

**Comment by vince-fugnitto** [comment] 2022-04-13 10:48
@LXY12121234 thank you for the additional details, please try with `master` or `next`, I mentioned in https://github.com/eclipse-theia/theia/issues/11004#issuecomment-1092878389 that it has been fixed already by https://github.com/eclipse-theia/theia/pull/10868.

**Comment by vince-fugnitto** [comment] 2022-05-02 12:26
The issue has been fixed by https://github.com/eclipse-theia/theia/pull/10868.

**Closed by vince-fugnitto** 2022-05-02 12:26 UTC
Labels: filesystem
