### ISSUE TITLE
Auto Save preference respects only 'off' and 'afterDelay' values

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#11459] opened 2022-07-25 07:11 UTC
### Bug Description:
Hi,
I think the auto-save 'onFocusChange' and 'onWindowChange' values in the preferences are not respected, in both regular text editors and in custom editors.

### Steps to Reproduce:

1. set the auto-save to one of the 'onFocusChange' and 'onWindowChange' values
2. you will see that autosave is done as it is on 'afterDelay'

### Additional Information

- Operating System: windows 10
- Theia Version: 1.26

**Comment by msujew** [comment] 2022-07-25 08:34
@safisa This is a duplicate of https://github.com/eclipse-theia/theia/issues/10812

**Closed by msujew** 2022-07-25 08:34 UTC
