### ISSUE TITLE
[terminal]: scrollbar width dynamically changes based on the width of the terminal widget

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#12911] opened 2023-09-15 14:26 UTC
### Bug Description:

When I resize the terminal, the width of the vertical scrollbar changes; sometimes, it's hardly visible.

### Steps to Reproduce:

1. Open a terminal and make sure you can vertically scroll in it (press `Enter` a few times, for example)
2. Check the width of the scrollbar
3. Horizontally resize the terminal widget to see that the width of the scrollbar changes.

https://github.com/eclipse-theia/theia/assets/1405703/f572a21d-6e39-480b-a7f9-69d28edb7c82

### Additional Information

- Operating System: macOS 13.5.2
- Theia Version: 1.41.0 Blueprint app

**Comment by vince-fugnitto** [comment] 2023-09-15 17:28
@kittaakos duplicate of your past issue? https://github.com/eclipse-theia/theia/issues/8096

**Closed** 2023-09-15 20:44 UTC
Labels: terminal, ui/ux
