### ISSUE TITLE
explorer tree view sometime cause cpu 100%

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5979] opened 2019-08-19 09:09 UTC
### Description
![image](https://user-images.githubusercontent.com/10203793/63253120-d0cc0480-c2a3-11e9-802b-48672d2d1930.png)
![image](https://user-images.githubusercontent.com/10203793/63253180-ed683c80-c2a3-11e9-86f6-c80ea24d4d6f.png)

### Reproduction Steps
I don't know how to reproduce it
but it happened several times.

**OS and Theia version:**
**Diagnostics:**

**Comment by vince-fugnitto** [comment] 2019-08-19 11:29
@502647092 please try and find reproduction steps and also any console logs that may be reported.
Also, if present, list any plugins that may have been used so we get the entire or full picture.

**Comment by AlexTugarev** [comment] 2019-08-19 16:29
@svenefftinge showed me today a quite intense update chain related to view containers. 
@akosyakov could be related, but unfortunately I've no more infos to support this.

**Comment by akosyakov** [comment] 2019-08-20 09:36
I've marked it as `criticial` meaning that it would be good to reproduce and fix before next release if it's indeed related to view containers changes.

**Comment by 502647092** [comment] 2019-08-20 09:41
@akosyakov 
if workspace file have circular reference will cause this problem?

**Comment by akosyakov** [comment] 2019-08-20 09:49
@502647092 I don't know, if you can provide an example it would be good.

I'm more worried that it is a regression caused by view containers, what you describe will be a bug.

**Comment by 502647092** [comment] 2019-08-20 10:55
![image](https://user-images.githubusercontent.com/10203793/63341327-8e75f680-c37b-11e9-9f1f-1930e9a0f4cb.png)
again cpu100%
i ctrl + click symbol to open a file
after file open window is freeze
i can't get snapshots
![image](https://user-images.githubusercontent.com/10203793/63341526-f88e9b80-c37b-11e9-8c49-242a98af76fd.png)

**Comment by akosyakov** [comment] 2019-08-20 13:57
@502647092 How big is a file? Could you share it? Could it be that textmate blows up the memory during tokenization.

**Comment by 502647092** [comment] 2019-08-20 17:35
@akosyakov 
not
is a normal ts file
i think maybe is explorer ref target file cause this problem

**Comment by 502647092** [comment] 2019-08-21 07:18
@akosyakov 
I find some problem
maybe is too many file updates cause cpu 100%
reproduce way
- open theia workspace
- open terminal
- run `yarn watch`
- after watch complate to wait
- switch git branch
- the window will freeze

**Comment by 502647092** [comment] 2019-08-21 07:30
![image](https://user-images.githubusercontent.com/10203793/63411542-52e53600-c428-11e9-9c65-0710de6a3206.png)
```
# root @ 2ee52f9bb3f8 in /home/project [15:29:21] 
$ ls -alR | wc -l
990061
```

**Comment by akosyakov** [comment] 2019-08-21 07:44
`yarn watch` on theia project is generally killing cpu, since it starts tsc on each packages. In this case i am not sure that a browser and a machine at any use at all.

**Comment by akosyakov** [comment] 2019-08-21 07:45
I've asked @svenefftinge and his issues was not related to performance and view containers.

**Comment by 502647092** [comment] 2019-08-21 07:52
@akosyakov but sometime only normal coding
cpu will 100%
I can't find problem
But the problem has recently arisen
if I have time I will test recent versions

**Comment by 502647092** [comment] 2019-09-27 02:15
@akosyakov 
maybe it's this problem
https://support.google.com/chrome/thread/11026607?hl=en

**Comment by akosyakov** [comment] 2019-09-27 10:13
Strange that only you see it, have not heard about such issue with Chrome from others. It would be good if there was a way to reproduce it.

**Comment by 502647092** [comment] 2019-09-27 10:46
![image](https://user-images.githubusercontent.com/10203793/65763700-8e290200-e156-11e9-8d69-65ffe681b48d.png)
I use Edge-dev version also have this problem

I found one thing in common 
most of the suspended animations are after I used Git at SCM View
then when I switch to explorer page will crash
Is there a way to get what the page is doing?

**Closed** 2023-07-10 03:30 UTC
Labels: bug, performance, navigator, :thinking: needs more info
