### ISSUE TITLE
Warning in the problem view does not show when an error is reported for the same JAVA file

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#6147] opened 2019-09-09 14:02 UTC
### Description
Warning in the problem view does not show when an error is reported for the same JAVA file.

### Reproduction Steps
- Open a JAVA project 
- Open a java file : No problem (error or warnings)
-  insert the following: `Object myObject = null;` 
--> you will see a warning in the Problem view: value not used
- In the same file, now insert some code at a different line:` int`
--> An error is reported in the problem view : Syntax error...
**Note: you don't see the previous warning anymore** 
- Now remove the error by removing `"int"`
--> the initial warning show up again

**OS and Theia version:**
Theia: latest
Ubuntu: 16.04

**Diagnostics:** 
![JavaLinter](https://user-images.githubusercontent.com/419051/64537015-1484bd80-d2e8-11e9-8c2f-293e46f5d7e1.gif)

**Comment by tsmaeder** [comment] 2019-09-10 09:42
@lmcbout are you saying this is happening for _all_ pairs of warnings and errors or just this one? It may well be that the compiler gives up on analysing the rest of the file in this particular instance.

**Comment by lmcbout** [comment] 2019-09-10 15:57
@tsmaeder This is a small maven HelloWorld project I took on the web
If I had a second warning, then both go away and are replaced by the error. When I remove the error, then I can see all warnings. I find it strange if the whole project is not analyse. If I add a warning in another file, it shows

**Comment by JonasHelming** [comment] 2021-03-22 09:39
I retested this in Eclipse desktop, it leads to the same behavior. I agree with @tsmaeder that this is likely due to the compile not beeing able to analyize warning in the case the file is not syntactically correct after introducing the second error.
Therefore, I suggest to close this issue, we won't be able to fix this in Theia. If at all, it must be fixed in the compile/language server. However, I believe this is the behavior since forever, so I guess there are good reasons for this.
@tsmaeder Do you agree?

**Comment by vince-fugnitto** [comment] 2021-03-22 12:47
@JonasHelming if the behavior can be reproduced in vscode (with the [redhat java language extension](https://open-vsx.org/extension/redhat/java)), then I'd say we should close as it is not specific to the framework :+1:

**Comment by JonasHelming** [comment] 2021-03-22 12:51
I can reproduce this in VS Code, I therefore close this, as it is not really Theia related...

**Closed by JonasHelming** 2021-03-22 12:51 UTC
Labels: bug, java, problems
