### ISSUE TITLE
[git-scm] No repository found

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#7860] opened 2020-05-21 02:39 UTC
### Bug Description:

![image](https://user-images.githubusercontent.com/10203793/82516876-660b6a80-9b4e-11ea-82d0-43a05728dfa9.png)

- I manually add paths to local storage `theia:/:file:///home/project:theia-git-all-repositories`
- refresh ide Can fix it
![image](https://user-images.githubusercontent.com/10203793/82517193-34df6a00-9b4f-11ea-9297-e8968f52c312.png)
![image](https://user-images.githubusercontent.com/10203793/82517203-3872f100-9b4f-11ea-800b-6c8a57726669.png)

### Steps to Reproduce:

1. build latest theia
2. open a WorkSpace have multi git repo

### Additional Information

- Operating System: Windows10
- Theia Version: 1.2.0-next.f97ec33e

**Comment by vince-fugnitto** [comment] 2020-05-21 03:06
Duplicate of https://github.com/eclipse-theia/theia/issues/4107? 
You can try using the `git` and `git-ui` builtin extensions and determining if the use-case is handled correctly (`@theia/git` will be deprecated in the near future).

**Comment by 502647092** [comment] 2020-05-21 09:13
@vince-fugnitto 
![image](https://user-images.githubusercontent.com/10203793/82543542-4bed7e80-9b86-11ea-94c5-6cffeec1a34d.png)
also have this problem

**Comment by westbury** [comment] 2020-05-22 18:25
This is a regression caused by ecdb1517050fc4f13771edd8dbb6df94537a5150 .  With the typescript upgrade, the locator is no longer returning the repositories.  The repositories are being returned by findGitRepositories but then something weird is happening in git-locator-impl.doLocate

**Comment by 502647092** [comment] 2020-05-23 08:10
another problem if ide reconnect backend the git info will lose

**Comment by westbury** [comment] 2020-05-23 11:43
@502647092 I have pushed a fix to branch fix-locate-repos.  Can you test with this branch to see if it fixes the issues?

**Closed** 2020-05-25 06:52 UTC
Labels: git
