### ISSUE TITLE
[vscode][builtin][plugin] plugin vscode-builtin-typescript-language-features r.languages.registerSelectionRangeProvider is not a function

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#7244] opened 2020-02-29 06:10 UTC
### Description

install builtin plugin next version have some error

### Reproduction Steps

install next version builtin plugin
- `@theia/vscode-builtin-typescript-language-features`

**OS and Theia version:**
Theia 0.17.0-next.c965552a

**Diagnostics:** 
```
theia_1  | With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function
theia_1  |     at s.VersionDependentRegistration [as _doRegister] (/home/theia/plugins/vscode-builtin-typescript-language-features/package/dist/extension.js:1:174276)
theia_1  |     at s.update (/home/theia/plugins/vscode-builtin-typescript-language-features/package/dist/extension.js:1:13488)
theia_1  |     at t.VersionDependentRegistration.update (/home/theia/plugins/vscode-builtin-typescript-language-features/package/dist/extension.js:1:13957)
theia_1  |     at new t.VersionDependentRegistration (/home/theia/plugins/vscode-builtin-typescript-language-features/package/dist/extension.js:1:13756)
theia_1  |     at Object.t.register (/home/theia/plugins/vscode-builtin-typescript-language-features/package/dist/extension.js:1:174210)
theia_1  |     at Promise.all.Promise.resolve.then.then.t (/home/theia/plugins/vscode-builtin-typescript-language-features/package/dist/extension.js:1:127999)
theia_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by akosyakov** [comment] 2020-02-29 08:03
duplicate of https://github.com/eclipse-theia/theia/issues/7198

**Closed by akosyakov** 2020-02-29 08:03 UTC
