### ISSUE TITLE
Electron example not running in windows machine

### ISSUE THREAD

**Issue by NitinKhandelwal1947** [eclipse-theia/theia#6529] opened 2019-11-12 06:13 UTC
### Description
Electron example not running in windows machine

### Reproduction Steps
yarn &&  yarn rebuild:electron && cd examples/electron && yarn start
Electron window does not pops up. 
Also observed sometimes failing with native dependency find-git-repositories
Error: The specified procedure could not be found findGitRepos.node

$ yarn rebuild:electron
yarn run v1.7.0
$ theia rebuild:electron
Processing @theia/node-pty
Processing nsfw
Processing native-keymap
Processing find-git-repositories
Done in 7.96s.
$ cd examples/electron/
$ yarn start
yarn run v1.7.0
$ theia start --plugins=local-dir:../../plugins
Done in 2.74s.

**OS and Theia version:**
Windows 10
yarn version:- 1.7.0
node version:- 10.15.3
npm version:- 4.2.0

**Diagnostics:**

**Comment by akosyakov** [comment] 2019-11-12 08:13
@eclipse-theia/eclipse-theia Could someone with Windows machine double check?

**Comment by kittaakos** [comment] 2019-11-12 08:37
> Also observed sometimes failing with native dependency find-git-repositories

@NitinKhandelwal1947, do you have a stack trace? What is your `electron-builder` version? Does [this thread](https://github.com/implausible/find-git-repositories/issues/5) help?

**Comment by tsmaeder** [comment] 2019-11-12 11:05
Here you go: 

```
C:\Users\thomas\code\theia\examples\electron>yarn start
yarn run v1.19.1
$ theia start --plugins=local-dir:../../plugins

 Failed to start the backend application.
Error: The specified procedure could not be found.
\\?\C:\Users\thomas\code\theia\node_modules\find-git-repositories\build\Release\findGitRepos.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\thomas\code\theia\node_modules\find-git-repositories\dist\index.js:3:16)
    at Object.<anonymous> (C:\Users\thomas\code\theia\node_modules\find-git-repositories\dist\index.js:46:3)
Error: The specified procedure could not be found.
\\?\C:\Users\thomas\code\theia\node_modules\find-git-repositories\build\Release\findGitRepos.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\thomas\code\theia\node_modules\find-git-repositories\dist\index.js:3:16)
    at Object.<anonymous> (C:\Users\thomas\code\theia\node_modules\find-git-repositories\dist\index.js:46:3)
Done in 3.08s.
```

**Comment by NitinKhandelwal1947** [comment] 2019-11-12 11:36
> > Also observed sometimes failing with native dependency find-git-repositories
> 
> @NitinKhandelwal1947, do you have a stack trace? What is your `electron-builder` version? Does [this thread](https://github.com/implausible/find-git-repositories/issues/5) help?

```Error: The specified procedure could not be found.
\\?\C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\node_modules\find-git-repositories\build\Release\findGitRepos.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\node_modules\find-git-repositories\dist\index.js:3:16)
    at Object.<anonymous> (C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\node_modules\find-git-repositories\dist\index.js:46:3)```

I was using electron-builder 20.44.4 , but as mentioned in other 
link electron-builder@21.2.0 did not solve my problem

**Comment by kittaakos** [comment] 2019-11-12 12:33
> Here you go:
> 
> ```
> C:\Users\thomas\code\theia\examples\electron>yarn start
> yarn run v1.19.1
> $ theia start --plugins=local-dir:../../plugins
> 
>  Failed to start the backend application.
> Error: The specified procedure could not be found.
> \\?\C:\Users\thomas\code\theia\node_modules\fi
> ```

@tsmaeder, thanks but I have no idea what you did and I do not understand how the Theia electron example relates to the `electron-builder`.


> I was using electron-builder 20.44.4 , but as mentioned in other 
> link electron-builder@21.2.0 did not solve my problem

@NitinKhandelwal1947, any chance you can share your `package.json`? It is hard to see what you are doing. If you want to build the electron example inside the `eclipse-theia/theia`, it won't work.

**Comment by kittaakos** [comment] 2019-11-12 12:40
> but as mentioned in other 
> link

Where?

**Comment by marechal-p** [comment] 2019-11-12 15:45
According to Electron documentation, this issue comes from the way the `find-git-repositories` package builds its native bits. See https://electronjs.org/docs/tutorial/using-native-node-modules#a-note-about-win_delay_load_hook.

They have a commit that enables the `win_delay_load_hook` flag, but I don't think we pull this version, hence this issue.

I was able to get past that error on my Windows machine by editing this flag to `true` in my node_modules before running `yarn rebuild:electron` and it worked.

**Comment by marechal-p** [comment] 2019-11-12 15:48
I think this patch also fixes that issue: https://github.com/eclipse-theia/theia/pull/6255

**Comment by tsmaeder** [comment] 2019-11-13 09:03
> @tsmaeder, thanks but I have no idea what you did and I do not understand how the Theia electron example relates to the `electron-builder`.
> 
It's the output of doing "yarn start" in the electron example folder. Building works fine, running does not.

**Comment by NitinKhandelwal1947** [comment] 2019-11-13 10:08
> > Here you go:
> > ```
> > C:\Users\thomas\code\theia\examples\electron>yarn start
> > yarn run v1.19.1
> > $ theia start --plugins=local-dir:../../plugins
> > 
> >  Failed to start the backend application.
> > Error: The specified procedure could not be found.
> > \\?\C:\Users\thomas\code\theia\node_modules\fi
> > ```
> 
> @tsmaeder, thanks but I have no idea what you did and I do not understand how the Theia electron example relates to the `electron-builder`.
> 
> > I was using electron-builder 20.44.4 , but as mentioned in other
> > link electron-builder@21.2.0 did not solve my problem
> 
> @NitinKhandelwal1947, any chance you can share your `package.json`? It is hard to see what you are doing. If you want to build the electron example inside the `eclipse-theia/theia`, it won't work.

i am trying to build and package theia  as electron  app for Mac and Windows machine. Basically trying to make dmg and .exe . I took `eclipse-theia/theia` code base and trying to package it using electron-builder.

package.json:-

```
{
  "private": true,
  "name": "lite",
  "version": "0.11.0",
  "license": "EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0",
  "author": "abc",
  "theia": {
    "target": "electron",
    "frontend": {
      "config": {
        "applicationName": "Theia Electron Example"
      }
    },
    "backend": {
      "config": {
        "startupTimeout": -1
      }
    }
  },
  "main": "./src-gen/frontend/electron-main.js",
  "dependencies": {
    "@theia/callhierarchy": "^0.11.0",
    "@theia/console": "^0.11.0",
    "@theia/core": "^0.11.0",
    "@theia/debug": "^0.11.0",
    "@theia/editor": "^0.11.0",
    "@theia/editor-preview": "^0.11.0",
    "@theia/editorconfig": "^0.11.0",
    "@theia/file-search": "^0.11.0",
    "@theia/filesystem": "^0.11.0",
    "@theia/getting-started": "^0.11.0",
    "@theia/git": "^0.11.0",
    "@theia/java": "^0.11.0",
    "@theia/java-debug": "^0.11.0",
    "@theia/json": "^0.11.0",
    "@theia/keymaps": "^0.11.0",
    "@theia/languages": "^0.11.0",
    "@theia/markers": "^0.11.0",
    "@theia/merge-conflicts": "^0.11.0",
    "@theia/messages": "^0.11.0",
    "@theia/metrics": "^0.11.0",
    "@theia/mini-browser": "^0.11.0",
    "@theia/monaco": "^0.11.0",
    "@theia/navigator": "^0.11.0",
    "@theia/outline-view": "^0.11.0",
    "@theia/output": "^0.11.0",
    "@theia/plugin-dev": "^0.11.0",
    "@theia/preferences": "^0.11.0",
    "@theia/preview": "^0.11.0",
    "@theia/process": "^0.11.0",
    "@theia/python": "^0.11.0",
    "@theia/search-in-workspace": "^0.11.0",
    "@theia/task": "^0.11.0",
    "@theia/terminal": "^0.11.0",
    "@theia/textmate-grammars": "^0.11.0",
    "@theia/tslint": "^0.11.0",
    "@theia/typehierarchy": "^0.11.0",
    "@theia/typescript": "^0.11.0",
    "@theia/userstorage": "^0.11.0",
    "@theia/variable-resolver": "^0.11.0",
    "@theia/workspace": "^0.11.0",
    "electron-store": "^5.0.0",
    "fix-path": "2.1.0",
    "native-keymap": "^2.0.0",
    "oniguruma": "^7.2.0"
  },
  "scripts": {
    "start": "theia start --plugins=local-dir:../../plugins",
    "prepare": "yarn run build",
    "build": "theia build",
    "package": "electron-builder",
    "package:preview": "electron-builder --dir",
    "package:all": "electron-builder -mw"
  },
  "devDependencies": {
    "@theia/cli": "^0.11.0",
    "electron": "^4.0.2",
    "electron-builder": "20.44.4"
  }
}
```
packaging  is happening in windows machine but when try to execute or run the .exe its failing with native dependency like find-git-repositories.

**Comment by NitinKhandelwal1947** [comment] 2019-11-13 10:09
> > but as mentioned in other
> > link
> 
> Where?

https://github.com/implausible/find-git-repositories/issues/5

**Comment by akosyakov** [comment] 2019-11-13 10:12
I thought that it is not possible to bundle from yarn workspaces? Correct me if i'm wrong @kittaakos 

You could setup the standalone package as here: https://github.com/theia-ide/theia-apps/tree/master/theia-electron

**Comment by tsmaeder** [comment] 2019-11-13 11:09
@kittaakos @akosyakov I can confirm that building and running the electron example does not work for me on Windows 10 (this is what the issue title and description describe).  I do a git clone, yarn , yarn rebuild:electron and then yarn run start from the electron example. I provided a stack trace of my failure.

**Comment by akosyakov** [comment] 2019-11-13 11:24
@tsmaeder understood, just wanted to point out that bundling from sources won't work anyway since @NitinKhandelwal1947 is trying it

**Comment by akosyakov** [comment] 2019-11-13 11:25
@tsmaeder btw could you try again since https://github.com/eclipse-theia/theia/pull/6255 was merged and according to https://github.com/eclipse-theia/theia/issues/6529#issuecomment-552952506 it could help

**Comment by tsmaeder** [comment] 2019-11-13 12:45
I pulled this morning, so should have the contents of the merged PR and removed everything from node_modules and examples/electron node-modules. That should cover the case, right @akosyakov ?
I had a bit of trouble setting up the build enviroment on windows, so I'm ready to believe it's my setup. Not sure how to check, though.

**Comment by sorekz** [comment] 2019-11-13 16:13
This might be related to https://github.com/nodejs/node-gyp/issues/1933
which will be fixed with the next electron-rebuild release

**Comment by marechal-p** [comment] 2019-11-13 16:15
@sorekz this is precisely the error I see from this PR: https://github.com/eclipse-theia/theia/pull/6538#issuecomment-553103072

**Comment by Yashraj890** [comment] 2019-11-20 16:16
Hello Team

I found one solution for this issue, just run the below command

npm install sqlite3 --build-from-source --runtime-electron --target-|YOUR ELECTRON VERSION| --dist-url=https://atom.io/download/electron

After running the above command, please run the - npm rebuild

Please let me know if anyone is able to resolve the issue with my solution.

Thanks

**Comment by NitinKhandelwal1947** [comment] 2019-11-22 09:51
> According to Electron documentation, this issue comes from the way the `find-git-repositories` package builds its native bits. See https://electronjs.org/docs/tutorial/using-native-node-modules#a-note-about-win_delay_load_hook.
> 
> They have a [commit that enables the `win_delay_load_hook` flag](https://github.com/implausible/find-git-repositories/commit/99249606bc364105322f17d6948f5e9ba89a84f9), but I don't think we pull this version, hence this issue.
> 
> I was able to get past that error on my Windows machine by editing this flag to `true` in my node_modules before running `yarn rebuild:electron` and it worked.

Thanks @marechal-p it worked for me.

**Closed** 2020-01-09 19:55 UTC
Labels: :thinking: needs more info, OS/Windows, electron
