### ISSUE TITLE
Cannot register menu item asynchronously

### ISSUE THREAD

**Issue by bendavis78** [eclipse-theia/theia#8817] opened 2020-12-02 18:00 UTC
When creating a MenuContribution + CommandContribution, I am unable to use asynchronous logic inside the `registerCommands` and `registerMenus` functions. When you use async in either function, the menus are not registered properly (they simply don't appear).

You can reproduce this by starting from generator-theia-extension using the "widget" template. Update the `reigsterMenus` or `registerCommands` functions to register asynchronously, like so:

```typescript
    registerCommands(commands: CommandRegistry): void {
        setTimeout(() => {
            commands.registerCommand(TheiaTestCommand, {
                execute: () => super.openView({ activate: false, reveal: true })
            });
        });
    }

    registerMenus(menus: MenuModelRegistry): void {
        setTimeout(() => {
            super.registerMenus(menus);
        });
    }
```

I did some digging, and the issue appears to be with [core/lib/browser/menu/browser-menu-plugin:292](https://github.com/eclipse-theia/theia/blob/f1e37fbdbe9cf0bdcd30f58d2c8fbf6d6808419e/packages/core/src/browser/menu/browser-menu-plugin.ts#L292):
```typescript
                if (!(commands.isVisible(node.action.commandId) && (!when || contextKeyService.match(when)))) {
```
The `commands.isVisible(node.action.commandId)` returns `false` because the command is not registered with the menu. The only place I can see where commands are registered with the menu is in `MenuCommandRegistry.registerActionMenu()`, and this is only called during `BrowserMenuContribution.onStart()`.

**Comment by vince-fugnitto** [comment] 2020-12-02 18:17
@bendavis78 duplicate of https://github.com/eclipse-theia/theia/issues/6259?

**Comment by bendavis78** [comment] 2020-12-02 19:26
@vince-fugnitto yes, that possibly could be a duplicate. You can go ahead and mark this as duplicate and I will respond on that issue.

**Comment by vince-fugnitto** [comment] 2020-12-02 19:27
Duplicate of  #6259.

**Closed by vince-fugnitto** 2020-12-02 19:27 UTC
Labels: menus
