### ISSUE TITLE
Drawio Activating extentsion failed. o.window.registerCustomEditorProvider is not a function, etc

### ISSUE THREAD

**Issue by HansUXdev** [eclipse-theia/theia#8447] opened 2020-08-30 22:38 UTC
### Describe the bug

Not sure if this is the right place to report the bug but I just helped publish this [drawio](https://open-vsx.org/extension/hediet/vscode-drawio) extension to try and bring remote collaboration on designs between designers and coders in the cloud. 

It works on vscodium but not in the Theia IDE on GitPod

### Steps to reproduce

Install the extension and it fails.
Try creating a file called test.drawio or test.drawio.svg 

### Expected behavior

Should install properly.
Should be able to open files such  test.drawio or test.drawio.svg and have them appear similar to below.

<img width="1198" alt="Screen Shot 2020-08-30 at 3 01 15 PM" src="https://user-images.githubusercontent.com/5007073/91670688-8abf9880-ead4-11ea-8ca1-800e412c2cb1.png">

### Additional information

ecb2f9ba-02ae-4b9f-a3da-cc4e81785c2b

[<img width="500" alt="Screen Shot 2020-08-30 at 2 44 41 PM" src="https://user-images.githubusercontent.com/5007073/91670568-a4acab80-ead3-11ea-816e-87d5868a234f.png">](url)

**Comment by vince-fugnitto** [comment] 2020-08-30 23:26
@HansUXdev thank you for the issue, it is however a duplicate of the following: https://github.com/eclipse-theia/theia/issues/8266

The custom editor API is not yet supported.

**Comment by vince-fugnitto** [comment] 2020-08-30 23:46
@HansUXdev thank you for reporting the issue, however it is a duplicate as the issue is already being tracked (the custom editor api is not yet supported)
- dupplicate drawio issue: https://github.com/eclipse-theia/theia/issues/8266
- custom editor api issue: https://github.com/eclipse-theia/theia/issues/6636

**Closed by vince-fugnitto** 2020-08-30 23:46 UTC
Labels: vscode, webviews
