### ISSUE TITLE
Set focus to another editor if current one is closed

### ISSUE THREAD

**Issue by mmorhun** [eclipse-theia/theia#4502] opened 2019-03-07 10:50 UTC
### Description
When current text editor gets closed, focus isn't set into another one.

This is related to VSCode compatibility in Theia plug-in API.

### Reproduction Steps

1. Open a few editors
2. Set focus into one
3. Close active editor tab

Another editor is shown but focus is not there. When typing text, nothing happens.

**Comment by akosyakov** [comment] 2019-03-08 06:37
Sounds like it should be generally done on the shell level. If a focused widget is closed in the tab group then new visible widget in the same tab group should be focused. Not sure what should happen if the focused widget was the last, probably a visible widget from next (or first if a tab group was last) tab group should be focused.

**Comment by spoenemann** [comment] 2020-03-05 12:58
Duplicate of #2234

**Closed by spoenemann** 2020-03-05 12:58 UTC
Labels: bug, help wanted, plug-in system, shell, vscode
