### ISSUE TITLE
[c/c++] cursor appearing in wrong position

### ISSUE THREAD

**Issue by boomanaiden154** [eclipse-theia/theia#3796] opened 2018-12-10 17:50 UTC
When using theia as a c++ editor, I am getting strange issues with cursor spacing. The cursor is out of line with the text, with the cursor being in the middle of characters.
![screenshot 2018-12-10 at 7 47 09 am](https://user-images.githubusercontent.com/39388941/49750703-741e4180-fc60-11e8-99dc-8f32d02b245d.png)
The longer the string of text, the more the cursor gets shifted to the right. This occurs on Chrome 70.0.3538.110 on chromeOS, but I have duplicated this issue on a Chrome 70 on Ubuntu. This occurs on Theia version 0.3.17.

**Comment by virtualgraham** [comment] 2019-01-11 08:57
I was having the same issue. I resolved it by installing the Advanced Font Settings extension in chrome and setting the Fixed-width font size to 14pt which matches the 14pt in the Theia settings. I am not sure why this would matter since css should determine font size.

**Comment by boomanaiden154** [comment] 2019-01-13 05:03
Do you have any additional information? Operating system and browser version? It does not seem to occur on my windows 10 machine, but it does on ChromeOS.

**Comment by virtualgraham** [comment] 2019-01-13 06:38
I am also having the same issue with Chrome OS version 71.0.3578.94 (32-bit) on arm.
I have noticed that when you click on a line to edit it for the first time, the font size and or character spacing of that line will increase slightly (or decrease slightly if the page scale is very high). The only workaround i found is to set the scale of the web page to 80% and then increase the size of the font to 14pt.

**Comment by caseyflynn-google** [comment] 2019-02-05 22:35
@boomanaiden154 @virtualgraham Are either of you able to successfully reproduce this issue?

**Comment by akosyakov** [comment] 2019-02-06 06:10
@caseyflynn-google Did you pin on the purpose? Now everybody see it on https://github.com/theia-ide/theia/issues.

**Comment by caseyflynn-google** [comment] 2019-02-06 16:49
> @caseyflynn-google Did you pin on the purpose? Now everybody see it on https://github.com/theia-ide/theia/issues. I've unpinned it. This feature seems to be to highlight 3 most important issues repo-wide.

Apologies, I didn't realize.

**Comment by boomanaiden154** [comment] 2019-02-09 22:56
@caseyflynn-google The common link seems to be ChromeOS. I cannot duplicate the issue with Chrome on Windows, or Ubuntu, but I can duplicate the issue in ChromeOS easily.

**Comment by virtualgraham** [comment] 2019-02-09 23:54
Yeah, it can be consistently reproduced on Chrome OS (though it may take a
couple of mins). I have not encountered the error on Chrome for Mac.

**Comment by caseyflynn-google** [comment] 2019-02-11 18:03
@boomanaiden154 @virtualgraham What version / build of ChromeOS are you able to duplicate this on? I have been unable to reproduce on 71.0.3578.127

**Comment by boomanaiden154** [comment] 2019-02-12 15:53
I think I have just more or less reproduced it, and it has to do with spaces vs tabs for indents in the editor. If you are editing a file that has been indented with spaces, and you create a new line than the font spacing will be off. However, if you re indent the line with tabs, then the font spacing issue will not occur.

**Comment by caseyflynn-google** [comment] 2019-02-12 17:39
> I think I have just more or less reproduced it, and it has to do with spaces vs tabs for indents in the editor. If you are editing a file that has been indented with spaces, and you create a new line than the font spacing will be off. However, if you re indent the line with tabs, then the font spacing issue will not occur.

@boomanaiden154 I was unable to reproduce by following the steps you provided. Can you provide some more detail on the file content you are dealing with, your Theia settings, and the version of ChromeOS you are using?

**Comment by boomanaiden154** [comment] 2019-02-12 19:14
I created a new text file from the terminal, with spaces for the indent(four of them)
`echo "    testing" >> test.txt`
I then opened it in the editor, and when I created a new line below I was able to observe the issue.
![screenshot 2019-02-12 at 11 13 17 am](https://user-images.githubusercontent.com/39388941/52661674-629f2300-2eb7-11e9-95ea-a5e3251f905a.png)

**Comment by parsley42** [comment] 2019-02-22 18:27
Same issue for me on ChromeOS; I installed Linux Firefox in crostini, and that works fine - so it's a Chrome/ChromeOS thing. I'm also currently stuck with Chrome71, when my chromebook updates I'll test and try to remember to report back.

**Comment by parsley42** [comment] 2019-02-26 15:34
![image](https://user-images.githubusercontent.com/5324707/53424931-20470d00-39b2-11e9-95b4-335df63d3ce6.png)

Still an issue w/ Chrome 72.0.3626.117 on Chromebook. Note that if I just move the cursor around on the line, it seems fine; once I edit the line, the text shrinks a little and the cursor position is way off. It's very touchy; the text size seems to vary slightly.

**Comment by parsley42** [comment] 2019-03-04 21:00
I found a fix for this with my Chromebook, wondering if it works for others. I found that for some reason my Chromebook had display scaling turned on for the internal display; "Display Size" was set to 110%. When I set it instead to 100%, the issue disappeared and I couldn't reproduce it.

**Comment by virtualgraham** [comment] 2019-03-05 04:52
From my experience it can be worked around using the in-browser scaling by
finding the scale sweet spot which is around 110% as David Parsley said.
This may very well be an issue with chrome os and not with Theia. However,
i feel Theia's ability to work on Chrome OS is one of its core strengths.

**Comment by parsley42** [comment] 2019-03-05 15:11
Ugh - this bug is really touchy. Turns out, I had to have set my font size to 16; the default (14 I think) still exhibited the bug for me. So, Display size = 100%, Font size = 16 -> works for me.

**Comment by perguth** [comment] 2019-03-28 11:56
I experience that bug too. When first opening Theia everything is fine. After a bit of work (tabbing between windows etc.) the bug appears. (ChromeOS, PixelBook, Page zoom: 100%, "Looks like" 1714 x 1143)

![image](https://user-images.githubusercontent.com/85259/55155799-9036e780-5158-11e9-9d8b-29087ccbdd1a.png)

**Comment by caseyflynn-google** [comment] 2019-04-09 21:36
Confirmed this is an issue with ChromeOS when scaling the screen resolution. It looks like Monaco recently exposed API to remeasure character widths which should be invoked when the devicePixelRatio changes: https://github.com/Microsoft/vscode/commit/d8bc1fa0ff04ec74bbfac8431699765b18f2d41e @akosyakov  could you provide some information on how I would go about patching this into Theia?

**Comment by akosyakov** [comment] 2019-04-10 04:33
@caseyflynn-google We cannot update Monaco yet, it is long chain of dependencies :( We are using https://github.com/Microsoft/vscode/tree/standalone/0.14.x now. If `CSSBasedConfiguration.clearCahce` is there, you can expose it monaco extension as we expose other APIs and trigger when necessary.

**Comment by caseyflynn-google** [comment] 2019-04-11 18:57
It looks like there are actually two problems here. One is with Monaco cursor placement calculation, the other may be a CrOS rendering issue: https://bugs.chromium.org/p/chromium/issues/detail?id=949299&can=2&start=0&num=100&q=owner%3Ame&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&hotlist_id= The Repro case on the ticket is for Theia in Google Cloud Shell, but it can be reproduced in the same manner on GitPod.

**Comment by akosyakov** [comment] 2019-04-12 04:05
@caseyflynn-google If we fix Monaco part would it help or without CrOS fixes it does not make sense? I wonder is there API to get notified about display resolution changes to clean Monaco cache?

**Comment by caseyflynn-google** [comment] 2019-04-12 17:13
I will confirm, but I think we can resolve all issues if we ensure all fonts are loaded before rendering Monaco (This will fix CrOS rendering two separate fonts) in addition we will need to call the API to invalidate the cache if/when the devicePixelRatio changes (if a user changes screen resolution, or drags Theia to another device on CrOS).

**Comment by GDJason12** [comment] 2019-04-15 09:04
Just change the zoom on the page.

**Comment by GDJason12** [comment] 2019-04-15 09:07
CTRL+Shift+-

**Comment by davemecha** [comment] 2019-05-14 12:55
I think I found a simple solution for this problem.

The problem also occurs on [gitpod.io](gitpod.io) as well, which is using the Theia IDE and I posted my solution [there](https://github.com/gitpod-io/gitpod/issues/339#issuecomment-492210300) first. 

To solve the problem I simply changed the default font setting for the editor to:

```
   "editor.fontFamily": "'Noto Sans Mono', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"
```

So I added `Noto Sans Mono` to the font list, to make sure the default monospace font of chromebooks `Cousine` is not used.

The `Cousine` font metrics seem to confuse the Theia editor somehow. But with other monotyped fonts there is no problem.

I want to suggest updating the default fonts in the [editor preferences](https://github.com/theia-ide/theia/blob/a6f62c986d6a72a69c5ee0d2eb8488b4875cd983/packages/editor/src/browser/editor-preferences.ts#L30) for Linux to make the fallback to work also for ChromeOS.

I would just change

```
const DEFAULT_LINUX_FONT_FAMILY = '\'Droid Sans Mono\', \'monospace\', monospace, \'Droid Sans Fallback\'';
```

to 

```
const DEFAULT_LINUX_FONT_FAMILY = '\'Droid Sans Mono\', \'monospace\', monospace, \'Droid Sans Fallback\', \'Noto Sans Mono\'';
```

I could add a pull request for this.

**Comment by akosyakov** [comment] 2019-05-15 05:17
@caseyflynn-google does it sound reasonable? @davemecha yes, PRs are welcomed, adding a fallback font should not hurt even if it does not fix the issue completely

**Comment by caseyflynn-google** [comment] 2019-05-24 16:58
This may help, but I don't think it resolves the underlying race condition that causes the issue (Monaco is added to the page before the fonts have completed downloading).

**Comment by msujew** [comment] 2024-03-15 15:05
After multiple monaco upgrades, I assume this is no longer relevant/reproducible. Closing.

**Closed by msujew** 2024-03-15 15:05 UTC
Labels: bug, monaco, browser/chrome

**Comment by boomanaiden154** [comment] 2024-03-15 18:50
Yep. Last couple times I've tried using Theia, I haven't seen this issue. Thanks for following up!
