### ISSUE TITLE
upgrade to latest VS Code built-in extensions

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7712] opened 2020-05-01 08:12 UTC
Typescript now supports new syntax, like null coalescing and type imports. Extensions which we use cannot deal with it. I suggest we break it down to several steps:
- publish built-in extensions for April version of VS Code
- start using them in this repo
- some stuff won't work, collect issues
- fix issues

Maybe we should make it the standard practice after each VS Code release.

We could also start using them in theia-apps by introducing new `insider` tag, i.e.:
- `latest` means stable Theia and VS Code extensions
- `next` means unstable Theia but stable VS Code extensions
- `insider` means unstable Theia and VS Code extensions

@eclipse-theia/ecd-theia-committers WDYT?

**Comment by akosyakov** [comment] 2020-05-01 08:13
We should also use latest stable tech supported by built-in extensions like https://github.com/eclipse-theia/theia/issues/7693 to see these issues earlier in this repo.

**Comment by marcdumais-work** [comment] 2020-05-11 20:39
Update: the first two items above are ready. The VS Code Builtin extensions v1.44.2 were published to open-vsx.org last week and the example app in this repo is [now using them for the most part](https://github.com/eclipse-theia/theia/blob/master/package.json#L83-L147)

> - publish built-in extensions for April version of VS Code
> - start using them in this repo

**Comment by akosyakov** [comment] 2020-05-12 07:20
@marcdumais-work I wonder how we can routinise it?

**Comment by lmcbout** [comment] 2020-05-12 12:23
Looking inside the package.json for the builtins, I see it requires node >12
- vscode-builtin-npm 
      "@types/node": "^12.11.7"
- vscode-builtin-markdown-language-features
      "@types/node": "^12.11.7"

**Comment by akosyakov** [comment] 2020-05-12 12:50
That seems to be only typings, does it break anything?

**Comment by lmcbout** [comment] 2020-05-12 19:18
I was just mentioning that the 2 Builtins not working are both referencing this version of @type/node

**Comment by vince-fugnitto** [comment] 2020-05-12 19:22
> I was just mentioning that the 2 Builtins not working are both referencing this version of @type/node

@lmcbout I don't believe the `node` version for these extensions is the reason they are not working, you can see that there are missing APIs. Moreover, it looks like many of the extensions have this node `@types` version:

<img width="536" alt="Screen Shot 2020-05-12 at 3 22 05 PM" src="https://user-images.githubusercontent.com/40359487/81736313-5ca24400-9464-11ea-93df-1404b5af45b8.png">

**Comment by marcdumais-work** [comment] 2020-05-15 01:13
> I wonder how we can routinise it?

Yes, we should be. Not much missing to automatically package and publish nightly - still working on it. 

There's also an incoming enhancement in open vsx to add a stable URL for the most recent `preview` release in addition to the one for the `stable` version, of any given extension. So if we are willing to accept (occasional?) breakage here for the example app, we can eventually use the `preview` URL. Else we can at least use it for `theia-apps`for `insider` images as per description above.

**Comment by akosyakov** [comment] 2020-05-15 06:38
> So if we are willing to accept (occasional?) breakage here for the example app, we can eventually use the preview URL.

I will prefer to know about breakage.

**Comment by marcdumais-work** [comment] 2020-06-04 22:37
Update: we now have a GH workflow that publishes to https://open-vsx.org the solid revisions of the vscode builtins. Upon committing the PR, current latest, `1.45.1`, was published. It will try again nightly, skipping already published extensions of that version, until a new vscode version is out.

**Comment by rgrunber** [comment] 2022-05-25 18:54
@colin-grant-work , thanks. Yes I was using Node 12. Tried with Node 14 and the issue is gone now, though I seem to be getting `TypeError: Class extends value undefined is not a constructor or null` on `class i extends r.TypeHierarchyItem`.

**Comment by colin-grant-work** [comment] 2022-05-25 19:13
`TypeError: Class extends value undefined is not a constructor or null` on `class i extends r.TypeHierarchyItem`, so I'll have to work through that.

Looking at our Plugin API, it doesn't appear that we support `TypeHierarchyItem` (as [this](https://eclipse-theia.github.io/vscode-theia-comparator/status.html) confirms), so if the plugin attempts to access that class, it would still fail on activation (but this time, after parsing :-)).

**Comment by JonasHelming** [comment] 2023-07-04 13:53
@vince-fugnitto @marcdumais-work I believe we regularily do this now, hence we could close this issue, right?

**Closed** 2023-07-04 13:54 UTC
Labels: vscode, builtins
