### ISSUE TITLE
Don't open an editor for large files & binary files by default 

### ISSUE THREAD

**Issue by davemecha** [eclipse-theia/theia#8054] opened 2020-06-19 12:35 UTC
### Feature Description:

When a file is single clicked in the tree, it is immediately opened in an editor. This is a real problem for large files like a large .tiff image or other binary content as well as for large log files. The IDE freezes and becomes unusable in many cases, while it tries to load a 20MB file.
This makes it difficult to rename a large file in the tree, because it gets opened on click.

I suggest to only open large files on double click to avoid IDE freezing. Unknown binary files should never be opened on a single click.

Another option would be to show a warning before opening a large file.

**Comment by vince-fugnitto** [comment] 2020-06-19 12:53
@davemecha thank you for the issue!
I'm closing the issue since it is a duplicate of https://github.com/eclipse-theia/theia/issues/3859, which has additional information and discussions.

**Closed by vince-fugnitto** 2020-06-19 12:53 UTC
Labels: editor, filesystem
