### ISSUE TITLE
User configuration is buggy

### ISSUE THREAD

**Issue by a1994846931931** [eclipse-theia/theia#6098] opened 2019-09-04 02:46 UTC
#### Summary:
1. Change of user configuration doesn't take effect
2. Editor of the user configuration is buggy

#### 1. Change of user configuration doesn't take effect
Change Workspace Configuration (good - takes a while to take effect though):
![workspace-configuration-valid](https://user-images.githubusercontent.com/17487291/64221492-ac0c9980-ceff-11e9-9b3f-4846e929c78b.gif)

Change User Configuration (buggy):
![user-configuration-invalid](https://user-images.githubusercontent.com/17487291/64221583-f4c45280-ceff-11e9-9a19-ecd475df85c1.gif)

#### 2. Editor of the user configuration is buggy
"Add Value" Doesn't Refresh the Editor
![user-configuration-editor-2](https://user-images.githubusercontent.com/17487291/64221909-09edb100-cf01-11e9-8be7-0e1eb56bb971.gif)

Editor's Weird Behaviour
![user-configuration-editor](https://user-images.githubusercontent.com/17487291/64221677-3a811b00-cf00-11e9-9f08-c9730f35d59e.gif)
Notice how the user configuration editor becomes dirty every time I click on it. It only happens with "editor.formatOnSave" on. In addition, the font size configuration doesn't affect user configuration editor.

### Reproduction Steps
See gifs.

**OS and Theia version:**
OS: Ubuntu 18.04
Theia: 4852766f4

**Diagnostics:**

**Comment by akosyakov** [comment] 2019-09-04 03:37
@a1994846931931 workspace settings are overriding user settings, are you sure that workspace settings don't contain `editor.formatOnSave` when you edit user settings?

**Comment by a1994846931931** [comment] 2019-09-04 03:45
> @a1994846931931 workspace settings are overriding user settings, are you sure that workspace settings don't contain `editor.formatOnSave` when you edit user settings?

@akosyakov Do you mean in "Editor's Weird Behaviour"? Yes, it does. The workspace settings contain `editor.formatOnSave`, and it's set to `true`.

**Comment by akosyakov** [comment] 2019-09-04 03:52
@a1994846931931 oh, sorry, i meant `editor.fontSize` and `Change User Configuration (buggy):`. It looks like an event is missing, we have a good coverage of tests for resolving preferences but not emitting change events.

**Comment by a1994846931931** [comment] 2019-09-04 06:16
> @a1994846931931 oh, sorry, i meant `editor.fontSize` and `Change User Configuration (buggy):`. It looks like an event is missing, we have a good coverage of tests for resolving preferences but not emitting change events.

@akosyakov No. As you can see in the gif, I've deleted `settings.json` before testing on user configuration.

**Comment by colin-grant-work** [comment] 2021-04-14 22:22
I'm unable to reproduce this behavior after #7105.

**Closed by colin-grant-work** 2021-04-14 22:22 UTC
Labels: bug, help wanted, preferences
