### ISSUE TITLE
feature-request: add support for localization (language packs)

### ISSUE THREAD

**Issue by AlbertXiao1994** [eclipse-theia/theia#5000] opened 2019-04-25 13:53 UTC
### Description

The goal is to support [localization](https://code.visualstudio.com/docs/getstarted/locales) (ability to change the display language), and also add support for vscode [language pack extensions](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans).

**Comment by akosyakov** [comment] 2019-04-25 13:56
Localization is not supported at the moment.

**Comment by kittaakos** [comment] 2021-01-21 08:19
Duplicate of https://github.com/eclipse-theia/theia/issues/1327. Closing.

**Closed by kittaakos** 2021-01-21 08:19 UTC
Labels: duplicate, enhancement, help wanted, vscode
