### ISSUE TITLE
Unable to open a new file or folder if the preference editor is opened

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7253] opened 2020-03-02 16:56 UTC
### Description
Unable to open a new File or Folder in a workspace when the Preference editor is opened

### Reproduction Steps
Open a workspace
Open a java file
Open the preference editor
Try to open from the menu context: File -> New File  ==> DO NOT WORK
Try to open from the menu context: File -> New Folder  ==> DO NOT WORK

**OS and Theia version:**
OS: Ubuntu 18.04
Theia: latest commit e48b9b5fb5fbe66c6c91c41397e74f9fd73e9195
Web: Chrome and Electron

**Diagnostics:** 

![DialogNotWithpreferenceEditor](https://user-images.githubusercontent.com/419051/75698357-98f34000-5c7c-11ea-87b9-2b4032151b1e.gif)

**Comment by vince-fugnitto** [comment] 2020-03-02 18:45
Duplicate of https://github.com/eclipse-theia/theia/issues/7067

**Closed by vince-fugnitto** 2020-03-02 18:45 UTC
Labels: bug, help wanted, preferences
