### ISSUE TITLE
Dragging a file results in screen blackout.

### ISSUE THREAD

**Issue by ashu-taide** [eclipse-theia/theia#11785] opened 2022-10-18 10:21 UTC
### Bug Description:
Dragging a file to move to any folder results in blacking out of screen.  
We are using theia in our browser based IDE, we have to reload the screen to view contents of the window again after screen blackout.

https://user-images.githubusercontent.com/109804134/196404147-6e2731db-3ebe-4ae8-a17e-620565143a21.mp4

### Steps to Reproduce:

1.Click on explorer icon to view files.
2.Drag any visible file in Explorer to a different directory.
3.The blackout should happen as soon as we drag the file.

### Additional Information

- Operating System: Ubuntu 20.04 "Bionic"
- Theia Version: 1.30.0

**Comment by vince-fugnitto** [comment] 2022-10-18 11:58
@ashu-taide thank you for reporting the issue, it is a duplicate of https://github.com/eclipse-theia/theia/issues/11757 and related to Chrome's recent update (verified that other browser's work well).

**Closed by vince-fugnitto** 2022-10-18 11:58 UTC
