### ISSUE TITLE
Webview Doesn't exist in Electron Instance

### ISSUE THREAD

**Issue by lucas-phillips** [eclipse-theia/theia#7156] opened 2020-02-14 14:12 UTC
### Description
I'm getting a 404 error when opening a webview vscode extension in an Electron instance of Theia. This only happens in the Electron instance. When I open the webview in the browser, everything works just fine.

### Reproduction Steps
I downloaded the latest version of Theia. I then cloned this repo into the plugins folder: https://github.com/leocll/vscode-extension-webview-template (If I loaded with a VSIX, a webview panel wouldn't even open, the extension just did nothing, but I believe it may be an issue with the VSIX he uploaded to the marketplace.) After cloning the repo and running Theia, I ran the command "Example: Webview", which resulted in this:
![WebviewError](https://user-images.githubusercontent.com/60973951/74538217-b8167180-4f09-11ea-86d6-676ccc44f31e.png)
(Text says: "Not Found. HTTP Error 404. The requested resource is not found" for those that don't like reading black on dark gray text :D)

Thanks for any help you can provide!

**Comment by vince-fugnitto** [comment] 2020-02-14 14:48
I tried using the [vscode-extension-samples webview-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample) and it also did not work correctly in Electron. When testing it on the browser it worked correctly.

**Comment by marcdumais-work** [comment] 2020-04-22 20:04
@akosyakov Any insights about this issue? Did you have the chance to investigate when you self-assigned? I see absolutely no errors anywhere, just a black view, as per the screenshot above.

**Comment by akosyakov** [comment] 2020-04-23 06:30
@marcdumais-work Unfortunately not, we don't have capacity at TypeFox for it. I think someone who build Electron products should step up here. Important thing that we should not rely on Electron tech.

**Comment by vince-fugnitto** [comment] 2020-05-13 18:59
I did some quick tests to try and identify the issue and I noticed one anomaly when in electron.
I verified the behavior of the [cat-coding webview sample](https://github.com/vince-fugnitto/webview-example/releases/download/1.0.0/cat-coding-0.0.1.vsix) in both the browser and electron and noticed that the method `loadResource` is called on the browser but never electron:

https://github.com/eclipse-theia/theia/blob/09d90c45dc3596f491428af60719e7a3ef3d502e/packages/plugin-ext/src/main/browser/webview/webview.ts#L421

The result is that I see a blank webview on electron.

<div align='center'>

<img width="1088" alt="Screen Shot 2020-05-13 at 2 56 52 PM" src="https://user-images.githubusercontent.com/40359487/81853107-05ff3d80-952a-11ea-8ac0-a48d68bb231f.png">

</div>

I wonder if the `WebviewChannels` are not properly communicating, I don't understand the webview code completely at the moment but I will keep investigating in the hopes of getting it to work. I've also noticed that vscode uses **webviews** and not **iframes** to render webviews in electron, but even when I modified vscode sources to use **iframes** the webviews were still properly rendered.

If others have some ideas please don't hesitate to reach out.

**Comment by akosyakov** [comment] 2020-05-14 06:42
There is a service worker that intercept requests from webview iframe and dispatch to the main window. Could you check that such service worker is running? If not why, if so then you can debug while it does not dispatch.

**Comment by vince-fugnitto** [comment] 2020-05-14 14:12
> There is a service worker that intercept requests from webview iframe and dispatch to the main window. Could you check that such service worker is running? If not why, if so then you can debug while it does not dispatch.

Thank you for the pointers @akosyakov, through logging I actually do not see the service-worker running on electron, but it is on the browser. I'll try to investigate further why this is the case.

**Comment by vince-fugnitto** [comment] 2020-05-14 15:36
I found the following electron limitation regarding **service-workers** and a corresponding vscode issue:
- https://github.com/electron/electron/issues/20248#issue-494325314
- https://github.com/microsoft/vscode/issues/83188#issue-511598573

It looks like electron does not support service workers created with a custom protocol.

**Comment by akosyakov** [comment] 2020-05-14 17:44
I don’t think it applies to us, we don’t use any electron apis or custom protocols, only standard web apis and iframes. That’s what vs code want to have eventually.

**Comment by akosyakov** [comment] 2020-05-14 17:45
Did you manage to debug it and see what is the root cause?

**Comment by vince-fugnitto** [comment] 2020-05-14 17:46
> Did you manage to debug it and see what is the root cause?

@akosyakov no I wasn't able to successfully debug it and determine the root cause yet.

**Comment by akosyakov** [comment] 2020-05-14 19:24
<img width="1306" alt="Screenshot 2020-05-14 at 21 22 55" src="https://user-images.githubusercontent.com/3082655/81976613-19450280-9629-11ea-8248-0bdb9641ec4f.png">

There are 2 issues:
- webview hostname placeholder is resolved without port in Electron
- our security token is not applied to subdomains of localhost

**Comment by akosyakov** [comment] 2020-05-14 19:54
@svenefftinge @marcdumais-work @marechal-p I wonder how we should go about security token for iframes? Webview URL is dynamically generated to deploy it on own origin and isolate from the main window context, so it does not have access to cookies and so on.

**Comment by marechal-p** [comment] 2020-05-14 21:22
@akosyakov write the security cookie in a way that they would be shared across subdomains?

**Comment by akosyakov** [comment] 2020-05-15 05:03
Webviews are 3rd party remote content. I don’t think we want to let them to access this token.

**Comment by marechal-p** [comment] 2020-05-15 13:39
WebViews are contributed by extensions, the same extensions that can access the full nodejs APIs. The token prevents parties that are not part of Theia from accessing the service (via DNS rebinding attacks or other means). But how is VS Code doing? Do they have such mechanism?

**Comment by akosyakov** [comment] 2020-05-15 13:43
> WebViews are contributed by extensions, the same extensions that can access the full nodejs APIs.

That's true. Could you try to configure a cookie that it works for localhost and its subdomains?

> But how is VS Code doing? Do they have such mechanism?

I don't know. Don't think that they have such mechanism. They use electrion APIs and custom protocols. We don't want to go this way because of single sourcing.

**Comment by marcdumais-work** [comment] 2020-05-27 15:20
I believe this issue is fixed by a combination of the following merged PRs:
- https://github.com/eclipse-theia/theia/pull/7823
- https://github.com/eclipse-theia/theia/pull/7847

**Closed by marcdumais-work** 2020-05-27 15:20 UTC
Labels: bug, electron, help wanted, webviews
