### ISSUE TITLE
Theia terminal unusable due to div covering text

### ISSUE THREAD

**Issue by buvoli** [eclipse-theia/theia#8248] opened 2020-07-27 22:06 UTC
### Bug Description:

A div is covering the Theia terminal text, making it very difficult to read and use. Notice white box covering the letter "s" in screenshot below:
![Screen Shot 2020-07-27 at 3 01 06 PM](https://user-images.githubusercontent.com/9490185/88596496-1186de80-d01a-11ea-9902-0e8323d440d0.png)
In case it is useful, the div in question has class _.xterm-helper-textarea_. Also this was not happening in earlier builds (roughly when Theia 1.2 was released) so some new dependency is likely causing the problem.

### Steps to Reproduce:

I was able to reproduce this bug using the following package.json

```json
{
  "private": true,
  "dependencies": {
    "@theia/callhierarchy": "1.3.0",
    "@theia/file-search": "1.3.0",
    "@theia/git": "1.3.0",
    "@theia/json": "1.3.0",
    "@theia/markers": "1.3.0",
    "@theia/messages": "1.3.0",
    "@theia/mini-browser": "1.3.0",
    "@theia/navigator": "1.3.0",
    "@theia/outline-view": "1.3.0",
    "@theia/plugin-ext": "1.3.0",
    "@theia/plugin-ext-vscode": "1.3.0",
    "@theia/preferences": "1.3.0",
    "@theia/preview": "1.3.0",
    "@theia/search-in-workspace": "1.3.0",
    "@theia/terminal": "1.3.0"
  },
  "scripts": {
    "prepare": "yarn run clean && yarn build",
    "clean": "theia clean",
    "build": "theia build",
    "start": "theia start --plugins=local-dir:plugins",
    "download:plugins": "theia download:plugins"
  },
  "devDependencies": {
    "@theia/cli": "1.3.0"
  },
  "theiaPluginsDir": "plugins",
  "theiaPlugins": { }
}

```
paired with the Dockerfile
```Docker
FROM node:dubnium-alpine
WORKDIR /opt/theia
COPY package.json ./package.json
RUN apk add python2 build-base ; \
    yarn ; \
    yarn prepare
ENTRYPOINT ["yarn", "start", "--hostname", "0.0.0.0"]
```
and the build/run commands
```console
$ docker build . -t alpine-theia:latest
$ docker run --rm -ti -p 3000:3000 alpine-theia:latest
```

### Additional Information

- Operating System: Alpine Linux
- Theia Version: 1.3.0

**Comment by vince-fugnitto** [comment] 2020-07-27 23:08
@buvoli thank you for reporting the issue, it has been fixed already by #8204 (duplicate of https://github.com/eclipse-theia/theia/issues/8233). The next release will be this Thursday, else you can use `next` in your docker image instead of the `latest` tag.

**Closed by vince-fugnitto** 2020-07-27 23:08 UTC
