### ISSUE TITLE
[preferences] Improve display of complex datatypes

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#2834] opened 2018-09-10 15:42 UTC
![image](https://user-images.githubusercontent.com/14182238/45307773-e3638880-b4ed-11e8-8645-ca7859db2453.png)

In the above image, I tried to specify the true type that `cpp.buildConfigurations` was expecting. As you can see it is not looking super nice.

Maybe we should add children nodes to this preference, listing the sub items one by one with a description?

```
- Cpp(2):
    cpp.buildPreferences: list / List of build configurations
        name: string / Name of the configuration
        directory: string / Compilation database directory (parent folder of compile_commands.json)
    cpp.experimentalCommands: boolean / ...
```

It doesn't even have to be expandable.

**Comment by vince-fugnitto** [comment] 2020-01-30 18:21
Closing since it is a duplicate of the generic https://github.com/eclipse-theia/theia/issues/2834

**Closed by vince-fugnitto** 2020-01-30 18:21 UTC
Labels: cpp, enhancement, preferences
