### ISSUE TITLE
Cannot use GitLens in Theia

### ISSUE THREAD

**Issue by meng-jpg** [eclipse-theia/theia#14335] opened 2024-10-21 03:00 UTC
### Bug Description:
A number of buttons in GitLens sidebar are in the state of grey unable to click, and most of the clickable buttons have no response after clicking. For example, `Open a Folder or Repository`, `Start Here (Welcome)`, `Open GitLens Settings`, `Connect an Integration`, `Commands`. 
<img width="1278" alt="截屏2024-10-21 10 45 50" src="https://github.com/user-attachments/assets/ea2feaad-d97d-451c-aba0-2838b404db21">

When I try to login from `GitLens: Sign In to GitKraken` in the command panel, I get the following error:
<img width="588" alt="截屏2024-10-21 10 51 52" src="https://github.com/user-attachments/assets/9298caa8-88f5-4217-b050-c06867dec83b">

### Steps to Reproduce:

1. Install GitLens — Git supercharged
2. Click buttons in the GitLens sidebar
3. Nothing will happen

### Additional Information

- Operating System: ubuntu 20
- Theia Version: 1.54.0 electron

**Comment by tsmaeder** [comment] 2024-10-21 08:53
Confirmed on Windows 11/1.54.0 when doing "sign into gitkraken" from the command quickpick

**Comment by tsmaeder** [comment] 2024-10-21 09:30
This is a bug in GitLens: they call `vscode.env.openExternal()` with a string instead of an URI as documented in https://code.visualstudio.com/api/references/vscode-api#env. And it seems they are even doing this on purpose https://github.com/gitkraken/vscode-gitlens/blob/main/src/system/vscode/utils.ts#L280.
@meng-jpg I would suggest you open an issue with gitkraken so that they are aware folks _are_ using their product on Theia and that it's not working if they rely on VS Code implementation details.
Considering GitLens is a very popular extension, we still probably want to be bug-compatible in this case.

**Comment by meng-jpg** [comment] 2024-10-21 10:11
> This is a bug in GitLens: they call `vscode.env.openExternal()` with a string instead of an URI as documented in https://code.visualstudio.com/api/references/vscode-api#env. And it seems they are even doing this on purpose https://github.com/gitkraken/vscode-gitlens/blob/main/src/system/vscode/utils.ts#L280. @meng-jpg I would suggest you open an issue with gitkraken so that they are aware folks _are_ using their product on Theia and that it's not working if they rely on VS Code implementation details. Considering GitLens is a very popular extension, we still probably want to be bug-compatible in this case.

Thank you for your advice. I have submitted the issue to gitkraken and am waiting for a reply.

**Comment by msujew** [comment] 2024-10-21 10:21
@tsmaeder Without invalidating what you said, it seems like passing a `string` actually "fixes" a bug in VS Code related to incorrectly encoded URI strings. Apparently it's unfixable due to backwards compatibility, see https://github.com/microsoft/vscode/issues/156859#issuecomment-1263474264 (related to the discussion surrounding URIs we had a while back). It seems like the VS Code people want to use `URL` in addition to `URI`, but that change hasn't landed yet.

We should consider supporting `string` in the meantime, since this actually resolves the issue. I'm not a big fan of this myself, but the VS Code team coded themselves into a corner here.

**Comment by tsmaeder** [comment] 2024-10-21 12:00
Yeah, I remember I've seen this one before. It's kind sad, though, that in five years, they couldn't be arsed to add an alternative signature to the API.

**Closed** 2024-10-24 14:14 UTC
