### ISSUE TITLE
improve user feedback of plugin deployment

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5552] opened 2019-06-21 03:02 UTC
### Description
```
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler { unpackedFolder: '/tmp/vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'vscode:extension/humao.rest-client',
     pluginId: 'vscode:extension/humao.rest-client',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath: '/tmp/vscode-extension-marketplace/humao_rest_client.vsix',
     initPath: '/tmp/vscode-extension-marketplace/humao_rest_client.vsix',
     resolved: true,
     resolvedByName: 'VsCodePluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root ERROR Request deploy failed with error: unexpected end of file Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
```

### Reproduction Steps
Press F1
Plugin: Deploy Plugin by Id
input vscode:extension/humao.rest-client
enter

**OS and Theia version:**
**Diagnostics:**

**Comment by 502647092** [comment] 2019-06-21 03:03
maybe we need display plugin deploy process and result

**Comment by akosyakov** [comment] 2019-07-01 08:26
Right now there is no any user feedback about failed deployment. We should improve it.

**Comment by 502647092** [comment] 2019-07-02 00:52
@akosyakov 
I am in China
Here download vscode plugin very slow and some time failed
I think we can add download status in statusbar and support proxy download

**Comment by akosyakov** [comment] 2019-07-02 05:32
Agreed, indicating progress will be good and reporting deployment errors. We could also use `requestretry` similar to how we download debug adapters that it attempts to download 5 times on network errors.

**Comment by danarad05** [comment] 2021-05-25 12:43
@akosyakov @502647092 
@offer8

Please check PR #9510 which fixes issue #3632 - is solution in #9510 sufficient in regard to this PR?
Thanks

**Comment by danarad05** [comment] 2021-05-25 12:47
@vince-fugnitto is this duplicate of #3632?

**Comment by vince-fugnitto** [comment] 2021-05-25 12:57
Closing in favor of https://github.com/eclipse-theia/theia/issues/3632.

**Closed by vince-fugnitto** 2021-05-25 12:57 UTC
Labels: enhancement, help wanted, plug-in system
