### ISSUE TITLE
How can i use my code snippets inside theia project?

### ISSUE THREAD

**Issue by alimoncul** [eclipse-theia/theia#7052] opened 2020-02-03 06:13 UTC
### Description
I would like to use my custom snippets for my projects inside theia like vscode

**OS and Theia version:**
Theia: 0.14
OS: Alpine Linux (default docker for theia)

**Comment by akosyakov** [comment] 2020-02-03 09:21
It's not possible right now. PRs are welcomed, please see https://github.com/eclipse-theia/theia/issues/3686#issuecomment-530761985

Duplicate of https://github.com/eclipse-theia/theia/issues/3686

**Closed by akosyakov** 2020-02-03 09:21 UTC
Labels: question
