### ISSUE TITLE
Warn about insecure context

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7550] opened 2020-04-12 06:15 UTC
### Description
When running in insecure context, only this warning is shown when using copy/paste:
![image](https://user-images.githubusercontent.com/19504461/79061908-aea54d80-7c9d-11ea-96c7-4d7a75134c1e.png)
Probably it'll be better if a warning is displayed when the windows is opened.

### Reproduction Steps
1. Run browser example with `--hostname 0.0.0.0` option
2. Access it using your IP in local network (it'll be HTTP running outside of localhost, insecure browser context)
3. See no warning
4. Try to copy/paste something (other apis might not work as well, read docs about insecure context)
5. See this message:
![image](https://user-images.githubusercontent.com/19504461/79061934-0774e600-7c9e-11ea-92af-a5511b595e88.png)
No warning is shown when logged in, but that would be great.

**OS and Theia version:**
OS: Ubuntu 19.10
Theia: `master`

**Diagnostics:**

**Comment by vince-fugnitto** [comment] 2020-04-12 14:34
The issue is not about running in an insecure context, it’s an issue regarding permissions and the if the commands are supported by the given browser: https://github.com/eclipse-theia/theia/issues/2171

We should re-use the new clipboard service API as mentioned in the original issue to attempt to support across the browser targets.

I don’t think the way forward is to warn users on app startup since:
- it is noisy
- it is caused by insecure contexts

Additional Information:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by vince-fugnitto** [comment] 2020-04-15 16:09
Closing the issue for the moment as I do not believe there is anything for the framework to do.
The message (regarding copy/paste) is not caused by an insecure context, nor do I believe the framework should impose warning messages to downstream applications regarding how applications are deployed.

Please re-open the issue if it's not the case.

**Closed by vince-fugnitto** 2020-04-15 16:09 UTC
Labels: clipboard, question
