### ISSUE TITLE
Atlassian Jira fails in Theia Blueprint

### ISSUE THREAD

**Issue by kineticsquid** [eclipse-theia/theia#13087] opened 2023-11-21 19:52 UTC
Atlassian Jira extension is available on open-vsx.org, https://open-vsx.org/extension/atlassian/atlascode. It is up to date with the Visual Studio Marketplace, 3.0.7. I can install and use it in Visual Studio (1.84.2 on OSX). When I attempt to do so in Theia Blueprint (1.43.0.128) the settings page renders blank. When you click the 'Please login to Jira' link in the upper left, the settings open for Jira instance credentials.

Visual Studio:
<img width="1597" alt="image" src="https://github.com/eclipse-theia/theia/assets/681707/6b89e3b1-db68-4ea0-8619-f8d5d456afff">

Theia Blueprint:
<img width="1414" alt="image" src="https://github.com/eclipse-theia/theia/assets/681707/d946cca5-9afc-4a29-be09-43adcd555d0e">

**Comment by msujew** [comment] 2023-11-21 20:13
It actually loads a few JS bundles that are supposed to render something to the webview. But they seem to error out with some obfuscated/minified error:

![image](https://github.com/eclipse-theia/theia/assets/4377073/70749e45-4739-4180-a2af-e579f7c4cfaf)

Doesn't seem to be an issue with Theia, but rather something that the extension is doing wrong when running in Theia.

The extension code is open source, so one could build a non-minified version to debug the issue: https://bitbucket.org/atlassianlabs/atlascode/src/main/

**Comment by kineticsquid** [comment] 2023-11-28 20:49
@msujew I tried your suggestion. I cloned the Bitbucket repo and was able to build and debug it in VS Code. But when I attempted the same in Theia (Theia Blueprint) I was able to build it, but extension initialization failed with instructions to check the debug log, which was empty.

**Comment by rschnekenbu** [comment] 2023-12-06 09:15
@msujew, I can have a look. Can you assign me the task?

**Comment by planger** [comment] 2024-01-25 18:26
https://github.com/eclipse-theia/theia/issues/12371 may be potentially related?

**Comment by rschnekenbu** [comment] 2024-01-31 09:02
I could reproduce the error from a local build version. While trying to configure the settings, the setting page shows up, and then goes blank. The console is spammed with these messages:
`root ERROR [webview: 5667b641-105c-4a35-a710-d03821097319] Warning: A component is changing a controlled input of type checkbox to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components%s`


`root ERROR [webview: 5667b641-105c-4a35-a710-d03821097319] The above error occurred in the <InlineTextEditorList> component:
    in InlineTextEditorList
    in div (created by Styled(MuiBox))
    in Styled(MuiBox)
   [...]
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.`

The InlineTextEditorList comes from atlassian library (guipi core components) and is used in several places.

I could not investigate further to understand why the extensions works fine in vscode and not in theia. I could still create new tasks on Jira and access their information from the extension in Theia, but this setting page has to be fixed in order to proper use the tool.  
 
Zipped vsix: [atlascode-3.1.0.zip](https://github.com/eclipse-theia/theia/files/14098399/atlascode-3.1.0.zip)

**Comment by tortmayr** [comment] 2024-03-05 14:36
@tsmaeder @rschnekenbu :I further investigated this issue
As @rschnekenbu already mentioned, the initial render of the UI works. Once the UI receives the first update from the Jira extension, rendering breaks. The render update input for the Settings page is derived from the configured settings for `atlascode`, which are computed by the extension. In Theia, this update object is not complete/looks different than in VS Code.
The extension retrieves the config settings for `atlasco` and flattens and merges global/workspace/folder values with default values before sending the update to the webview. For this, the library [flatten-anything](https://www.npmjs.com/package/flatten-anything) is used.

To break it further down,
the extension calls `workspace.getConfiguration('atlascode').inspect()`. Semantically, the result of this looks the same in both VSCode and Theia (i.e.,  defaultValue and globalWorkspacevalues are the same in both applications).
After that, flatten-anything is used to create a merged representation, which is then sent to the webview.
Here, the merge result is different. In Theia, merging doesn't seem to have an effect, and the result just contains the original defaultValue.

The root cause for this is that the inspect result is not the same on a prototype level. In Theia, certain object properties of the result, e.g., `inspectResult.defaultValue` and `inspectResult.globalValue`, don't have the property prototype (meaning they must have been created with `Object.create(null)`). It seems like flatten-anything cannot handle prototype-less objects.

I tested a temporary fix in the atlascode extension by preprocessing the inspection result before merging and converting all nested properties into "real" objects again. This seems to fix the issue, and the settings page is rendered again.

Nevertheless, we should further investigate why the behavior in Theia. regarding `workspace.getConfiguration().inspect()` differs  in the first place. Other extension contributors could also run into issues caused by this behavioral difference.

It seems like some `Prototype Pollution` mitigation is in place (https://github.com/eclipse-theia/theia/pull/8675/) that could cause that issue. Unfortunately, I could not find any additional details on this, but I'm wondering why we need this mitigation here in the first place (resp. why it is not necessary in VS Code).

**Comment by tsmaeder** [comment] 2024-03-11 10:08
The mitigation of prototype pollution does not work anyway: the attack vector we're trying to prevent are workspace settings. However, settings files are processed in the front-end (preference-provider.ts, etc.) and the resulting structures then sent to the plugin host process. At this time, the prototype injection will have already worked on the browser side, in which case the evil properties like `__proto__` will no longer be sent. 
I think a proper approach would be to use `Object.prototype" as the prototype of the settings objects and to ignore any properties that are in both in the `settings.json` and in the `Object.prototype`. This will include things like `constructor` and '__proto__`.

**Comment by tortmayr** [comment] 2024-03-11 13:36
@tsmaeder I did test this by tweaking the `atlascode` extension and converting the object (and nested objects) received from the inspect() call to "real" prototype objects:

```ts
public flattenedConfigForTarget(target: ConfigTarget): FlattenedConfig {
        const inspect = this.convertToPrototypeObject(configuration.inspect<IConfig>());
        //...     
  }
  
 convertToPrototypeObject(obj: any): any {
        // Base case: if it's not an object or it's null, return it directly
        if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) {
            return obj;
        }

        // Create a new object that inherits from Object.prototype
        const newObj = {};

        // Recursively process each property of the object
        for (const key of Object.keys(obj)) {
            newObj[key] = this.convertToPrototypeObject(obj[key]);
        }

        return newObj;
    }
```

With that change the settings page renders as expected in Theia:

![image](https://github.com/eclipse-theia/theia/assets/2311075/2b3b4ad9-992e-45c7-9c1a-9e8256b8b33a)

You can find the vsix+source code here:
[atlascode_theia13087.zip](https://github.com/eclipse-theia/theia/files/14559358/atlascode_theia13087.zip)


So I guess, we are still missing some `Object.null` creations somewhere because my changes do nothing special other than
creating proper objects and reassigning the properties.

**Comment by tsmaeder** [comment] 2024-03-11 15:29
I guess the problem is ultimately that our code in `PreferenceRegistryExtImpl` uses the `Configuration` class form monaco: this class ultimately calls `toValuesTree()` from `configuratoin.ts`, which creates objects using `Object.create(null)`.

**Comment by tsmaeder** [comment] 2024-03-12 07:52
In the end, the answer why this works in VS Code is surprisingly simple: in `extHostConfiguration.ts`, the configuration object returned from `getConfiguration()` does a `deepClone` of all values in it's `inspect` method. If you look at the  equivalent code in `preference-registry.ts`, it's `configInspect.defaultValue = result.default?.value;` vs `defaultValue: deepClone(config.policy?.value ?? config.default?.value),`. The 'deepClone()' takes the prototype-less object in the default values and clones them into objects with a proper prototype.

**Closed** 2024-03-27 11:15 UTC
Labels: vscode, webviews

**Comment by kineticsquid** [comment] 2024-04-15 17:35
Thanks, confirmed this works now
