### ISSUE TITLE
[debug console]copy selected item will cause console scroll to the top position

### ISSUE THREAD

**Issue by yeweiasia** [eclipse-theia/theia#5970] opened 2019-08-17 03:03 UTC
### Description
copy selected item will cause console scroll to the top position

### Reproduction Steps
![debug_console_copy_scroll_to_top](https://user-images.githubusercontent.com/16164849/63205927-7766a880-c0de-11e9-8096-e9fb2b063451.gif)

**OS and Theia version:**
theia 0.9.0
ubuntu 18.04

**Diagnostics:**

**Comment by 502647092** [comment] 2019-08-17 07:54
@akosyakov 
maybe this problem same as tree view

**Comment by akosyakov** [comment] 2019-08-17 08:09
@502647092 could be, generally scrolling in the debug console is quite broken right now :( see also https://github.com/theia-ide/theia/issues/5495 and https://github.com/theia-ide/theia/issues/5493

**Comment by tsmaeder** [comment] 2019-09-25 08:32
This works for me.

**Comment by akosyakov** [comment] 2019-09-25 10:01
@yeweiasia @502647092 Could you double check whether you can reproduce it?

**Comment by yeweiasia** [comment] 2019-10-08 02:45
@akosyakov I've test on the head of marster, this problem still exists.

**Comment by akosyakov** [comment] 2019-10-08 02:46
@yeweiasia which browser? os?

**Comment by yeweiasia** [comment] 2019-10-08 03:24
> @yeweiasia which browser? os?

os: ubuntu 18.04 
browser: firefox 69.0.1 & Chromium (Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit))

**Comment by 502647092** [comment] 2019-10-08 08:00
![temp](https://user-images.githubusercontent.com/10203793/66377524-59ce0500-e9e4-11e9-937d-177eafeea451.gif)
this problem still exists
Windows 10
Chrome 77.0.3865.90

**Comment by tsmaeder** [comment] 2019-10-08 08:28
@502647092 that is not the debug console.

**Comment by svenefftinge** [comment] 2019-11-25 10:54
Should be fixed with https://github.com/eclipse-theia/theia/pull/6621 (please reopen if not)

**Closed by svenefftinge** 2019-11-25 10:54 UTC
Labels: bug, debug, help wanted
