### ISSUE TITLE
Unable to install the latest extension released by Microsoft

### ISSUE THREAD

**Issue by zhouxinghong** [eclipse-theia/theia#14153] opened 2024-09-10 12:39 UTC
### Bug Description:

Unable to install the latest extension released by Microsoft

### Additional Information
Unable to install the latest extension released by Microsoft

https://github.com/user-attachments/assets/02da27d1-f4d7-4265-965e-7a2d47411f16

- Operating System: Windows 10 19044
- Theia Version: 1.53.200.162

**Comment by alculete** [comment] 2024-09-11 06:54
Eclipse Theia-IDE marketplace is https://open-vsx.org and not the one you are searching on the browser.

**Comment by JonasHelming** [comment] 2024-09-11 07:17
To add a few more details:

The Microsoft extension marketplace forbids any other tool than VS Code to connect to it to install extensions (e.g. also VS Codium is disallowed). Therefore, an open marketplace exists called openvsx. If an extension is not available on OpenVSX, you should request the extension builders to publish it there, too.

**Comment by JonasHelming** [comment] 2024-09-11 07:18
I am closing this, as this is not a bug in Theia.

**Closed by JonasHelming** 2024-09-11 07:18 UTC

**Comment by msujew** [comment] 2024-09-11 07:48
@zhouxinghong Note that the [RedHat Java extension](https://open-vsx.org/extension/redhat/java) is available on open-vsx. The official Microsoft extension for C# however is not. Generally, all closed source extensions built by Microsoft (like the C# or Pylance extensions) are not available on open-vsx.

**Comment by alculete** [comment] 2024-09-11 09:19
One of the ideas for creating the open source marketplace was to able to make available a vendor neutral marketplace where everyone could use without limitations.

**Comment by zhouxinghong** [comment] 2024-09-11 13:00
Thanks for your answer! 🙏

Also, I have another question🤔?
Is there a way to port the C# and Python extensions built by Microsoft to the [Open](https://open-vsx.org/) Marketplace?

**Comment by msujew** [comment] 2024-09-11 13:11
@zhouxinghong The C# extension code is available [here](https://github.com/dotnet/vscode-csharp) someone would need to add instructions on how to build and publish it to [this repository](https://github.com/open-vsx/publish-extensions). As for `Pylance`: Microsoft keeps it closed source and its license disallows installing the extension outside of vscode. Meaning that no Theia user is allowed to legally install it. A good alternative is [Pyright](https://open-vsx.org/extension/ms-pyright/pyright).

**Comment by zhouxinghong** [comment] 2024-09-11 14:36
Thanks for your answer! 🙏
