### ISSUE TITLE
[Java] Support RedHat JDT LS extensions

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse-theia/theia#1878] opened 2018-05-09 22:31 UTC
VSCode has support RedHat Java LS extensions/plugins: https://github.com/redhat-developer/vscode-java/wiki/Contribute-a-Java-Extension
This needs to be mirrored in Theia IDE. Our LS has an extension for JDT LS to get classpath for a project from the JDT LS. 

JDT LS extension is a JAR that JDT LS should be aware of. This JAR is an eclipse plugin... The path to the JAR is to be sent with `InitializeParams`:
```
{
  ...
  initializationOptions: {
    bundles: [ '/Users/me/myfolder/jars/jdt-extension.jar', '/Users/me/myfolder/jars/another-jdt-extension.jar'  ]
  }
  ...
}
```
Paths to JARs are entered in `package.json` under `javaExtensions: [ 'jars/jdt-extension.jar', 'jars/another-jdt-extension.jar' ]
Note that JSON RPC message should have absolute paths.

This also needs a small protocol extension on the Java extension client side. Namely handling for `workspace/executeClientCommand` - this message is sent to the client to execute a command on the client: https://github.com/eclipse/eclipse.jdt.ls/commit/b5f383f45503645baf5f0497bbb37952031bec90

**Comment by marcdumais-work** [comment] 2018-05-11 10:57
Duplicate of https://github.com/theia-ide/theia/issues/1869 ?

**Comment by BoykoAlex** [comment] 2018-05-11 13:50
Same with exception of `workspace/executeClientCommand` message support.

**Comment by gorkem** [comment] 2018-06-03 00:36
@fbricon @tsmaeder another architectural puzzle to solve.

**Comment by tsmaeder** [comment] 2018-06-07 13:22
This is not a duplicate at all...#1869 is about consuming the che-ls-jdt product instead of jdt.ls. Extensibility is another story.

**Comment by tsmaeder** [comment] 2018-08-15 08:34
Valeri Svydenko is working on this.

**Comment by marcdumais-work** [comment] 2020-02-28 13:11
Since we no longer support `@theia/java` and instead advise to use `vscode-java`, I think we can close this issue. Please re-open if disagree.

**Closed by marcdumais-work** 2020-02-28 13:11 UTC
Labels: java
