### ISSUE TITLE
core: building minimal app fails

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#7056] opened 2020-02-03 15:09 UTC
### Description

When building an application using only `@theia/core`, webpack fails with:

```
ERROR in ./node_modules/@theia/core/lib/common/lsp-types.js
Module not found: Error: Can't resolve 'vscode-languageserver-protocol' in 'D:\sources\tests\theia-prefs\node_modules\@theia\core\lib\common'
 @ ./node_modules/@theia/core/lib/common/lsp-types.js 18:39-80
 @ ./node_modules/@theia/core/lib/common/index.js
 @ ./node_modules/@theia/core/lib/browser/frontend-application-module.js
 @ ./src-gen/frontend/index.js
```

Not really sure why core depends on `vscode-languageserver-protocol` directly, but either:
- add this package as a peer-dependency.
- add this package as a dependency.
- remove this dependency from core?

@akosyakov ?

### Reproduction Steps

```
yarn init -y
yarn add @theia/core
yarn add -D @theia/cli
yarn theia build --mode development
```

**OS and Theia version:** Windows 10 - Theia 0.15.0

**Diagnostics:**

**Comment by vince-fugnitto** [comment] 2020-02-03 15:17
@marechal-p duplicate of https://github.com/eclipse-theia/theia/issues/6129? Maybe report your findings there.

**Comment by marechal-p** [comment] 2020-02-03 15:24
I guess mine is more up to date? In your issue it seems to fail at runtime, mine doesn't even fully builds.

**Comment by marechal-p** [comment] 2020-02-03 15:27
If I manually add the missing package, it builds but then the browser app fails with:

```
root ERROR ./node_modules/@theia/core/lib/browser/preferences/preference-provider.js/PreferenceProvider.prototype.resolve@http://localhost:3000/bundle.js:38714:26
./node_modules/@theia/core/lib/browser/preferences/preference-provider.js/PreferenceProvider.prototype.get@http://localhost:3000/bundle.js:38711:21
./node_modules/@theia/core/lib/browser/preferences/preference-service.js/PreferenceServiceImpl.prototype.doInspectInScope@http://localhost:3000/bundle.js:39502:37
./node_modules/@theia/core/lib/browser/preferences/preference-service.js/PreferenceServiceImpl.prototype.inspectInScope@http://localhost:3000/bundle.js:39482:26
./node_modules/@theia/core/lib/browser/preferences/preference-service.js/PreferenceServiceImpl.prototype.inspect@http://localhost:3000/bundle.js:39476:32
./node_modules/@theia/core/lib/browser/common-frontend-contribution.js/CommonFrontendContribution.prototype.updateThemePreference@http://localhost:3000/bundle.js:29349:46
./node_modules/@theia/core/lib/browser/common-frontend-contribution.js/CommonFrontendContribution.prototype.init/<@http://localhost:3000/bundle.js:29340:71
./node_modules/@theia/core/lib/common/event.js/CallbackList.prototype[Symbol.iterator]/</<@http://localhost:3000/bundle.js:56976:33
./node_modules/@theia/core/lib/common/event.js/CallbackList.prototype.invoke@http://localhost:3000/bundle.js:56991:39
./node_modules/@theia/core/lib/common/event.js/Emitter.prototype.fire@http://localhost:3000/bundle.js:57078:29
./node_modules/@theia/core/lib/browser/icon-theme-service.js/IconThemeService.prototype.setCurrent@http://localhost:3000/bundle.js:33708:40
./node_modules/@theia/core/lib/browser/icon-theme-service.js/IconThemeService.prototype.register@http://localhost:3000/bundle.js:33667:18
./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/DefaultFileIconThemeContribution.prototype.registerIconThemes@http://localhost:3000/bundle.js:33536:20
./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/IconThemeApplicationContribution.prototype.onStart/</<@http://localhost:3000/bundle.js:33491:59
step@http://localhost:3000/bundle.js:33454:23
verb/<@http://localhost:3000/bundle.js:33435:53
./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/__awaiter</<@http://localhost:3000/bundle.js:33429:71
./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/__awaiter<@http://localhost:3000/bundle.js:33425:12
./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/IconThemeApplicationContribution.prototype.onStart@http://localhost:3000/bundle.js:33479:16
_loop_3/</<@http://localhost:3000/bundle.js:33144:155
./node_modules/@theia/core/lib/browser/frontend-application.js/FrontendApplication.prototype.measure/</<@http://localhost:3000/bundle.js:33226:46
step@http://localhost:3000/bundle.js:32690:23
verb/<@http://localhost:3000/bundle.js:32671:53
./node_modules/@theia/core/lib/browser/frontend-application.js/__awaiter</<@http://localhost:3000/bundle.js:32665:71
./node_modules/@theia/core/lib/browser/frontend-application.js/__awaiter<@http://localhost:3000/bundle.js:32661:12
./node_modules/@theia/core/lib/browser/frontend-application.js/FrontendApplication.prototype.measure@http://localhost:3000/bundle.js:33217:16
_loop_3/<@http://localhost:3000/bundle.js:33144:69
step@http://localhost:3000/bundle.js:32690:23
verb/<@http://localhost:3000/bundle.js:32671:53
step@http://localhost:3000/bundle.js:32675:139
verb/<@http://localhost:3000/bundle.js:32671:53
fulfilled@http://localhost:3000/bundle.js:32662:58
```

**Comment by vince-fugnitto** [comment] 2020-02-03 15:27
> I guess mine is more up to date? In your issue it seems to fail at runtime, mine doesn't even fully builds.

I still think we should only have a single issue reporting the problem and it should contain updates?
(easier to track and continue previous discussions)

**Comment by vince-fugnitto** [comment] 2020-02-03 15:28
I'll close the original in favor of this one.

**Comment by vince-fugnitto** [comment] 2020-02-03 15:31
> If I manually add the missing package, it builds but then the browser app fails with:
> 
> ```
> root ERROR ./node_modules/@theia/core/lib/browser/preferences/preference-provider.js/PreferenceProvider.prototype.resolve@http://localhost:3000/bundle.js:38714:26
> ./node_modules/@theia/core/lib/browser/preferences/preference-provider.js/PreferenceProvider.prototype.get@http://localhost:3000/bundle.js:38711:21
> ./node_modules/@theia/core/lib/browser/preferences/preference-service.js/PreferenceServiceImpl.prototype.doInspectInScope@http://localhost:3000/bundle.js:39502:37
> ./node_modules/@theia/core/lib/browser/preferences/preference-service.js/PreferenceServiceImpl.prototype.inspectInScope@http://localhost:3000/bundle.js:39482:26
> ./node_modules/@theia/core/lib/browser/preferences/preference-service.js/PreferenceServiceImpl.prototype.inspect@http://localhost:3000/bundle.js:39476:32
> ./node_modules/@theia/core/lib/browser/common-frontend-contribution.js/CommonFrontendContribution.prototype.updateThemePreference@http://localhost:3000/bundle.js:29349:46
> ./node_modules/@theia/core/lib/browser/common-frontend-contribution.js/CommonFrontendContribution.prototype.init/<@http://localhost:3000/bundle.js:29340:71
> ./node_modules/@theia/core/lib/common/event.js/CallbackList.prototype[Symbol.iterator]/</<@http://localhost:3000/bundle.js:56976:33
> ./node_modules/@theia/core/lib/common/event.js/CallbackList.prototype.invoke@http://localhost:3000/bundle.js:56991:39
> ./node_modules/@theia/core/lib/common/event.js/Emitter.prototype.fire@http://localhost:3000/bundle.js:57078:29
> ./node_modules/@theia/core/lib/browser/icon-theme-service.js/IconThemeService.prototype.setCurrent@http://localhost:3000/bundle.js:33708:40
> ./node_modules/@theia/core/lib/browser/icon-theme-service.js/IconThemeService.prototype.register@http://localhost:3000/bundle.js:33667:18
> ./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/DefaultFileIconThemeContribution.prototype.registerIconThemes@http://localhost:3000/bundle.js:33536:20
> ./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/IconThemeApplicationContribution.prototype.onStart/</<@http://localhost:3000/bundle.js:33491:59
> step@http://localhost:3000/bundle.js:33454:23
> verb/<@http://localhost:3000/bundle.js:33435:53
> ./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/__awaiter</<@http://localhost:3000/bundle.js:33429:71
> ./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/__awaiter<@http://localhost:3000/bundle.js:33425:12
> ./node_modules/@theia/core/lib/browser/icon-theme-contribution.js/IconThemeApplicationContribution.prototype.onStart@http://localhost:3000/bundle.js:33479:16
> _loop_3/</<@http://localhost:3000/bundle.js:33144:155
> ./node_modules/@theia/core/lib/browser/frontend-application.js/FrontendApplication.prototype.measure/</<@http://localhost:3000/bundle.js:33226:46
> step@http://localhost:3000/bundle.js:32690:23
> verb/<@http://localhost:3000/bundle.js:32671:53
> ./node_modules/@theia/core/lib/browser/frontend-application.js/__awaiter</<@http://localhost:3000/bundle.js:32665:71
> ./node_modules/@theia/core/lib/browser/frontend-application.js/__awaiter<@http://localhost:3000/bundle.js:32661:12
> ./node_modules/@theia/core/lib/browser/frontend-application.js/FrontendApplication.prototype.measure@http://localhost:3000/bundle.js:33217:16
> _loop_3/<@http://localhost:3000/bundle.js:33144:69
> step@http://localhost:3000/bundle.js:32690:23
> verb/<@http://localhost:3000/bundle.js:32671:53
> step@http://localhost:3000/bundle.js:32675:139
> verb/<@http://localhost:3000/bundle.js:32671:53
> fulfilled@http://localhost:3000/bundle.js:32662:58
> ```

As mentioned in the original issue, the `preferences` error is related to https://github.com/eclipse-theia/theia/issues/667

**Comment by akosyakov** [comment] 2020-02-03 17:04
Why do we need lsp-types in core? Maybe it should go to @theia/languages?

**Comment by akosyakov** [comment] 2020-02-03 17:07
Also Range should be imported from vscode-languageserver-types, not protocol. That should be enough to fix.

**Comment by marechal-p** [comment] 2020-02-04 16:36
Updating the import statement would fix it indeed, but should this file be moved to languages?

Right now it is used by filesystem, it would make it dependent on languages.

**Comment by akosyakov** [comment] 2020-02-04 18:21
> Updating the import statement would fix it indeed, but should this file be moved to languages?

let's keep it as is

**Closed** 2020-03-30 15:40 UTC
Labels: core
