### ISSUE TITLE
Dragging files in file explorer blanks out the screen on Chrome

### ISSUE THREAD

**Issue by smelliot** [eclipse-theia/theia#11757] opened 2022-10-12 13:01 UTC
### Bug Description:

On the latest version of Chrome, clicking and dragging a file in the open workspace blanks out the entire screen and requires a page refresh, this prevents file moves. This issue is present in Chrome v106, but was not present in v104.

### Steps to Reproduce:

1. Click and drag a file in the file explorer pane
2. The screen should blank out

### Additional Information

- Operating System: Windows 10
- Theia Version: Experienced on 1.25.0, 1.28.0, 1.30.0

**Comment by vince-fugnitto** [comment] 2022-10-12 13:25
@smelliot thank you for reporting the issue, I was unable to reproduce (`106.0.5249.119 (Official Build)`) as the file is correctly uploaded into the workspace. Do you mind sharing a quick video showing the issue?

**Comment by smelliot** [comment] 2022-10-12 15:23
Hi @vince-fugnitto , thanks for responding so quickly, here's a screen recording of the issue, it happens with any file type and only occurs on Chromium browsers (tested on latest Chrome and Edge, both fail, works as expected on Firefox).

https://user-images.githubusercontent.com/39274321/195382683-d72470a1-54ea-49cf-8352-a8d3ff9cad22.mp4

This recording was taken on Theia v1.28.0 with the following plugins configuration, there is no log output to the console specifying any error.

```
"theiaPlugins": {
    "builtin-extension-pack": "https://open-vsx.org/api/eclipse-theia/builtin-extension-pack/1.62.3/file/eclipse-theia.builtin-extension-pack-1.62.3.vsix",
    "path-autocomplete": "https://open-vsx.org/api/ionutvmi/path-autocomplete/1.17.1/file/ionutvmi.path-autocomplete-1.17.1.vsix",
    "vscode-microsoft-python": "https://open-vsx.org/api/ms-python/python/2020.7.96456/file/ms-python.python-2020.7.96456.vsix"
  },
  "theiaPluginsExcludeIds": [
    "vscode.bat",
    "vscode.clojure",
    "vscode.coffeescript",
    "vscode.configuration-editing",
    "vscode.cpp",
    "vscode.csharp",
    "vscode.dart",
    "vscode.debug-auto-launch",
    "vscode.debug-server-ready",
    "vscode.docker",
    "vscode.emmet",
    "vscode.extension-editing",
    "vscode.fsharp",
    "vscode.git",
    "vscode.github",
    "vscode.github-authentication",
    "vscode.go",
    "vscode.groovy",
    "vscode.grunt",
    "vscode.gulp",
    "vscode.handlebars",
    "vscode.hlsl",
    "vscode.image-preview",
    "vscode.ini",
    "vscode.ipynb",
    "vscode.jake",
    "vscode.java",
    "vscode.julia",
    "vscode.less",
    "vscode.log",
    "vscode.lua",
    "vscode.make",
    "vscode.markdown-language-features",
    "vscode.markdown-math",
    "vscode.microsoft-authentication",
    "vscode.npm",
    "vscode.objective-c",
    "vscode.perl",
    "vscode.php",
    "vscode.php-language-features",
    "vscode.powershell",
    "vscode.pug",
    "vscode.r",
    "vscode.razor",
    "vscode.ruby",
    "vscode.rust",
    "vscode.scss",
    "vscode.shaderlab",
    "vscode.shellscript",
    "vscode.simple-browser",
    "vscode.sql",
    "vscode.swift",
    "vscode.theme-abyss",
    "vscode.theme-defaults",
    "vscode.theme-kimbie-dark",
    "vscode.theme-monokai",
    "vscode.theme-monokai-dimmed",
    "vscode.theme-quietlight",
    "vscode.theme-red",
    "vscode.vscode-theme-seti",
    "vscode.theme-solarized-dark",
    "vscode.theme-solarized-light",
    "vscode.theme-tomorrow-night-blue",
    "vscode.vb",
    "vscode.xml",
    "vscode.yaml",
    "ms-vscode.node-debug",
    "ms-vscode.node-debug2",
    "ms-vscode.references-view",
    "ms-vscode.js-debug-companion",
    "ms-vscode.js-debug"
  ],
```

**Comment by msujew** [comment] 2022-10-12 15:32
@smelliot @vince-fugnitto I can reproduce the issue on `master` on Windows as well. It probably doesn't affect other OS's. It's very weird, as resizing the application rerenders everything correctly. It seems to be a Chromium issue rather than something that we can fix on Theia's side.

**Comment by EvilBeaver** [comment] 2022-11-03 16:37
> It seems to be a Chromium issue rather than something that we can fix on Theia's side.

Have you reported an issue to Chromium team? It seems that most of clients will be frustrated by Theia, not Chromium

**Comment by msujew** [comment] 2022-11-03 16:44
@EvilBeaver We haven't but it seems like someone else has. See [this bug on the Chromium tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1373748). It appears to be a more general problem related to drag&drop in html elements which use `position: absolute`.

**Comment by vince-fugnitto** [comment] 2023-01-20 18:57
I believe this might be fixed with the latest Chrome. Verified with `109.0.5414.74`.

**Closed** 2023-03-06 16:50 UTC
Labels: browser/chrome
