### ISSUE TITLE
Tests files should not be compiled with the theia code

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#536] opened 2017-09-21 12:41 UTC
I think test files should be compiled only before the tests runs.

This would also allow tests that may depend on previously compiled code in the same package. Like the globalize PR needs to do.

Objections?

**Comment by svenefftinge** [comment] 2017-09-21 13:24
I don't understand this request.
Do you want to recompile the code base before every test? Or what are test files?

**Comment by hexa00** [comment] 2017-09-21 13:26
I mean we should not compile *.spec.ts when we compile theia with yarn.build
And rather compile *spec.ts* as we do yarn test

**Comment by svenefftinge** [comment] 2017-09-21 15:21
Ok, why?

**Comment by hexa00** [comment] 2017-09-21 15:33
In the case of the globalize PR you have like:

test.spec.ts 
   require(localize.ts);

generator.ts
   fs.write(localize.ts)

And this package would be built with:
generate-localize.ts && build

So since the test requires localize.ts and that this is a generated file by the package it fails to compile. 

We would need to compile the package, run the generator, then compile the test.

**Comment by hexa00** [comment] 2017-09-21 15:34
I think also it will save time when we package theia, we don't need to build the tests then..

**Comment by svenefftinge** [comment] 2017-09-22 11:15
why do we need to compile it first? I think it should be "generate, compile, test".

**Comment by hexa00** [comment] 2017-09-22 12:23
Well the generator needs to be compiled...

**Comment by svenefftinge** [comment] 2017-09-22 12:30
Ah, ok I didn't realize it is part of the runtime code. The generator should be in a separate package, actually being moved to `dev-packages` after https://github.com/theia-ide/theia/pull/527 was merged. We should also have a CLI command for it.

**Comment by hexa00** [comment] 2017-09-22 12:35
The problem in this case is that an extension dev may require that generator so it needs to be part of a proper package I think ? So it can be published etc ?

**Comment by svenefftinge** [comment] 2017-09-22 12:37
Yes, that is the case with all our dev dependencies. And the cli exposes the tools to extension developers.

**Comment by hexa00** [comment] 2017-09-22 12:40
OK So the dev-deps will be published ?

**Comment by svenefftinge** [comment] 2017-09-22 12:49
Yes. Extension developers (and Theia packaging jobs) will pull the tools from npm.js.

**Comment by hexa00** [comment] 2017-09-22 12:49
OK great then! :) We'll move it there

**Comment by vince-fugnitto** [comment] 2019-10-29 23:56
I believe the issue can be successfully closed, most dev packages are published (except for `ext-scripts). Please feel free to re-open the issue if the issue is still relevant.

**Closed by vince-fugnitto** 2019-10-29 23:56 UTC
