### ISSUE TITLE
[java]Theia server stopped after dealing with a java project

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#2106] opened 2018-06-12 14:45 UTC
With a very small java project, I made the Theia server crashed a few times. I haven't foungd an exact pattern, but usually, it occurs after I restart the server. A popup "JAVA LSP  got disposed..." and a few seconds after, the server crashes.

Here the little java project I used. I created an error in the "bye.java". I sometimes open the problem view to see the error reported . I sometimes have the editor in a dirty state before I restart the server

[helloBye.tar.zip](https://github.com/theia-ide/theia/files/2094481/helloBye.tar.zip)
To untar the file in a workspace: tar -xvf helloBye.tar.zip

 **The error on the server:**

[2018-06-12T12:56:07.728Z]  INFO: Theia/7294 on elxa36mbq32: (logger=root)
    [nsfw-watcher: 7421] Started watching: /home/lmcbout/.theia
    Started watching: /home/lmcbout/eclipse/eclipse_oxygen_rc4a/workspace2/HelloAndBye
     []

assert.js:42
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: false == true
    at RoundRobinHandle.add (internal/cluster/round_robin_handle.js:34:3)
    at queryServer (internal/cluster/master.js:300:10)
    at Worker.onmessage (internal/cluster/master.js:244:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Done in 12.60s.

**Comment by vince-fugnitto** [comment] 2020-02-28 13:30
> I haven't found an exact pattern (to reproduce the problem)

Closing the issue for the following reasons:
- the issue is quite outdated
- no procedure is available (based on the quote) to successfully reproduce the problem consistently
- the `@theia/java` extension has been replaced by `builtins` so this issue may no longer apply

**Closed by vince-fugnitto** 2020-02-28 13:30 UTC
Labels: java
