### ISSUE TITLE
'Jira and BitBucket' VS code Extension not working with Theia 

### ISSUE THREAD

**Issue by vishwanathcp** [eclipse-theia/theia#12371] opened 2023-04-03 13:24 UTC
### Bug Description:
Unable to load the VS Code Extension 'Jira and BitBucket'. Post installation of extension ](https://open-vsx.org/extension/atlassian/atlascode), when clicked on the 'Please login to Jira', the tab 'Atlassian Settings' opens, for 1-2 ms we can see the page launched and immediately the blank page displays
Error is Observed in the console (Attached)
Extension version v3.0.2. tried with older version, still same issue

### Steps to Reproduce:

1. Download install Theia Blueprint v 1.35.0
2. Launch the Theia Blueprint
3. Go to Extension and Install 'Jira and BitBucket' extension Link (https://open-vsx.org/extension/atlassian/atlascode version 3.0.2 (latest version as on 3rd April 2023)
4. Extension is successfully installed
5. On the left page we can see the Atlassian icon, Click to open it
6. Atlassian section opened
7. Click on 'Please login to Jira'

Expected: 'Atlassian Setting' page is opened with option to select Jira Login

Actual:  Atlassian Settings' page opens, for 1-2 ms and immediately the blank page displays

- Operating System: Windows 
- Theia Version: Theia Blueprint 1.35.0 (beta), VS Code API version 1.70.2

Additional info video recording, 

https://user-images.githubusercontent.com/41190439/229522631-ecb26197-88b2-4689-a171-5ae3a8d31bb6.mp4

screen shot and log 
[ConsoleLog.txt](https://github.com/eclipse-theia/theia/files/11138616/ConsoleLog.txt)
<img width="972" alt="JiraExtension" src="https://user-images.githubusercontent.com/41190439/229520759-048dc7ed-91a8-416b-9cb8-0a0449a62877.PNG">
attached

**Comment by msujew** [comment] 2024-06-04 22:16
This was very likely fixed by https://github.com/eclipse-theia/theia/pull/13527. Cannot reproduce any longer.

**Closed by msujew** 2024-06-04 22:16 UTC
