### ISSUE TITLE
All spaces are non-breaking

### ISSUE THREAD

**Issue by chadoh** [eclipse-theia/theia#7293] opened 2020-03-06 21:49 UTC
### Description
I noticed that when I copy & pasted a note from GitPod's editor into Slack, the line breaks got all wonky. Looking into it, I noticed that Theia uses `&nbsp;` for all spaces! I have confirmed this in both `.md` and `.js` files. Here you can see a side-by-side of the Theia editor and the browser's inspector, showing the markup:

<img width="897" alt="Screen Shot 2020-03-06 at 16 42 04" src="https://user-images.githubusercontent.com/221614/76124804-80ab5a00-5fc9-11ea-98fe-a02d457f26a1.png">

### Why this is a problem

1. It leads to a clumsy experience when trying to copy code from Theia to many other websites or web-based UIs (such as Slack)
2. It was never necessary! There's [a simple CSS rule for this](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space). I would guess that removing whatever logic puts in these non-breaking spaces will help simplify the Theia codebase 💪🏼

### Reproduction Steps
In a file that has any space characters, inspect the page source. Observe that the spaces use `&nbsp;`, rather than a normal space character.

**OS and Theia version:**
macOS 10.5.3
Brave 1.4.96
Not sure how to tell the version of Theia – the kind currently in-use on gitpod.io

**Comment by vince-fugnitto** [comment] 2020-03-06 23:59
@chadoh thank you for the issue!

We use the [monaco-editor](https://microsoft.github.io/monaco-editor/index.html) and verifying on their [playground](https://microsoft.github.io/monaco-editor/playground.html) I see they use `&nbsp;` for spaces so it is not something we are doing specifically but it can definitely be something we improve when attempting to copy. 

_Monaco Playground_:
<div align='center'>

<img width="893" alt="Screen Shot 2020-03-06 at 6 54 28 PM" src="https://user-images.githubusercontent.com/40359487/76131430-675fd900-5fdc-11ea-9361-fa2185d51113.png">


</div>
<br/>

It might also be related to the following issue we have already registered: https://github.com/eclipse-theia/theia/issues/3203

**Comment by akosyakov** [comment] 2020-03-07 05:33
It should be fixed either in Monaco (try latest PR) or Slack (they don’t seem to read clipboard content properly). I don’t think we put anything for clipboard management on top.

**Comment by msujew** [comment] 2021-07-13 08:25
@vince-fugnitto This seems to be fixed by some Monaco update. The playground looks like this:

![image](https://user-images.githubusercontent.com/4377073/125418012-c33143a2-5b20-46c8-ac43-cd9cf1949da1.png)

I confirmed that this is fixed in Theia as well.

**Comment by vince-fugnitto** [comment] 2021-07-13 12:22
> @vince-fugnitto This seems to be fixed by some Monaco update. The playground looks like this:
> I confirmed that this is fixed in Theia as well.

@msujew thank you for confirming, I believe you were using firefox? 
On chrome, electron and vscode `&nbsp;` are present, but I confirmed it does not cause any issues when copy + pasting.

**Closed by vince-fugnitto** 2021-07-13 12:22 UTC
Labels: clipboard, monaco
