### ISSUE TITLE
NPM SCRIPTS view contribution always visible after app start

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7475] opened 2020-04-01 11:20 UTC
### Description
 

If I hide it and refresh the window, it always comes back. I used the electron example.

![screencast 2020-04-01 13-17-45](https://user-images.githubusercontent.com/1405703/78131524-81de7400-741b-11ea-82a4-28502d456b0d.gif)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment] 2020-04-01 12:05
Duplicate of https://github.com/eclipse-theia/theia/issues/7037?

**Closed** 2020-04-01 12:33 UTC
Labels: bug
