### ISSUE TITLE
Cannot input with Chrome Extension Google Input Tool

### ISSUE THREAD

**Issue by mouse484** [eclipse-theia/theia#6702] opened 2019-12-06 06:18 UTC
### Description
Cannot input with [Chrome Extension Google Input Tool](https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab).
Alphabet can be entered.
Japanese and Chinese etc are impossible

Found by discussion #6673 

### Reproduction Steps

Install extension and enter in Japanese or Chinese

**OS and Theia version:**

**Diagnostics:**

**Comment by monaka** [comment] 2019-12-06 06:45
I started to check this issue. Even though I have no source code for this extension, it looks the extension handle composition related events correctly. So the issue will be in inserting texts.

![Screenshot 2019-12-06 at 14 23 09](https://user-images.githubusercontent.com/101795/70301980-3afeba00-183f-11ea-82aa-867af2e51861.png)

**Comment by monaka** [comment] 2019-12-06 06:53
And I found exceptions in the console of developer tools when I typed in the editor.
I suspect the root cause is there.
@mouse484 Are these exceptions reproduced on your environment? 

<details>
<summary>logs</summary>
keys.ts:369 Uncaught Error: Cannot get key code from the keyboard event: [object Event].
    at Function.toKey (keys.ts:369)
    at Function.../../packages/core/lib/browser/keyboard/keys.js.KeyCode.createKeyCode (keys.ts:191)
    at KeybindingRegistry.../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.run (keybinding.ts:614)
    at HTMLDocument.<anonymous> (frontend-application.ts:193)
toKey @ keys.ts:369
../../packages/core/lib/browser/keyboard/keys.js.KeyCode.createKeyCode @ keys.ts:191
../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.run @ keybinding.ts:614
(anonymous) @ frontend-application.ts:193
keys.ts:369 Uncaught Error: Cannot get key code from the keyboard event: [object Event].
    at Function.toKey (keys.ts:369)
    at Function.../../packages/core/lib/browser/keyboard/keys.js.KeyCode.createKeyCode (keys.ts:191)
    at HTMLBodyElement.<anonymous> (widget.ts:219)
toKey @ keys.ts:369
../../packages/core/lib/browser/keyboard/keys.js.KeyCode.createKeyCode @ keys.ts:191
(anonymous) @ widget.ts:219
keys.ts:369 Uncaught Error: Cannot get key code from the keyboard event: [object Event].
    at Function.toKey (keys.ts:369)
    at Function.../../packages/core/lib/browser/keyboard/keys.js.KeyCode.createKeyCode (keys.ts:191)
    at HTMLBodyElement.<anonymous> (widget.ts:219)
toKey @ keys.ts:369
../../packages/core/lib/browser/keyboard/keys.js.KeyCode.createKeyCode @ keys.ts:191
(anonymous) @ widget.ts:219
textAreaState.ts:96 Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.TextAreaState.selectedText (textAreaState.ts:96)
    at deduceComposition (textAreaInput.ts:178)
    at HTMLTextAreaElement.<anonymous> (textAreaInput.ts:217)
TextAreaState.selectedText @ textAreaState.ts:96
deduceComposition @ textAreaInput.ts:178
(anonymous) @ textAreaInput.ts:217
textAreaState.ts:96 Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.TextAreaState.selectedText (textAreaState.ts:96)
    at deduceComposition (textAreaInput.ts:178)
    at HTMLTextAreaElement.<anonymous> (textAreaInput.ts:232)
TextAreaState.selectedText @ textAreaState.ts:96
deduceComposition @ textAreaInput.ts:178
(anonymous) @ textAreaInput.ts:232
setTimeout (async)
Gp @ chext_driver.js:100
Ms @ chext_driver.js:141
x.Gb @ chext_driver.js:362
x.Lh @ chext_driver.js:446
Eo @ chext_driver.js:87
x.K @ chext_driver.js:303
x.vi @ chext_driver.js:417
Eo @ chext_driver.js:87
x.K @ chext_driver.js:303
Fw.B @ chext_driver.js:429
vw.push @ chext_driver.js:421
Tu @ chext_driver.js:165
x.Ga @ chext_driver.js:423
x.Dc @ chext_driver.js:413
x.handleEvent @ chext_driver.js:441
x.Ae @ chext_driver.js:447
x.handleEvent @ chext_driver.js:376
(anonymous) @ chext_driver.js:376
I @ chext_driver.js:241
x.handleEvent @ chext_driver.js:376
x.Nh @ chext_driver.js:482
Eo @ chext_driver.js:87
x.K @ chext_driver.js:303
x.qc @ chext_driver.js:362
(anonymous) @ chext_driver.js:361
Gt @ chext_driver.js:243
et.D @ chext_driver.js:361
Ao @ chext_driver.js:85
vo @ chext_driver.js:86
b @ chext_driver.js:83
</details>

**Comment by mouse484** [comment] 2019-12-06 07:00
Yes, I have the same error
<details>
```
keys.ts:369 Uncaught Error: Cannot get key code from the keyboard event: [object Event].
    at Function.e.toKey (keys.ts:369)
    at Function.e.createKeyCode (keys.ts:191)
    at e.run (keybinding.ts:614)
    at HTMLDocument.<anonymous> (frontend-application.ts:170)
e.toKey @ keys.ts:369
e.createKeyCode @ keys.ts:191
e.run @ keybinding.ts:614
(anonymous) @ frontend-application.ts:170
2keys.ts:369 Uncaught Error: Cannot get key code from the keyboard event: [object Event].
    at Function.e.toKey (keys.ts:369)
    at Function.e.createKeyCode (keys.ts:191)
    at HTMLBodyElement.<anonymous> (widget.ts:219)
e.toKey @ keys.ts:369
e.createKeyCode @ keys.ts:191
(anonymous) @ widget.ts:219
editor.main.js:411 Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.e.selectedText (editor.main.js:411)
    at h (editor.main.js:423)
    at HTMLTextAreaElement.<anonymous> (editor.main.js:423)
e.selectedText @ editor.main.js:411
h @ editor.main.js:423
(anonymous) @ editor.main.js:423
```
</details>

**Comment by mouse484** [comment] 2019-12-06 07:04
It may be a bad way. Chrome extension source code can be easily browsed.

Just look for the extension folder in the directory where you installed Chrome

**Comment by akosyakov** [comment] 2019-12-06 07:32
@mouse484 @monaka and it works fine with with the monaco playground?

**Comment by mouse484** [comment] 2019-12-06 07:51
don't work even on monaco play ground.

It's a monaco issue unlike other Theia IME issues

![image](https://user-images.githubusercontent.com/38714187/70305779-941f1b80-1848-11ea-8171-e78f91892808.png)

**Comment by akosyakov** [comment] 2019-12-06 08:06
@mouse484 Please take it to the VS Code repo with a reproducible steps in the monaco playground.

**Comment by vince-fugnitto** [comment] 2021-11-09 20:03
Closing as it seems to be a monaco related issue.
The follow-up steps are listed in https://github.com/eclipse-theia/theia/issues/6702#issuecomment-562474304.

**Closed by vince-fugnitto** 2021-11-09 20:03 UTC
Labels: bug, monaco
