### ISSUE TITLE
Suggestions window closes when you move cursor with a keyboard

### ISSUE THREAD

**Issue by xcariba** [eclipse-theia/theia#9576] opened 2021-06-10 10:55 UTC
### Bug Description:
When I move cursor with a keyboard (using right/left arrow keys) suggestions window closes in Theia, but stays open in VSCode. I expect that suggestions window to stay opened in both cases.

### Steps to Reproduce:

1. Open Theia 1.14 (browser version)
2. Create txt file
3. Write Text1 Text2 Text3
4. On next line write Text
5. Put your cursor on second line after letter T
6. Suggestions window will show up
7. Press right arrow key on keyboard
8. Suggestions window will close

Same steps in VSCode, suggestions window will still be open.

### Additional Information

![image](https://user-images.githubusercontent.com/7170514/121512769-bde37080-c9f2-11eb-9843-ab4fb85e95e8.png)

- Operating System: Fedora 33, chrome 91
- Theia Version: 1.14.0

**Comment by vince-fugnitto** [comment] 2021-06-10 12:40
By default it looks like the `monaco-editor` handles it correctly (keeps it opened) when testing with the [monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world). Unless it is a recent change, it is likely that the framework mishandles it and closes the suggestions prematurely.

One area you may want to debug through is the following if you're interested in providing a fix:

https://github.com/eclipse-theia/theia/blob/64e613fd31bb1adeb8e8078bc9b8725a21f2182b/packages/monaco/src/browser/monaco-snippet-suggest-provider.ts#L39-L40

**Comment by msujew** [comment] 2021-07-09 12:50
@vince-fugnitto This issue seems to be fixed by the monaco update. I can't reproduce it on `master` anymore.

**Comment by vince-fugnitto** [comment] 2021-07-09 12:54
> @vince-fugnitto This issue seems to be fixed by the monaco update. I can't reproduce it on `master` anymore.

I'll try as well and close if I can't reproduce either :+1:

**Comment by vince-fugnitto** [comment] 2021-07-09 12:56
Confirms it works now with the latest monaco upgrade :+1:

**Closed by vince-fugnitto** 2021-07-09 12:56 UTC
Labels: help wanted, monaco
