### ISSUE TITLE
Vscode engine version not considered in download plugins

### ISSUE THREAD

**Issue by Tpuljak** [eclipse-theia/theia#12198] opened 2023-02-18 18:18 UTC
https://github.com/eclipse-theia/theia/blob/79ce67d25542865c635b1b43a682a90c0beba7b5/dev-packages/ovsx-client/src/ovsx-client.ts#L139

As you can see above, when checking for the extension api version, the `extension.version` is considered instead of `extension.engines.vscode` which I believe to be the intended behavior of the function, correct?

**Comment by msujew** [comment] 2023-02-18 20:23
This branch is only relevant when we're downloading a vscode built-in extension. These extensions are always versioned together with vscode (i.e. `vscode@1.72` will come with `vscode.git@1.72`). When looking [at the commit](https://github.com/eclipse-theia/theia/commit/dab288cdb78d122bc5ade9ac05612d2eacc20cde) that added this code, there's even an awesome commit message explaining why we explicitly use `extension.version`:

```
Since the `engines.vscode` property is generally not maintained by
vscode builtin extensions (since they are bundled with vscode at a
specific version) we cannot rely on the `engines.vscode` version to
fetch a compatible extension. Instead, we now fetch a version which
corresponds to the api level the framework defines.
```

With that being said, this is intended behavior, so I'll close this issue.

**Closed by msujew** 2023-02-18 20:23 UTC
