### ISSUE TITLE
Opening multiple files at once breaks the opened editors

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#6298] opened 2019-10-01 06:10 UTC
### Description
opening multiple files at once breaks the editor activation.

### Reproduction Steps
 - Select multiple files in the navigator
 - right click 'open'
 - now active he last editor and try editing. Also [ESC] will no longer close the completion pop up.

**OS and Theia version:**
current master

**Comment by lmcbout** [comment] 2019-10-16 18:41
After some research, this bug looks similar to previous one when dealing with the preference editor. It looks like the active editor is not the one being displayed, the data typed  goes to a different editor.
Similar issue: issue #3184 and issue #4465

**Comment by kittaakos** [comment] 2020-03-10 12:17
Steps to reproduce: https://github.com/eclipse-theia/theia/issues/7133#issuecomment-588092099

**Comment by akosyakov** [comment] 2020-05-27 10:01
@lmcbout Could you check whether it is still the case?

**Comment by lmcbout** [comment] 2020-05-27 13:30
@akosyakov I tried to reproduce the wrong editor focus with electron, Chrome and Firefox, could not reproduce, so It seems to be fixed

**Comment by kittaakos** [comment] 2020-05-27 13:49
> @akosyakov I tried to reproduce the wrong editor focus with electron, Chrome and Firefox, could not reproduce, so It seems to be fixed

I can confirm. I have noticed, opening multiple files in editor is slower a bit UX-wise, but this is OK. Opening was parallel previously, now we do not open the next editor unless the current is up, and the focus is set. How to try: select 20-30 files in the Explorer and DND into the main area; it works now.

**Comment by akosyakov** [comment] 2020-05-27 14:57
> Opening was parallel previously, now we do not open the next editor unless the current is up, and the focus is set.

Do you know where we have such logic?

**Comment by kittaakos** [comment] 2020-05-27 15:02
> Do you know where we have such logic?

It just feels slower. 👇 

> is slower a bit UX-wise,

**Comment by lmcbout** [comment] 2020-05-27 15:11
Tested with UBUNTU with an older version of Theia. Opening multiple files a the same time seems to be similar timewise at what was there before

**Comment by kittaakos** [comment] 2020-05-27 15:25
Thanks for taking care of it and comparing the performances 👍 I am fine closing it, for sure, the error does not occur anymore when I open multiple files.

**Closed** 2020-05-27 17:30 UTC
Labels: bug, help wanted, monaco
