### ISSUE TITLE
[VScode extension] Make language packs available

### ISSUE THREAD

**Issue by mouse484** [eclipse-theia/theia#6022] opened 2019-08-23 00:19 UTC
### Description
Multilingualization is currently not available in Theia (Gitpod)
I tried to use the language pack (Japanese) provided as an extension of VScode, but it was not available 
I think it is important to be able to use language packs

### Reproduction Steps
Installation of extension language pack (Japanese)

**OS and Theia version:**

**Diagnostics:**

**Comment by Lzw2016** [comment] 2020-04-03 01:57
I think it is important to be able to use language packs (Chinese (Simplified) )

**Comment by vince-fugnitto** [comment] 2020-05-14 15:04
Thank you for the issue, at the moment localization is still not yet supported.
Closing as it is a duplicate of https://github.com/eclipse-theia/theia/issues/5000.

**Closed by vince-fugnitto** 2020-05-14 15:04 UTC
Labels: enhancement, vscode
