### ISSUE TITLE
references-view: reference is not highlighted in the tree

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7335] opened 2020-03-13 14:55 UTC
**Description**

Triggering the `References View` (selecting a term and executing <kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>F12</kbd>) does not successfully highlight the results in the tree. As a user I'd expect to see the referenced term being highlighted (ex: `ExtensionInfo`):

_Theia:_

<img width="509" alt="Screen Shot 2020-03-13 at 10 52 11 AM" src="https://user-images.githubusercontent.com/40359487/76632053-f6a74800-6518-11ea-9d96-ed314aa412e3.png">

_VS Code:_

<img width="493" alt="Screen Shot 2020-03-13 at 10 52 01 AM" src="https://user-images.githubusercontent.com/40359487/76632081-01fa7380-6519-11ea-9877-4f649bc6d131.png">

**Comment by akosyakov** [comment] 2020-03-13 14:58
A duplicate of https://github.com/eclipse-theia/theia/issues/7335

**Comment by vince-fugnitto** [comment] 2020-03-13 14:58
In addition, clicking a reference in the view does not successfully highlight the editor (something that works correctly in VS Code).

**Comment by vince-fugnitto** [comment] 2020-03-13 14:59
> A duplicate of #7335

Sorry @akosyakov, but you referenced the same issue.

**Closed by akosyakov** 2020-03-13 14:58 UTC
Labels: vscode

**Comment by akosyakov** [comment] 2020-03-13 19:09
> In addition, clicking a reference in the view does not successfully highlight the editor (something that works correctly in VS Code).

It is worth a separate bug

**Comment by vrubezhny** [comment] 2020-03-13 19:14
> > In addition, clicking a reference in the view does not successfully highlight the editor (something that works correctly in VS Code).
> 
> It is worth a separate bug

It looks like when clicking a reference the editor doesn't receives the focus. 
If after clicking a reference on the tree make a click on editor area according highlighting appears immediately. So, imho, it's a editor activation/focusing problem
