### ISSUE TITLE
Theia Build fails due to non-existing node-debug Built-in Version

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#7529] opened 2020-04-08 12:47 UTC
To reproduce:

1. Remove everything from the `plugins` folder inside the theia source
2. run `yarn` in the root folder
3. Observe: the build fails when downloading built-in extensions:

```
Uncaught Exception:  Error: Not a valid zip file
Error: Not a valid zip file
    at UnzipStream.processDataChunk (C:\Users\thomas\code\chedev\theia\node_modules\unzip-stream\lib\unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (C:\Users\thomas\code\chedev\theia\node_modules\unzip-stream\lib\unzip-stream.js:651:28)
    at UnzipStream._transform (C:\Users\thomas\code\chedev\theia\node_modules\unzip-stream\lib\unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at UnzipStream.Writable.write (_stream_writable.js:299:11)
    at Extract._transform (C:\Users\thomas\code\chedev\theia\node_modules\unzip-stream\lib\extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10)
+ vscode-builtin-node-debug: downloaded successfully
```

It turns out the last line of the log is a lie ;-). In fact, our root package.json contains a reference to 

`http://open-vsx.org/api/ms-vscode/node-debug/1.44.2/file/ms-vscode.node-debug-1.44.2.vsix`

This url does not exist and open-vsx.org correctly reports a 404 error.

@Anasshahidd21  since you introduced that reference in https://github.com/eclipse-theia/theia/pull/7437, could you comment on what the right fix is here? Fix the reference in package.json or put the version up on open-vsx.org?

**Comment by vince-fugnitto** [comment] 2020-04-08 12:54
@tsmaeder the build does not fail, just that the script complains that the entry does not exist (better error reporting is definitely needed). The issue is a duplicate of https://github.com/eclipse-theia/theia/issues/7488 which is already tracking the fix and has previous discussions.

**Comment by kittaakos** [comment] 2020-04-08 13:23
> @tsmaeder the build does not fail

Correct.

> The issue is a duplicate of #7488 which is already tracking the fix and has previous discussions.

#7501, isn't it?

Closing as a duplicate of #7501. Please reopen if required.

**Closed by kittaakos** 2020-04-08 13:23 UTC
Labels: bug, builtins
