### ISSUE TITLE
vscode-database extension not working

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6372] opened 2019-10-11 18:07 UTC
### Description
 I have deployed the [vscode-database](https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-database) extension using command palette
which deployed successfully but when I try to create a new database connection then it doesn't work.
When I select to create new connection then the page opens but shows only "connect" button. 
However it should suppose to show the full form to fill the server details(as same as desktop version).
on pressing that button it gives connection error.
Checked on console log and editor application logs but no message.
<sceenshot1> doesnt show any form inputs to fill the server details:
![image](https://user-images.githubusercontent.com/902289/66674669-1512ca00-ec81-11e9-84b6-ae34ce42c4d9.png)

### Reproduction Steps

**OS and Theia version:**
Alpine-Docker having node 10.15
**Diagnostics:**

**Comment by akosyakov** [comment] 2019-10-13 03:38
@dhananjayharel any exceptions in dev tools console and backend logs?

**Comment by dhananjayharel** [comment] 2019-10-14 06:55
there is no any error in console and the backend logs .

**Comment by akosyakov** [comment] 2019-12-02 04:46
@dhananjayharel Could you try again please? support of webviews were landed, maybe the issue is resolved with it

**Comment by akosyakov** [comment] 2019-12-02 05:49
It would be helpful if someone double check whether it is still the case and if yes investigate why it is happening.

**Comment by akosyakov** [comment] 2020-01-23 02:43
please reopen if it is still an issue

**Closed by akosyakov** 2020-01-23 02:43 UTC
Labels: :thinking: needs more info, bug, help wanted, vscode
