### ISSUE TITLE
Getting musl binaries version of an extension on glibc platform

### ISSUE THREAD

**Issue by hsnoil** [eclipse-theia/theia#13824] opened 2024-06-18 22:12 UTC
### Bug Description:

I loaded up the `rust-analyzer` plugin and found that it wasn't working on the appimage. I tried to run the binary it shows manually and it said "file or directory not found", doing a `file rust-analyzer` it reported that the interpreter was `ld-musl`. I checked with my vscodium version and it is `ld-linux`. Copying the binary from vscodium and it worked

### Steps to Reproduce:

1. Get the Theia appimage from eclipse website and run it
2. Install rust-analyzer plugin
3. It will not work, the output tab will display an error

### Additional Information

By getting the file inside the outputs tab it points to rust-analyzer --version. Using `file` to check it points to musl interpreter. Swapping it manually with the one from vscodium binary makes it work

- Operating System: Linux
- Theia Version: 1.50.1

**Comment by msujew** [comment] 2024-06-18 22:52
Hey @hsnoil,

this is a duplicate of https://github.com/eclipse-theia/theia/issues/13558, Theia currently does not respect the platform version property when downloading an extension.

**Closed by msujew** 2024-06-18 22:52 UTC
