### ISSUE TITLE
File search cannot get history by up or down key

### ISSUE THREAD

**Issue by gaomin** [eclipse-theia/theia#11177] opened 2022-05-19 07:47 UTC
### Bug Description:
File search cannot get search history by up or down key. 

![截屏2022-05-19 下午3 44 40](https://user-images.githubusercontent.com/5135098/169240335-f10757f3-4d9b-49d6-a824-fbea7955410e.png)

### Steps to Reproduce:

1.  open a file
2.  search in file
3.  press the up key on the keyboard
4.  check history in search input

### Additional Information

- Operating System: macOS 12.0.1
- Theia Version:   1.25.0 (Beta)
- VS Code API Version: 1.53.2

**Comment by vince-fugnitto** [comment] 2022-05-19 12:07
@gaomin thank you for the issue, it works well for me when I navigate previous history using the up and down arrow keys.

https://user-images.githubusercontent.com/40359487/169289337-9086bfd6-84f8-4386-9a63-28cb2534e970.mp4


Does the feature not work for you at all, or is it because you restarted the application? If its the latter I don't think we store the history anywhere to restore it on subsequent starts (it would be a new feature request I presume).

**Comment by vince-fugnitto** [comment] 2022-05-19 15:00
It looks like vscode also does not store the editor `find` history across restarts.

**Comment by gaomin** [comment] 2022-05-20 02:50
> It looks like vscode also does not store the editor `find` history across restarts.



> 

This feature is not work at all， not restarted application

**Comment by gaomin** [comment] 2022-05-20 03:08
https://user-images.githubusercontent.com/5135098/169442644-6c389c85-0675-4658-9cfb-df78aaed9606.mov

**Comment by gaomin** [comment] 2022-05-20 03:18
https://user-images.githubusercontent.com/5135098/169443672-844c0e4c-9f5c-43e2-a2ac-4134cb65812d.mp4

**Comment by vince-fugnitto** [comment] 2022-05-20 11:57
@gaomin it works well on `master` but I confirmed that `blueprint` where you tested does not, it might be fixed this month when blueprint is updated to the latest version of the framework.

**Comment by gaomin** [comment] 2022-05-24 01:31
ok, thanks

**Comment by vince-fugnitto** [comment] 2022-06-10 15:05
It should be fixed in the latest release of blueprint :+1:

**Closed by vince-fugnitto** 2022-06-10 15:05 UTC
Labels: :thinking: needs more info, blueprint
