### ISSUE TITLE
a breakpoint becomes inline after line copying

### ISSUE THREAD

**Issue by tom-shan** [eclipse-theia/theia#7114] opened 2020-02-10 08:17 UTC
### Description

![inline-breakpoint](https://user-images.githubusercontent.com/7686800/74131939-77280f80-4c20-11ea-8a5f-eec7ae76530a.gif)

### Reproduction Steps

**OS and Theia version:**
OS: centos 7
Theia: d5f32625017a6ea38bc2a6bcdd0060ec8a92ab9c

**Diagnostics:**

**Comment by akosyakov** [comment] 2020-02-10 08:28
@tom-shan Do you have active debug session?

**Comment by tom-shan** [comment] 2020-02-10 08:32
> @tom-shan Do you have active debug session?

no active debug session

**Comment by justinang1** [comment] 2020-02-18 08:12
Would like to look into this issue, but I'm unsure of which files to look into to get started. I'm thinking that this issue is probably caused by the editor window and the handler for the copy command, any pointers on which files these components would be under? 

I also believe this issue might be related to #6910.

**Comment by akosyakov** [comment] 2020-02-18 11:16
Breakpoints are updated here: https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/editor/debug-editor-model.ts#L227

**Comment by tom-shan** [comment] 2020-02-24 16:13
> Breakpoints are updated here: https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/editor/debug-editor-model.ts#L227

if column number is 1, will it be an inline breakpoint?

**Comment by akosyakov** [comment] 2020-02-24 16:46
@tom-shan Could you send a PR please? let's try your approach

**Comment by akosyakov** [comment] 2020-02-24 16:46
Maybe https://github.com/eclipse-theia/theia/issues/6910 is another issue which will be get fixed by such PR.

**Comment by justinang1** [comment] 2020-02-24 17:05
I was testing the same approach as @tom-shan. Breakpoints are initialized with column undefined but when copied, the column becomes 1. I was going to do more testing and create a PR by the end of today.

**Closed** 2020-02-27 08:04 UTC
Labels: bug, debug, help wanted
