### ISSUE TITLE
Assorted Biscuits extension doesn't work properly

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8902] opened 2020-12-24 14:12 UTC
### Bug Description:
Appears only after modifying the file, disappears when switching to another file.
Works in vscode.

### Steps to Reproduce:

1. Install Assorted Biscuits extensions (codebiscuits.assorted-biscuits) from Open VSX Registry.
2. Open a *.json file with data
3. Modify the file to see text by the end brackets 
4. Switch to another file
5. Go back to the .json file and see text disappeared

https://user-images.githubusercontent.com/49866055/103093347-ba099080-4602-11eb-8d44-0c2940b3163a.mp4

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by danarad05** [comment] 2021-01-04 16:21
IMO, as far as I can tell, there is no fault in Theia itself as the flickering "assorted-biscuits" extension is setting text editor decorations twice - first time with populated decorations and second time  with empty decorations array. therefore they are first displayed and then removed.

From extension source code - second invocation is from onDidChangeTextDocument:
![image](https://user-images.githubusercontent.com/71069170/103555449-fbc6f080-4eb8-11eb-9de3-782e01231613.png)


These is comparison of logs between first (left) and second (right) invocations from extension:|

![image](https://user-images.githubusercontent.com/71069170/103555244-a094fe00-4eb8-11eb-872f-5db16ac0c7cc.png)

 For test purposes, I did a little change in code to check if decorations are not empty and result is as wanted
 
![image](https://user-images.githubusercontent.com/71069170/103555858-932c4380-4eb9-11eb-85a0-bb4af44313ab.png)
![image](https://user-images.githubusercontent.com/71069170/103555919-ae974e80-4eb9-11eb-9cbd-df77c4de4955.png)

**Comment by danarad05** [comment] 2021-01-17 11:56
@rayakoren @amiramw 
Opened PR for this issue on assorted-biscuits repo: https://github.com/code-biscuits/assorted-biscuits/pull/6

**Comment by danarad05** [comment] 2021-02-10 09:01
@rayakoren code-biscuits/assorted-biscuits#6 was merged. could you re-download [assorted biscuits](https://open-vsx.org/extension/CodeBiscuits/assorted-biscuits)?

**Comment by amiramw** [comment] 2021-02-14 10:42
I confirm that the issue is resolved on assorted-biscuites 0.0.21

**Closed by amiramw** 2021-02-14 10:42 UTC
