### ISSUE TITLE
support octicon in the quick pick items

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5412] opened 2019-06-10 18:35 UTC
See https://github.com/theia-ide/theia/issues/4005#issuecomment-475247786

I cannot come up with a way to reuse Monaco quick palette for it. It could be we need to implement our own to have the control over it.

It's reproducible with checkout status bar item contributed by vscode git extension.

**Comment by kittaakos** [comment] 2019-06-10 18:47
New icons were added to Octicon in VS Code: https://code.visualstudio.com/updates/v1_35#_updated-octicons

**Comment by benoitf** [comment] 2019-11-26 14:53
FYI now it's called codicons https://github.com/microsoft/vscode-codicons :-)
https://github.com/microsoft/vscode/pull/82729

**Comment by RomanNikitenko** [comment] 2020-01-13 08:42
I investigated the issue and found that the [octiconLabel.mock](https://github.com/TypeFox/vscode/blob/b0650697162f9e0ad03e55c869b7faa89a9eaea7/src/vs/base/browser/ui/octiconLabel/octiconLabel.mock.ts#L8-L9) is used for rendering icons instead of the real [implementation](https://github.com/TypeFox/vscode/blob/b0650697162f9e0ad03e55c869b7faa89a9eaea7/src/vs/base/browser/ui/octiconLabel/octiconLabel.ts#L10-L18). 
If I understand correctly the cause of the problem is the [redirection](https://github.com/TypeFox/vscode/blob/b0650697162f9e0ad03e55c869b7faa89a9eaea7/build/gulpfile.editor.js#L93)
At the same time the last version of vs code doesn't have such [redirection](https://github.com/microsoft/vscode/blob/528202e34f9b98ba92d07a00d743847b9bed7b12/build/gulpfile.editor.js#L81)

@akosyakov maybe you know more about this problem, could you confirm or refute my assumptions about it.

I would like to know your opinion about the direction of resolving this problem. 
Is it possible to avoid the redirection and use the vs code implementation for rendering instead of the mock?
Or should we consider the providing the own implementation of rendering on theia side?

Thanks in advance!

**Comment by akosyakov** [comment] 2020-01-14 01:25
Maybe we just should upgrade to latest Monaco and it will come with octicons already? Could you check in the monaco playground?

**Comment by RomanNikitenko** [comment] 2020-01-14 09:01
I checked for 0.19.2 version of Monaco, `codicons` work well for command palette: https://youtu.be/Y1PRBSYKtLM

![codIcons_monaco](https://user-images.githubusercontent.com/5676062/72329346-3d192b80-36bd-11ea-8c0a-a704622e3981.gif)

**Comment by akosyakov** [comment] 2020-01-14 09:06
We have to migrate then. It is a bit involving, see https://github.com/eclipse-theia/theia/wiki/LSP-and-Monaco-integration#migration-guidelines and last migration PR:  https://github.com/eclipse-theia/theia/pull/5901.

The plan was to land https://github.com/eclipse-theia/theia/pull/6852, switch to VS Code extensions instead of Theia extensions (cc @vince-fugnitto @marcdumais-work ) and automate tests from https://github.com/eclipse-theia/theia/pull/5901

**Comment by azatsarynnyy** [comment] 2020-01-14 10:15
> ... see https://github.com/eclipse-theia/theia/wiki/LSP-and-Monaco-integration#migration-guidelines and last migration PR: #5901

@akosyakov PR: #5901 - am I understand it right that all amount of work in this PR is related to upgrading to a newer version of monaco?

> The plan was to land #6852, switch to VS Code extensions instead of Theia extensions for typescript/node (cc @vince-fugnitto @marcdumais-work ) and automate tests from #5901

@akosyakov do you mean that upgrading monaco work shouldn't be started before completing the mentioned plan?

**Comment by akosyakov** [comment] 2020-01-15 05:29
> @akosyakov PR: #5901 - am I understand it right that all amount of work in this PR is related to upgrading to a newer version of monaco?

It is more. First https://github.com/TypeFox/monaco-languageclient have to be migrated, after that we should update and test Theia. Testing usually is the biggest effort. If you want to start working on monaco-languageclient, I can make you maintainers that you can move faster, see https://github.com/TypeFox/monaco-languageclient/issues/164

> @akosyakov do you mean that upgrading monaco work shouldn't be started before completing the mentioned plan?

Upgrading monaco-languageclient is irrelevant to it. Generally I would like to minimize testing effort, but if it is super important we can do manual testing one time more.

**Closed** 2020-03-27 11:22 UTC
Labels: Team: Che-Editors, enhancement, git, monaco, vscode
