### ISSUE TITLE
Status bar content too large

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6931] opened 2020-01-21 09:51 UTC
> When an extension (e.g. a language server) shows a lot of text in the status bar, it may push the remaining content out of the visible area.

From https://github.com/gitpod-io/gitpod/issues/987

**Comment by vince-fugnitto** [comment] 2020-01-21 11:22
I believe it is a duplicate of https://github.com/eclipse-theia/theia/issues/5925 or at least related.

**Closed** 2020-01-21 11:23 UTC
Labels: bug, help wanted, statusbar, ui/ux
