### ISSUE TITLE
Support for multiple workspace folder in SCM Widget

### ISSUE THREAD

**Issue by balajiv113** [eclipse-theia/theia#9031] opened 2021-02-05 08:06 UTC
### Feature Description:
The current SCM Widget supports only one repository, even with multiple workspace folder user have to select the repository accordingly.

### Proposal 
The proposal is to provide multiple repository support like in VS Code.

**Example**
<img width="450" alt="Screenshot 2021-02-05 at 1 35 11 PM" src="https://user-images.githubusercontent.com/13016475/107006351-0544c080-67b7-11eb-800f-2f75cdd40d06.png">

**Comment by vince-fugnitto** [comment] 2021-02-05 12:56
@balajiv113 thank you for the issue, it is a duplicate of https://github.com/eclipse-theia/theia/issues/8291 where we want to support displaying multiple providers and workspaces in the `scm` view similarly to vscode.

**Closed by vince-fugnitto** 2021-02-05 12:56 UTC
