### ISSUE TITLE
[editor] EditorManager handles any URI (even folders...)

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#3858] opened 2018-12-18 20:44 UTC
Because of [this line](https://github.com/theia-ide/theia/blob/master/packages/editor/src/browser/editor-manager.ts#L98-L100), the editor ends up being displayed in the `Open With` menu, even when right clicking on a folder in the navigator... Trying to open a folder using the editor results in nothing happening, no errors, just nothing.

One of the issues is that we cannot ask the filesystem at this point, as the method is expected to be synchronous. On the other hand, the navigator already has information about the URI (it correctly displays a folder if it is one, file otherwise), it is simply not propagated to the method call:

```ts
canHandle(uri: URI, options?: ...) {
    return whatExactlyIsThisUri(uri); // ?
}
```

I don't see a clean way to fix it other than changing the API, any ideas?

**Comment by AlexTugarev** [comment] 2018-12-18 21:33
First though on this: why is the `Open With` entry shown at all for folders?

**Comment by marechal-p** [comment] 2018-12-18 22:51
> Because of this line, the editor ends up being displayed in the Open With menu, even when right clicking on a folder in the navigator...

**Comment by kittaakos** [comment] 2018-12-21 09:37
Duplicate? https://github.com/theia-ide/theia/issues/1308

If so, please close one of them. It is up to you, just pick one. Thanks!

**Comment by vince-fugnitto** [comment] 2019-11-11 15:10
> Duplicate? #1308
> 
> If so, please close one of them. It is up to you, just pick one. Thanks!

Closing as it's a duplicate of #1308

**Closed by vince-fugnitto** 2019-11-11 15:10 UTC
Labels: editor, navigator, ui/ux
