### ISSUE TITLE
[terminal] forward slash ( / ) does not display on Edge

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5038] opened 2019-04-29 17:08 UTC
**Description**

The forward slash <kbd>/</kbd> does not display in the `terminal` when running Theia on Windows using Edge.

**Steps to reproduce**
1. Open Theia on Edge.
2. Open a new terminal.
3. Attempt to insert  <kbd>/</kbd> and notice nothing gets outputted.

**Diagnostics**

```bash
Cannot get key code from keyboard event: [object KeyboardEvent]
```

**OS and Theia Version**
- Theia 61cf13d
- Windows 10
- Microsoft Edge 44.17764.10

**Comment by marcdumais-work** [comment] 2019-05-01 11:03
@vince-fugnitto has confirmed that this bug is not Windows-specific: he was able to reproduce by running the B-E on Mac, accessing it with Edge browser.

**Comment by koying** [comment] 2019-11-03 17:47
Not really sure if it's related, but using a self-cooked container based upon https://github.com/theia-ide/theia-apps , built today so I assume 0.12, I have exactly the same symptom, but both in chrome and firefox... Even copy-pasting rips the slashes off.

I *think* it worked in the past days, so maybe 0.12 has a regression?

**Comment by FernandoAscencio** [comment] 2023-02-28 14:31
Seems Fixed now

![Issue5038Fixed](https://user-images.githubusercontent.com/48699277/221883913-553d37b9-c35e-4748-bd74-2f1adfaf7517.gif)

Microsoft Edge: 110.0.1587.57
Chrome: 110.0.5481.178

**Comment by msujew** [comment] 2023-02-28 14:33
I can confirm that I can't reproduce this. It's likely an old `xterm` bug that has been fixed some time ago 👍

**Closed by msujew** 2023-02-28 14:33 UTC
Labels: bug, terminal, keybindings, browser/edge
