### ISSUE TITLE
Dirty Preference editor pop-ups two dialogs when closing the editor

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#2780] opened 2018-09-05 11:35 UTC
After opening the preferences setting and do a modification (No auto-save),  if you try to kill the preferences editor, it will pop-up two dialogs to save the new information. Only one pop-up dialog should be enough when pressing "Don't save" button.

![prefdialogsavedtwice](https://user-images.githubusercontent.com/419051/45090623-db66ab80-b0dd-11e8-9331-4420095fbb76.gif)

**Comment by elaihau** [comment] 2018-11-27 16:33
It happens because both PreferenceContainer and PreferenceEditor are `Saveable`, and therefore the dialog gets created once on each.

**Comment by lmcbout** [comment] 2018-11-27 16:40
@elaihau Even if there is two Preferences (editor_container),
we should either save both or cancel both on the first dialog

**Comment by vince-fugnitto** [comment] 2020-05-06 12:48
Closing as the bug is no longer reproducible with the new user-interface:
- #7105

**Closed by vince-fugnitto** 2020-05-06 12:48 UTC
Labels: preferences
