### ISSUE TITLE
Task output does not display

### ISSUE THREAD

**Issue by odeliat** [eclipse-theia/theia#9098] opened 2021-02-21 14:02 UTC
### Bug Description:
When running task the output is not display on the console.

### Steps to Reproduce:

1. create new task
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "node-version",
			"type": "shell",
			"command": "node --version"
        }
	]
}
```
2. run task
3. no output is display

### Additional Information

- Operating System: gitpod
- Theia Version: master

**Comment by vince-fugnitto** [comment] 2021-02-21 15:06
@odeliat the issue is a duplicate of https://github.com/eclipse-theia/theia/issues/2961, you can confirm by adding a sleep before your actual command.

**Closed by vince-fugnitto** 2021-02-21 15:06 UTC
Labels: bug, tasks
