### ISSUE TITLE
Can't set defaultIconTheme to be "vs-seti"

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#9101] opened 2021-02-21 21:00 UTC
### Bug Description:

When building theia application with "vs-seti" default icon theme, there seems to be a race condition on the first load between loading of the theme and registering it. It is loaded before it is registered. Probably due to the fact that vs-seti comes from vs code extension activation.

### Steps to Reproduce:

1. Build theia app with frontend config set to `"defaultIconTheme": "vs-seti"`
2. Load theia for the first time (you can also pause in debugger when it loads and then claer theia host browser local storage)
3. All icons are empty instead of vs-seti

### Additional Information

- Operating System: windows
- Theia Version: 1.10.0

**Comment by vince-fugnitto** [comment] 2021-02-22 00:31
@amiramw thanks for the issue, it is a duplicate of https://github.com/eclipse-theia/theia/issues/6999.
Both `themes` and `icon-themes` do not work reliably when setting default values in the application's `package.json` at the moment.

- https://github.com/eclipse-theia/theia/issues/6999#issuecomment-754728485

**Closed by vince-fugnitto** 2021-02-22 00:31 UTC
Labels: theming

**Comment by EstherPerelman** [comment] 2021-11-09 09:07
@vince-fugnitto 
I have this issue with contributed theme (by an extension) when setting the `"defaultTheme"`  of the extension in the application `package.json`
The first time loading theia (with empty `localStorage`) the `dark` theia theme is applied, 
as I saw the extension theme is registered only [here (waiting to many promises)](https://github.com/eclipse-theia/theia/blob/16f3309d88a8a2dd6a7eb32645b8903ed2667784/packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts#L289-L294) so meantime when `theia` setting the `"defaultTheme"` from the config it's not registered yet and it fallback to the default dark theme,
The use of the `indexedDB` not working for this case of empty `localStorage`
What can be done to fix it? can we register the themes earlier (before loading the frontend ui)?

**Comment by vince-fugnitto** [comment] 2021-11-09 14:03
@EstherPerelman you referenced the plugin-system which I assume means your default theme is in fact a plugin theme. The issue is that the plugin likely activates late resulting in you seeing the `dark` theme. The fix that was implemented was the following https://github.com/eclipse-theia/theia/pull/9303#issuecomment-816156365.

> What can be done to fix it? can we register the themes earlier (before loading the frontend ui)?

I'm not sure we can eagerly load themes but perhaps you might want to investigate.
