### ISSUE TITLE
builtin-node-debug return a status code 404 with the requested version

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7675] opened 2020-04-27 13:17 UTC
### Bug Description:
Try to build the latest Theia this morning.
The following vscode builtin fails to download:
```
 vscode-builtin-node-debug: failed to download  { statusCode: 404 } 
```
In package.json, the link is:
    "vscode-builtin-node-debug": "https://open-vsx.org/api/ms-vscode/node-debug/1.44.2/file/ms-vscode.node-debug-1.44.2.vsix",
 If I look at the open-vsx registry, I only see version 1.44.1, Does the latest version been removed ! 

### Steps to Reproduce:

1. Remove the plugins folder
2. yarn download:plugins
3.

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: Latest: commit bea6be60159f87ff31b0d9553e18dccec3baf637

**Comment by vince-fugnitto** [comment] 2020-04-27 13:19
Duplicate of https://github.com/eclipse-theia/theia/issues/7488, the issue is already known.

**Closed by vince-fugnitto** 2020-04-27 13:19 UTC
