### ISSUE TITLE
Copy & Paste issues 

### ISSUE THREAD

**Issue by i501378** [eclipse-theia/theia#8933] opened 2021-01-10 18:54 UTC
### Bug Description:

Issue 1
When user select file or folder and press 'Ctrl+C' and 'Ctrl+V' he error.
At vscode a new file created that end with copy suffix.
This functionality is exist when user select duplicate from the menu, can it be used in the same way here?

Issue 2
Select paste at chrome browser from the menu is not supported and return this error https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/common-frontend-contribution.ts#L573
Can it be supported? 
If it can't be supported, can the command not be registered (vscode doesn't registered unsupported commands).

### Additional Information

- Operating System: Gitpod
- Theia Version: last version

**Comment by vince-fugnitto** [comment] 2021-01-10 19:41
@i501378 thank you for reporting the issue, in the future it'd be better to create separate it into individual issues so they are easier to track, and close.

> Issue 1

For the first issue, it should be fine to duplicate files with the `-copy` suffix (similarly by the `duplicate` command).
Pull-requests are welcome!


> Issue 2

I believe the second issue is a duplicate of https://github.com/eclipse-theia/theia/issues/2171.

**Closed** 2021-03-04 15:21 UTC
Labels: filesystem
