### ISSUE TITLE
[code-lens] Code-lens display wrong

### ISSUE THREAD

**Issue by shuyaqian** [eclipse-theia/theia#9443] opened 2021-05-06 07:01 UTC
### Bug Description:
When I use the debugger for java plug-in, text overlap occurs:

### Steps to Reproduce:

1.Open file B, ,
2.activate the debugger plug-in,
3.and switch back to file A. Codelens overlaps.
![1](https://bbs-img.huaweicloud.com/blogs/img/1620284327116015684.gif)

The same operation is correctly displayed in vscode:
![2](https://bbs-img.huaweicloud.com/blogs/img/1620284332768068583.gif)

I found that this is because in theia,  _prepareRenderWidget is executed together with files A and B in the editor area, but in file A that is not open at this time, so the domNode.clientHeight of codelens is 0. 
![image](https://user-images.githubusercontent.com/6367259/116643943-bcab3680-a9a4-11eb-9548-eb6d88ce1994.png)
Therefore, the value of _cachedDomNodeClientHeight is incorrectly calculated, causing overlap.

So, Can we active code-lens when a file is actived, instead of all files which are opened in main panel, to  align  VSCode?

### Additional Information

- Operating System:  Ubuntu18.04.1_server_64bit_en_basic
- Theia Version: 1.11.0

**Comment by shuyaqian** [comment] 2021-05-06 07:12
@colin-grant-work

**Comment by vince-fugnitto** [comment] 2021-05-06 12:48
@shuyaqian what are the two buttons you have present in the extensions-view (red and blue buttons), unfortunately I cannot read them, and I do not see them on `master`. The view looks very different, is it some custom implementation of the `extensions-view`?

I confirmed that it seems to work properly for me:

![image](https://user-images.githubusercontent.com/40359487/117300169-49437200-ae47-11eb-82d4-ccce0e4de2aa.png)

**Comment by colin-grant-work** [comment] 2021-05-06 14:29
@vince-fugnitto, it looks like those are 'Enable' / 'Disable' (blue, toggleable) and 'Uninstall' (presumably toggled from 'Install').

**Comment by vince-fugnitto** [comment] 2021-05-06 14:36
> @vince-fugnitto, it looks like those are 'Enable' / 'Disable' (blue, toggleable) and 'Uninstall' (presumably toggled from 'Install').

@colin-grant-work right, but the features you mentioned along with the rest of the updates in the view are not present in `master`. I cannot guarantee that the reported bug is not introduce by this logic, or any other customizations made in the product as I cannot reproduce on `master`, nor can I follow their reproduction steps.

**Comment by colin-grant-work** [comment] 2021-05-06 15:10
I'm also unable to reproduce the bug on `master`, in part because `master` simply doesn't have the `Enable` / `Disable` functionality, so it's impossible to replicate that sequence of events - though it would be great if that could be contributed upstream! Given that that's the sequence of events that causes problems, I would guess that something is going wrong in the reactivation of the plugin. Since the rendering of the code lenses is handled primarily by Monaco, it could be that events or data aren't being passed correctly, so it's rendering the code lens, but not adjusting the spacing of the document lines to accommodate the new content.

**Comment by shuyaqian** [comment] 2021-05-07 02:08
> I'm also unable to reproduce the bug on `master`, in part because `master` simply doesn't have the `Enable` / `Disable` functionality, so it's impossible to replicate that sequence of events - though it would be great if that feature could be contributed upstream! Given that that's the sequence of events that causes problems, I would guess that something is going wrong in the reactivation of the plugin. Since the rendering of the code lenses is handled primarily by Monaco, it could be that events or data aren't being passed correctly, so it's rendering the code lens, but not adjusting the spacing of the document lines to accommodate the new content.
Sorry, 'Enable`/'Disable` is a function of our products. I think this problem may not be caused by plug-in reactivation . This is because you can reproduce the problem as follows:  
1. Open two Java files A and B,  
2. keep A activated,  
3. install the debugger for java plug-in.  
4. After the plug-in is installed, activate file B, then you will see the code-lens in file B is misplaced.

**Comment by shuyaqian** [comment] 2021-05-07 02:31
I see that vscode had this [problem ](https://github.com/microsoft/vscode/issues/71745)before, but it has now been fixed. The difference between theia and vscode is that code-lens in the vscode is rendered asynchronously when a file is activated. In theia, the code-lens' positions of all opened files are calculated at a time. So there's an error in calculating the location in @theia/monaco-editor-core,  domNode.clientHeight of codelens is 0  in the file that's not activated, 
![image](https://user-images.githubusercontent.com/6367259/116643943-bcab3680-a9a4-11eb-9548-eb6d88ce1994.png)
so when it's activated again, you'll see that it's shifted by clientHeight.

**Comment by colin-grant-work** [comment] 2021-05-07 14:45
> Sorry, 'Enable/'Disable is a function of our products. I think this problem may not be caused by plug-in reactivation . This is because you can reproduce the problem as follows...

Thanks for the suggestion. I was eventually able to reproduce the bug on `master` by installing and switching files:

![image](https://user-images.githubusercontent.com/62660806/117466932-d73b5d80-af18-11eb-82f5-e325ce48586e.png)

> I see that vscode had this [problem ](https://github.com/microsoft/vscode/issues/71745)before, but it has now been fixed. The difference between theia and vscode is that code-lens in the vscode is rendered asynchronously when a file is activated. In theia, the code-lens' positions of all opened files are calculated at a time.

Good find! Would it be possible to make a fix to bring Theia into line with VSCode's approach to rendering on activation, rather than processing all editors when the marker messages come in?

**Comment by shuyaqian** [comment] 2021-05-14 09:28
> 
> Good find! Would it be possible to make a fix to bring Theia into line with VSCode's approach to rendering on activation, rather than processing all editors when the marker messages come in?

I looked at the code in monaco and found `editor.onDidChangeModel` can fire codelens rerender. Can we fire this event when we toggle the current editor?

**Comment by tsmaeder** [comment] 2021-06-23 07:40
Maybe https://github.com/eclipse-theia/theia/pull/9154 will fix this problem.

**Comment by msujew** [comment] 2021-07-20 14:46
@tsmaeder You were right, I did mostly fix this issue. I was still able to reproduce it for a few frames. It will fix itself almost instantly:

https://user-images.githubusercontent.com/4377073/126344482-e59fda7a-3784-48e3-a8a4-714fdfc79704.mp4

Does this warrant keeping this issue open? Or should we close it?

**Comment by colin-grant-work** [comment] 2021-07-20 14:49
Since there don't seem to be any competing solutions, I'd say we may as well count it as solved? I think I've seen that level of jumpiness in VSCode, as well, for what that's worth.

**Comment by msujew** [comment] 2021-07-20 14:52
@colin-grant-work I agree. Can someone close this issue and the associated PR?

**Closed** 2021-07-20 15:01 UTC
Labels: bug, java, monaco
