### ISSUE TITLE
rpc: maximum call stack size exceeded

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12173] opened 2023-02-10 16:00 UTC
#### Bug Description:

I noticed when using the `vscode-git` and `vscode-git-base` builtins that we get a **maximum call stack exceeded error**:

```
Uncaught (in promise) Error: Error during encoding: 'Maximum call stack size exceeded'
    at MsgPackMessageEncoder.encode (rpc-message-encoder.ts:151)
    at MsgPackMessageEncoder.request (rpc-message-encoder.ts:137)
    at RpcProtocol.sendRequest (rpc-protocol.ts:161)
    at proxy-handler.ts:74
```

![image](https://user-images.githubusercontent.com/40359487/218136652-6280ebe7-47b0-43a0-81a1-e91992250fcc.png)

The error is thrown when interacting with the inline toolbar item for resources.

### Steps to Reproduce:

1. start the application without `@theia/git` in either the `browser` or `electron`
2. comment out the following so `yarn download:plugins` pulls the builtins https://github.com/eclipse-theia/theia/blob/371ab02dda5c6df2c1381ab68b2f5ae341f7d258/package.json#L122-L123
3. build, download plugins, and start the application
4. open a workspace under git version control
5. make changes
6. attempt to interact with the `scm` view with the inline toolbar item for the changes

**Comment by tsmaeder** [comment] 2023-02-21 12:44
Maybe something like https://github.com/eclipse-theia/theia/pull/12172?

**Comment by vince-fugnitto** [comment] 2023-02-21 13:01
> Maybe something like #12172?

I don't believe so, I believe it has to do with some circular reference. I tried #12172 and could still reproduce the issue.

**Comment by marcdumais-work** [comment] 2023-02-22 14:55
Here are `vscode.git` warning traces, perhaps related to this issue, from the browser console. They are about the extension registering menu items and finding missing sub-menus `scm/sourceControl` and `scm/change/title`:

![image](https://user-images.githubusercontent.com/25749063/220658812-d51ad963-4885-4694-ae07-e7c63d4a87fc.png)

**Comment by safisa** [comment] 2023-02-28 10:21
I got these errors too...

**Comment by vince-fugnitto** [comment] 2023-02-28 14:21
The issue happens as I've mentioned due to circular reference issues when we attempt to `encode`, we should do a better job at serializing:

![Screen Shot 2023-02-28 at 9 05 52 AM](https://user-images.githubusercontent.com/40359487/221881319-32ffd8dc-97c1-4b93-9de5-e7cbd9aa0adf.png)

The `ScmPluginResource` is referencing itself.

**Comment by tsmaeder** [comment] 2023-03-01 09:39
@vince-fugnitto I would argue that the problem is that we're trying to send plugin-provided objects over the main/ext interface, when we really should be sending well-known DTO's instead. Is this what's happening? Handling general recursive structures is out of scope for our rpc framework.

**Comment by msujew** [comment] 2023-03-01 10:30
@tsmaeder The `PluginScmResource` actually isn't a plugin provided object, but created on the frontend side:

https://github.com/eclipse-theia/theia/blob/60209ecf17f695518856fe3bcf4383dea5512950/packages/plugin-ext/src/main/browser/scm-main.ts#L82-L99

But you're right anyway, as we need to send a DTO instead.

**Closed** 2023-03-17 17:54 UTC
Labels: messaging
