### ISSUE TITLE
Find in Folder - no results

### ISSUE THREAD

**Issue by vseager** [eclipse-theia/theia#6896] opened 2020-01-16 12:24 UTC
### Description
When using the "Find in Folder" option, no results are returned. The files can be found is searching all files, just not when searching specific directories.

### Reproduction Steps
* Copy text from file
* Right click on a parent folder and click "Find in Folder"
* Paste text and search

![screencast-che-che dev edge-servers com-2020 01 16-12_14_57](https://user-images.githubusercontent.com/2035088/72525026-1b55ab00-385b-11ea-8c36-b05e72a764ee.gif)

**OS and Theia version:**

* Ubuntu
* Che-Theia@f3c54f1 using Theia@39d6cc67

List of extensions:
* @theia/core 0.14.0
* @theia/output 0.14.0
* @theia/process 0.14.0
* @theia/filesystem 0.14.0
* @theia/variable-resolver 0.14.0
* @theia/workspace 0.14.0
* @theia/languages 0.14.0
* @theia/editor 0.14.0

**Comment by vseager** [comment] 2020-01-17 14:42
@akosyakov I'm sorry I'm an end user and not sure what you mean by this. I've already explained the issue the best I can and included a screencast so hopefully this helps you find a resolution.

**Comment by benoitf** [comment] 2020-01-17 14:55
@vseager it would be nice if you can provide the link to the source code (like a github repository if it's public) and the string that you're searching with text format in the issue.

**Comment by vseager** [comment] 2020-01-17 14:59
@benoitf The repository is private but the project is a Magento project (https://github.com/magento/magento2/) . You could replicate the issue by searching for any term, for example if you were trying to find the string "class DefaultConfigProvider" in the file https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/DefaultConfigProvider.php by searching within one of it's parent directories.

**Comment by Anasshahidd21** [comment] 2020-01-21 20:26
I tried reproducing using the steps provided, I used Eclipse Theia to reproduce it, and the issue seems to be resolved already. The "Find in Folder" works perfectly fine in theia. 
![Screenshot from 2020-01-21 15-25-42](https://user-images.githubusercontent.com/43870550/72840510-65c39700-3c62-11ea-9a55-457fcc8f0a88.png)

**Comment by vseager** [comment] 2020-01-30 11:39
@Anasshahidd21 It is still an issue for me. Which version of Theia are you testing it in?

**Comment by davidwindell** [comment] 2020-02-03 13:14
@Anasshahidd21 this seems to happen only in the vendor folder. I think the logic needs to be changed so that when explicitly searching "in folder", it ignores any ignore rules?

**Comment by akosyakov** [comment] 2020-02-03 14:11
> it ignores any ignore rules?

probably if you search in ignored folder only

**Comment by davidwindell** [comment] 2020-02-03 14:19
Yeah, I think that's what it's doing and that should be changed?

**Comment by akosyakov** [comment] 2020-02-04 07:46
I meant currently one cannot search in ignored folder, but we could suppress ignore filter if we detect that a search is started in such folder.

**Comment by davidwindell** [comment] 2020-02-04 10:05
That would be awesome!

**Comment by vince-fugnitto** [comment] 2020-02-17 20:00
> I meant currently one cannot search in ignored folder, but we could suppress ignore filter if we detect that a search is started in such folder.

I thought this was already the case (https://github.com/eclipse-theia/theia/issues/3917#issuecomment-450914317). If I search globally, the search will respect the `.gitignore`. If I narrow down the search to explicitly choose a directory to search from (`find in folder`), I do successfully get results from said folder.

_Search Globally_:

<img width="899" alt="Screen Shot 2020-02-17 at 2 58 06 PM" src="https://user-images.githubusercontent.com/40359487/74683198-22dbdd00-5196-11ea-8e14-6ca6fd8ddf80.png">

_Searching Specifically in 'tmp/*' returns me gitignored results_:

<img width="902" alt="Screen Shot 2020-02-17 at 2 58 18 PM" src="https://user-images.githubusercontent.com/40359487/74683225-35561680-5196-11ea-9318-902b599d7a16.png">

**Comment by davidwindell** [comment] 2020-02-19 01:32
This doesn't work for me on the latest Eclipse Che, Theia@e1d08d00

**Comment by vseager** [comment] 2020-02-19 13:44
Doesn't work for me either!

**Comment by davidwindell** [comment] 2020-05-21 11:58
This is getting really annoying, should we raise it on the eclipse/che repo instead?

**Comment by vince-fugnitto** [comment] 2020-05-21 12:36
> This is getting really annoying, should we raise it on the eclipse/che repo instead?

I'm sorry, the community has been busy with other priorities (marked by the 'help wanted' label)
If the issue is important to you please don't hesitate to open a pull-request to resolve it.

**Comment by davidwindell** [comment] 2020-05-21 14:11
Can you confirm if this is a Che or Theia issue?

**Comment by vince-fugnitto** [comment] 2020-05-21 14:24
> Can you confirm if this is a Che or Theia issue?

@davidwindell I see that in theia, if we search for a term that is in an ignored folder/file (ex: file under node_modules), performing a 'search-in-workspace' does not yield any results unless we explicitly set 'include ignored files' option (eye icon):

_Searching Without 'Include Ignored Files'_

<div align='center'>

<img width="1232" alt="Screen Shot 2020-05-21 at 10 23 09 AM" src="https://user-images.githubusercontent.com/40359487/82568709-3740c480-9b4d-11ea-9ed8-f0b657a97d8c.png">

</div>

_Searching With 'Include Ignored Files'_

</div align='center'>

<img width="1232" alt="Screen Shot 2020-05-21 at 10 23 18 AM" src="https://user-images.githubusercontent.com/40359487/82568724-3dcf3c00-9b4d-11ea-9f9b-3162a60affd1.png">


</div>

**Comment by davidwindell** [comment] 2020-05-22 21:13
Ah, that does seem to help! I apologise for not spotting the eye icon. It does feel odd that when you explicitly request a folder to include it still excludes it without manual action. I'll go ahead and close this issue now.

**Comment by vince-fugnitto** [comment] 2020-08-20 14:56
> Ah, that does seem to help! I apologise for not spotting the eye icon. It does feel odd that when you explicitly request a folder to include it still excludes it without manual action. Let's go ahead and close this issue now.

Closing.

**Closed by vince-fugnitto** 2020-08-20 14:56 UTC
Labels: :thinking: needs more info, bug, help wanted, search in workspace
