### ISSUE TITLE
TypeError: Cannot read property 'localUri' of null at DugiteGit.getFsPath

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#700] opened 2017-10-21 09:30 UTC
Console log is full of following errors while using the git extension:

```
[2017-10-21T09:29:05.475Z] ERROR: Theia/42280 on MacKosyakov-2.local:
    TypeError: Cannot read property 'localUri' of null
        at DugiteGit.getFsPath (/Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git.js:509:75)
        at DugiteGit.<anonymous> (/Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git.js:136:47)
        at step (/Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git.js:52:23)
        at Object.next (/Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git.js:33:53)
        at /Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git.js:27:71
        at Promise (<anonymous>)
        at __awaiter (/Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git.js:23:12)
        at DugiteGit.status (/Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git.js:131:16)
        at DugiteGitWatcherServer.<anonymous> (/Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git-watcher.js:101:67)
        at step (/Users/kosyakov/oomph/theia-master/git/EclipseCon_Europe_2017/backup/myapp/node_modules/@theia/git/lib/node/dugite-git-watcher.js:50:23) []
```

**Comment by kittaakos** [comment] 2017-10-22 19:06
> /myapp/node_modules//lib/node/dugite-git-watcher.js

The double forward-slashes (`//`) looks weird in the URI.

**Comment by vince-fugnitto** [comment] 2021-02-26 13:18
I have not seen this error for some time, and there is no reproduction steps.
Closing the issue since it is outdated, we can open a new one if we can reproduce on `master`.

**Closed by vince-fugnitto** 2021-02-26 13:18 UTC
Labels: bug, git
