### ISSUE TITLE
ctrl-s does not work for Webview Editor

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12979] opened 2023-10-08 08:17 UTC
### Steps to Reproduce:
When I edit a file with the draw.io editor (https://open-vsx.org/extension/hediet/vscode-drawio) `ctrl-s` has no effect

1. Install the draw.io extension
2. Create a file `foo.drawio` and open it
3. Add a square figure
4. Observe: the editor tab shows the "unsaved" circle
5. type `ctrl-s`
6. Observe: the editor tab still shows the "unsaved" circle

My expectation is for `ctrl-s` to save the editor. It works for text editors.

### Additional Information

- Operating System: Windows
- Theia Version: 1.42.0 master

**Comment by msujew** [comment] 2024-05-05 10:48
I believe this is a duplicate of https://github.com/eclipse-theia/theia/issues/9230. [Our implementation of `$trySaveDocument`](https://github.com/eclipse-theia/theia/blob/b20a7513502fada4045b375f068152a7235e6c05/packages/plugin-ext/src/main/browser/documents-main.ts#L209) uses the `EditorManager` which doesn't seem to return the custom editor widget when you use `getByUri`.

**Closed by msujew** 2024-05-05 10:48 UTC
Labels: webviews, custom-editor
