### ISSUE TITLE
Plugin-ext only can use one plugin at the same time

### ISSUE THREAD

**Issue by misakajimmy** [eclipse-theia/theia#9901] opened 2021-08-13 03:07 UTC
### Bug Description:
Theia frontend plugin can start one at the same time. 

### Steps to Reproduce:

1. Use yo generate two frontend hello-world example plugin in the same dir
2. Start theia with `--plugins=local-dir:path/to/dir`
3. Theia successful load two plugin but only one plugin `Started plugin`,the second plugin will be overwrited

There seems a bug here

> https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#:~:text=const%20host%20%3D%20plugin,set(host%2C%20dynamicContributions)%3B

```typescript
                const host = plugin.model.entryPoint.frontend ? 'frontend' : plugin.host;
                const dynamicContributions = hostContributions.get(plugin.host) || [];
                dynamicContributions.push(contributions);
                hostContributions.set(host, dynamicContributions);
```

if two plugins all frontend plugins,at first plugin load `host = "frontend"`, `plugin.host = "main"`,  `dynamicContributions = 
 hostContributions.get("main")`,
but `dynamicContributions` which load from `main`  will set to  `host` which is `frontend` .
when load second plugin, `dynamicContributions` will load from `main` and it will lead to `dynamicContributions = []`, i think it should load from `forntend`,Otherwise first plugin will be overwrite

### Additional Information

- Theia Version: since 1.13.0

**Comment by misakajimmy** [comment] 2021-08-13 03:14
> https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#:~:text=const%20host%20%3D%20plugin,set(host%2C%20dynamicContributions)%3B

**Comment by vince-fugnitto** [comment] 2021-08-13 12:03
@misakajimmy I believe it is a duplicate of https://github.com/eclipse-theia/theia/issues/9064, I'll close the other issue as you already attempted a fix :+1:

**Closed** 2021-08-20 11:52 UTC
Labels: plug-in system

**Comment by tsmaeder** [comment] 2021-08-20 11:53
@misakajimmy do you have an interesting use case for front-end plugins you could share?
