### ISSUE TITLE
Dirty editor ignores when file was changed in background 

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-theia/theia#7102] opened 2020-02-07 14:41 UTC
1. Open the same file in two frontends
2. Modify in both frontends
3. Save in first frontend
4. Than save in second frontend
   Observer no alert is shown. 

Expectation: there used to be a warning message which led you decide which state to chose IIRC.

I set a breakpoint in `MonacoEditorModel.sync` and saw that there is indeed an incoming call on a file change event, but nothing happen then.

Likely related, though could be just a caused-by:
```
logger-protocol.ts:112 root ERROR Error: Request 'updateContent' failed
    at Proxy.<anonymous> (https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/bundle.js:136377:33)
    at FileResource.<anonymous> (https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/4.bundle.js:381:62)
    at step (https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/4.bundle.js:247:23)
    at Object.next (https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/4.bundle.js:228:53)
    at https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/4.bundle.js:222:71
    at new Promise (<anonymous>)
    at push.../../packages/filesystem/lib/browser/file-resource.js.__awaiter (https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/4.bundle.js:218:12)
    at FileResource.push.../../packages/filesystem/lib/browser/file-resource.js.FileResource.saveContentChanges (https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/4.bundle.js:372:16)
    at https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/bundle.js:138098:55
    at step (https://3001-e68e572c-9e6f-40f4-bd12-786f21bbecdc.ws-eu01.gitpod.io/bundle.js:138039:23)
Caused by: Error: 'file:///workspace/theia/README.md' is out of sync.
    at FileSystemNode.createOutOfSyncError (/workspace/theia/packages/filesystem/lib/node/node-filesystem.js:306:45)
    at FileSystemNode.<anonymous> (/workspace/theia/packages/filesystem/lib/node/node-filesystem.js:236:40)
    at step (/workspace/theia/packages/filesystem/lib/node/node-filesystem.js:59:23)
```

**Comment by AlexTugarev** [comment] 2020-02-07 14:41
cc. @akosyakov

**Comment by marcdumais-work** [comment] 2020-02-12 14:34
This issue seems a partial duplicate of https://github.com/eclipse-theia/theia/issues/7036. That issue has one additional aspect that could be an enhancement: when it's detected that there is a conflict, offer a way for the user to open both versions of the file in a diff editor to reconcile the conflicting changes.

**Comment by akosyakov** [comment] 2020-02-12 14:59
@marcdumais-work true, i think we can keep it to add fix detection of conflicts and add integration tests. And #7036 to add diff editor

**Closed** 2020-02-18 16:29 UTC
Labels: bug, editor, monaco
