### ISSUE TITLE
monaco editor hangs sometimes

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7462] opened 2020-03-31 13:38 UTC
I don't know how to reproduce, happens sporadically, following stack trace in logs:
```
RangeError: Maximum call stack size exceeded
    at e.fire (editor.main.js:115)
    at t.endDeferredEmit (editor.main.js:1241)
    at o.deltaDecorations (editor.main.js:1217)
    at e.deltaDecorations (debug-editor-model.ts:401)
    at e.renderBreakpoints (debug-editor-model.ts:180)
    at e.render (debug-editor-model.ts:175)
    at e.render (debug-editor-service.ts:77)
    at debug-editor-service.ts:54
    at event.ts:117
    at e.invoke (event.ts:125)
    at editor.main.js:30
editor.main.js:30 Uncaught Error: Maximum call stack size exceeded
```

It seems to be related to debugging.

It seems to be a regression from latest Monaco migration. cc @RomanNikitenko

**Comment by danidoedel** [comment] 2020-03-31 22:20
I had something similar today. It was really really slow while typing and also the code suggestions were hanging a lot. Happened after a longer session of coding. I didn‘t check for any logs though as I thought it might have been caused by my internet, but after reading this and having the migration in mind it could be related. 
It was not related to debugging though.
I’ll try to get more infos if it happens again.

**Comment by akosyakov** [comment] 2020-04-01 12:00
I don't think it is a regression, nothing was changed in Theia or VS Code in these areas. Also still not clear how it could happen there is a guard preventing rendering breakpoints on breakpoint decorations changed. So probably `Maximum call stack size exceeded` is related to something else.

**Comment by csweichel** [comment] 2020-04-01 13:50
The user-facing effect/symptoms of this issue was that the editor became very very slow to the point that it would hang/barely respond at all to e.g. scrolling. Also, I did not see line numbers on the left-hand side anymore.

**Comment by akosyakov** [comment] 2020-04-03 09:33
It seems that breakpoints serialization goes in endless recursion while we try to send them to the plugin host process. The original error is a follow-up.

**Comment by RomanNikitenko** [comment] 2020-04-03 10:18
@akosyakov 
Did you notice something common, some conditions/steps to reproduce it?
Did you have the same stack trace this time?

I'm going to test it tomorrow, so any info how to reproduce it would be helpful...
thanks in advance!

**Comment by akosyakov** [comment] 2020-04-03 11:02
@RomanNikitenko I'm struggling to understand myself. I just see that logs are full of such errors on Gitpod staging environment and users complain about hanging UI.

@danidoedel But could it be that you had some breakpoints? Do you remember of what kind and how they were created? by you or provided by some VS Code extension?

**Comment by akosyakov** [comment] 2020-04-03 11:34
I've noticed that there was a breaking change to URI inside Monaco: https://github.com/microsoft/vscode/pull/83060

But in rest of Theia we still use `vscode-uri@1.8.0` not 2.x which is aligned with a breaking change.

From logs it seems that an issue happens when we try to seralize/deserialize vscode URI. I suspect that for some Monaco URI (aligned with 2.x)  we create old VS Code URI via string conversion and then it leads to some state which cannot be serialized properly.

**Comment by akosyakov** [comment] 2020-04-03 11:35
Switching to latest VS Code URI in Theia will be a good idea in anyway.

**Comment by vince-fugnitto** [comment] 2020-04-07 17:39
> Switching to latest VS Code URI in Theia will be a good idea in anyway: #7495

Is the issue fixed by #7506?

**Comment by akosyakov** [comment] 2020-04-07 17:41
I’m going to run new version in Gitpod next week and if it is fine now. I will close this issue.

**Comment by marcdumais-work** [comment] 2020-04-13 14:50
@akosyakov This seems like an important issue. If confirmed fixed by #7506, should we do a `1.0.1` bugfix release ASAP that includes this commit?

**Comment by akosyakov** [comment] 2020-04-14 06:31
@marcdumais-work I don't think new Monaco was a part of `1.0.0`.

**Comment by marcdumais-work** [comment] 2020-04-14 13:23
> @marcdumais-work I don't think new Monaco was a part of `1.0.0`.

Ah, right - that would be a big "bugfix" release. Nevermind

**Closed** 2020-05-12 12:36 UTC
Labels: bug, critical, debug, monaco, plug-in system
