### ISSUE TITLE
[terminal] Do not resize to full width on the right side panel

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#1358] opened 2018-02-22 19:05 UTC
Terminal window in the side panel does not resize properly
To reproduce
1- Open a terminal in the bottom panel
2- execute a command
3- Reload the web client --> sems ok
4- Move the Terminal in the right side panel
5- Just resize it by dragging the sidebar -> it expands to show the data -> OK
6- Reload the web client --> the terminal window do not use all the width of the sidepanel, but just a sub-set
![peek 2018-02-22 13-54termonalsidebarresize](https://user-images.githubusercontent.com/419051/36558512-47b7aea4-17d9-11e8-874f-3e27f5489acf.gif)

**Comment by lmcbout** [comment] 2018-02-22 19:12
Another comment, when moving back the Ternimal in the bottom-panel, re-execute a command, then resize the side panel, then reload
--> After a web client reload, the re-size of the terminal has some chars hidden under the side panel.
![peek 2018-02-22 14-08terminalresizebottomhidechar](https://user-images.githubusercontent.com/419051/36558809-3d2a4ce8-17da-11e8-8e33-8feebf6a67de.gif)

**Comment by elaihau** [comment] 2018-03-23 22:08
I cannot reproduce this problem with the latest version of theia. Could you please take a look at it one more time?

**Comment by lmcbout** [comment] 2018-03-26 13:15
@elaihau I just downloaded the latest master this morning 
( commit 1235a62fde86d1f300738616d22bbbfa42f19ac7 ) and the problem is still valid. Follow the step describe above.

**Comment by vince-fugnitto** [comment] 2018-11-05 16:19
@lmcbout it seems to work correctly, both on Chrome and Firefox.
Can you confirm if this is still an issue?

**Comment by lmcbout** [comment] 2018-11-05 17:03
Just tested on Chrome and the issue is still present :(

**Comment by vince-fugnitto** [comment] 2021-02-26 13:33
Closing, as Liang and I expressed earlier we cannot reproduce the bug any longer.
We can re-open if we notice any future regressions.

**Closed by vince-fugnitto** 2021-02-26 13:33 UTC
Labels: bug, terminal
