### ISSUE TITLE
VS Code extension contribution point viewsWelcome doesn't seem to work

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#12716] opened 2023-07-17 14:46 UTC
### Bug Description:

Looking at the Theia codebase, I can see that it tries to support `contributes.viewsWelcome`. This is a feature that defines "welcome" view context to be shown when the TreeView associated with a custom view is empty.

I created a very simple contribution and it's working as expected in VS Code. In Theia, the same contribution doesn't show anything in the custom view.

**VS Code**

![image](https://github.com/eclipse-theia/theia/assets/109228283/1eb358f0-b50c-4cfa-9d0f-bae530d61c37)

**Theia**

![image](https://github.com/eclipse-theia/theia/assets/109228283/1e23a773-b404-472a-b408-ed9feb29effa)

### Steps to Reproduce:

git clone -b views_welcome https://github.com/jcortell68/theiasandbox
cd theiasandbox
yarn
yarn start:electron

### Additional Information

- Operating System: Windows
- Theia Version: 1.39

**Comment by vince-fugnitto** [comment] 2023-07-17 18:18
Thanks for the issue, it is a duplicate of https://github.com/eclipse-theia/theia/issues/9361.

**Closed by vince-fugnitto** 2023-07-17 18:18 UTC
Labels: vscode
