### ISSUE TITLE
Preferences page performs horribly with lots of items

### ISSUE THREAD

**Issue by RDIL** [eclipse-theia/theia#8802] opened 2020-11-30 15:13 UTC
### Bug Description:
To be expected, the preferences page doesn't perform well with a lot of options, but come on, just using Gitpod, my browser feels like one of the sloths from the movie Zootopia.  If there is anything that can be done on Theia's end to reduce the render lag, that would be amazing.

### Steps to Reproduce:

1. Open preferences on Gitpod
2. See issue

### Additional Information

- Operating System: Windows + Firefox
- Theia Version: Gitpod

**Comment by vince-fugnitto** [comment] 2020-11-30 16:44
Closing as it is a duplicate of https://github.com/eclipse-theia/theia/issues/7875.

> To be expected, the preferences page doesn't perform well with a lot of options, but come on, just using Gitpod, my browser feels like one of the sloths from the movie Zootopia.

In the future please be professional when describing issues.

**Closed by vince-fugnitto** 2020-11-30 16:44 UTC
Labels: performance, preferences

**Comment by RDIL** [comment] 2020-11-30 17:14
> 
> 
> Closing as it is a duplicate of #7875.
> 
> > To be expected, the preferences page doesn't perform well with a lot of options, but come on, just using Gitpod, my browser feels like one of the sloths from the movie Zootopia.
> 
> In the future please be professional when describing issues.

Alright sorry, just trying to make a joke
