### ISSUE TITLE
Cannot execute npm Task

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#9335] opened 2021-04-13 08:19 UTC
### Bug Description:
When I try to execute detected tasks, I get a failure message saying "Error launching task '<task name>': Error starting process (ENOENT)"

### Steps to Reproduce:

1. Build & Run Browser example
2. Open a workspace with a npm example, for example https://github.com/Axosoft/nsfw
3. Do a "Run Task..." and pick a task, for example 'lint' in the above example
4. Observe: the task is not executed and you get an error dialog.

### Additional Information

- Operating System: Window 10
- Theia Version: master

**Comment by tsmaeder** [comment] 2021-04-13 09:06
Hmh...this is not restricted to Windows. Problem seems to be that we're trying to run the file `npm run test`, for example instead of just `npm` plus arguments

**Comment by RomanNikitenko** [comment] 2021-04-13 13:26
I did git reset locally to the commit https://github.com/eclipse-theia/theia/commit/221d90e420f47b7ef13e0ee3b52c8301c1e3df63, so it's before these changes https://github.com/eclipse-theia/theia/pull/9189

npm tasks work well for me, so it looks like the current issue is a regression after merging https://github.com/eclipse-theia/theia/pull/9189
thanks if someone could check it as well...

**Comment by tsmaeder** [comment] 2021-04-13 17:07
Hmmm I cannot reproduce the problem with that commit, neither. However, I don't really understand yet how that commit broke the npm tasks. I'll have to debug through it.

**Comment by tsmaeder** [comment] 2021-04-14 07:13
Funnily, parsing the command line (like we used to do) fixes the problem, as well. I think we're just not hitting the "shell" case anymore and are using the 'process' case for running the command.

**Comment by tsmaeder** [comment] 2021-04-14 07:21
A candidate for the relevant change is here:  https://github.com/eclipse-theia/theia/pull/9189/files#diff-89cc6d20975ccb34aa4eda6fa7202f6817bb30ef36391d2ca36093e88a706440L1888 
Note that the the `TaskDefinition.type' is no longer updated to be `shell`, for example. Since the `type` field is queried in `TaskProcessRunner` that could make use fall into the default case in this if-else: https://github.com/eclipse-theia/theia/blob/5e45d2b8ad4b27832c976aa406db03c561da9588/packages/task/src/node/process/process-task-runner.ts#L146

**Comment by RomanNikitenko** [comment] 2021-04-16 08:57
@tsmaeder 
should we close the issue?

**Closed** 2021-04-16 08:58 UTC
Labels: bug, tasks
