### ISSUE TITLE
quick-open: multi-step input does not work well

### ISSUE THREAD

**Issue by bjornhansen** [eclipse-theia/theia#8777] opened 2020-11-24 23:56 UTC
### Bug Description:
The [PostgreSQL](https://open-vsx.org/extension/ckolkman/vscode-postgres) plugin has a UI issue with the command palette. It wants a series of inputs put into the palette, but pressing "enter" causes the palette to disappear. Thus making it impossible to enter all the fields and connect a database.

### Steps to Reproduce:

1. Install the plugin from OpenVSX.
![Install](https://user-images.githubusercontent.com/19376185/100164211-455cfe00-2e6c-11eb-827e-c22760cd18e5.png)
2. Go to the new Postgres menu and click the little + in the top right corner.
![Screenshot_2020-11-24 blackbirdcode app - stage](https://user-images.githubusercontent.com/19376185/100164296-70dfe880-2e6c-11eb-8451-d202ceede60c.png)
3. You should see the command palette open with the add database dialogs.
![Screenshot_2020-11-24 blackbirdcode app - stage(1)](https://user-images.githubusercontent.com/19376185/100164473-c61bfa00-2e6c-11eb-961e-7bbd67f65618.png)

4. Enter a value for the hostname, e.g. "localhost" and press enter.

**Expected:** The next input appears in the command palette.
**Result:** The command palette disappears without error or confirmation.

### Additional Information

- Operating System: Gitpod
- Theia Version: Not sure how to tell

**Comment by vince-fugnitto** [comment] 2020-11-25 13:32
@bjornhansen I believe it is the same issue as https://github.com/eclipse-theia/theia/issues/6193, it looks like there is a bug with multi-step input where <kbd>enter</kbd> accepts and closes the input rather than continuing (confirmed the bug using the [QuickInput Sample](https://github.com/microsoft/vscode-extension-samples/tree/master/quickinput-sample)).
- https://github.com/vince-fugnitto/quick-open-samples/releases/download/1.0.0/quickinput-sample-0.0.1.vsix

**Comment by vince-fugnitto** [comment] 2020-11-25 13:47
@bjornhansen I believe it is the same issue as https://github.com/eclipse-theia/theia/issues/6193.
I confirmed that the multi-step input works fine using the using the [QuickInput](https://github.com/microsoft/vscode-extension-samples/tree/master/quickinput-sample) [sample](https://github.com/vince-fugnitto/quick-open-samples/releases/download/1.0.0/quickinput-sample-0.0.1.vsix).

![quick-open](https://user-images.githubusercontent.com/40359487/100235699-ba771480-2efa-11eb-8e99-cf4fed3a6d5d.gif)

The fact that the input is hidden after step `2/3` would be fixed by the following https://github.com/eclipse-theia/theia/issues/6195.

**Comment by Tpuljak** [comment] 2022-02-18 21:34
Another extension that doesn't work in Theia is https://open-vsx.org/extension/fernandoescolar/vscode-solution-explorer.

To reproduce:

1. Install the extension
2. Open the widget in the left sidebar
3. Right click the only tree item and select Create new solution
4. Input a name for the solution
5. Observe that nothing happens on Enter

No error is emitted on Enter. It just seems that the input is not accepting.

I tried to browse through the monaco implementation but I had no luck in tracking the issue down.

It's a shame that such a nice extension cannot work in Theia just yet.

**Closed** 2022-04-22 19:44 UTC
Labels: bug, vscode, quick-open
