### ISSUE TITLE
vscode: implement 'editorScroll' command

### ISSUE THREAD

**Issue by tavoda** [eclipse-theia/theia#7567] opened 2020-04-14 12:19 UTC
### Description
After pressing CTRL + F with VIM plugin I get:

> TaskQueue: Error running task. Failed to handle key=&lt;C-f>. Command with id 'editorScroll' is not registered..

### Reproduction Steps
- Build from master
- Download VSCODE VIM plugin from  https://marketplace.visualstudio.com/items?itemName=vscodevim.vim -> Download extension
- Place downloaded file to $THEIA/plugins/
- Start browser environment 'cd examples/browser; yarn run start'
- Open file and press CTRL + F

**OS version:**
Linux xxxx 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
**Theia version:**
Latest from master

**Comment by vince-fugnitto** [comment] 2020-04-14 12:31
It looks like the [editorScroll](https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/controller/coreCommands.ts#L1100-L1169) implementation is still missing in order for the command to be properly discoverable and executable.

**Comment by tavoda** [comment] 2020-04-14 12:43
I can help with implementation. Can you point me somewhere to source code where can I put it? I have no time to study whole project structure. TNX

**Comment by vince-fugnitto** [comment] 2020-04-14 13:02
> I can help with implementation. Can you point me somewhere to source code where can I put it? I have no time to study whole project structure. TNX

The changes look a bit involving but it looks like we can register a command in [editor-commands](https://github.com/eclipse-theia/theia/blob/master/packages/editor/src/browser/editor-command.ts) without a label (so it does not show up in the quick-command menu), and the plugin-system would delegate any call from any plugin to it, similarly to:

https://github.com/eclipse-theia/theia/blob/c3d6b9f787b1b73557038bdf08d12ff54ff7f94c/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L187-L189

**Comment by tavoda** [comment] 2020-04-14 13:08
Because of MIT licence I can copy command from vscode repo and than register it in plugin-vscode-commands-contribution.ts, right?

**Comment by vince-fugnitto** [comment] 2020-04-14 13:11
> Because of MIT licence I can copy command from vscode repo and than register it in plugin-vscode-commands-contribution.ts, right?

Yes, but it is likely it will need to be modified slightly to follow our internals.
The only thing is that we need to make sure that the code we are copying from is covered by a [CQ](https://github.com/eclipse-theia/theia/wiki/Registering-CQs), else we will need to register a new one. We can worry about that during the review.

**Comment by akosyakov** [comment] 2020-04-14 13:36
We don't need to copy this code. It comes with Monaco and it was there already for 3 years. Something is wrong with how we reregister this command in our registry.

Please try against this PR: https://github.com/eclipse-theia/theia/pull/7539

**Comment by akosyakov** [comment] 2020-04-15 09:17
I cannot reproduce it on master with #7539 merged. Can someone?

**Comment by vince-fugnitto** [comment] 2021-07-13 17:32
The scroll works for me, sorry for taking time to confirm :+1:

**Closed by vince-fugnitto** 2021-07-13 17:32 UTC
Labels: :thinking: needs more info, help wanted, monaco, vscode
