### ISSUE TITLE
[java][lsp] Only stubs are available for Java types after refreshing the browser

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#3147] opened 2018-10-11 12:19 UTC
Steps to reproduce:
 - Open a `java.lang` type in the editor. For instance, `Number`.
 - Refresh the browser.
 - Got a stub in the editor:
```java
 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
package java.lang;
public abstract class Number implements java.io.Serializable {
  
  private static final long serialVersionUID = -8742448824652078965L;
  
  public Number() {
  }
  
  public abstract int intValue();
  
  public abstract long longValue();
  
  public abstract float floatValue();
  
  public abstract double doubleValue();
  
  public byte byteValue() {
    return 0;
  }
  
  public short shortValue() {
    return 0;
  }
}
```

**Comment by AlexTugarev** [comment] 2018-10-11 12:27
cannot reproduce. could you provide more details on your setup? java version (sdk?) running jdt.ls?

I can see sources after reload; checked quickly for Number, ArrayList, e.g.
```
    /**
     * Returns the value of the specified number as a {@code short},
     * which may involve rounding or truncation.
     *
     * <p>This implementation returns the result of {@link #intValue} cast
     * to a {@code short}.
     *
     * @return  the numeric value represented by this object after conversion
     *          to type {@code short}.
     * @since   JDK1.1
     */
    public short shortValue() {
        return (short)intValue();
    }
```

**Comment by tsmaeder** [comment] 2021-05-07 09:16
We no longer implement any LSP functionality. Closing.

**Closed by tsmaeder** 2021-05-07 09:16 UTC
Labels: editor, java, lsp
