### ISSUE TITLE
failed to update thread frames during python debugging

### ISSUE THREAD

**Issue by tom-shan** [eclipse-theia/theia#7264] opened 2020-03-03 10:54 UTC
### Description
When debugging python file, `Call Stack` will show the message of `Load More Stack Frames`.
it will show thread frames only after clicking this message.
![image](https://user-images.githubusercontent.com/7686800/75768643-b0ffb800-5d7f-11ea-835d-c758e4aef557.png)

### Reproduction Steps

1 download vscode python plugin
2 start theia
3 create a simple python file and add a breakpoint
4 debug this python file and click `Step Over`

**OS and Theia version:**
OS: centos 7
Theia: 6d0abe589df60fcbce48710d6a637b01ae73bf72
**Diagnostics:** 
a regression caused by https://github.com/eclipse-theia/theia/commit/d1678ad8068d9a9bf9ed8b90d2a67f01c116e850

**Comment by tom-shan** [comment] 2020-03-03 11:00
I think we should put https://github.com/eclipse-theia/theia/commit/d1678ad8068d9a9bf9ed8b90d2a67f01c116e850#diff-bb75a296f1f7fdc09c2d755ef791d61cR229 in the branch of `if (thread.stoppedDetails && thread.stoppedDetails.allThreadsStopped)` accoring to it's commit message.

**Comment by akosyakov** [comment] 2020-03-03 11:17
@marcdumais-work @marechal-p Could you have a look please? It seems to be caused by the recently merged PR or revert it.

**Comment by marcdumais-work** [comment] 2020-03-03 14:05
Reproduced on master. Will now confirm if same happens or not before https://github.com/eclipse-theia/theia/commit/d1678ad8068d9a9bf9ed8b90d2a67f01c116e850

**Comment by marcdumais-work** [comment] 2020-03-03 14:24
> Will now confirm if same happens or not before [d1678ad](https://github.com/eclipse-theia/theia/commit/d1678ad8068d9a9bf9ed8b90d2a67f01c116e850)

Confirmed - testing one commit before https://github.com/eclipse-theia/theia/commit/d1678ad8068d9a9bf9ed8b90d2a67f01c116e850, the call stack frames are displayed after stepping, without having to click on "load more stack frames".

I will talk with @marechal-p before reverting, but this looks like we will likely proceed doing this later today.

**Comment by akosyakov** [comment] 2020-03-04 10:35
@marcdumais-work Can we have a PR to revert https://github.com/eclipse-theia/theia/commit/d1678ad8068d9a9bf9ed8b90d2a67f01c116e850 please? It breaks products which use next version. A proper PR can be reintroduced later.

**Comment by marcdumais-work** [comment] 2020-03-04 12:20
> Can we have a PR to revert [d1678ad](https://github.com/eclipse-theia/theia/commit/d1678ad8068d9a9bf9ed8b90d2a67f01c116e850) please?

Yes, we'll either have a fix or revert that commit today.

**Comment by marcdumais-work** [comment] 2020-03-04 15:00
> btw was it a part of last release? 

Indeed it was. 

> We need a bug fix release probably then as well.

+1

**Comment by marechal-p** [comment] 2020-03-04 16:22
From my investigation, it seems that for some reason, the `DebugStackFramesSource.getElement` function is not called on stop, when replicating the situation mentioned by this issue.

https://github.com/eclipse-theia/theia/blob/357b8e9d4413bc5c566a7d4b751bb381b8fe5db8/packages/debug/src/browser/view/debug-stack-frames-source.tsx#L44

I wasn't able to make sense of what doesn't happen/what would need to happen to fix that, and I need to focus on other tasks for now.

**Comment by marcdumais-work** [comment] 2020-03-04 18:01
> I wasn't able to make sense of what doesn't happen/what would need to happen to fix that, and I need to focus on other tasks for now.

Thanks for the investigation @marechal-p - We'll revert the PR for now and do a bugfix release.

**Comment by marcdumais-work** [comment] 2020-03-04 18:07
The original PR is reverted - we'll make sure this issue here is no longer present if we bring it back.

**Closed** 2020-03-04 18:21 UTC
Labels: bug, critical, debug, vscode
