### ISSUE TITLE
Playwright tests failing on MacOS?

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#10797] opened 2022-02-24 19:37 UTC
I'd also add here continued misgivings about the new Playwright tests (@JonasHelming, @planger). À propos [a failure in CI](https://github.com/eclipse-theia/theia/runs/5322296169?check_suite_focus=true), I went to run the tests locally (MacOS) and got numerous failures. I switched to `master` and still got numerous failures; I did a thorough `git clean` and deleted `~/.theia` and got one fewer failures, but still many:

```
[playwright]   Slow test file: ../../tests/theia-quick-command.test.ts (4m)
[playwright]   Slow test file: ../../tests/theia-explorer-view.test.ts (2m)
[playwright]   Slow test file: ../../tests/theia-preference-view.test.ts (2m)
[playwright]   Slow test file: ../../tests/theia-problems-view.test.ts (2m)
[playwright]   Consider splitting slow test files to speed up parallel execution
[playwright] 
[playwright]   10 failed
[playwright]     ../../tests/theia-explorer-view.test.ts:46:9 › Theia Explorer View › should be possible to close and reopen it 
[playwright]     ../../tests/theia-explorer-view.test.ts:56:9 › Theia Explorer View › should show one folder named "sampleFolder" and one file named "sample.txt" 
[playwright]     ../../tests/theia-main-menu.test.ts:50:9 › Theia Main Menu › should return menu item by name 'New File' 
[playwright]     ../../tests/theia-preference-view.test.ts:30:9 › Preference View › should be visible and active after being opened 
[playwright]     ../../tests/theia-preference-view.test.ts:37:9 › Preference View › should be able to read, set, and reset String preferences 
[playwright]     ../../tests/theia-problems-view.test.ts:30:9 › Theia Problems View › should be visible and active after being opened 
[playwright]     ../../tests/theia-problems-view.test.ts:37:9 › Theia Problems View › should be opened at the bottom and have the title 'Problems' 
[playwright]     ../../tests/theia-quick-command.test.ts:34:9 › Theia Quick Command › should show quick command palette 
[playwright]     ../../tests/theia-quick-command.test.ts:39:9 › Theia Quick Command › should trigger 'About' command after typing 
[playwright]     ../../tests/theia-quick-command.test.ts:53:9 › Theia Quick Command › should trigger 'Toggle Explorer View' command after typing 
[playwright]   10 skipped
[playwright]   28 passed (11m)
```

The runtime was quite long - at least the reported 11 min - and tests that can't be run in a variety of environments are not very productive.

_Originally posted by @colin-grant-work in https://github.com/eclipse-theia/theia/discussions/10790#discussioncomment-2245940_

**Comment by JonasHelming** [comment] 2022-02-24 19:41
@planger

**Comment by paul-marechal** [comment] 2022-02-24 20:39
Duplicate of https://github.com/eclipse-theia/theia/issues/10793

**Closed by paul-marechal** 2022-02-24 20:39 UTC
