### ISSUE TITLE
ci: failing on "editor.action.quickFix"

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#7678] opened 2020-04-27 21:01 UTC
### Bug Description:

CI keeps failing because of some "editor.action.quickFix" test.

First commit with this issue: https://github.com/eclipse-theia/theia/commit/bea6be60159f87ff31b0d9553e18dccec3baf637

- https://travis-ci.com/github/eclipse-theia/theia/jobs/323881311#L10525
- https://travis-ci.com/github/eclipse-theia/theia/jobs/323710626#L15580

### Steps to Reproduce:

I don't know, running tests on Linux maybe? Am currently on Windows, could not see the error.

### Additional Information

- Operating System: Linux
- Theia Version: 1.0.0

**Comment by akosyakov** [comment] 2020-04-28 06:28
Duplicate of https://github.com/eclipse-theia/theia/issues/7635

**Closed by akosyakov** 2020-04-28 06:28 UTC
Labels: bug, ci
