### ISSUE TITLE
Two preview buttons for Markdown

### ISSUE THREAD

**Issue by gbodeen** [eclipse-theia/theia#9214] opened 2021-03-17 15:55 UTC
### Bug Description:

With a Markdown file open, the tab bar has two buttons both labeled "Open Preview to the Side". They both work. One comes from the `@theia/preview` package, and the other comes from the `vscode-builtin-markdown` & `vscode-builtin-markdown-language-features` plugins.

![image](https://user-images.githubusercontent.com/20653241/111496043-ef0f1600-870d-11eb-8729-5a30973bb312.png)

The MarkdownPreviewHandler in `@theia/preview` may be unnecessary at this time.

### Steps to Reproduce:

1. Launch Theia & open a Markdown file in the editor.

### Additional Information

- Operating System: RHEL 7
- Theia Version: current `master` branch

**Comment by vince-fugnitto** [comment] 2021-03-17 16:01
@gbodeen thank you for reporting the issue, it is a duplicate of https://github.com/eclipse-theia/theia/issues/6984 and not a bug.
For your own application, you would either use `@theia/preview` or the builtin. We include both in the examples for test purposes.

**Closed by vince-fugnitto** 2021-03-17 16:01 UTC
Labels: builtins, preview
