### ISSUE TITLE
Cannot Stop "Hosted Instance" on Windows

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#8428] opened 2020-08-25 08:43 UTC
Stopping an instance of the "Hosted Plugin" support has no effect: when you try to start it again, the system refuses to start the instance because it's already running

### Steps to Reproduce:
Running the browser version of Theia:

1. Run the command "Hosted Plugin: Start Instance"
2. Wait until a second Theia browser tab opens
3. Run the command "Hosted Plugin: Stop Instance"
4. Wait until the status bar says the instance is stopped
5. Run the command "Hosted Plugin: Start Instance"
6. Observe: you get a dialog saying the hosted instance is already running

In the log of the Theia back end process, you can see the the log output:

```
root ERROR Error: spawn kill ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

### Additional Information

`hosted-instance-manager.ts` has the following code:
```
                const args = ['-SIGTERM', this.hostedInstanceProcess.pid.toString()].concat(children.map((p: any) => p.PID));
                cp.spawn('kill', args);
```
Which obviously will not work on Windows. 

- Operating System: Windows
- Theia Version: 1.4 (master as of today)

**Comment by rayncc** [comment] 2020-09-12 00:53
That's correct.
change
```
cp.spawn('kill', args)
```
to
```
cp.spawn('powershell', 'kill', args)
```

will work.

**Comment by danarad05** [comment] 2020-10-27 14:59
@tsmaeder @amiramw @DoroNahari 

1. this issue is duplicate of https://github.com/eclipse-theia/theia/issues/5692
2. As I'm working on #4016 I would like to fix that also. Please assign it to me.

Thanks,
Dan

**Closed** 2020-11-15 19:07 UTC
Labels: OS/Windows, bug, plug-in system
