### ISSUE TITLE
Menu items need to be clicked twice to display the drop-down menu

### ISSUE THREAD

**Issue by Markingit** [eclipse-theia/theia#14651] opened 2024-12-19 02:04 UTC
### Bug Description:
After clicking the search area or source control area on the left, click the menu item. need to click twice to display the drop-down menu list.
### Steps to Reproduce:

![lQHPKG-w6W9uaE3NA6nNB3ywRLKXzoivkJoHSMdTm6hYAA_1916_937](https://github.com/user-attachments/assets/b82d698d-38d8-41ee-bc86-70e78f7cf708)

### Additional Information

- Operating System:Windows
- Theia Version:1.56.2

**Comment by JonasHelming** [comment] 2024-12-19 07:08
@rschnekenbu

**Comment by rschnekenbu** [comment] 2024-12-19 08:43
Thanks for reporting this, @Markingit!

I was able to reproduce the issue on the Electron version of Theia on Windows (versions 1.56.2 and 1.57).
For the browser version, I observed the same behavior on the first click when running on Ubuntu 22.04. However, this issue doesn’t occur on the Electron version when using Linux.

Further investigation will be needed to pinpoint the cause.

**Comment by cristiandmonda** [comment] 2024-12-19 08:53
Could this be the same as #14002?

**Comment by rschnekenbu** [comment] 2024-12-19 08:59
yes, this look like definitely as a duplicate of #14002. I will close it in favor of the original one, and I will add it to the Theia IDE Epic issue

**Closed by rschnekenbu** 2024-12-19 08:59 UTC
