### ISSUE TITLE
Task terminal is not appeared for simple tasks

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-theia/theia#7117] opened 2020-02-10 12:20 UTC
### Description
 

Task terminal cannot be opened when task command runs very fast.

Video demonstrating the issue https://www.youtube.com/watch?v=KljOipWyVG4

### Reproduction Steps

Run Theia locally, create `.theia/tasks.json` with following content and run `List...` task.
```json
{
    "tasks": [
        {
            "type": "shell",
            "label": "List...",
            "command": "ls -la",
            "problemMatcher": []
        }
    ]
}
``` 

**OS and Theia version:**
Latest linux mint

**Comment by vince-fugnitto** [comment] 2020-02-10 12:43
Duplicate of #2961?

**Comment by vitaliy-guliy** [comment] 2020-02-10 12:55
@vince-fugnitto it looks yes. Should we close it?

**Comment by vince-fugnitto** [comment] 2020-02-10 12:58
> @vince-fugnitto it looks yes. Should we close it?

I think so, we already have the original issue with some previous discussions.
Overall, it looks like the `process` extension needs further improvements in order to properly support the output of short lived tasks.

**Closed by vince-fugnitto** 2020-02-10 12:58 UTC
Labels: process, tasks
