### ISSUE TITLE
Reference View State Restoration is Buggy

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#9363] opened 2021-04-15 21:20 UTC
### Bug Description:

When the reference view widget restores state, the restoration is only partial:

![image](https://user-images.githubusercontent.com/62660806/114939507-24d71580-9e06-11eb-9092-dfeb4676a3e3.png)

You can see that before I refreshed the window, I had 6 results in 3 files, but now none are shown.

### Steps to Reproduce:

1. Open a TS file and find a symbol with references to it in other files.
2. Invoke 'Show all references'
3. See that it reports the number of results and the number of files that contain them, as well as showing a tree view of the results.
4. Refresh the window.
5. See that the result counts persist, but the results are gone.

### Additional Information

- Operating System: RHEL
- Theia Version: 8b9fb43c763f2f1d179f9839ef993d7218d99073

**Comment by colin-grant-work** [comment] 2021-04-26 16:15
For reference, VSCode's behavior is just to close the reference view entirely between sessions, even if it was open when you closed the application.

**Comment by vince-fugnitto** [comment] 2023-03-17 14:31
Closing as duplicate of https://github.com/eclipse-theia/theia/issues/7336.

**Closed by vince-fugnitto** 2023-03-17 14:31 UTC
Labels: bug, plug-in system
