### ISSUE TITLE
TypeError: r.SemanticTokensLegend is not a constructor

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7910] opened 2020-05-27 13:42 UTC
### Bug Description:
I noticed this error when I first open a typescript file on the console. 
"r.SemanticTokensLegend is not a constructor"

### Steps to Reproduce:

1. Star Theia in a workspace
2. Open any "*.ts" file    i.e. quick-input-service.ts
3. Look at the console, the error is reported

Logs:
root ERROR [hosted-plugin: 13119] Promise rejection not handled in one second: TypeError: r.SemanticTokensLegend is not a constructor , reason: TypeError: r.SemanticTokensLegend is not a constructor
root ERROR [hosted-plugin: 13119] With stack trace: TypeError: r.SemanticTokensLegend is not a constructor
    at a.getLegend (/home/lmcbout/theia/stable/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:182974)
    at s.i.VersionDependentRegistration [as _doRegister] (/home/lmcbout/theia/stable/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:182814)

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: Latest commit 99a7aa3c10e00de269329e48b0929fb5b7301dd7

**Comment by akosyakov** [comment] 2020-05-27 13:53
duplicate of https://github.com/eclipse-theia/theia/issues/7840

**Closed by akosyakov** 2020-05-27 13:53 UTC
Labels: bug, typescript
