### ISSUE TITLE
blockchain-vscode-extension : Welcome page and tutorials do not render correctly

### ISSUE THREAD

**Issue by christinesu12** [eclipse-theia/theia#8549] opened 2020-09-23 02:22 UTC
IBM-Blockchain/blockchain-vscode-extension - Welcome page and tutorials do not render correctly

blockchain-vscode-extension : Welcome page and tutorials do not render correctly
![theia-blockchain-home](https://user-images.githubusercontent.com/50400404/93957068-0d5f0f00-fd86-11ea-9aad-e00cce609334.png)
![theia-blockchain-pre](https://user-images.githubusercontent.com/50400404/93957084-16e87700-fd86-11ea-9ec7-e844a54ff21a.png)

**Comment by vince-fugnitto** [comment] 2020-09-23 12:32
@christinesu12 thank you for the issue, in the future please respect the issue template and provide as much detail as possible so the project is able to better help you. 

Do you mind updating the issue with the following?:
- link to the actual extension
- steps to reproduce the bug (`browser` or `electron` example application?)
- include any console logs in the issue (if the view fails to render, it is likely that some output is generated in the console)

I suspect it may have to do with configuring [`webviews`](https://github.com/eclipse-theia/theia/pull/6465#issuecomment-557494879), and providing additional information will help with the investigation.

**Comment by christinesu12** [comment] 2020-09-24 01:57
1.extension - 
       https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases/download/v2.0.0-beta.7/ibm-blockchain-platform-2.0.0-beta.7.vsix
       https://open-vsx.org/api/vscode/markdown-language-features/1.39.1/file/vscode.markdown-language-features-1.39.1.vsix
       https://github.com/IBM/vscode-ibmcloud-account/releases/download/v1.0.2/ibmcloud-account-1.0.2.vsix
2.browser
3. The server IP address of 7310ff67-f4be-44b9-b8b1-5e885e582d32.webview.10.78.153.145 cannot be found.

**Comment by akosyakov** [comment] 2020-09-24 04:11
I don't think it is a bug in Theia. I looks like the point 2 from a link referenced by @vince-fugnitto is not satisfied.

**Comment by Techevan** [comment] 2021-01-20 08:04
This happens to my vscode extension / plugin as well. In webview panel, giving error like: 
bd7f319d-a892-49fc-8473-4a8a4e1e38d0.webview.10.236.xxx.xxx’s server IP address could not be found.

I build theia in docker and using docker file in theia-app. This plugin works fine on GitPod.

**Comment by Not-Leave-Regrets** [comment] 2021-02-08 09:34
> This happens to my vscode extension / plugin as well. In webview panel, giving error like:
> bd7f319d-a892-49fc-8473-4a8a4e1e38d0.webview.10.236.xxx.xxx’s server IP address could not be found.
> 
> I build theia in docker and using docker file in theia-app. This plugin works fine on GitPod.

This happens to my theia extension / plugin as well , How did you solve it?

**Comment by tincopper** [comment] 2021-07-02 07:47
I also encountered this problem in the browser, but using localhost is normal, how do you solve it?

**Comment by tincopper** [comment] 2021-07-02 07:48
> This happens to my vscode extension / plugin as well. In webview panel, giving error like:
> bd7f319d-a892-49fc-8473-4a8a4e1e38d0.webview.10.236.xxx.xxx’s server IP address could not be found.
> 
> I build theia in docker and using docker file in theia-app. This plugin works fine on GitPod.

I also encountered this problem in the browser, but using localhost is normal, how do you solve it?

**Comment by luxingxiao** [comment] 2024-04-17 09:49
> > This happens to my vscode extension / plugin as well. In webview panel, giving error like:我的 vscode 扩展/插件也会发生这种情况。在 webview 面板中，给出如下错误：
> > bd7f319d-a892-49fc-8473-4a8a4e1e38d0.webview.10.236.xxx.xxx’s server IP address could not be found. 找不到bd7f319d-a892-49fc-8473-4a8a4e1e38d0.webview.10.236.xxx.xxx的服务器IP地址。
> > I build theia in docker and using docker file in theia-app. This plugin works fine on GitPod.我在 docker 中构建 theia 并在 theia-app 中使用 docker 文件。这个插件在 GitPod 上运行良好。
> 
> I also encountered this problem in the browser, but using localhost is normal, how do you solve it?我在浏览器中也遇到了这个问题，但是使用localhost就正常了，请问怎么解决呢？

+1

**Comment by msujew** [comment] 2024-05-18 19:39
@luxingxiao Are you using `localhost`, or some IP address? Theia's webviews don't work on plain IPs, due to how we use subdomains (which aren't supported with plain IPs).

I would close this issue, as the webviews not working when serving Theia on a plain IP address is expected. Please use a service such as `nip.io` to get a domain name for your IP.

**Closed by msujew** 2024-05-18 19:39 UTC
Labels: vscode, :thinking: needs more info
