### ISSUE TITLE
Java Dependency Icon duplicate issue 

### ISSUE THREAD

**Issue by Flasharsh** [eclipse-theia/theia#13591] opened 2024-04-11 10:30 UTC
### Bug Description:
vscode-java-dependency extension icons are getting added multiple times in the toolbar menu like on terminal side , project explorer menu debug toolbar  

Check attached images for more bug information
![Screenshot 2024-04-11 155621](https://github.com/eclipse-theia/theia/assets/120726640/f85502a6-ba20-42c4-a99f-1b6f1045818f)

### Steps to Reproduce:

1. Java Project Extension Run some java files 
2. Those icons will register everywhere in the toolbar menu. It was working perfectly in theia 1.27 Update but not in 1.48

### Additional Information

- Theia Version: 1.48

**Comment by msujew** [comment] 2024-04-11 10:34
Duplicate of https://github.com/eclipse-theia/theia/issues/13375.

**Closed by msujew** 2024-04-11 10:34 UTC
