### ISSUE TITLE
Don't allow duplicate editors to exist in the same group

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#10409] opened 2021-11-11 23:18 UTC
### Bug Description:
When splitting an editor horizontally it opens the second instance in a new editor group (tabbar). Currently, if you drag the second editor back into the same group as the first editor you end up with two identical editors in the same tabbar. In VSCode, the second editor is automatically closed so you don't end up with something like this:

![image](https://user-images.githubusercontent.com/62660714/141382366-9c08a219-fa39-4228-844e-6d62f759fac8.png)

### Steps to Reproduce:

1. Open an editor
2. Split it horizontally or vertically
3. Drag the second instance into the same tabbar as the first editor
4. Observe that you end up with multiple listings for the same editor in the open editors view and that all editors are allowed to exist on the same tabbar
5. Try this in VSCode and observe that the second instance is automatically closed

### Additional Information

- Operating System: Linux
- Theia Version: master

**Comment by vince-fugnitto** [comment] 2023-03-06 17:16
I believe the issue is fixed with https://github.com/eclipse-theia/theia/pull/12147. If we split an editor and attempt to add it to a group that already has the editor the editor is closed.

**Closed by vince-fugnitto** 2023-03-06 17:16 UTC
Labels: editor, open-editors
