### ISSUE TITLE
[docker] Error: write EPIPE after the backend start

### ISSUE THREAD

**Issue by jopit** [eclipse-theia/theia#2013] opened 2018-06-01 15:26 UTC
We have a developer who is seeing the following in the logs when running 0.3.10 in a docker container.
```
Starting server worker...

Server worker has been started. [ID: 1 | PID: 13]

Server worker is ready to accept messages. [ID: 1 | PID: 13]

{"name":"Theia","hostname":"86596cfdc6","pid":13,"level":30,"msg":"Theia app listening on http://0.0.0.0:4191. []","time":"2018-06-01T12:37:37.162Z","v":0}

{"name":"Theia","hostname":"86596cfdc6","pid":13,"level":50,"msg":"Uncaught Exception:  [ 'Error: write EPIPE' ]","time":"2018-06-01T12:38:39.746Z","v":0}

{"name":"Theia","hostname":"86596cfdc6","pid":13,"level":50,"msg":"Error: write EPIPE\n    at _errnoException (util.js:1022:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14) []","time":"2018-06-01T12:38:39.747Z","v":0}
```
Looking in my local theia build, the only `net.js` files are
```
node_modules/pn/net.js
node_modules/node-libs-browser/mock/net.js
```
neither of which has anywhere near 800 lines.

Any Ideas on what could be wrong, or how to debug this?

**Comment by kittaakos** [comment] 2018-06-01 17:56
Which docker image? This one [`docker pull theiaide/theia`](https://hub.docker.com/r/theiaide/theia/)?

It is from node: https://github.com/nodejs/node/blob/dce6d53e6b0c8dfc72eaaf096f7a2ebed775e5b7/lib/net.js#L817

> who is seeing the following in the logs

Did it cause any side-effects, malfunction or backend stop?

> Any Ideas on what could be wrong

It is hard to tell anything from these few lines of outputs. Can you share the rest of the logs, if there is any?

**Comment by jopit** [comment] 2018-06-01 19:37
It's this image: `docker pull ibmcom/microclimate-theia:1805`

The person who's seeing the error is running this in a Kubernetes pod.  The docker image is crashing at around the time the error occurs.  Unfortunately I don't have any more logs, which is making it really hard to figure out what's going on.

`Error: write EPIPE` indicates a write on a pipe, socket, or FIFO for which there is no process to read the data.  If somebody hit the URL for Theia, and then closed the socket before Theia finished writing the response, would that cause this error?  Would Theia handle that gracefully, or would it crash?

**Comment by vince-fugnitto** [comment] 2021-03-05 13:54
Closing since the issue is quite old, and there is unfortunately not enough information to easily reproduce or debug the issue as is.

**Closed by vince-fugnitto** 2021-03-05 13:54 UTC
Labels: docker, question
