### ISSUE TITLE
editor/title buttons don't show if file is opened as "preview"

### ISSUE THREAD

**Issue by DanTup** [eclipse-theia/theia#9388] opened 2021-04-21 13:18 UTC
I'm not sure if this is intended, but the buttons don't show up in the editor title unless the file is properly "open". If you just click once to open in "preview" mode, they don't show:

<img width="335" alt="Screenshot 2021-04-21 at 14 17 17" src="https://user-images.githubusercontent.com/1078012/115560341-67886a00-a2ac-11eb-87d4-e8b82c20114a.png">

<img width="337" alt="Screenshot 2021-04-21 at 14 17 10" src="https://user-images.githubusercontent.com/1078012/115560336-66efd380-a2ac-11eb-8541-33d39559b713.png">

**Comment by vince-fugnitto** [comment] 2021-04-21 13:44
@DanTup thank you for reporting the issue, it is a duplicate of https://github.com/eclipse-theia/theia/issues/3579.

**Closed by vince-fugnitto** 2021-04-21 13:44 UTC
Labels: duplicate, editor-preview

**Comment by DanTup** [comment] 2021-04-21 13:45
@vince-fugnitto ah, thanks! I did try searching but guess I didn't use good terms 😞
