### ISSUE TITLE
vscode extension view/title do not work normally

### ISSUE THREAD

**Issue by huzhixiao** [eclipse-theia/theia#13490] opened 2024-03-14 07:29 UTC
### Bug Description:

VSCode extension view/title contribution do not work normally
### Steps to Reproduce:

1. Developing VS Code Extensions in a Theia Project(https://theia-ide.org/docs/authoring_vscode_extensions/#developing-vs-code-extensions-in-a-theia-project)
2. provide contribution with vscode extension package.json
```json
  "contributes": {
    "views": {
      "scm": [
        {
          "id": "taskList",
          "name": "任务列表"
        }
      ]
    },
    "viewsWelcome": [
      {
        "view": "taskList",
        "contents": "没有发现任务\n[刷新](command:tasks.refresh)"
      }
    ],
    "menus": {
      "view/title": [
        {
          "command": "taskList.refresh",
          "group": "navigation",
          "when": "view == taskList"
        },
        {
          "command": "taskList.filter",
          "group": "navigation@4",
          "when": "view == taskList && taskListVisible"
        }
      ]
    },
    "commands": [
      {
        "command": "taskList.refresh",
        "title": "刷新",
        "icon": "$(refresh)"
      },
    ]
  },
```
3. click treeItem
4. refresh button will be pined on all widget

![image](https://github.com/eclipse-theia/theia/assets/17584383/65cc8889-2766-4bdb-8547-aad56ad004c5)

**Comment by msujew** [comment] 2024-03-15 14:37
Thanks for the report, but I believe this is a duplicate of https://github.com/eclipse-theia/theia/issues/13375.

**Closed by msujew** 2024-03-15 14:37 UTC
