### ISSUE TITLE
[vscode-plugin] Metals can't find java 8

### ISSUE THREAD

**Issue by captainwasabi** [eclipse-theia/theia#4261] opened 2019-02-06 01:48 UTC
https://marketplace.visualstudio.com/items?itemName=scalameta.metals#overview

it's looking for  a configuration setting metals.javaHome

**Comment by tsmaeder** [comment] 2019-02-06 10:26
@captainwasabi could you add some additional info like a stack trace? What are you doing and how does it fail?

**Comment by captainwasabi** [comment] 2019-02-06 13:07
Not much else to tell. It registers,  but just a bit after startup puts up a message that it can't find java8 and to set the Java Home setting, which isn't the SSA e one that is already in Theia.  Looking in their code they are looking for a metals.javaHome somewhere. 

---- From: "Thomas Mäder" <notifications@github.com> -- Sent: 2/6/19 - 5:26 AM ----

**Comment by kamilkloch** [comment] 2019-04-17 10:30
I just tried to follow https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions to check Metals. (Metals configuration already contains entry "metals.javaHome": "/usr/lib/jvm/java-8-oracle").

I stumbled on the same issue while opening Theia in the browser: `Unable to find Java 8 home. To fix this problem, update the 'Java Home' setting to point to a Java 8 home directory`.

Clicking `Open Settings` button ends in 
```
root ERROR [hosted-plugin: 28263] (node:28263) UnhandledPromiseRejectionWarning: Error: The command 'workbench.action.openSettings' cannot be executed. There are no active handlers available for the command. (args: [{"_isCancelled":false}])
    at CommandRegistry.<anonymous> (http://localhost:3000/bundle.js:97680:31)
    at step (http://localhost:3000/bundle.js:97487:23)
    at Object.next (http://localhost:3000/bundle.js:97468:53)
    at http://localhost:3000/bundle.js:97462:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/command.js.__awaiter (http://localhost:3000/bundle.js:97458:12)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (http://localhost:3000/bundle.js:97667:16)
    at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (http://localhost:3000/82.bundle.js:4661:72)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/82.bundle.js:861:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/82.bundle.js:846:41)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.receiveRequest (http://localhost:3000/82.bundle.js:808:45)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.receiveOneMessage (http://localhost:3000/82.bundle.js:782:22)
    at http://localhost:3000/82.bundle.js:715:89
    at http://localhost:3000/82.bundle.js:887:17
    at http://localhost:3000/bundle.js:98266:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:98281:39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:98369:29)
    at Object.postMessage (http://localhost:3000/82.bundle.js:4193:32)
    at JsonRpcProxyFactory.<anonymous> (http://localhost:3000/bundle.js:99948:73)
    at step (http://localhost:3000/bundle.js:99778:23)
    at Object.next (http://localhost:3000/bundle.js:99759:53)
    at http://localhost:3000/bundle.js:99753:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/messaging/proxy-factory.js.__awaiter (http://localhost:3000/bundle.js:99749:12)
    at JsonRpcProxyFactory.../../packages/core/lib/common/messaging/proxy-factory.js.JsonRpcProxyFactory.onRequest (http://localhost:3000/bundle.js:99942:16)
    at http://localhost:3000/bundle.js:99905:48
    at handleRequest (http://localhost:3000/bundle.js:74609:27)
    at processMessageQueue (http://localhost:3000/bundle.js:74500:17)
    at http://localhost:3000/bundle.js:74490:13
    at run (http://localhost:3000/bundle.js:71495:13)
    at runIfPresent (http://localhost:3000/bundle.js:71524:21)
    at onGlobalMessage (http://localhost:3000/bundle.js:71564:17)

root ERROR [hosted-plugin: 28263] (node:28263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by akosyakov** [comment] 2019-12-02 06:02
If someone investigates what is the root cause it would be helpful.

**Comment by vince-fugnitto** [comment] 2022-06-02 12:34
I gave this a quick try this morning and it works fine for me, the extension properly reads my `JAVA_HOME` environment variable as documented in their readme, and the extension starts.

I'll close the issue since it is quite old, and if there are additional problems we should probably new issues to track them with full reproduction steps.

**Closed by vince-fugnitto** 2022-06-02 12:34 UTC
Labels: bug, help wanted, plug-in system, vscode, :thinking: needs more info
