### ISSUE TITLE
Theia loading blink to black theme and back

### ISSUE THREAD

**Issue by DoroNahari** [eclipse-theia/theia#7116] opened 2020-02-10 08:58 UTC
### Description
 
When on white theme and refreshing the browser the loading screen blinking from white to black and back to white again.

![loading-blinking](https://user-images.githubusercontent.com/24614792/74134954-14208380-4bf4-11ea-8170-1214dfa9f1c1.gif)
### Reproduction Steps

Run Theia on localhost. change to white theme and refresh the browser.

**OS and Theia version:**
master

**Comment by akosyakov** [comment] 2020-02-10 10:27
Duplicate of https://github.com/eclipse-theia/theia/issues/6999 It requires some refactoring to fix it cleanly: https://github.com/eclipse-theia/theia/issues/6999#issuecomment-579711945

**Closed** 2020-02-10 10:35 UTC
Labels: bug, monaco, theming
