### ISSUE TITLE
[java] rouge text on the screen

### ISSUE THREAD

**Issue by RDIL** [eclipse-theia/theia#7951] opened 2020-06-03 14:56 UTC
I have no idea how to reproduce this but here is what I do know:
* This was on a Gitpod workspace
* A Java file was opened
* I have never seen this before
* I am on a chromebook

![Screenshot 2020-06-03 at 10 57 58 AM](https://user-images.githubusercontent.com/34555510/83652922-2babbf80-a589-11ea-95f6-913d44913e68.png)

**Comment by vince-fugnitto** [comment] 2020-06-03 15:00
@RDIL thank you for the issue, it seems to be a duplicate of https://github.com/eclipse-theia/theia/issues/7411 which provides reproduction steps.

**Closed by vince-fugnitto** 2020-06-03 15:00 UTC
