### ISSUE TITLE
Run/Debug vscode extension from .vscode launcher

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8197] opened 2020-07-19 21:05 UTC
### Feature Description:

As a vscode extension developer I want to run/debug vscode extension from the same launch configuration "Run Extension" that runs on vscode.
I believe it is not possible in theia and one can only use the Hosted Plugin commands.

**Comment by akosyakov** [comment] 2020-07-27 07:00
a duplicate of https://github.com/eclipse-theia/theia/issues/4016

**Closed by akosyakov** 2020-07-27 07:00 UTC
Labels: vscode
