### ISSUE TITLE
[windows][edge] Cursor is never visible in the editors

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#1716] opened 2018-04-17 13:58 UTC
So one **cannot** edit the files. I ran into this in a Windows 10 image. Could be different on a "real" Windows.

Works from Chrome.

**Comment by akosyakov** [comment] 2018-04-17 14:00
Could you please check on monaco playground?

**Comment by kittaakos** [comment] 2018-04-17 14:14
The [monaco playground examples](https://microsoft.github.io/monaco-editor/playground.html) work on Windows from Edge.

**Comment by marcdumais-work** [comment] 2018-05-14 00:49
> I ran into this in a Windows 10 image. Could be different on a "real" Windows.

I see this issue on a physical windows 10 machine, using edge

**Comment by marcdumais-work** [comment] 2018-05-14 01:17
This comment https://github.com/theia-ide/theia/issues/1478#issuecomment-373134089 matches what I see on Windows, using edge. Probably same as reported here? (but distinct from #1478):

**Comment by JonasHelming** [comment] 2021-06-18 08:29
@marcdumais-work : Could you retest this, whether it still occurs?

**Comment by JonasHelming** [comment] 2021-08-06 07:58
@vince-fugnitto : I believe you are on Windows, too, could you retest with the latest version, please?

**Comment by vince-fugnitto** [comment] 2021-08-06 11:54
> @vince-fugnitto : I believe you are on Windows, too, could you retest with the latest version, please?

Unfortunately I'm on Ubuntu and macOS, @OmarSdt-EC do you mind verifying if the issue persists?

**Comment by msujew** [comment] 2021-08-06 12:05
@vince-fugnitto I just confirmed that the issue does not appear on Edge (Windows). But perhaps this is because I use the "new" chromium based Edge. Though, anyone who has automatically updated their Windows in the last year or two should have this new version as well.

**Comment by JonasHelming** [comment] 2021-08-06 14:39
I will close this then. There has been zero activity for 2 years, so very likely, this wont be fixed. People should rather update their browser. Please reopen if you disagree.

**Closed by JonasHelming** 2021-08-06 14:39 UTC
Labels: bug, editor, OS/Windows
