### ISSUE TITLE
[monaco][quick-open] Using `fuzzySort: true` throws an error

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8012] opened 2020-06-15 14:03 UTC
### Bug Description:

I can see the following error when I use the `fuzzySort: true` properties for the quick open service:

```
Uncaught (in promise) TypeError: monaco.quickOpen.compareEntries is not a function
    at monaco-quick-open-service.ts:358
    at Array.sort (<anonymous>)
    at MonacoQuickOpenControllerOptsImpl.push.../../packages/monaco/lib/browser/monaco-quick-open-service.js.MonacoQuickOpenControllerOptsImpl.toOpenModel (monaco-quick-open-service.ts:358)
    at monaco-quick-open-service.ts:369
    at Object.onType (api-samples-frontend-module.ts:45)
    at MonacoQuickOpenControllerOptsImpl.push.../../packages/monaco/lib/browser/monaco-quick-open-service.js.MonacoQuickOpenControllerOptsImpl.onType (monaco-quick-open-service.ts:368)
    at MonacoQuickOpenService.<anonymous> (monaco-quick-open-service.ts:299)
    at step (monaco-quick-open-service.ts:15)
    at Object.next (monaco-quick-open-service.ts:15)
    at monaco-quick-open-service.ts:15
```

Here is the code that produces the error:
```diff
diff --git a/examples/api-samples/src/browser/api-samples-frontend-module.ts b/examples/api-samples/src/browser/api-samples-frontend-module.ts
index 1a397ab..65cefd1 100644
--- a/examples/api-samples/src/browser/api-samples-frontend-module.ts
+++ b/examples/api-samples/src/browser/api-samples-frontend-module.ts
@@ -14,15 +14,43 @@
  * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
  ********************************************************************************/
 
-import { ContainerModule } from 'inversify';
+import { injectable, inject, ContainerModule } from 'inversify';
 import { bindDynamicLabelProvider } from './label/sample-dynamic-label-provider-command-contribution';
 import { bindSampleUnclosableView } from './view/sample-unclosable-view-contribution';
 import { bindSampleOutputChannelWithSeverity } from './output/sample-output-channel-with-severity';
 import { bindSampleMenu } from './menu/sample-menu-contribution';
+import { FrontendApplicationContribution, QuickOpenService, QuickOpenItem, QuickOpenItemOptions } from '@theia/core/lib/browser';
+import { CommandRegistry } from '@theia/core/lib/common';
 
 export default new ContainerModule(bind => {
     bindDynamicLabelProvider(bind);
     bindSampleUnclosableView(bind);
     bindSampleOutputChannelWithSeverity(bind);
     bindSampleMenu(bind);
+    bind(FrontendApplicationContribution).to(MonacoFuzzySortQuickOpenServiceContribution).inSingletonScope();
 });
+
+@injectable()
+export class MonacoFuzzySortQuickOpenServiceContribution implements FrontendApplicationContribution {
+
+    @inject(CommandRegistry)
+    protected readonly commandRegistry: CommandRegistry;
+
+    @inject(QuickOpenService)
+    protected readonly quickOpenService: QuickOpenService;
+
+    onStart(): void {
+        const model = {
+            onType(lookFor: string, acceptor: (items: QuickOpenItem<QuickOpenItemOptions>[]) => void): void {
+                acceptor(['one', 'two', 'three'].map(label => new QuickOpenItem({ label })));
+            }
+        };
+        this.commandRegistry.registerCommand({ id: 'quick-open-sample-with-monaco-fuzzy-search', label: 'API Sample: Quick Open with fuzzy sort' }, {
+            execute: () => this.quickOpenService.open(model, { fuzzySort: true })
+        });
+        this.commandRegistry.registerCommand({ id: 'quick-open-sample', label: 'API Sample: Quick Open' }, {
+            execute: () => this.quickOpenService.open(model, {})
+        });
+    }
+
+}
```

`monaco.quickOpen` does not have `compareEntries` property.
![Screen Shot 2020-06-15 at 16 01 56](https://user-images.githubusercontent.com/1405703/84666671-ab3e7480-af21-11ea-82af-857003d94f6e.jpg)

### Steps to Reproduce:

![screencast 2020-06-15 15-58-40](https://user-images.githubusercontent.com/1405703/84666361-44b95680-af21-11ea-94a4-50d33a33362c.gif)

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by akosyakov** [comment] 2020-06-15 14:09
duplicate of https://github.com/eclipse-theia/theia/issues/7899

**Closed by akosyakov** 2020-06-15 14:09 UTC
