### ISSUE TITLE
Uncaught (in promise) Error: Request 'resize' failed

### ISSUE THREAD

**Issue by monaka** [eclipse-theia/theia#6909] opened 2020-01-17 23:58 UTC
### Description

Sometimes I got the error like this.

```
construct.js:30 Uncaught (in promise) Error: Request 'resize' failed
    at Proxy.<anonymous> (proxy-factory.ts:232)
    at n.resizeTerminalProcess (remote-terminal-widget.ts:272)
    at n.<anonymous> (remote-terminal-widget.ts:142)
    at bundle.js:8
    at Object.next (bundle.js:8)
    at bundle.js:8
    at new Promise (<anonymous>)
    at s (bundle.js:8)
    at remote-terminal-widget.ts:141
```

Actually my environment is Che-Theia. But this will be caused by Theia component.

### Reproduction Steps

I've not prepared reproduction steps yet.

**OS and Theia version:**

`Che-Theia@e148767 using Theia@10d526f`

**Diagnostics:**

**Comment by vince-fugnitto** [comment] 2020-01-18 00:31
It'd be nice to have proper reproduction steps before opening the issue so it can be properly investigated/validated. From the error logs it looks like it comes from a Che specific component `RemoteTerminalWidget` which extends Theia's `TerminalWidgetImpl`.

https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts#L272 should be verified first.

**Comment by akosyakov** [comment] 2020-01-18 01:54
Please transfer to che theia. There is no such component in Theia.

**Comment by monaka** [comment] 2020-01-18 02:45
@akosyakov The direct trigger is in Theia. 
https://github.com/eclipse-theia/theia/blob/6f1651655d879a2a00a30d6aa46eeb86f7834b13/packages/core/src/common/messaging/proxy-factory.ts#L232
I'm inspecting it and I agree it should be added an error handler to Che-Theia.
At the same, IMO, it have a room for improving API in Theia.

**Comment by vince-fugnitto** [comment] 2020-01-18 03:14
> @akosyakov The direct trigger is in Theia.
> https://github.com/eclipse-theia/theia/blob/6f1651655d879a2a00a30d6aa46eeb86f7834b13/packages/core/src/common/messaging/proxy-factory.ts#L232
> 
> 
> I'm inspecting it and I agree it should be added an error handler to Che-Theia now.
> At the same, IMO, it have a room for improving API in Theia.

It is a pretty generic error, something that should be handled properly by clients.
Please take the time to find reproduction steps if you truly believe the problem resides in Theia.

I'm closing the issue for the moment.

**Closed by vince-fugnitto** 2020-01-18 03:14 UTC
Labels: :thinking: needs more info, terminal

**Comment by akosyakov** [comment] 2020-01-18 11:19
@monaka if such error is indeed reproducible in Theia without RemoteTerminalWidget, please reopen with steps how to reproduce. but first authors of this widget should look for root cause of the error

**Comment by RomanNikitenko** [comment] 2020-01-20 08:30
@monaka 
thank you very much for reporting the issue, I created [the corresponding issue](https://github.com/eclipse/che/issues/15746) for `che` project.
