### ISSUE TITLE
Cross file editing bug

### ISSUE THREAD

**Issue by jgaiao** [eclipse-theia/theia#7566] opened 2020-04-14 12:01 UTC
### Description
While editing a tab (and the tab close button changes to the ball as expected), I go to another tab and start typing but doesn't enter in edit mode, so everything I type there reflects on the previous tab in edit mode.

### Reproduction Steps
Start writing on a file, and then go to another file and start writing on that one also without saving any. Doesn't always happen, but I would say 1 out of 20 (following the steps)

**OS and Theia version:**
On Ubuntu 16.04.5 LTS, and since the early versions of Theia. And still does it on 1.0 and 1.1.

**Comment by akosyakov** [comment] 2020-04-14 13:38
@jgaiao Could you provide steps to reproduce for Theia repo? I'm struggling to get it.

**Comment by jgaiao** [comment] 2020-04-14 16:07
@akosyakov I always update/install and build Theia from Yarn. And I disabled the preview, always pinned editor. Oh, and it's mainly on PHP files, with the vscode-builtin-php installed.

Another piece of information is that, I built an "Instance Launcher" that spawns Theia IDE instances on specific folders inside a RAID mounted main folder. Meaning, on this setup, we are several users spawning several instances at once. Not sure that matters, but just so you know hehe. (and it handles it well, just needed a small tweek on the plugin-ext to extract the .vsix to a different folder for each user, instead of globally)

Will run it on my PC and try to reproduce to a screencast when I get the chance. Never heard of screencast with keystrokes, is that a thing or you mean them separately? Waiting feedback on that to help as much as possible.

Thanks, and awesome work.

**Comment by akosyakov** [comment] 2020-04-15 07:27
> Never heard of screencast with keystrokes, is that a thing or you mean them separately? 

@elaihau @lmcbout @kittaakos Do you know how to record a gif (or video) which shows pressed keys as well?

**Comment by kittaakos** [comment] 2020-04-15 08:04
I use [`keycastr`](https://github.com/keycastr/keycastr) on macOS, and for the recording, I tend to use [`monosnap`](https://monosnap.com/welcome).

**Comment by jgaiao** [comment] 2020-04-15 09:24
Well, good news. With the help of a co-worker (one of the avid users of theia also) he was able to identify the exact steps o reproduce the bug on demand. They are as follows:

(all this with preview disabled, not sure with it turned on)

1. With no files opened, open one to edit and save it but don't close it.
2. Go to the explorer and click to open a second file, but don't focus this new file or click anything.
3. Press Ctrl+F to search and it opens the search on explorer instead of the file.
4. Write something on that explorer search, and close it manually.
5. Now focus that second file opened and try writing anything there, it is writing the first file.

(The first time I did this before recording, after all this I saved the first file and closed the buggy search opened on that file and on writing it would write the second file)

Here goes to screencast
[theia_cross_editing_bug.zip](https://github.com/eclipse-theia/theia/files/4480231/theia_cross_editing_bug.zip)

**Comment by lmcbout** [comment] 2020-04-15 11:34
I work on Ubuntu
For recording, I used " peek  " and to see the keys pressed, I start another application in the terminal. Like
     1- peek 
     2- key-mon --visible_click

**Comment by akosyakov** [comment] 2020-04-15 13:55
@jgaiao I've tried but could not reproduce :( there was a fix to `Ctrl+F` today, maybe it is related. Could you try on latest master?

**Comment by jgaiao** [comment] 2020-04-15 13:58
@akosyakov using yarn, will the "next" tag have that fix?

**Comment by akosyakov** [comment] 2020-04-15 14:12
@jgaiao It should

**Comment by jgaiao** [comment] 2020-04-15 14:35
@akosyakov Well..... the cross editing seems fixed now, dam coincidence! I was even using the 1.1 already, must have been that fix...... But on that note, noticed it still spawned a "buggy search" half visible on the first file spawned (like it is visible on video also). Worth opening another issue or how is it done? And thanks

**Comment by akosyakov** [comment] 2020-04-15 14:48
@jgaiao Yes, another issues sounds good. Please close this one if there are no issues with focus anymore.

**Closed** 2020-04-15 15:23 UTC
Labels: :thinking: needs more info, bug, editor
