### ISSUE TITLE
VS Code Extension API gap: menu contribution point "webview/context"

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#12829] opened 2023-08-11 17:59 UTC
### Bug Description:
A VS Code extension contributing a Webview can contribute to the view's context menu. By default, the menu has three items: Cut, Copy and Paste. To add to that, the extension can contribute as follows (in package.json):

```
  "contributes": {
    "commands": [
      {
        "command": "myext.helloWorld",
        "title": "Hello World"
      },
    ],
    "menus": {
      "webview/context": [
        {
           "command": "myext.helloWorld"
        }
      ]
    }
  },
```

Theia currently doesn't support this, as can be seen by the lack of `webview/context` [here](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/main/browser/menus/vscode-theia-menu-mappings.ts#L40)

### Steps to Reproduce:

git clone -b webview_panel_gap1 https://github.com/jcortell68/theiasandbox
cd theiasandbox
yarn
yarn start:electron

### Additional Information

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment] 2023-08-11 19:45
Thank you for opening the issue! Closing since it is a duplicate of https://github.com/eclipse-theia/theia/issues/12756.

**Closed by vince-fugnitto** 2023-08-11 19:45 UTC
