### ISSUE TITLE
[messaging] Move to separate npm package

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#1578] opened 2018-03-25 13:24 UTC
It would be nice to have the RPC proxy stuff and so on in a separated Theia-independent npm package, so one can use it in other applications, too.

**Comment by JonasHelming** [comment] 2021-02-18 08:04
I believe, this is a duplicate of https://github.com/eclipse-theia/theia/issues/1783 , hence closing this.
Please reopen in case you disagree.

**Closed by JonasHelming** 2021-02-18 08:04 UTC
