### ISSUE TITLE
quick pick not support multi step

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6193] opened 2019-09-16 02:45 UTC
### Description
![temp](https://user-images.githubusercontent.com/10203793/64931926-35ac5780-d86e-11e9-9e6e-94aac468aa7e.gif)

### Reproduction Steps

- install ext `vscode:extension/humao.rest-client`
- create http file `google.http`
```
GET http://google.com
```
- right click and select `Generate Code Snippet`
- select any language

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment] 2019-09-16 07:45
Possible duplicate of https://github.com/eclipse-theia/theia/issues/2182?

**Comment by 502647092** [comment] 2019-09-16 07:50
@kittaakos not
maybe it’s what I said is not clear
emm
this plugin gen code have many step
step1 select language
step2 select code template
but after select language next quick pick is not show

my English is not very good, sorry.

**Comment by kittaakos** [comment] 2019-09-16 07:54
> @kittaakos not

OK. Thanks for the update, @502647092!

**Comment by akosyakov** [comment] 2019-09-17 01:14
@502647092 Is it about multi step support? I thought it was implemented already. cc @JPinkney @vinokurig

**Comment by 502647092** [comment] 2019-09-17 01:19
@akosyakov  yes
I update Reproduction Steps

**Comment by vince-fugnitto** [comment] 2020-11-25 13:33
Closing in favor of https://github.com/eclipse-theia/theia/issues/8777.

**Closed by vince-fugnitto** 2020-11-25 13:33 UTC
Labels: bug, quick-open, vscode
