### ISSUE TITLE
Test View hides when I want it to focus

### ISSUE THREAD

**Issue by meysholdt** [eclipse-theia/theia#6832] opened 2020-01-06 15:24 UTC
### Description
The [test icon](https://github.com/eclipse-theia/theia/blob/c99cc1d574864d3ef4049775645313032b36b66d/packages/plugin-ext/src/main/browser/style/test.svg) disappears when I actually want to open the test view.

### Reproduction Steps
1. Ensure test icon is present next to the icons of File Explorer, Search, etc.
2. Focus the File Explorer. 
3. Click on Main Menu -> View -> Test.

Observe the Test Icon (and the View) to disappear. 
Expectation: The test view should get the focus.

**Comment by meysholdt** [comment] 2020-01-06 15:25
The Explorer and the Search view do not have this issue.

**Comment by vince-fugnitto** [comment] 2020-01-06 15:58
The widgets are toggle at the moment, something we discussed updating in the past https://github.com/eclipse-theia/theia/issues/6187

All the widgets have the same issue unfortunately but it was previously by design.
Closing as it is a duplicate of https://github.com/eclipse-theia/theia/issues/6187 which is more general.

**Closed by vince-fugnitto** 2020-01-06 15:58 UTC
