### ISSUE TITLE
Autocomplete for workspace-variable in launch.json

### ISSUE THREAD

**Issue by maksimr** [eclipse-theia/theia#8565] opened 2020-09-26 07:16 UTC
It would be nice to have autocomplete for defined [workspace-variables](https://github.com/eclipse-theia/theia/blob/8bf15dc1d9b186b11c1f954b4c51500e611d3072/packages/workspace/src/browser/workspace-variable-contribution.ts) when you edit launch.json

```json
"cwd": "${fil|}", // autosuggest file, fileBasename, fileDirname etc
```

**Comment by vince-fugnitto** [comment] 2020-11-20 18:22
@maksimr I believe it is already supported, for example:

![auto2](https://user-images.githubusercontent.com/40359487/99835972-66071a00-2b33-11eb-9f4e-8bfa777d7660.gif)

**Comment by maksimr** [comment] 2020-11-20 18:46
@vince-fugnitto hm... I have checked it doesn't work for me. I try to edit file `.theia/launch.json`
<img width="763" alt="image" src="https://user-images.githubusercontent.com/616193/99838195-c8830900-2b79-11eb-949f-cc061bb05753.png">

[Repository with this file](https://github.com/maksimr/playground)

**Comment by vince-fugnitto** [comment] 2020-11-20 18:57
> @vince-fugnitto hm... I have checked it doesn't work for me. I try to edit file [`.theia/launch.json`](https://github.com/maksimr/playground/blob/master/.theia/launch.json)


@maksimr please note that `gitpod` is a product based on the `theia` framework and may be using older versions of the framework's extensions, and/or may not include the necessary builtin extensions to support launch configurations.


I confirmed it worked from the `example-electron` example present in the framework's sources.

**Comment by maksimr** [comment] 2020-11-20 19:03
@vince-fugnitto got it, thanks!

**Comment by vince-fugnitto** [comment] 2020-11-25 14:08
Closing since the issue is confirmed to work on `master` (@DukeNgn also confirmed for me).
@maksimr if not already done so, you may want to open the issue directly on [gitpod](https://github.com/gitpod-io/gitpod/issues).

**Closed by vince-fugnitto** 2020-11-25 14:08 UTC
Labels: debug, help wanted, json
