### ISSUE TITLE
[auto-save] [performance] file read 3 extra times after stopping editing  and refreshing the browser

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#1225] opened 2018-02-07 19:44 UTC
When fixing issue #1185 , after completing the edition, I noticed that an extra 3 messages are sent to the browser to refresh the data in it, With large file, it makes the browser less responsive and for user with slow network, it will be unusable .

Trace added in the node-filesystem.resolveContent showing the filestat and time we return the message:
{"name":"Theia","hostname":"elxa8z6zp12","pid":5121,"level":30,"msg":"node-filesystem.resolveContent time: Wed Feb 07 2018 **14:18:50** GMT-0500 (EST)\t **size: 3000006**\t fileStamp: 1518031130827\t uri: file:///home/lmcbout/zz/folder50_3M/file33 []","time":"2018-02-07T19:18:50.880Z","v":0}
{"name":"Theia","hostname":"elxa8z6zp12","pid":5121,"level":30,"msg":"node-filesystem.resolveContent time: Wed Feb 07 2018 **14:18:51** GMT-0500 (EST)\t **size: 3000006**\t fileStamp: 1518031130827\t uri: file:///home/lmcbout/zz/folder50_3M/file33 []","time":"2018-02-07T19:18:51.605Z","v":0}
{"name":"Theia","hostname":"elxa8z6zp12","pid":5121,"level":30,"msg":"node-filesystem.resolveContent time: Wed Feb 07 2018 **14:18:52** GMT-0500 (EST)\t **size: 3000006**\t fileStamp: 1518031130827\t uri: file:///home/lmcbout/zz/folder50_3M/file33 []","time":"2018-02-07T19:18:52.263Z","v":0}

Small video to show what I was typing:
![peek 2018-02-07 11-18testkeyandnumbermessages2](https://user-images.githubusercontent.com/419051/35937482-57112a86-0c14-11e8-9bd6-12d24d8a1a1f.gif)

Finally, A screenshot showing the tree extra messages received on the browser side matching the traces above from the node side. The highlighted one is the initial message updating the data on the browser.

![repetitionmsgafterlasttyping](https://user-images.githubusercontent.com/419051/35937549-79dfc798-0c14-11e8-96d2-6cdcc038960f.png)

**Comment by lmcbout** [comment] 2018-02-07 20:01
Another observation. 
When the auto-save is "off", the node return 2 copies of the same data to to the browser, the first one is an update and the second one is an extra.
Trace from the node:
{"name":"Theia","hostname":"elxa8z6zp12","pid":5121,"level":30,"msg":"node-filesystem.resolveContent time: Wed Feb 07 2018 **14:55:53** GMT-0500 (EST)\t size: 3000010\t **fileStamp: 1518033353611**\t uri: file:///home/lmcbout/zz/folder50_3M/file33 []","time":"2018-02-07T19:55:53.721Z","v":0}
{"name":"Theia","hostname":"elxa8z6zp12","pid":5121,"level":30,"msg":"node-filesystem.resolveContent time: Wed Feb 07 2018 **14:55:54** GMT-0500 (EST)\t size: 3000010\t **fileStamp: 1518033353611**\t uri: file:///home/lmcbout/zz/folder50_3M/file33 []","time":"2018-02-07T19:55:54.881Z","v":0}

**Comment by marcdumais-work** [comment] 2018-02-07 20:04
@lmcbout Do you see this all the time? In my quick test, when I trigger the save manually (auto-save off), I typically see the file is saved then re-read once from the filesystem.

**Comment by lmcbout** [comment] 2018-02-07 20:08
Yes each time I press save, I see two messages coming back to the browser to refresh the data with about 1 sec apart.

**Comment by lmcbout** [comment] 2018-02-07 20:19
I have a video showing the frames coming to the browser. After selecting then "save", the time is 15:11:42.083 and I receive the data back with the following timestamp at 15:11:**42**.445 and 15:11:**43**.234
![peek _autosaveoff_2msgs](https://user-images.githubusercontent.com/419051/35939415-12db4d0a-0c1a-11e8-9b4d-18270fe3e629.gif)

**Comment by marcdumais-work** [comment] 2018-02-07 20:29
Is it possible you have 2 theia clients open?

**Comment by lmcbout** [comment] 2018-02-07 20:44
I though the same thing, possibility of two workspaces open, but I verified and I have only one workspace in one one browser available, the other browser is closed and no theia client.

**Comment by epatpol** [comment] 2018-03-19 19:37
@lmcbout can you still reproduce this issue?

**Comment by akosyakov** [comment] 2018-03-20 06:48
It should be fixed by https://github.com/theia-ide/theia/issues/1225

**Comment by lmcbout** [comment] 2018-03-20 12:07
After the file is loaded initially in front-end, here the message flow
1- Edit the file 
2- Save it (CTRL + s)
--> In the front end

**SEND -------------RECEIVE**
updateContent 
---------------------->result: (filestat)
exist
getFilestat
---------------------->true
---------------------->result: (filestat)
exist
getFilestat
---------------------->true
---------------------->result: (filestat)


This is after the patch from @akosyakov 
[file-resource] support incremental content updates
commit bace685a8a77ad1ddfe986f1663cd7e081376c6b

Even with large file, there is still some handshake but the data being transfer now is small (< 200 bytes).
This does not decrease the performance as before even with a few extra messages. If we can remove those messages, it would even be better, but we have to make sure we have the latest data available remains in sync between the f-e and the b-e. With small messages now ,  the performance will remain OK even if we do nothing.
The data update start at the highlighted message:
![issue1225](https://user-images.githubusercontent.com/419051/37653320-d789bf3c-2c14-11e8-9f2c-b201f426aa25.png)

**Comment by msujew** [comment] 2024-10-02 08:48
As far as I can tell, this seems to be fixed (as per https://github.com/eclipse-theia/theia/issues/1225#issuecomment-374574261).

**Closed by msujew** 2024-10-02 08:48 UTC
Labels: performance
