### ISSUE TITLE
Console output is sometimes lost in VSCode extensions

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-theia/theia#3035] opened 2018-10-01 11:22 UTC
For some VSCode extensions invoking `console.log()` has no effect. No log messages are present. 

For example, [vscode-JS-CSS-HTML-formatter](https://github.com/lonefy/vscode-js-css-html-formatter) has this problem.
But [vscode-css-formatter](https://github.com/aeschli/vscode-css-formatter) works as expected.

**Comment by JonasHelming** [comment] 2021-02-22 14:00
Hi and thank you for the report!
What exactly do you mean by "console.log()". I had a quick look at the sources of both extensions and both seem to not call "console.log()", but maybe I misunderstand the issue you report?

**Comment by JonasHelming** [comment] 2021-03-16 21:57
I am closing this issue, cause I was not able to reproduce this. Probably I misunderstood your request, sorry if that is the case. If the issue still persists, please comment on this issue and mention me!

**Closed by JonasHelming** 2021-03-16 21:57 UTC
Labels: plug-in system
