### ISSUE TITLE
Switching the menu bar causes the custom title to be misplaced

### ISSUE THREAD

**Issue by fly-bue** [eclipse-theia/theia#13311] opened 2024-01-25 02:22 UTC
### Bug Description:
Switching the menu bar causes the custom title to be misplaced.I found that there is no listening for switching menu bar events in the 'electron-menu-contribution.ts' file.I tried to solve this problem (see below), but cannot completely fix the issue.

```js
// packages\core\src\electron-browser\menu\electron-menu-contribution.ts

this.preferenceService.onPreferenceChanged(e => {
        if (e.preferenceName === 'window.menuBarVisibility') {
            setTimeout(() => {
                this.adjustTitleToCenter();
                // Waiting for menu bar generation
            }, 100);
        }
});
```
![image](https://github.com/eclipse-theia/theia/assets/54001753/6b82a9ec-5c4a-43a0-9d12-37e7cb53fc1a)

### Steps to Reproduce:
https://github.com/eclipse-theia/theia/assets/54001753/82f67d86-7f54-4b14-8476-7b4cd333e5ce

### Additional Information

- Operating System: Windows 11 家庭中文版
- Theia Version: master

**Comment by JonasHelming** [comment] 2024-01-25 07:48
"but cannot completely fix the issue." => could you describe what is missing in the fix?

**Comment by fly-bue** [comment] 2024-01-25 08:47
The problem occurs when reopening the IDE, an event should be listened to when the menu bar has finished rendering, I don't know if this event exists.

https://github.com/eclipse-theia/theia/assets/54001753/ef3a839a-1574-46c9-846a-6b07c35b9dff

**Comment by msujew** [comment] 2024-01-25 12:46
Hey @fly-bue, I can confirm the main issue (i.e. the incorrect behavior when changing the preference), but cannot reproduce the startup rendering issue:


https://github.com/eclipse-theia/theia/assets/4377073/c3da1f4f-3b77-4df8-8f0b-a04a5b3d2d48

Does it occur consistently? I cannot seem to reproduce it at all.

**Comment by fly-bue** [comment] 2024-01-26 02:48
Hey @msujew,It continues to occur on my computer. And we can find that clientWidth is incorrect. I think it is related to menu bar rendering.

![image](https://github.com/eclipse-theia/theia/assets/54001753/6b46ab0f-686e-448a-bd15-c38f906d547b)

The following code can solve my problem.
```js
 this.windowTitleService.onDidChangeTitle(title => {
    animationFrame(10).then(() => this.updateTitle(title));
});
```

**Comment by msujew** [comment] 2024-02-13 15:51
@fly-bue Does the fix also work if you run `animationFrame().then(() => this.updateTitle(title));`, or do you need more than one animation frame? If so, just waiting for a specific number of animationframes won't fix the issue.

**Closed** 2024-02-20 17:10 UTC
