### ISSUE TITLE
[Plugin-API] Apply timeline vscode plugin-API  

### ISSUE THREAD

**Issue by vinokurig** [eclipse-theia/theia#7683] opened 2020-04-28 12:56 UTC
The latest version of the vscode git plugin requires the [timeline](https://github.com/microsoft/vscode/blob/2e4d797e51f8c105cdcbef99a609df9ad1f71c8c/src/vs/vscode.proposed.d.ts#L1823-L1975) plugin API: https://github.com/microsoft/vscode/blob/c583456c3b5f9dcccfc7850384e85a9a157effbe/extensions/git/src/timelineProvider.ts#L7

### Feature Description:
see https://github.com/microsoft/vscode/issues/84297

**Comment by akosyakov** [comment] 2020-04-28 13:09
Duplicate of https://github.com/eclipse-theia/theia/issues/7577

**Closed by akosyakov** 2020-04-28 13:09 UTC
Labels: plug-in system, vscode
