### ISSUE TITLE
Disappearing icons in editors 

### ISSUE THREAD

**Issue by gbodeen** [eclipse-theia/theia#12305] opened 2023-03-14 20:08 UTC
### Steps to Reproduce:

1. Open several editor tabs.
2. Use the palette to switch the icon theme from `File Icons (Theia)` to something else and back.

before:
![image](https://user-images.githubusercontent.com/20653241/225123915-bb598e3a-ece5-4792-8225-639945604d6e.png)

after:
![image](https://user-images.githubusercontent.com/20653241/225124001-331ad5ad-29ea-4d95-aaba-639f6b3e8074.png)

Maybe related: the ellipsis icon (.codicon-ellipsis:before) in the top right of the File Explorer has gone missing.

### Additional Information

- Operating System: RHEL7
- Theia Version: master branch as of March 14th, 3PM Central

**Comment by vince-fugnitto** [comment] 2023-03-16 11:44
I believe it is a duplicate of https://github.com/eclipse-theia/theia/issues/11837.

**Closed** 2023-03-17 16:58 UTC
