### ISSUE TITLE
Dendron extension doesn't work 

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8900] opened 2020-12-24 12:30 UTC
### Bug Description:
Getting error when trying to initialize Dendron workspace

### Steps to Reproduce:

1. Install dendron extension (dendron.dendron) from Open VSX Registry
2. Ctrl + Shift + P
3. Dendron: Initialize Workspace
4. Click 'Enter'

Getting an error:
"ctx":"v:run","err":{"status":"unknown","msg":"","payload":"{"msg":"l.default.Uri.joinPath is not a function","stack":"TypeError: l.default.Uri.joinPath is not a function\n at v.execute

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by vince-fugnitto** [comment] 2021-01-04 20:30
Closing as it is a duplicate of https://github.com/eclipse-theia/theia/issues/8752 with additional information.
`vscode.Uri.joinPath` is not yet supported.

**Closed by vince-fugnitto** 2021-01-04 20:30 UTC
