### ISSUE TITLE
Theia does not load with Firefox

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#6590] opened 2019-11-20 12:47 UTC
### Description
Theia does not load on Firefox. Tried to load Theia with the latest configuration and did not start the frontend. Tried with an older version of Theia (commit 05f2e07bb77637723e6720231342b9acce01a159 ) with the same Browser and it loads

### Reproduction Steps
Start backend Theia latest version
Start Theia frontend using Firefox
--> Frontend does not start
Start Frontend with Chrome
--> works fine

**OS and Theia version:**
Theia latest: commit 21da05edcf6b79b57e55f6f543ebba49d28f7a9d
Firefox 70.0.1
Ubuntu 16.04

**Diagnostics:** 
![FireFoxNotLoading](https://user-images.githubusercontent.com/419051/69240133-d1f22380-0b69-11ea-8f42-c3c4b1b3ba3a.png)

**Comment by tsmaeder** [comment] 2019-11-20 12:51
Duplicate of https://github.com/eclipse-theia/theia/issues/6582

**Closed by tsmaeder** 2019-11-20 12:51 UTC
