### ISSUE TITLE
preview: 'open preview' does not work for editor-previews

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7078] opened 2020-02-04 18:14 UTC
### Description
 Preview view not showing data in electron

### Reproduction Steps

Open a README.md file in electron
Open The same README.md with the preview view in electron
--> The data is not showing in the preview view

Open the same README.md file from VSCode with the preview view
--> The data shows in the preview editor view

**OS and Theia version:**
OS: Ubuntu 18.04
Theia: latest commit cc0da4e69f8141122496c119bb72f4df46584e76

**Diagnostics:** 

Theia electron:
![ElectronNotShowingPreview](https://user-images.githubusercontent.com/419051/73773329-fbc1ec00-474f-11ea-9f90-f6e33dabcb24.gif)

VSCode preview view:
![VSCodeShowPreview](https://user-images.githubusercontent.com/419051/73773360-0a100800-4750-11ea-8327-cc3662488710.gif)

**Comment by vince-fugnitto** [comment] 2020-02-04 18:18
Possibly a duplicate of https://github.com/eclipse-theia/theia/issues/3579? 
Such commands are not present or work correctly for `editor-preview` editors.

**Closed** 2021-06-09 15:43 UTC
Labels: bug, editor-preview, help wanted
