### ISSUE TITLE
big size file and reopen thiea is not work

### ISSUE THREAD

**Issue by jiungbaek** [eclipse-theia/theia#10792] opened 2022-02-23 23:27 UTC
### Bug Description:

when i open big size file in theia, and close theia and reopen theia.

and then theia doesn't open. it shows only progress bar.

when i delete or rename big size file, it will open.

### Steps to Reproduce:

1. open theia
2. open big size file (over the 100mb)
3. watch big sizefile opened in theia
3. close theia
4. reopen theia

### Additional Information

- Operating System: k8s, ubuntu 16~20
- Theia Version: 1.19

**Comment by tsmaeder** [comment] 2022-02-24 10:34
How big is the file?

**Comment by msujew** [comment] 2022-02-24 10:47
@jiungbaek @tsmaeder I believe this is a duplicate of https://github.com/eclipse-theia/theia/issues/9843. I would recommend to continue the discussion there. Back then, I was able to replicate the issue using a relatively small file of ~10MB.

**Closed** 2022-02-24 10:47 UTC
Labels: filesystem, shell

**Comment by jiungbaek** [comment] 2022-02-24 15:25
> How big is the file?

80MB~ 
log file

**Comment by jiungbaek** [comment] 2022-02-24 15:25
> @jiungbaek @tsmaeder I believe this is a duplicate of #9843. I would recommend to continue the discussion there. Back then, I was able to replicate the issue using a relatively small file of ~10MB.

oh, it's right. it is the same issue. thank you
