### ISSUE TITLE
The official Theia Extensions Demo could not start

### ISSUE THREAD

**Issue by xmasong** [eclipse-theia/theia#10859] opened 2022-03-08 11:48 UTC
Follow the documentation steps（https://theia-ide.org/docs/authoring_extensions/）

#### Step1
```shell
npm install -g yo generator-theia-extension
mkdir theia-hello-world-extension
cd theia-hello-world-extension
yo theia-extension # select the 'Hello World' option and complete the prompts
```
<img width="816" alt="image" src="https://user-images.githubusercontent.com/22997127/157232007-d91b42b4-22ae-42e7-9a93-2befb56c951b.png">

#### Step2
```shell
cd browser-app && yarn start
```
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/22997127/157232299-3cd76d51-9e16-4524-acb3-3decd825dd86.png">

#### Step3
access `localhost:3000`
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22997127/157232470-9eb35412-9438-4a1f-88f9-2e6c0cc62f33.png">
---
How can I start the demo correctly?

**Comment by msujew** [comment] 2022-03-08 12:24
Hi @xmasong, the first issue is just Webpack not finding some metadata, that happens for a lot of users and shouldn't have any impact on the build.

The second one has been fixed with https://github.com/eclipse-theia/theia/pull/10818, but also should not impact the actual runtime behavior of the app.

However, the last one is a bit more crucial. The `Cannot apply @injectable decorator multiple times` error message indicates that you are pulling multiple versions of Theia packages. I cannot reproduce this issue on a fresh execution of the `Hello World` example extension. @vince-fugnitto Any ideas?

**Comment by vince-fugnitto** [comment] 2022-03-08 12:44
@msujew I confirmed with a fresh generation of the hello-world example that the application starts fine, there are no `Cannot apply @injectable decorator multiple times` errors :+1: 

@xmasong please be sure not to mix-and-match versions of theia extensions (perhaps you included a new one after the generation).

**Comment by xmasong** [comment] 2022-03-09 02:54
@msujew @vince-fugnitto 
Thank you for your reply~！
But I didn't change the generated code. How do I confirm if there is a mix of theia versions or theia extensions versions, or what information need to be provided?

**Comment by vince-fugnitto** [comment] 2022-03-09 03:09
@xmasong no problem!

What output do you see when you execute `yarn why @theia/core`? You should only see one version of `@theia/core` present, if there are multiple versions then you'll encounter the issue regarding the `@injectable decorator`:

```bash
$ yarn why @theia/core
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@theia/core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@theia/core@1.23.0"
info Reasons this module exists
   - "_project_#example" depends on it
   - Hoisted from "_project_#example#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#core"
   - Hoisted from "_project_#electron-app#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#editor#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#filesystem#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#markers#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#messages#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#monaco#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#navigator#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#preferences#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#process#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#terminal#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#workspace#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#monaco#@theia#outline-view#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#preferences#@theia#userstorage#@theia#core"
   - Hoisted from "_project_#browser-app#@theia#editor#@theia#variable-resolver#@theia#core"
info Disk size without dependencies: "14.15MB"
info Disk size with unique dependencies: "49.18MB"
info Disk size with transitive dependencies: "72.95MB"
info Number of shared dependencies: 178
✨  Done in 1.02s.
```

In my output I only have the one version present, `@theia/core@1.23.0`.

**Comment by xmasong** [comment] 2022-03-09 03:20
@vince-fugnitto 
I did find version inconsistencies in theia extensions.
For example:
1. theia-hello-world-extension/node_modules/@theia/editor
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/22997127/157365195-4c1091ad-3dcf-497c-9d62-da57c006b073.png">
2. theia-hello-world-extension/browser-app/node_modules/@theia/editor
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/22997127/157365555-93575a1d-5897-4ca5-a895-f968aa9e9cc4.png">

The package versions in `theia-hello-world-extension/node_modules/browser-app/node_modules/@theia` are v1.23.0，But all packages in `theia-hello-world-extension/node_modules/@theia` are 1.21.0. They are all generated by command(`yo theia-extension`)

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/22997127/157366361-051519dd-9b49-405b-b590-11f947256132.png">

**Comment by vince-fugnitto** [comment] 2022-03-09 03:23
@xmasong the mismatch is definitely why the error happens. I confirmed twice that a fresh generation (using a new folder each time) works as did Mark earlier. Can you retry the generation using a completely different parent directory? (Perhaps it was some folder that was used in the past).

**Comment by xmasong** [comment] 2022-03-09 07:25
@vince-fugnitto I tried again in a new directory. There is still a 1.21.0 vs. 1.23.0 conflict.  I ran the experiment on the machines of two friends who had never used theia at all, and both repeated the same problem. How do I analyze where abnormal @theia/core@1.21.0 dependencies in yarn why come from?

**Comment by msujew** [comment] 2022-03-09 10:43
@xmasong Alternatively, it Vince's advice does not work, you can pin all `@theia/*` dependencies to `1.23.0` instead of using `latest`. This should definitely ensure that all packages use the same version.

**Comment by xmasong** [comment] 2022-03-09 12:35
@msujew @vince-fugnitto
Thanks again！
I have located the problem. I used the private yarn registry and did not synchronize @theia/cli latest version in time. Now I can start the project normally.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22997127/157442618-a681e3eb-0964-4d0c-b7ba-fbe5eb4d52cd.png">
By the way, what caused the error in the red box? (`bundle.js:59427 root ERROR TypeError: Failed to fetch
    at DefaultJsonSchemaContribution.registerSchemas`)

**Comment by vince-fugnitto** [comment] 2022-03-09 13:05
@xmasong glad to hear that the issue was resolved for you :+1: 

> By the way, what caused the error in the red box? (bundle.js:59427 root ERROR TypeError: Failed to fetch at DefaultJsonSchemaContribution.registerSchemas)

I'm not sure, it is difficult to tell without more information about how it occurred, or your setup.

**Closed** 2022-03-10 02:38 UTC
Labels: :thinking: needs more info
