### ISSUE TITLE
Visual indication when a file or directory is Git ignored

### ISSUE THREAD

**Issue by anavarre** [eclipse-theia/theia#8450] opened 2020-09-01 08:56 UTC
In Theia, you don't know when a file or directory is Git ignored:

![theia](https://user-images.githubusercontent.com/293478/91829330-9b415180-ec41-11ea-9555-000e31827916.jpg)

In PhpStorm, you do:

![phpstorm](https://user-images.githubusercontent.com/293478/91829331-9bd9e800-ec41-11ea-90db-690a25d8316f.jpg)

The feature request is for Theia to indicate when a file or directory is Git ignored.

**Comment by kittaakos** [comment] 2020-09-01 09:07
Duplicate of #1564

**Closed by kittaakos** 2020-09-01 09:07 UTC
