### ISSUE TITLE
Add order property to SubMenuOptions

### ISSUE THREAD

**Issue by Hanksha** [eclipse-theia/theia#7958] opened 2020-06-04 08:23 UTC
Currently it's not possible to manage the order of sub menus like menu actions via the `order` property. I'd like to add the `order` property to `SubMenuOptions` so it can be sorted with the menu actions.

**Comment by Hanksha** [comment] 2020-06-04 08:31
I'll start working on it.

**Comment by vince-fugnitto** [comment] 2020-06-04 12:40
> I'll start working on it.

Thank you for taking care of it!
Is it a duplicate of https://github.com/eclipse-theia/theia/issues/6768? I'm asking only so we can successfully close both issues (or keep one open so we can track it).

**Comment by Hanksha** [comment] 2020-06-04 13:23
@vince-fugnitto yes it would fix that ticket as well, although I'm not entirely sure it will fix everything mentioned on that ticket (changing the order of existing sub menus).

**Comment by vince-fugnitto** [comment] 2020-06-04 13:25
> @vince-fugnitto yes it would fix that ticket as well, although I'm not entirely sure it will fix everything mentioned on that ticket (changing the order of existing sub menus).

I don't think the idea is to update existing menu items, I think the idea is to support an optional `order` property which when defined will be used to sort menu items instead of by their id (segment of the menu path).

**Comment by Hanksha** [comment] 2020-06-04 13:26
Ok you can close this issue as duplicate then.

**Comment by vince-fugnitto** [comment] 2020-06-04 13:27
> Ok you can close this issue as duplicate then.

I'll close the older one since we had discussions here, and you've assigned it to yourself :)

**Comment by Hanksha** [comment] 2020-06-04 13:28
Alright!

**Closed** 2020-06-05 08:20 UTC
Labels: enhancement, menus
