### ISSUE TITLE
vscode.window.registerWebviewViewProvider is not a function

### ISSUE THREAD

**Issue by plane-hjh** [eclipse-theia/theia#9404] opened 2021-04-27 02:44 UTC
### Feature Description:

when i use vscode.window.registerWebviewViewProvider to create webview，it  show me a meaage 

vscode.window.registerWebviewViewProvider is not a function

![image](https://user-images.githubusercontent.com/28526327/116176954-93409f80-a745-11eb-97ac-c2a9eb6f8ecb.png)

**Comment by vince-fugnitto** [comment] 2021-04-27 11:56
Thank you for the report, it is a duplicate of https://github.com/eclipse-theia/theia/issues/8740.

**Closed by vince-fugnitto** 2021-04-27 11:56 UTC
Labels: duplicate, vscode
