### ISSUE TITLE
TypeError: Cannot read property 'items' of undefined when selecting "Find All implementations"

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7813] opened 2020-05-13 15:25 UTC
### Bug Description:
Selecting in the context menu -> Find All implementations 
generates the following error:

```
root ERROR [hosted-plugin: 29023] Promise rejection not handled in one second: **TypeError: Cannot read property 'items' of undefined** , reason: TypeError: Cannot read property 'items' of undefined
root ERROR [hosted-plugin: 29023] With stack trace: TypeError: Cannot read property 'items' of undefined
    at g (/home/lmcbout/theia/theia/plugins/vscode-references-view/extension/dist/extension.js:1:8294)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Steps to Reproduce:

1. Open Theia, select a file (quick-view-service.ts)
2. From the context menu, select "Find All Implementations"
--> Observe on the console, the error is reported

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: Latest
- Builtin versions: 139.1 and 144.2

**Comment by vince-fugnitto** [comment] 2020-05-13 16:11
@lmcbout the command still works correctly for me (it displays the implementations), is the same case for you?

1. open `quick-view-service.ts`
2. highlight `QuickOpenModel`
3. execute the command '**Find All Implementations**'

<div align='center'>

<img width="1088" alt="Screen Shot 2020-05-13 at 12 10 39 PM" src="https://user-images.githubusercontent.com/40359487/81837382-cbd67180-9512-11ea-88f3-34203a62caef.png">

</div>

**Comment by lmcbout** [comment] 2020-05-13 19:43
@vince-fugnitto Yes, it display some information, but there is still the error log on the console. The priority to fix it is low since it returns some data

**Comment by vince-fugnitto** [comment] 2020-05-13 19:46
> @vince-fugnitto Yes, it display some information, but there is still the error log on the console. The priority to fix it is low since it returns some data

It looks like it still works, I’m not sure when the error is reported it is likely only when there are no implementations available. The logging should not be harmful.

**Comment by akosyakov** [comment] 2020-05-14 06:40
Getting rid of such logging is good as well, plus sometimes it reveals some incompatibilities to support VS Code extensions, then it should be fixed.

**Comment by vince-fugnitto** [comment] 2020-11-27 17:19
I cannot reproduce the error on the console any longer, the `find all implementations` functionality still works correctly.

**Closed by vince-fugnitto** 2020-11-27 17:19 UTC
Labels: :thinking: needs more info, help wanted, typescript
