### ISSUE TITLE
Python extension on Theia throws errors

### ISSUE THREAD

**Issue by kaustav-aarish** [eclipse-theia/theia#7999] opened 2020-06-11 14:51 UTC
### Bug Description:
Python extension on Theia throws errors.

### Steps to Reproduce:

I have added built-in extensions for ms-python and python in my package.json file as follows:

![image](https://user-images.githubusercontent.com/65616588/84387905-9db88000-abeb-11ea-8bae-1d3e602328b3.png)

My yarn scripts are as follows:

![image](https://user-images.githubusercontent.com/65616588/84387949-ae68f600-abeb-11ea-8a24-778a026b95c4.png)

![image](https://user-images.githubusercontent.com/65616588/84387959-b32daa00-abeb-11ea-972b-2cdfa915b39a.png)

However, I get these errors when running yarn start:

![image](https://user-images.githubusercontent.com/65616588/84387976-b9bc2180-abeb-11ea-9cf7-828c2c309b60.png)

![image](https://user-images.githubusercontent.com/65616588/84387984-bd4fa880-abeb-11ea-8ec7-3fea00874a87.png)

![image](https://user-images.githubusercontent.com/65616588/84387998-c0e32f80-abeb-11ea-9e89-c4e122e1cf81.png)

**Comment by akosyakov** [comment] 2020-06-12 05:50
Duplicate of https://github.com/eclipse-theia/theia/issues/3186#issuecomment-610356821

**Closed by akosyakov** 2020-06-12 05:50 UTC
Labels: python, vscode
