### ISSUE TITLE
Tag v1.0.0 yarn download:plugins fails

### ISSUE THREAD

**Issue by fbouteruche** [eclipse-theia/theia#7706] opened 2020-04-30 14:52 UTC
### Bug Description:

Following the described steps here https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md but with the source code from tag v1.0.0, yarn command fails due to error with vscode-builtin-extension

### Steps to Reproduce:

1. install the prerequisite on Amazon Linux 2
2. git checkout v1.0.0
3. yarn

you get the following errors during yarn download:plugins

vscode-references-view: downloading from https://github.com/theia-ide/vscode-references-view/releases/download/v0.0.47/references-view-0.0.47.vsix
Uncaught Exception:  Error: Not a valid zip file
Error: Not a valid zip file
    at UnzipStream.processDataChunk (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
    at UnzipStream._transform (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at UnzipStream.Writable.write (_stream_writable.js:299:11)
    at Extract._transform (/home/ec2-user/theia/node_modules/unzip-stream/lib/extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10)
+ vscode-builtin-docker: downloaded successfully
Uncaught Exception:  Error: Not a valid zip file
Error: Not a valid zip file
    at UnzipStream.processDataChunk (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
    at UnzipStream._transform (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at UnzipStream.Writable.write (_stream_writable.js:299:11)
    at Extract._transform (/home/ec2-user/theia/node_modules/unzip-stream/lib/extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10)
+ vscode-builtin-groovy: downloaded successfully
Uncaught Exception:  Error: Not a valid zip file
Error: Not a valid zip file
    at UnzipStream.processDataChunk (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
    at UnzipStream._transform (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at UnzipStream.Writable.write (_stream_writable.js:299:11)
    at Extract._transform (/home/ec2-user/theia/node_modules/unzip-stream/lib/extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10)
+ vscode-builtin-go: downloaded successfully
Uncaught Exception:  Error: Not a valid zip file
Error: Not a valid zip file
    at UnzipStream.processDataChunk (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
    at UnzipStream._transform (/home/ec2-user/theia/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at UnzipStream.Writable.write (_stream_writable.js:299:11)
    at Extract._transform (/home/ec2-user/theia/node_modules/unzip-stream/lib/extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10)

### Additional Information

- Operating System: Amazon Linux 2
- Theia Version: v1.0.0

**Comment by vince-fugnitto** [comment] 2020-04-30 15:04
@fbouteruche the build is in fact successful, there seems to be some errors with the `download:plugins` script which is fixed in the latest release.

**Comment by fbouteruche** [comment] 2020-04-30 15:20
Indeed, I've ran yarn download:plugins and it is where it fails. Then, I've switched to master, run download:plugins and then I went back to the tag v1.0.0 and I was able to run browser examples.

**Comment by vince-fugnitto** [comment] 2020-04-30 15:20
@fbouteruche when checking out **v1.1.0** I confirmed that it works correctly.

**Comment by fbouteruche** [comment] 2020-04-30 15:33
I've just tested from a clean git clone and it works great with tag v1.1.0.

Thanks.

**Comment by vince-fugnitto** [comment] 2020-04-30 15:42
Closing since the bug has been fixed in the latest release **v1.1.0**.

**Closed by vince-fugnitto** 2020-04-30 15:42 UTC
Labels: question
