### ISSUE TITLE
nfsw fails when moving a folder out from the workspace

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#2283] opened 2018-07-05 15:28 UTC
![peek 2018-07-05 11-24](https://user-images.githubusercontent.com/37082801/42332640-892bff18-8046-11e8-8c7a-719e14edb61b.gif)

**Comment by msujew** [comment] 2023-06-30 14:42
I cannot reproduce this anymore. Closing.

**Closed by msujew** 2023-06-30 14:42 UTC
Labels: bug
