### ISSUE TITLE
Content  in terminal is displayed abnormally when resized.

### ISSUE THREAD

**Issue by shuyaqian** [eclipse-theia/theia#10093] opened 2021-09-14 09:15 UTC
### Bug Description:
![img](https://bbs-img.huaweicloud.com/blogs/img/20210914/1631610683256044118.gif)

### Steps to Reproduce:

1. open terminal
2. split it 
3. drag to resize window of terminal

<! -- Please provide any additional information available. -->

### Additional Information

- Operating System: linux
- Theia Version: 1.17.0

**Comment by vince-fugnitto** [comment] 2021-09-14 16:51
The issue is likely in `xterm` itself, not sure we can do much.
For reference, the same occurs for me in vscode:

![image](https://user-images.githubusercontent.com/40359487/133300370-c6962b76-3441-4cda-b6eb-87c22de3b76f.png)

**Comment by vince-fugnitto** [comment] 2022-07-21 15:27
I could not reproduce the issue any longer (also in vscode), it is likely fixed by an xterm.js update we made.
Closing but we can re-open if we experience it again.

**Closed by vince-fugnitto** 2022-07-21 15:27 UTC
Labels: terminal, ui/ux
