### ISSUE TITLE
[preferences][electron] use the native context menu in the pref widget

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7354] opened 2020-03-17 12:28 UTC
### Description
 

It works in the `Explorer`:
![Screen Shot 2020-03-17 at 13 27 34](https://user-images.githubusercontent.com/1405703/76856243-288b1800-6853-11ea-8aa1-9b32e706dd36.jpg)

It does not in the pref widget:

![Screen Shot 2020-03-17 at 13 26 54](https://user-images.githubusercontent.com/1405703/76856232-21fca080-6853-11ea-924c-11ba6cf54fa4.jpg)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment] 2020-05-06 12:56
Closing in favor of https://github.com/eclipse-theia/theia/issues/7744, the issue is now outdated after the recent preferences-ui update, and in fact the opposite use-case needs to be handled now (creating a custom browser menu).

**Closed by vince-fugnitto** 2020-05-06 12:56 UTC
Labels: bug, electron, help wanted, preferences
