### ISSUE TITLE
input not at force editor

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#7902] opened 2020-05-27 05:12 UTC
### Bug Description:
![github](https://user-images.githubusercontent.com/10203793/82980021-05cb6b80-a01b-11ea-8247-23a723fd33a4.gif)

### Steps to Reproduce:

I don't know how to reproduce it
but It happened several times

### Additional Information

- Operating System: Windows10 Chrome 83.0.4103.61
- Theia Version: 1.2.0-next.f7cecf20

**Comment by akosyakov** [comment] 2020-05-27 05:49
@502647092 Could you reproduce it with https://github.com/eclipse-theia/theia/commit/1bc44b3a29eab9f3d7f398dead06f3a7edb15b58? Your version does not seem to contain it.

**Comment by akosyakov** [comment] 2020-05-27 07:56
From reading the code I think i understand the issue now:
- We apply keystrokes either to focused monaco editor or last focused tracked by us. We have to do it since we don’t track inline (debug console) and embedded editors (editor in peek reference), but Monaco does. Plus it is the same what VS Code do.
- When we ask Monaco to focus something it expects that the editor is already revealed and forcefully override hasFocus flag.
- So in the situation when the widget is not revealed we apply keystrokes to wrong Monaco editor.

I can reproduce it by triggering `Go to symbol…` and changing the editor. First the quick pick does not get closed on an editor change and when i close it, it tries to focus the old editor.

**Closed** 2020-05-27 09:59 UTC
Labels: bug, editor
