### ISSUE TITLE
Error is reported after closing a workspace

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-theia/theia#5889] opened 2019-08-08 11:14 UTC
### Description
 
After closing a workspace an error is thrown.

### Reproduction Steps

Close a workspace.

**OS and Theia version:**

**Diagnostics:** 

```
root ERROR TypeError: Cannot read property 'className' of undefined
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderOptionElement (http://localhost:3000/88.bundle.js:2475:61)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderOptionContainer (http://localhost:3000/88.bundle.js:2463:36)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchField (http://localhost:3000/88.bundle.js:2428:36)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchAndReplace (http://localhost:3000/88.bundle.js:2377:32)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchHeader (http://localhost:3000/88.bundle.js:2369:46)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.onUpdateRequest (http://localhost:3000/88.bundle.js:2339:22)
    at SearchInWorkspaceWidget.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (http://localhost:3000/bundle.js:23628:22)
    at invokeHandler (http://localhost:3000/bundle.js:7614:21)
    at sendMessage (http://localhost:3000/bundle.js:7350:13)
    at runMessageLoop (http://localhost:3000/bundle.js:7664:17)
```

**Comment by vince-fugnitto** [comment] 2019-08-08 11:24
Similarly to https://github.com/theia-ide/theia/issues/5833, can you verify if the error is still thrown after executing 
the command `Reset Workbench Layout`?

**Comment by azatsarynnyy** [comment] 2019-08-08 12:03
The issue is still reproducible after executing `Reset Workbench Layout` command.
Note, the error isn't thrown when in Chrome incognito mode.

**Comment by vince-fugnitto** [comment] 2019-08-08 12:54
Do you have any additional steps to reproduce the issue?
Simply closing a workspace I am unable to get the error :(

**Comment by azatsarynnyy** [comment] 2019-08-08 13:01
yes, just closing a workspace
or opening page with Theia with no opened workspace

**Comment by vince-fugnitto** [comment] 2019-08-08 13:07
> yes, just closing a workspace

I tested on `master` 0953ba7 and I was unable to reproduce the problem by closing a workspace.
Do you get any other error logs?

**Comment by azatsarynnyy** [comment] 2019-08-08 13:21
Just the mentioned one, thrown three times.
![image](https://user-images.githubusercontent.com/1636395/62706555-75268f00-b9f8-11e9-9789-55ef6567c537.png)

**Comment by vince-fugnitto** [comment] 2019-08-08 13:25
> ![image](https://user-images.githubusercontent.com/1636395/62706555-75268f00-b9f8-11e9-9789-55ef6567c537.png)

I see, and you mentioned <kbd>F1</kbd> `Reset Workbench Layout` has no effect?

**Comment by azatsarynnyy** [comment] 2019-08-08 13:27
> Reset Workbench Layout has no effect?

correct

**Comment by elaihau** [comment] 2020-06-15 00:13
is this still reproducible? @azatsarynnyy @vince-fugnitto I cannot, from my local environment.

**Comment by vince-fugnitto** [comment] 2020-06-15 12:28
> is this still reproducible? @azatsarynnyy @vince-fugnitto I cannot, from my local environment.

I am unable to reproduce the error, I'll close for now and we can re-open if it ever re-occurs.

**Closed by vince-fugnitto** 2020-06-15 12:28 UTC
Labels: bug, help wanted, search in workspace

**Comment by azatsarynnyy** [comment] 2020-06-15 13:03
can't reproduce it anymore
