### ISSUE TITLE
integrated terminal incorrectly interpret SHIFT+arrows key combinations to mark text

### ISSUE THREAD

**Issue by ratermir** [eclipse-theia/theia#8999] opened 2021-01-28 13:23 UTC
### Bug Description:
In integrated terminal, when I want to mark text using usual keyboard combinations (CTRL/SHIFT + navigation keys), the text is not marked, but some letters are written

CTRL + arrows work correctly, only combinations with SHIFT do not work.

### Steps to Reproduce:
Open internal terminal, type any text, then try to mark it with (for example) SHIFT+LEFT/RIGHT, CTRL+SHIFT+LEFT/RIGHT ... etc
Only a letter is written at the cursor position: "C" for right arrow, "D" for left arrow, "H" for home key, "F" for end key

### Additional Information
tested in firefox and chrome, Theia 1.8.9 docker (the "next" build) , also my own docker build based on current GIT repo, and also on theia docker 1.9.0 alpine - still the same result.

**Comment by vince-fugnitto** [comment] 2021-01-28 15:29
@ratermir thank you for reporting the issue, can you confirm that the behavior works correctly for you in vscode? If it does, can you please provide a quick demonstration (such as a `.gif`) to illustrate the expected behavior.

**Comment by ratermir** [comment] 2021-01-28 15:50
Yes in VS Code on the same machine it works. 
![image](https://user-images.githubusercontent.com/52619304/106162368-4ff78480-6188-11eb-9d68-2ca66c3f44c0.png)
![image](https://user-images.githubusercontent.com/52619304/106162552-86350400-6188-11eb-83d4-d6a9e0e4dc2c.png)
![image](https://user-images.githubusercontent.com/52619304/106162731-b5e40c00-6188-11eb-8d0d-a6a098dd5b67.png)
![image](https://user-images.githubusercontent.com/52619304/106162800-cb593600-6188-11eb-9399-350481cf6d90.png)

The difference is that in case of Theia, the terminal is Linux (docker), in case os VS Code it is windows (I can't connect VS Code to the linux)

**Comment by vince-fugnitto** [comment] 2021-01-28 16:14
@ratermir I verified with Linux (theia and vscode) and cannot use those same keybindings to reproduce the behavior you described. I also had a colleague verify on windows and they could not reproduce as well. Did you perhaps set some custom keybindings under `keymaps.json`?

**Comment by vince-fugnitto** [comment] 2021-01-28 16:21
@ratermir I believe the support comes from `powershell`, therefore it is not a bug.

**Comment by ratermir** [comment] 2021-01-28 17:57
In VS Code on Windows and powershell as a console it works correctly. 
The issue is observer with shell of the remote instance - started in Docker.

I started new instance here: "ext.anirad.cz:3301", you may try it out . It behaves as I described. This nstance is started from fresh docker image theiaide/theia-python:next, I tried this behaviour in Chrome on clean user profile

**Comment by vince-fugnitto** [comment] 2021-01-28 18:04
@ratermir I'm a bit confused with your expectations, the functionality comes straight from `powershell`. If you want such functionality in your docker images I assume you can install it yourself ([installing powershell on linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1)). 

The issue is not a bug with the framework as `powershell` works with Theia as well (which was confirmed by a colleague).

**Comment by ratermir** [comment] 2021-01-28 18:38
I don't expect powershell - it was only example (since I have not VS code on linux and I don't have libux shell on windows). 
I expect ability **to mark text** text in terminal panel (to be then copied to clipboard or deleted), as it is usual in almost every editor - i.e. SHIFT + arrows. 
It is possible to mark text using mouse, but it is very unconfortable (mainly for old school develpers keyboard-oriented  :) )

**Comment by vince-fugnitto** [comment] 2021-01-28 18:47
As mentioned, this is a feature contributed by `powershell` so if you want support please use `powershell` as your shell.
The behavior at the moment is consistent with vscode, and `xterm` and I don't believe we should deviate but respect the behavior of the user's current shell.

**Comment by ratermir** [comment] 2021-01-28 18:56
So it is impossible to achieve this behaviour in linux shell ? I supposed that it may be similar like CTRL+C/V. These actions are also caught by the terminal app (it bhaves differently if there is a marked text and wwithout selected text)

**Comment by vince-fugnitto** [comment] 2021-01-28 18:58
> So it is impossible to achieve this behaviour in linux shell ? I supposed that it may be similar like CTRL+C/V. These actions are also caught by the terminal app (it bhaves differently if there is a marked text and wwithout selected text)

As expressed before https://github.com/eclipse-theia/theia/issues/8999#issuecomment-769270927, you can also install and use `powershell` on linux and it should give you the behavior you want and are accustomed to.

I'll be closing the issue as it is not a bug in the framework.

**Closed by vince-fugnitto** 2021-01-28 18:58 UTC
Labels: :thinking: needs more info, terminal
