### ISSUE TITLE
Plugin not work and show webpack error in console

### ISSUE THREAD

**Issue by misakajimmy** [eclipse-theia/theia#9711] opened 2021-07-08 02:57 UTC
I meet some problem when i use `@theia/generator-plugin` to generate a frontend hello-world plugin, and use `Host Plugin: start instance` to develop it, but it seems not work and i got this error in console.
```
logger-protocol.ts:112 root ERROR Failed to load plugins: TypeError: __webpack_require__(...) is not a constructor
    at new PluginWorker (http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:14631:23)
    at HostedPluginSupport.push../node_modules/@theia/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.initRpc (http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:1806:41)
    at HostedPluginSupport.<anonymous> (http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:1753:36)
    at step (http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:1203:23)
    at Object.next (http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:1184:53)
    at http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:1178:71
    at new Promise (<anonymous>)
    at push../node_modules/@theia/plugin-ext/lib/hosted/browser/hosted-plugin.js.__awaiter (http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:1174:12)
    at HostedPluginSupport.push../node_modules/@theia/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.obtainManager (http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:1744:16)
    at http://localhost:3030/vendors-node_modules_theia_plugin-ext_lib_plugin-ext-frontend-module_js.bundle.js:1637:73
```
### Steps to Reproduce:

i deliver to github [https://github.com/misakajimmy/theia-webpack-error](https://github.com/misakajimmy/theia-webpack-error)

i just use `theia` of `1.15.0` and use  `@theia/generator-plugin` to generate a frontend hello world plugin.

### Additional Information

- Operating System: Windows
- Theia Version: 1.15.0

**Comment by misakajimmy** [comment] 2021-07-08 03:01
i also tried to pack this plugin and use `Plugin: deploy by id` to use this plugin bug got the same problem

**Comment by vince-fugnitto** [comment] 2021-07-08 03:10
@misakajimmy it is a duplicate of https://github.com/eclipse-theia/theia/issues/6601.

**Closed** 2021-07-08 03:44 UTC
