### ISSUE TITLE
Error resolving 'vscode

### ISSUE THREAD

**Issue by CannyDuck** [eclipse-theia/theia#8763] opened 2020-11-19 12:19 UTC
The build of theia fails with this error:
```
' Module not found: Error: Can't resolve 'vscode' in ..\node_modules\vscode-languageclient\lib'
```
package.json
```
{
    "private": true,
    "theia": {
        "frontend": {
            "config": {
                "applicationName": "Theia Java",
                "preferences": {
                    "files.enableTrash": false
                }
            }
        }
    },
    "dependencies": {
        "@theia/callhierarchy": "latest",
        "@theia/editor-preview": "latest",
        "@theia/filesystem": "latest",
        "@theia/file-search": "latest",
        "@theia/getting-started": "latest",
        "@theia/json": "latest",
        "@theia/markers": "latest",
        "@theia/messages": "latest",
        "@theia/navigator": "latest",
        "@theia/outline-view": "latest",
        "@theia/plugin": "latest",
        "@theia/plugin-ext": "latest",
        "@theia/plugin-ext-vscode": "latest",
        "@theia/preferences": "latest",
        "@theia/preview": "latest",
        "@theia/search-in-workspace": "latest",
        "@theia/terminal": "latest",
        "@theia/vsx-registry": "latest",
        "@theia/keymaps": "latest",
        "@theia/typehierarchy": "latest"
    },
    "devDependencies": {
        "@theia/cli": "latest"
    },
    "scripts": {
        "prepare": "yarn run clean && yarn build && yarn run download:plugins",
        "clean": "theia clean",
        "build": "theia build",
        "start": "theia start  --plugins=local-dir:plugins",
        "download:plugins": "theia download:plugins"
    },
    "theiaPluginsDir": "plugins",
    "theiaPlugins": {
        "vscode-builtin-configuration-editing": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/configuration-editing-1.39.1-prel.vsix",
        "vscode-builtin-css": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/css-1.39.1-prel.vsix",
        "vscode-builtin-debug-auto-launch": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/debug-auto-launch-1.39.1-prel.vsix",
        "vscode-builtin-groovy": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/groovy-1.39.1-prel.vsix",
        "vscode-builtin-gulp": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/gulp-1.39.1-prel.vsix",
        "vscode-builtin-html": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/html-1.39.1-prel.vsix",
        "vscode-builtin-java": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/java-1.39.1-prel.vsix",
        "vscode-builtin-javascript": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/javascript-1.39.1-prel.vsix",
        "vscode-builtin-json": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/json-1.39.1-prel.vsix",
        "vscode-builtin-less": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/less-1.39.1-prel.vsix",
        "vscode-builtin-merge-conflicts": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/merge-conflict-1.39.1-prel.vsix",
        "vscode-builtin-sql": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/sql-1.39.1-prel.vsix",
        "vscode-builtin-xml": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/xml-1.39.1-prel.vsix",
        "vscode-editorconfig": "https://github.com/theia-ide/editorconfig-vscode/releases/download/v0.14.4/EditorConfig-0.14.4.vsix",
        "vscode-java-redhat": "https://open-vsx.org/api/redhat/java/0.70.0/file/redhat.java-0.70.0.vsix",
        "vscode-java-debug": "https://github.com/microsoft/vscode-java-debug/releases/download/0.29.0/vscjava.vscode-java-debug-0.29.0.vsix",
        "vscode-java-test": "https://github.com/microsoft/vscode-java-test/releases/download/0.26.0/vscjava.vscode-java-test-0.26.0.vsix",
        "vscode-java-dependency-viewer": "https://github.com/microsoft/vscode-java-dependency/releases/download/0.14.0/vscjava.vscode-java-dependency-0.14.0.vsix"
  }
}
```

**Comment by kittaakos** [comment] 2020-11-19 12:23
[`@theia/json`](https://www.npmjs.com/package/@theia/json) has been deprecated since `1.3.0` with `@theia/languages`. Please remove that dependency and use the appropriate VS Code extensions instead:

https://github.com/eclipse-theia/theia/blob/e2098321a66e96e72248b555ca32063127857a98/package.json#L111-L112

Closing as not a bug.

**Closed by kittaakos** 2020-11-19 12:23 UTC

**Comment by kittaakos** [comment] 2020-11-19 12:25
@CannyDuck, if you have any follow-up issues, please feel free to ask. I'll try to assist you.
