### ISSUE TITLE
Context menu from any views are modified when the "Extension" view is available on the side-bar

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7520] opened 2020-04-07 19:23 UTC
### Description
 
Context menu from any views are modified when the "Extension" view is available on the side-bar,
WE don't need to display the "Extension" view, any Views (Explorer, Debug...), select the context menu and there is two new menu items: "Installed" and "Built-in"
Those  menu items should only be available when we display the  "Extensions" view, not any other views.

### Reproduction Steps

Open Theia front end in a Browser
**Note: The Extensions view is closed, not available to the side bar yet**
Select the Explorer view context menu
    --> Display the Npm scripts menu item
Select View -> Extensions
    --> The Extensions view shows on  the left side bar
Select again the Explorer view
Note: Now we have in the left side-bar the "Extensions" view, but the content is hidden by the Explorer view
- Open the context menu for the Explorer view
     --> "Npm Scripts" + "Installed" + Built-in"  menu items show
The last two menu items only belong to the "Extensions" view, not to any other views.

**OS and Theia version:**
Theia: latest master
OS: Ubuntu 18.04

**Diagnostics:** 

![ExtensionViewContextMenu](https://user-images.githubusercontent.com/419051/78710085-c1590480-78e2-11ea-9709-6bd428145268.gif)

**Comment by vince-fugnitto** [comment] 2021-07-01 02:15
Closing as the issue is no longer reproducible 👍

**Closed by vince-fugnitto** 2021-07-01 02:15 UTC
Labels: bug, help wanted, vscode
