### ISSUE TITLE
mouse navigation and vim extension not working

### ISSUE THREAD

**Issue by Michaelhobo** [eclipse-theia/theia#8858] opened 2020-12-14 04:46 UTC
### Bug Description:

I'm using Gitpod, which uses Theia. After using a new workspace for a bit, mouse navigation in the browser breaks. When I move somewhere else in my current file, the next action will get applied to the previous location.

e.g. while in vim insert mode, I'm currently on line 30. I click to line 40, and type "hello". The "h" gets written to line 30, and "ello" gets written to line 40.

The same problem applies in vim's command mode.

Other observations:

- This doesn't happen with a new workspace - it takes a while for it to kick in.
- Once it starts happening, it doesn't fix itself. I don't know if restarting the workspace solves it, but I usually create a new one.
- It happens pretty often (most of my longer-running workspaces run into this)

### Steps to Reproduce:

1. Open a new workspace in gitpod, with the "vscodevim.vim" plugin installed
2. use it for a while (hours)
3. Eventually, vim mouse navigation breaks

**Comment by vince-fugnitto** [comment] 2020-12-14 13:22
@Michaelhobo can you confirm if the bug occurs from the framework's [sources](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start)? Based on your description, it may be an issue specific to `gitpod` and not the general framework.

**Comment by Michaelhobo** [comment] 2020-12-14 14:02
The bug takes a while to reproduce (probably hours). I ran theia from source, but I haven't been able to reproduce the issue yet.

**Comment by vince-fugnitto** [comment] 2021-10-08 13:07
> The bug takes a while to reproduce (probably hours). I ran theia from source, but I haven't been able to reproduce the issue yet.

Given that the issue is quite old, and there is no clear way to reproduce I will close it for the time being.
If you discover the way to reproduce it, please don't hesitate in commenting.

**Closed by vince-fugnitto** 2021-10-08 13:07 UTC
Labels: vscode, :thinking: needs more info
